import React from 'react'

const DanHarmonsCircularStructurePartTwo = () =>
  <div>
    <p style="text-align: center;"><em>This post is part of the </em>Outline With Me <em>series. </em><em>For more like this, check out the <a href="https://ryanrcampbell.com/outlining-your-novel/">outlining your novel</a> page.</em></p>
<p><a href="https://ryanrcampbell.com/2017/06/23/dan-harmons-circular-structure-part-one/" target="_blank" rel="noopener">In part one</a>, we examined each of the eight steps of circular structure. As a refresher, those eight steps are:</p>
<ol>
<li>Our main character is in her comfort zone,</li>
<li>but there’s something she wants.</li>
<li>She enters an unfamiliar world or situation,</li>
<li>adapts to it,</li>
<li>and gets what she wanted.</li>
<li>But! She pays heavily for achieving this</li>
<li>before returning to a familiar world or situation</li>
<li>as a changed person.</li>
</ol>
<p>All of which fits nicely onto&#8212;you guessed it&#8212;a circle, wherein our main character both starts and ends in a zone of comfort. For a visual representation, check out the below.</p>
<div id="attachment_2352" style="width: 1034px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-2352" data-attachment-id="2352" data-permalink="https://ryanrcampbell.com/2017/06/23/dan-harmons-circular-structure-part-one/circular-structure/" data-orig-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/06/circular-structure.jpg?fit=1024%2C512&amp;ssl=1" data-orig-size="1024,512" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="circular structure" data-image-description="" data-image-caption="" data-medium-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/06/circular-structure.jpg?fit=300%2C150&amp;ssl=1" data-large-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/06/circular-structure.jpg?fit=1024%2C512&amp;ssl=1" class="alignnone size-full wp-image-2352" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/06/circular-structure.jpg?resize=1024%2C512&#038;ssl=1" alt="circular structure" width="1024" height="512" srcset="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/06/circular-structure.jpg?w=1024&amp;ssl=1 1024w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/06/circular-structure.jpg?resize=300%2C150&amp;ssl=1 300w" sizes="(max-width: 1024px) 100vw, 1024px" data-recalc-dims="1" /><p id="caption-attachment-2352" class="wp-caption-text">You are the circle; the circle is you.</p></div>
<p>One of the things I like most about this representation is that it shows us additional theoretical angles from which we are empowered to explore our stories as a whole. Let's examine each of these below with the goal using this knowledge to better frame higher-level concepts like theme.</p>
<h1>Life versus Death</h1>
<div id="attachment_2478" style="width: 1034px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-2478" data-attachment-id="2478" data-permalink="https://ryanrcampbell.com/2017/07/14/dan-harmons-circular-structure-part-two/life-death/" data-orig-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/06/LIFE-DEATH.jpg?fit=1024%2C512&amp;ssl=1" data-orig-size="1024,512" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="LIFE-DEATH" data-image-description="" data-image-caption="" data-medium-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/06/LIFE-DEATH.jpg?fit=300%2C150&amp;ssl=1" data-large-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/06/LIFE-DEATH.jpg?fit=1024%2C512&amp;ssl=1" class="alignnone size-full wp-image-2478" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/06/LIFE-DEATH.jpg?resize=1024%2C512&#038;ssl=1" alt="LIFE-DEATH" width="1024" height="512" srcset="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/06/LIFE-DEATH.jpg?w=1024&amp;ssl=1 1024w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/06/LIFE-DEATH.jpg?resize=300%2C150&amp;ssl=1 300w" sizes="(max-width: 1024px) 100vw, 1024px" data-recalc-dims="1" /><p id="caption-attachment-2478" class="wp-caption-text">The cirrrrcle of lifeeeee&#8212;and death.</p></div>
<p>This image alone might already set your gears to grinding. If it does, fantastic. If not, let's see if we can wind them up before unleashing on the page.</p>
<p>Remember the numbered circle above, with each number corresponding to a step in this circular structure? Imagine those numbers are placed around our Life-Death circle above. What two critical points are located along the equator dividing our character's world into hemispheres of life and death? That's right: numbers three and seven&#8212;those “crossing the threshold” moments from the familiar to the unfamiliar and back again.</p>
<p>Why is this of note? Because these are the moments in our story at which our character enters a world in which she must confront death (three) before she can emerge on the other side with hope of life once again (seven).</p>
<p>In some stories, these notions of life or death can be quite literal. If our main characters aren't facing their own mortality, however, perhaps their ideals are. Perhaps they're confronting the death of their innocence, a dream, or hope.</p>
<p>Contrast this with emergence on the far side of the story in step seven&#8212;the transition back into life. Here is where our character finally “sees the light” or “comes back to their deity of choice” or holds out some hope for a better self or an improved world as a result of the knowledge she's earned.</p>
<p>The critical point here is that this life-death balance be kept in mind as we write so that it manifests itself on the page. At any point in time during our character's journey around the circle, if a reader were to examine our character's primary struggle, he should be able to note that she's either:</p>
<ol>
<li>Experiencing a disturbance to life as she knew it (steps one and two)</li>
<li>Confronting death (itself or of an ideal or identity in steps three through six), or</li>
<li>Adjusting to a new world and/or perspective (steps seven, eight, and ultimately back to one)</li>
</ol>
<p>I've found using this as a tool to be effective both when crafting a plot and examining one after it's been put to the page&#8212;if I don't quite see how my main character's journey aligns with this set-up, I try to pinpoint where her journey has perhaps strayed in focus to either change the plot's focus point or otherwise adjust course accordingly.</p>
<p>The above may seem like a useful coincidence as the result of the equivalent of a literary-theory parlor trick… but wait! There's more! This show's just getting started, and circular structure never tires of being a (circular) star.</p>
<h1>Conscious versus Unconscious</h1>
<div id="attachment_2477" style="width: 1034px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-2477" data-attachment-id="2477" data-permalink="https://ryanrcampbell.com/2017/07/14/dan-harmons-circular-structure-part-two/conscious-unconscious/" data-orig-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/06/CONSCIOUS-UNCONSCIOUS.jpg?fit=1024%2C512&amp;ssl=1" data-orig-size="1024,512" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="CONSCIOUS-UNCONSCIOUS" data-image-description="" data-image-caption="" data-medium-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/06/CONSCIOUS-UNCONSCIOUS.jpg?fit=300%2C150&amp;ssl=1" data-large-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/06/CONSCIOUS-UNCONSCIOUS.jpg?fit=1024%2C512&amp;ssl=1" class="alignnone size-full wp-image-2477" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/06/CONSCIOUS-UNCONSCIOUS.jpg?resize=1024%2C512&#038;ssl=1" alt="CONSCIOUS-UNCONSCIOUS" width="1024" height="512" srcset="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/06/CONSCIOUS-UNCONSCIOUS.jpg?w=1024&amp;ssl=1 1024w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/06/CONSCIOUS-UNCONSCIOUS.jpg?resize=300%2C150&amp;ssl=1 300w" sizes="(max-width: 1024px) 100vw, 1024px" data-recalc-dims="1" /><p id="caption-attachment-2477" class="wp-caption-text">Is my use of “unconscious” disconcerting to you, Psych 101 student? Please sit back down; we'll get there in a second.</p></div>
<p>Where the forthcoming analysis is concerned, I'll go on record and say I'm well aware that the “unconscious” hemisphere would technically be more correct were it reframed as “subconscious.” In the interest of verisimilitude with Dan Harmon's original post on this matter, I've decided to roll with unconscious here, however, though it probably goes without saying that your character need not be actually unconscious for half of her journey (seriously, please avoid the whole “it was all a dream” thing&#8212;or anything that might pull the rug out from your reader in a similar fashion).</p>
<p>Defense of my honor aside, here again we have the opportunity to create or examine plot from the perspective of the conscious and unconscious worlds of our main character. In the earliest and final moments of her journey, the world is as the character sees it&#8212;she's either blissfully journeying through the world with a sense of comfort and perhaps naiveté in steps one and two, or truly seeing the world with a new awareness in steps seven and eight.</p>
<p>The unconscious, however, is where her story really has its legs. Steps three through six are where our character suddenly has to confront her deepest fears or explore the most hidden-away parts of her&#8212;things she may have known or suspected existed within herself, but were always kept well enough below her level of consciousness as to not let them disturb the happy bubble in which she lived previously.</p>
<p>That is to say, she has to confront the most dangerous aspects of her unconscious (subconscious) mind.</p>
<p>And of course she does! How will she emerge on the far side as a changed person if she doesn't have to do battle with her most foundational beliefs or fears? If she were to emerge in steps seven and eight without having done so, her change wouldn't be earned or feel as though it occurred organically: two things we should aim to avoid at all costs.</p>
<p>Does your main character confront her deepest, darkest fears or secrets or beliefs as part of her journey? She does?! That's fantastic. We can now address the final of the almighty circles, that which balances order and chaos.</p>
<h1>Order versus Chaos</h1>
<div id="attachment_2479" style="width: 1034px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-2479" data-attachment-id="2479" data-permalink="https://ryanrcampbell.com/2017/07/14/dan-harmons-circular-structure-part-two/order-chaos/" data-orig-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/06/ORDER-CHAOS.jpg?fit=1024%2C512&amp;ssl=1" data-orig-size="1024,512" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="ORDER-CHAOS" data-image-description="" data-image-caption="" data-medium-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/06/ORDER-CHAOS.jpg?fit=300%2C150&amp;ssl=1" data-large-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/06/ORDER-CHAOS.jpg?fit=1024%2C512&amp;ssl=1" class="alignnone size-full wp-image-2479" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/06/ORDER-CHAOS.jpg?resize=1024%2C512&#038;ssl=1" alt="ORDER-CHAOS" width="1024" height="512" srcset="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/06/ORDER-CHAOS.jpg?w=1024&amp;ssl=1 1024w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/06/ORDER-CHAOS.jpg?resize=300%2C150&amp;ssl=1 300w" sizes="(max-width: 1024px) 100vw, 1024px" data-recalc-dims="1" /><p id="caption-attachment-2479" class="wp-caption-text">This color scheme is way too peaceful to drive home the necessity of chaos, isn't it?</p></div>
<p>The order-chaos balance is the one that I find easiest to see in action. When considering both, however, it's important to keep in mind that order doesn't mean or have to mean “everything is perfect,” and chaos doesn't have to me “constant and absolute panic at every conceivable moment.”</p>
<p>To frame this paradigm differently, it could also be examined as stability-instability, or, perhaps in the right genre, even peace-war.</p>
<p>No matter how one chooses to frame the order-chaos balance (or any of the above, really), it's critical to keep in mind that we aren't working with a switch-operated system, wherein a lever is thrown from on to off (or vice versa), and everything is suddenly hunky-dory or downright dangerous.</p>
<p>Instead, think of the circle like the dial for a dimmer system that can turn 360 degrees–and only turn clockwise. To begin, let's say light is off at step one in our circle. As it's slowly turned clockwise, light begins to creep in. It's almost imperceptible at first, but before you know it, you've turned the knob to step three, at which point all of the room's ugliness has been made apparent.</p>
<p>In the legendary words of The Dude, “some things have come to light, man,” and there's no turning back. The only way back to the comforts of darkness is to keep turning that dial around to four and five and six, when the light has finally become just dim enough to return to some sort of solitude.</p>
<p>But can you “unsee” what you saw when the light was on? Of course not. Neither can our characters.</p>
<p>Whether the chaos hiding in the room's corners is a long-kept secret that comes to literal or figurative light, or simply some unfolded laundry from last week, the instability introduced to the plot needs to be apparent and inescapable.</p>
<h1>Summary</h1>
<p>The above can be useful in helping us outline, as well as in analyzing our work after it's been written to verify whether we've incorporated these paradigms successfully.</p>
<p>For further exploration, think of your favorite books and movies. How do they make use of the life-death, conscious-unconscious, and order-chaos paradigms? How can you make them work for you in your manuscript?</p>
<p>Dan Harmon's original posts can be found <a href="http://channel101.wikia.com/wiki/Story_Structure_101:_Super_Basic_Shit">here</a> (part one) and <a href="http://channel101.wikia.com/wiki/Story_Structure_102:_Pure,_Boring_Theory">here</a> (part two) for those of you who are curious. <a href="https://www.youtube.com/watch?v=LuD2Aa0zFiA">This video</a> on the topic is also pretty neat, if you're into that sort of thing.</p>
<hr />
<p>Thanks as always for reading. For more writing tips, be sure to explore the <a href="https://ryanrcampbell.com/podcasts/" target="_blank" rel="noopener">r. r. campbell writescast</a>, the <a href="https://ryanrcampbell.com/writing-your-novel/"><em>Write with Me</em> series</a>, or follow me on <a href="http://twitter.com/iamrrcampbell" target="_blank" rel="noopener">Twitter</a>.</p>
<p>&nbsp;</p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default DanHarmonsCircularStructurePartTwo
