import React from 'react'

const ImminentDawnNamedAsFinalistin2020InternationalBookAwards = () =>
  <div>
    <p>I'm honored to announce my science fiction debut, <em>Imminent Dawn</em>, has been selected as a finalist in the 2020 International Book Awards.</p>
<p><a href="https://www.facebook.com/jeffreykeenlosangeles" target="_blank" rel="noopener noreferrer">Jeffrey Keen</a>, President and CEO of <a href="https://www.facebook.com/AmericanBookFest/" target="_blank" rel="noopener noreferrer">American Book Fest</a>, said this year’s contest yielded over 2,000 entries from authors and publishers around the world, which were then narrowed down to the final results.<img loading="lazy" decoding="async" data-attachment-id="7973" data-permalink="https://ryanrcampbell.com/2020/07/23/imminent-dawn-named-as-finalist-in-2020-international-book-awards/imminent-dawn-award-winning-novel/" data-orig-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Imminent-Dawn-Award-Winning-Novel.png?fit=1595%2C1063&amp;ssl=1" data-orig-size="1595,1063" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="Imminent Dawn Award Winning Novel" data-image-description="" data-image-caption="" data-medium-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Imminent-Dawn-Award-Winning-Novel.png?fit=300%2C200&amp;ssl=1" data-large-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Imminent-Dawn-Award-Winning-Novel.png?fit=1024%2C682&amp;ssl=1" class="  wp-image-7973 alignright" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Imminent-Dawn-Award-Winning-Novel.png?resize=240%2C160&#038;ssl=1" alt="Imminent Dawn Award Winning Novel" width="240" height="160" srcset="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Imminent-Dawn-Award-Winning-Novel.png?w=1595&amp;ssl=1 1595w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Imminent-Dawn-Award-Winning-Novel.png?resize=300%2C200&amp;ssl=1 300w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Imminent-Dawn-Award-Winning-Novel.png?resize=1024%2C682&amp;ssl=1 1024w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Imminent-Dawn-Award-Winning-Novel.png?resize=768%2C512&amp;ssl=1 768w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Imminent-Dawn-Award-Winning-Novel.png?resize=1536%2C1024&amp;ssl=1 1536w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Imminent-Dawn-Award-Winning-Novel.png?resize=360%2C242&amp;ssl=1 360w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Imminent-Dawn-Award-Winning-Novel.png?resize=624%2C416&amp;ssl=1 624w" sizes="(max-width: 240px) 100vw, 240px" data-recalc-dims="1" /></p>
<p>Keen says of the awards, “The 2020 results represent a phenomenal mix of books from a wide array of publishers throughout the world.”</p>
<p><em>Imminent Dawn </em>is the story of art-school dropout Chandra, a woman who would do anything to apologize for her role in her wife’s coma—including enroll in the first round of human trials for an internet-access brain implant.</p>
<p>It also follows the story of ruthless tech magnate, Wyatt Halman; relentless investigative journalist, Meredith Maxwell; and advancement-hungry administrative assistant, Ariel Commons.</p>
<p>Forced to confront conspiracies stretching from the highest levels of the North American Union government to the lowest dredges of its shadowy hacking collectives, all four characters are set on a collision course that leaves them fighting to reclaim that which they value most: their loved ones, their freedom, their lives.</p>
<p><em><img loading="lazy" decoding="async" data-attachment-id="7974" data-permalink="https://ryanrcampbell.com/2020/07/23/imminent-dawn-named-as-finalist-in-2020-international-book-awards/imminent-dawn-award-winning-novel-board-room/" data-orig-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Imminent-Dawn-Award-Winning-Novel-Board-Room.png?fit=1600%2C1311&amp;ssl=1" data-orig-size="1600,1311" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="Imminent Dawn Award Winning Novel Board Room" data-image-description="" data-image-caption="" data-medium-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Imminent-Dawn-Award-Winning-Novel-Board-Room.png?fit=300%2C246&amp;ssl=1" data-large-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Imminent-Dawn-Award-Winning-Novel-Board-Room.png?fit=1024%2C839&amp;ssl=1" class="  wp-image-7974 alignleft" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Imminent-Dawn-Award-Winning-Novel-Board-Room.png?resize=238%2C195&#038;ssl=1" alt="Imminent Dawn Award Winning Novel Board Room" width="238" height="195" srcset="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Imminent-Dawn-Award-Winning-Novel-Board-Room.png?w=1600&amp;ssl=1 1600w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Imminent-Dawn-Award-Winning-Novel-Board-Room.png?resize=300%2C246&amp;ssl=1 300w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Imminent-Dawn-Award-Winning-Novel-Board-Room.png?resize=1024%2C839&amp;ssl=1 1024w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Imminent-Dawn-Award-Winning-Novel-Board-Room.png?resize=768%2C629&amp;ssl=1 768w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Imminent-Dawn-Award-Winning-Novel-Board-Room.png?resize=1536%2C1259&amp;ssl=1 1536w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Imminent-Dawn-Award-Winning-Novel-Board-Room.png?resize=624%2C511&amp;ssl=1 624w" sizes="(max-width: 238px) 100vw, 238px" data-recalc-dims="1" />New York Times </em>bestselling author Matt Forbeck has hailed <em>Imminent Dawn </em>as “an incisive techno-thriller that gets more tense with every page,” and, upon its release, <em>Imminent Dawn </em>debuted at number one for its genre on Amazon.</p>
<p>You can order <em>Imminent Dawn </em>through your local bookseller or <a href="https://www.amazon.com/dp/B07N1Q8C6G/" target="_blank" rel="noopener noreferrer">find it on Amazon</a> or via its publisher, <a href="https://ninestarpress.com/product/imminent-dawn/" target="_blank" rel="noopener noreferrer">NineStar Press</a>. The book, which is the first in the EMPATHY sci-fi saga, is available in both ebook and print.</p>
<p>The full list of 2020 International Book Awards winners and finalists can be found <a href="http://www.internationalbookawards.com/2020pressrelease.html" target="_blank" rel="noopener noreferrer">here.</a></p>
<p>Thank you to everyone who has supported this book at every stage of its journey; this book and series would not be where it is today without you.</p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default ImminentDawnNamedAsFinalistin2020InternationalBookAwards
