import React from 'react'

const TheressomeoneIdlikeyoutomeet = () =>
  <div>
    <p style="text-align: center;"><img loading="lazy" decoding="async" data-attachment-id="7946" data-permalink="https://ryanrcampbell.com/2020/07/21/theres-someone-id-like-you-to-meet/rachael-a-edwards-author-photo/" data-orig-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Rachael-A-Edwards-Author-Photo.jpg?fit=1210%2C1814&amp;ssl=1" data-orig-size="1210,1814" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="Rachael A Edwards Author Photo" data-image-description="" data-image-caption="" data-medium-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Rachael-A-Edwards-Author-Photo.jpg?fit=200%2C300&amp;ssl=1" data-large-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Rachael-A-Edwards-Author-Photo.jpg?fit=683%2C1024&amp;ssl=1" class="  wp-image-7946 aligncenter" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Rachael-A-Edwards-Author-Photo.jpg?resize=353%2C529&#038;ssl=1" alt="Rachael A Edwards Author Photo" width="353" height="529" srcset="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Rachael-A-Edwards-Author-Photo.jpg?w=1210&amp;ssl=1 1210w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Rachael-A-Edwards-Author-Photo.jpg?resize=200%2C300&amp;ssl=1 200w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Rachael-A-Edwards-Author-Photo.jpg?resize=683%2C1024&amp;ssl=1 683w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Rachael-A-Edwards-Author-Photo.jpg?resize=768%2C1151&amp;ssl=1 768w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Rachael-A-Edwards-Author-Photo.jpg?resize=1025%2C1536&amp;ssl=1 1025w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Rachael-A-Edwards-Author-Photo.jpg?resize=624%2C935&amp;ssl=1 624w" sizes="(max-width: 353px) 100vw, 353px" data-recalc-dims="1" /></p>
<h2>Meet Rachael A. Edwards.</h2>
<p>Rachael is, like many of you, a reader, a writer, a dreamer. She hails from Chester, England, and, here's something fun: she was born on Halloween.</p>
<p>She's also the embodiment of perseverance.</p>
<p>In 2018, I had the good fortune of mentoring Rachael as part of the 2018 Revise and Resubmit (RevPit) competition. In my capacity as a mentor, I received 100 submissions from the online writing community, and, from them, had to choose one author with whom to work intensively over the course of a six week period.</p>
<p>Our goal by the end of those six weeks? To do a full developmental edit of the manuscript and to revise the query letter such that, by the time our six weeks were up, we could use the new, shinier version of the winner's work to attract the attention of a literary agent.</p>
<p>After reading Rachael's first five pages, her submission immediately had her on my shortlist of prospective mentees. I would go on to request additional material from nearly a dozen others, but part of me always new: I was going to choose Rachael and her eerie—and when it had to be, charming—young adult fantasy manuscript inspired by fate, magic, and Russian and Slavic folklore.</p>
<p><img loading="lazy" decoding="async" data-attachment-id="7949" data-permalink="https://ryanrcampbell.com/2020/07/21/theres-someone-id-like-you-to-meet/rachael-edwards-featured-image-one/" data-orig-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Rachael-Edwards-Featured-Image-One.jpeg?fit=2048%2C2048&amp;ssl=1" data-orig-size="2048,2048" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="Rachael Edwards Featured Image One" data-image-description="" data-image-caption="" data-medium-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Rachael-Edwards-Featured-Image-One.jpeg?fit=300%2C300&amp;ssl=1" data-large-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Rachael-Edwards-Featured-Image-One.jpeg?fit=1024%2C1024&amp;ssl=1" class="  wp-image-7949 alignleft" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Rachael-Edwards-Featured-Image-One.jpeg?resize=248%2C248&#038;ssl=1" alt="Rachael Edwards Featured Image One" width="248" height="248" srcset="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Rachael-Edwards-Featured-Image-One.jpeg?w=2048&amp;ssl=1 2048w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Rachael-Edwards-Featured-Image-One.jpeg?resize=300%2C300&amp;ssl=1 300w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Rachael-Edwards-Featured-Image-One.jpeg?resize=1024%2C1024&amp;ssl=1 1024w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Rachael-Edwards-Featured-Image-One.jpeg?resize=150%2C150&amp;ssl=1 150w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Rachael-Edwards-Featured-Image-One.jpeg?resize=768%2C768&amp;ssl=1 768w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Rachael-Edwards-Featured-Image-One.jpeg?resize=1536%2C1536&amp;ssl=1 1536w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Rachael-Edwards-Featured-Image-One.jpeg?resize=180%2C180&amp;ssl=1 180w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Rachael-Edwards-Featured-Image-One.jpeg?resize=624%2C624&amp;ssl=1 624w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Rachael-Edwards-Featured-Image-One.jpeg?resize=100%2C100&amp;ssl=1 100w" sizes="(max-width: 248px) 100vw, 248px" data-recalc-dims="1" />Folks, I cannot emphasize this enough: <strong>I absolutely adored the version of the manuscript I had the opportunity to read</strong>, and that was <em>before</em> Rach and I spent any time revising and ruminating in order to make it shine that much brighter.</p>
<p>I also, along the way, had the opportunity to get in touch with British slang like “fab” and “brill,” which was an unexpected perk.</p>
<p>But as it's wont to do when trying to read and revise an entire book twice in six weeks, our time working together flew past, and when the day arrived for the literary agent showcase, I was sure Rach would be among the immediate success stories. Surely within days, if not weeks, Rachael and her manuscript would be swept off their feet by an industry professional and prepared for submission to one of the big-time publishers with which many of you are familiar.</p>
<p>It did not, exactly, work out that way.</p>
<p><img loading="lazy" decoding="async" data-attachment-id="7951" data-permalink="https://ryanrcampbell.com/2020/07/21/theres-someone-id-like-you-to-meet/edwards-featured-two/" data-orig-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Edwards-Featured-Two.jpeg?fit=945%2C756&amp;ssl=1" data-orig-size="945,756" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="Edwards Featured Two" data-image-description="" data-image-caption="" data-medium-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Edwards-Featured-Two.jpeg?fit=300%2C240&amp;ssl=1" data-large-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Edwards-Featured-Two.jpeg?fit=945%2C756&amp;ssl=1" class="  wp-image-7951 alignright" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Edwards-Featured-Two.jpeg?resize=324%2C259&#038;ssl=1" alt="Edwards Featured Two" width="324" height="259" srcset="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Edwards-Featured-Two.jpeg?w=945&amp;ssl=1 945w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Edwards-Featured-Two.jpeg?resize=300%2C240&amp;ssl=1 300w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Edwards-Featured-Two.jpeg?resize=768%2C614&amp;ssl=1 768w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/07/Edwards-Featured-Two.jpeg?resize=624%2C499&amp;ssl=1 624w" sizes="(max-width: 324px) 100vw, 324px" data-recalc-dims="1" /></p>
<p>Summer came and went. Fall, too. Winter descended without anything coming of Rach's brilliant showcase, and all of our hard work in those six weeks felt as though it might have been for naught.</p>
<p>This was not, as Rach might say, fab.</p>
<p>But Rach didn't let this deter her. She queried agents the traditional way, by looking them up online, evaluating their interests, and, if it felt like this agent might be a good fit, emailing them with her manuscript's query letter (cover letter) and some sample pages.</p>
<p>Rach would do this for months. A year. Nothing.</p>
<p>In the meantime, she continued to write, but I know the lack of perceived success for the manuscript she referred to as THREADS (as in THREADS OF FATE) was taking its toll. It broke my heart to see tweets from her in which she contemplated abandoning the project altogether.</p>
<p>But she didn't quite do that, no. Instead, based on my understanding from afar, she rewrote the manuscript. We're talking earth-shaking, tectonic plate-level rewrites. I always imagined the world and the characters were the same, but it seemed the threads we so carefully stitched in our time together were simply not destined to be.</p>
<p>And yet: even these substantial revisions bore no fruit.</p>
<p>Rach and I stayed in touch throughout it all, and I was honored when she asked me for a letter of recommendation to an MA program in creative writing. This not only gave me an opportunity to rave about Rach and her writing; it let me, as I would say in the letter of recommendation, revisit her manuscript that, “to this day, captures my imagination during life's quiet moments.”</p>
<p>This venture, however, also proved to be a dead end. I sincerely started to worry Rach might abandoning writing altogether. And could you blame her if she had? By this time, rejection's jagged edge would have cut most people far too deep for them to consider pressing on.</p>
<p>But nevertheless, Rachael persisted.</p>
<p>And finally:</p>
<blockquote class="twitter-tweet" data-width="550" data-dnt="true">
<p lang="en" dir="ltr">*drum roll*</p>
<p>I am so beyond excited to announce I am now represented by the amazing <a href="https://twitter.com/renarossner?ref_src=twsrc%5Etfw">@renarossner</a> of The Deborah Harris Literary Agency!! 🥰 Rena’s enthusiasm and belief in my wintery, Slavic book about fate magic is everything I could have ever hoped for in an agent!! <a href="https://t.co/n6zPvrNkIn">pic.twitter.com/n6zPvrNkIn</a></p>
<p>&mdash; Rachael A Edwards 🌙 ❄️ - on (semi) hiatus (@RachaelAWrites) <a href="https://twitter.com/RachaelAWrites/status/1283103129454678017?ref_src=twsrc%5Etfw">July 14, 2020</a></p></blockquote>
<p><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></p>
<blockquote class="twitter-tweet" data-width="550" data-dnt="true">
<p lang="en" dir="ltr">I have SO MANY people to thank and I’m probably going to forget people but first I wanna thank the <a href="https://twitter.com/ReviseResub?ref_src=twsrc%5Etfw">@ReviseResub</a> 2018 gang, especially my mentor <a href="https://twitter.com/iamrrcampbell?ref_src=twsrc%5Etfw">@iamrrcampbell</a> 🖤 you were one of the first people to believe in this story and I wouldn’t have gotten here without you all! <a href="https://twitter.com/hashtag/revpit?src=hash&amp;ref_src=twsrc%5Etfw">#revpit</a></p>
<p>&mdash; Rachael A Edwards 🌙 ❄️ - on (semi) hiatus (@RachaelAWrites) <a href="https://twitter.com/RachaelAWrites/status/1283104204505194510?ref_src=twsrc%5Etfw">July 14, 2020</a></p></blockquote>
<p><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></p>
<p>Just this last week, Rachael was able to make public some news she had shared with me privately a few days earlier: at long last, THREADS found representation in Rena Rossner, a literary agent at The Deborah Harris Literary Agency.</p>
<p>I'd be lying if I said I didn't tear up at the news.</p>
<p>Oh, and did I mention the version that attracted Rena's attention was the one Rach and I had poured our hearts into two years ago?</p>
<p>Whew.</p>
<p>I could go on about the importance of perseverance, about how one should never give up, but Rach's lived journey tells you all you need to know and more.</p>
<p>So whether you're a writer, an artist, searching for a job or trying to learn a new skill, know that success can and will come.</p>
<p>You'll have to do the work, but it <em>will</em> happen.</p>
<p>And I think that's pretty fab.</p>
<hr />
<p style="text-align: center;"><strong><a href="http://www.twitter.com/rachaelawrites" target="_blank" rel="noopener noreferrer">Follow Rach's ongoing journey on Twitter here.</a></strong></p>
<p style="text-align: center;"><strong><a href="http://www.rrcampbellwrites.com/coaching">Learn more about working with me as your writing coach.</a></strong></p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default TheressomeoneIdlikeyoutomeet
