import React from 'react'

const TheHerosJourneyandAdventureTimePartOne = () =>
  <div>
    <p style="text-align: center;"><em>This post is part of the&nbsp;</em>Outline With Me&nbsp;<em>series.&nbsp;</em><em>For more like this, check out the <a href="https://ryanrcampbell.com/outlining-your-novel/">outlining your novel</a> page.</em></p>
<p style="text-align: center;"><em><strong>Author's note:&nbsp;</strong>this content is now available as a podcast, complete with additional perspective. You can find the podcast version <a href="http://writescast.net/2018/10/05/bibliobreakdown003" target="_blank" rel="noopener">at this link</a>.</em></p>
<p>So you've got your <a href="http://ryanrcampbell.com/2016/12/09/the-logline-your-novel-in-50-words-or-fewer/" target="_blank" rel="noopener noreferrer">logline</a>, but, after checking out the seven-point story structure in <a href="http://ryanrcampbell.com/2016/12/16/from-logline-to-narrative-arc-connecting-the-dots-part-one/" target="_blank" rel="noopener noreferrer">these</a> <a href="http://ryanrcampbell.com/2016/12/23/from-logline-to-narrative-arc-connecting-the-dots-part-two/" target="_blank" rel="noopener noreferrer">posts</a>, you're not sure if it's right for your story.</p>
<p>Then let's explore another traditional storytelling structure&#8212;namely, Joseph Campbell's (no relation) The Hero's Journey, otherwise known as the monomyth.</p>
<p>The Hero's Journey differs from the seven-point structure in that it consists of twelve steps and is generally incorporated&nbsp;more often in epic storytelling a là&nbsp;<em>Star Wars&nbsp;</em>(episode IV is a prime example) or the&nbsp;<em>Lord of the Rings</em> series.</p>
<p>Your story need not be an epic in Sci-fi or Fantasy in order to make use of The Hero's Journey, however. For&nbsp;<a href="http://www.accountingforitall.com"><em>XXX Accounting</em></a>&#8212;which has taken shape as adult contemporary fiction&#8212;I used The Hero's Journey to construct my protagonist's timeline in the present, but implemented&nbsp;more of a seven-point and Hero's Journey hybrid for her past.</p>
<p>As further evidence that we need not have a trilogy or series lined up to take advantage of this structure, for this two-part series we'll be seeing how Pendleton Ward and his team of writers&nbsp;employed (most of) this structure in a twelve minute(!) episode of the popular cartoon&nbsp;<em>Adventure Time</em>.</p>
<p class="separator" style="clear: both; text-align: center;"><i>Note: If you haven't watched this particular episode of </i>Adventure Time<i>, now might be the time. </i>The Enchiridion <i>is episode five of season one, which is available for streaming on Hulu as of the time of this post.</i></p>
<h1 class="separator" style="clear: both; text-align: left;">The Ordinary World</h1>
<p class="separator" style="clear: both; text-align: left;">The ordinary world is how our Hero's Journey stories open:&nbsp;where the reader (henceforth “viewer” in our analysis) sees the world as it exists for our hero before the introduction of the primary conflict.</p>
<p class="separator" style="clear: both; text-align: left;">In this (and all) episodes of <em>Adventure Time</em>,&nbsp;the opening credits themselves provide a brief overview of the ordinary world&#8212;that is to say, everything that happens leading up to the fist bump Finn and Jake share to kick-off the show's theme song.</p>
<p class="separator" style="clear: both; text-align: left;">We see further establishment of the ordinary world in the moments immediately following the show's introduction, in which we see that a party that is taking place in the Candy Kingdom. &nbsp;Everything's fine, everything's good…</p>
<p class="separator" style="clear: both; text-align: left;">Until some clumsy donut dives into the tower from which Princess Bubblegum is overseeing the goings-on below. &nbsp;The princess falls from high above, but Finn rescues her just before she hits the ground. Our hero's prowess in the ordinary world has now been established, and we're less than a minute into the episode! &nbsp;Finn's heroics give Princess Bubblegum an idea, which leads us to…</p>
<h1 class="separator" style="clear: both; text-align: left;">The Call to Action</h1>
<p class="separator" style="clear: both; text-align: left;">In the broadest sense, this step is the moment when the hero faces some sort of challenge or change to their ordinary world. In the second scene of this episode, Princess Bubblegum presents Finn with an image of<i>&nbsp;</i>The Enchiridion, a book that, were he to possess it, would make him an “even better hero.” The problem? It lies in Mount Cragdoor and is guarded by “a manly minitaur.” Princess Bubblegum says the book is waiting for a righteous hero to claim it.</p>
<p class="separator" style="clear: both; text-align: left;">At this juncture in the Hero's Journey, our protagonist must decide whether to take up or refuse this call to action. That is to say: will we have a reluctant or eager hero?</p>
<h1 class="separator" style="clear: both; text-align: left;">A Refusal of the Call</h1>
<p class="separator" style="clear: both; text-align: left;">In most Hero's Journey arcs, this our protagonist initially refuses this call. Showing our protagonist as reluctant leaves room for growth and can deepen the notion that they're really making a sacrifice by going on this journey.</p>
<p class="separator" style="clear: both; text-align: left;">In <em>Adventure</em> <em>Time</em>, however, the whole point is, well, adventure. This is what leads Finn to immediately take up the call, literally saying he is “totally into this [adventure] stuff.”&nbsp;He&nbsp;does have one moment of brief hesitation when he asks Princess Bubblegum if she thinks he will succeed,&nbsp;but Finn's doubt is short-lived:&nbsp;Finn then proceeds to dive out of a window and onto&nbsp;the next step of The Hero's Journey.</p>
<h1 class="separator" style="clear: both; text-align: left;">Meet the Mentor</h1>
<p class="separator" style="clear: both; text-align: left;">Before Finn hits the ground (he just jumped out of a window, remember)&nbsp;Jake, his&nbsp;best friend, catches him before he falls to his cartoon death. It's in this moment that Finn has met his mentor: the individual who will train or advise the protagonist as part of his quest.</p>
<p class="separator" style="clear: both; text-align: left;">One could understandably argue that Jake is more of an ally than a mentor, but in either case we're seeing the introduction of a partner with whom our hero will take on&nbsp;the challenges that ahead.</p>
<p class="separator" style="clear: both; text-align: left;">Without providing his mentor with any details, Finn enlists Jake in the quest.</p>
<p class="separator" style="clear: both; text-align: left;">They're off to Mount Cragdoor!</p>
<h1 class="separator" style="clear: both; text-align: left;">Cross the Threshold</h1>
<p>As the fifth step in our Hero's Journey, the crossing of the threshold is the moment where we would normally have a&nbsp;turning point for our protagonist, one in which he or she abandons the ordinary world and begins their quest. Critically, this should be seen as a point of no return: once our protagonist crosses this threshold, they can't go back to life as it was before.</p>
<p>This episode of&nbsp;<em>Adventure Time</em> takes the crossing of the threshold about as literally as it possibly could, however: Finn and Jake simply walk across a drawbridge over a moat.</p>
<p>That's it. That's their “crossing of the threshold.”</p>
<p>I understand how this might seem like a cop-out, but keep in mind these episodes are twelve minutes long and we have twelve steps to cover. With the real meat of The Hero's Journey before us, it makes sense the show's writers wouldn't spend too much time lingering on this threshold moment.</p>
<p>As writers ourselves, though, this can be one final moment to show some trepidation on the part of our protagonist&#8212;perhaps they recognize that once they take this action or say these words or swear this oath, their lives will never be the same.</p>
<p>Again, though, Finn is “totally into this [adventure] stuff” so there's no sense in dwelling too long on the crossing of the threshold. Speaking of which…</p>
<h1>Tests, Allies, and Enemies</h1>
<p>Though they're all important, this is a major step in the&nbsp;the Hero's Journey. This is where our protagonists are tested both physically and mentally, and their relationship with their mentor may or may not become strained. Will our hero become disillusioned with the quest on which they've been sent, or perhaps even with the person they've become? This is where these seeds of doubt can be sown, for this garden is great and full of action, and why not make our protagonist's struggle that much&nbsp;greater?</p>
<p>Really, though, the emphasis of this step in the Hero's Journey is on the action: there are puzzles to solve, alliances to be made (and broken?), and enemies to identify and defeat.</p>
<p>Once Finn and Jake cross the threshold in “The Enchiridion,” they encounter a gatekeeper&#8212;Keeper, as he is so aptly named (he's even dressed like a key)&#8212;who confronts them with a riddle.</p>
<p>Keeper gives a long-winded speech about how many have tried to enter, but none have had the key to use in the locked gate that separates Mount Cragdoor from the outside world. As Keeper keeps rattling on, Finn&#8212;without so much as a word&#8212;picks up Keeper, inserts him into the lock, and walks on through the gate.</p>
<p>To make this moment even more on the nose, Keeper then hollers after Finn and Jake as they walk away. “You've passed the first trial, young heroes,” he says, in an extremely explicit acknowledgment of the episode's Hero's Journey structure. After Finn and Jake are out of earshot, Keeper even adds that “there are many trials ahead of you, and each trial is more treacherous than the last.”</p>
<p class="separator" style="clear: both; text-align: left;">And just like that, we're set up for the rest of step six. We're at the halfway mark in The Hero's Journey, and we're hardly over four minutes into the episode. Algebraic, am I right?</p>
<p class="separator" style="clear: both; text-align: left;">From here on out, there are at least two major tests that Finn faces as part of this stage in his journey. To paint with a wider brush, however, I'll offer up some additional examples of what one might encounter during this step from another favorite of mine, the&nbsp;<em>A Song of Ice and Fire</em> series. Some spoilers through&nbsp;<em>A Clash Of Kings</em>&nbsp;or season two of <em>Game of Thrones</em>&nbsp;below.</p>
<p class="separator" style="clear: both; text-align: left;">Think of Jon Snow (classic Hero's Journey arc). In&nbsp;<em>A Clash of Kings</em>, he ends up beyond the Wall as part of the Night's Watch's mission to figure out what Mance Rayder's up to, as well as to see if they can find his presumably dead uncle Benjen. The entire time Jon's beyond the wall is basically this sixth step in The Hero's Journey. He's <em>test</em>ed when he's tasked with killing a wildling (Ygritte), who, though originally his prisoner, makes Jon&nbsp;<em>her&nbsp;</em>prisoner (<em>enemy</em>). Jon is then reunited with the also captured Qhorin Halfhand (<em>ally</em>), and while all of this is going on we see Ygritte slowly go from <em>enemy to ally</em> by sticking up for Jon a few times when Rattleshirt would have much rather had him executed.</p>
<p class="separator" style="clear: both; text-align: left;">The list goes on. Seriously, go (re)read Jon's arc in particular and you can find many of these steps strewn throughout&nbsp;his story.</p>
<h1>Checkpoint</h1>
<p>No, “checkpoint” isn't the seventh step in The Hero's Journey&#8212;it's just where we'll leave things for now. The remaining six steps of The Hero's Journey in the context of&nbsp;<em>Adventure Time&nbsp;</em>are&nbsp;featured in&nbsp;<a href="https://ryanrcampbell.com/2017/05/12/the-heros-journey-and-adventure-time-part-two/">this post</a>.</p>
<hr>
<p>Thanks for reading. Have thoughts on the above? Noticing The Hero's Journey in other media and want to chat about it? You can find me on <a href="http://www.twitter.com/iamrrcampbell" target="_blank" rel="noopener noreferrer">Twitter</a> or email me through my <a href="http://ryanrcampbell.com/contact/">contact page</a> if you'd like to chat.</p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default TheHerosJourneyandAdventureTimePartOne
