import React from 'react'

const AnOutlinesNotaContractPartTwo = () =>
  <div>
    <p style="text-align:center;"><em>This post is part of the </em>Outline With Me <em>series. </em><em>For more like this, check out the <a href="https://ryanrcampbell.com/outlining-your-novel/">outlining your novel</a> page.</em></p>
<p class="separator" style="clear:both;text-align:left;">After covering The Paper Trail method in <a href="http://ryanrcampbell.com/2017/05/01/an-outlines-not-a-contract-part-one/">part one</a> of this mini-series, part two will focus on the use of beat sheets.</p>
<h1 class="separator" style="clear:both;text-align:left;">Beat Sheets</h1>
<p class="separator" style="clear:both;text-align:left;">In light of my admittedly muddled outlining approach for <em>The Fugue</em>, I did some independent research, and, after incorporating into it some of what I learned at my first writers' conference in 2013, I decided to give a beat sheet a try. A beat sheet is, well, a sheet of beats, with a beat being any event of significance that occurs in the course of the narrative. These include not only any one of the moments in our seven-point plot structure or steps of The Hero's Journey, but also developments like a character learning a critical bit of information, coming into possession of a useful item, or undergoing some change in perspective, for example.</p>
<p class="separator" style="clear:both;text-align:left;">Using a template I found <a href="http://www.danielrmarvello.com/archive/2011/07/29/evolution-of-a-beat-sheet.aspx" target="_blank" rel="noopener noreferrer">here</a>, I got to making a spreadsheet of my own, a sample of which ended up looking something like this:</p>
<div style="width: 650px" class="wp-caption alignnone"><a style="margin-left:1em;margin-right:1em;" href="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2013/05/b65b5-screenshot2013-05-12at5-44-59pm.png?ssl=1"><img loading="lazy" decoding="async" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2013/05/b65b5-screenshot2013-05-12at5-44-59pm.png?resize=640%2C281&#038;ssl=1" width="640" height="281" border="0" data-recalc-dims="1" /></a><p class="wp-caption-text">The beats themselves were originally blurred as to prevent spoilers, but with how much the manuscript has changed since 2013, I have to believe hardly any of the above beats are still in the manuscript.</p></div>
<p>&nbsp;</p>
<p class="separator" style="clear:both;text-align:left;">The above may only be a tidbit of the full beat sheet, but the gist is clear: columns for chapter, beat, point of view, the scenes themselves, setting, location, date, and then two columns for word-count per chapter and total word count. I even added pretty colors to track changes in the columns so that I could spot them as I wrote.</p>
<h2 class="separator" style="clear:both;text-align:left;">Pros</h2>
<p class="separator" style="clear:both;text-align:left;">The principle advantage I had with this system compared to The Paper Trail was that it was significantly easier to update. Aside from this, it allowed me to track the dates on which given events occurred, which became critical in a novel featuring four perspectives. If only I'd kept making use of beat sheets as I got into later drafts, I could've saved myself a lot of time lost to questions like: “Oh, wait. They said they were going to do that on Wednesday, but they agreed to do so on a Thursday, right? That means we have a week before&#8212;well, no. I think this scene is actually happening on a Friday, though, if I map it out.”</p>
<p class="separator" style="clear:both;text-align:left;">Why not save ourselves from tiresome continuity questions like that by using a beat sheet?</p>
<h2 class="separator" style="clear:both;text-align:left;">Cons</h2>
<p>Though beat sheets have their upsides, I eventually moved away from this model for two main reasons. Firstly, managing something so detailed&#8212;though valuable&#8212;didn't seem worth the patience required to maintain it as I made changes to the plot. If you're anything like I was when writing the early drafts of <em><a href="http://ryanrcampbell.com/current-projects/" target="_blank" rel="noopener noreferrer">EMPATHY</a></em>, your goal is to stay focused on the writing itself, which is of course imperative. That's perfectly fine, but it's worth noting there may be some work required after finishing a draft to go back and sort out your timelines after the fact.</p>
<p>The second reason I jumped ship on beat sheets actually ties directly into the first&#8212;every time I wanted to make a change, I felt like I had to consult this imposing, prescriptive outline. In keeping with the theme of this mini-series, however, I ultimately recognized that an outline wasn't a contract. I had to let the plot grow where it may, even if it came at the expense of deviating from my outline at times.</p>
<h1>Summary</h1>
<p>If you're looking for a close-up view of your manuscript's critical moments and don't mind maintaining it as you make changes to your plot, then a beat sheet is probably right for you. Looking back, I wish I had kept up with the beat-sheet method as I progressed through my drafts for <em>EMPATHY</em>.</p>
<p>For the most recent drafts of <em>EMPATHY</em>, however, I did return to a beat-sheet-esque model, which we'll cover in part three of this mini-series. Watch for more later this week.</p>
<hr />
<p>Thanks for reading. Have a different take on beat sheets or want to share your experience with them? Let me know on <a href="http://www.twitter.com/iamrrcampbell" target="_blank" rel="noopener noreferrer">Twitter</a> or through my <a href="http://ryanrcampbell.com/contact/">contact page</a>. It'd be great to hear from you.</p>
<h1></h1>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default AnOutlinesNotaContractPartTwo
