import React from 'react'

const TheHerosJourneyandAdventureTimePartTwo = () =>
  <div>
    <p style="text-align: center;"><em>This post is part of the&nbsp;</em>Outline With Me&nbsp;<em>series.&nbsp;</em><em>For more like this, check out the <a href="https://ryanrcampbell.com/outlining-your-novel/">outlining your novel</a> page.</em></p>
<p style="text-align: center;"><em><strong>Author's note:&nbsp;</strong>this content is now available as a podcast, complete with additional perspective. You can find the podcast version <a href="http://writescast.net/2018/10/05/bibliobreakdown003" target="_blank" rel="noopener">at this link</a>.</em></p>
<p>In the <a href="https://ryanrcampbell.com/2017/05/10/201304the-heros-journey-and-adventure-time-html/" target="_blank" rel="noopener noreferrer">previous post</a> in this mini-series, we walked through&nbsp;the first six stages of The Hero's Journey as featured in season one, episode five of&nbsp;<em>Adventure Time.&nbsp;</em>This post will cover the remaining six steps of this journey, all with the goal of helping us consider how we might implement a similar structure into our own work.</p>
<p>That being said, let's hop into step seven of The Hero's Journey and Adventure Time.</p>
<h1 class="separator">The Approach</h1>
<p class="separator">At this stage, the hero and his or her allies prepare to confront their primary challenge. Turning back to our&nbsp;<em>Adventure Time&nbsp;</em>example, this is the moment when Finn and Jake enter the “brain world” of a creature that seems to dwell inside the castle. &nbsp;This creature presents Finn with a beast that he says is “most certainly evil,” and Finn has no problem destroying&nbsp;it as part of what the castlekeeper says is “the last trial.” &nbsp;But he lies! &nbsp;For after Finn has slain the evil beast, he encounters…</p>
<h1 class="separator">The Ordeal</h1>
<p class="separator">Here our hero faces his or her primary challenge. This is the moment we've all been waiting for. As we'll soon see, this is a moment in which the hero (often) triumphs, but at some cost to him or herself (or someone they love) personally.</p>
<p class="separator">In <em>The Enchiridion</em>,&nbsp;Finn&#8212;still trapped in the castlekeeper's brain world&#8212;is presented with the “last last trial” of killing an ant. Finn, wanting to know whether or not the ant is evil, asks this question of the castlekeeper, who says the ant is “unaligned.” Finn must decide whether he will kill the unallied ant, sacrificing some of the goodness in himself to do so&#8212;all in the name of receiving The Enchiridion. Finn seems trapped until he breaks free of the castlekeeper's brain world and kicks him right in the craw, disabling the castlekeeper and overcoming the final challenge.</p>
<p class="separator">“So wait,” one might say, “but he didn't have to sacrifice part of himself, and he didn't even take on the task that was assigned to him.”</p>
<p class="separator">That's true, but Finn did make use of his wits (and foot) a bit in finding an option beyond the do-thing-one-or-do-thing-two paradigm. I've also heard moments like these described as “the dilemma,” wherein a character faces a tough choice, but finds some sort of loophole in the rules or defies the&nbsp;premise of the choice presented to them. A popular example of this can be found in&nbsp;<em>The Hunger Games</em> when Katniss encourages Peeta to pretend as though the two of them are to eat some poisonous berries (spoilers follow). By doing this rather than fighting one another to do the death, they spare both of their own lives, as those in charge of the games did not anticipate this third outcome (wherein both die), which actually leads to a fourth outcome (they both live).</p>
<h1 class="separator">The Reward</h1>
<p class="separator">Finally our hero overcomes the ordeal! Oftentimes, however, there exists the possibility that they may lose their reward for having done so.</p>
<p class="separator">Back in <em>Adventure Time</em>, this is the moment in which the manly minitaur enters into the scene and hands The Enchiridion over to Finn. He receives all sorts of praise from the minitaur and Keeper.</p>
<p class="separator">We don't really&nbsp;get the feeling that Finn might lose his reward, however, and the next three steps in the Hero's Journey are more or less skipped over in this particular episode. Why, you ask? Well, remember we only have twelve minutes of show available to us, and through these nine steps we've already seen the (almost) completion of a full story arc.</p>
<p class="separator">That the final three steps are either not featured or included very briefly is only a testament to the notion that these “formulas” are meant to be toyed with. Just like outlines are not contracts, we as writers shouldn't feel as though we have to adhere exactly to any one structure&#8212;though it'd behoove us to incorporate some sort of structure, lest we end up with our characters milling about with nothing to lose.</p>
<p class="separator">Let's consider how the remaining steps&nbsp;<em>could have</em> been incorporated into this episode, however, for those who want to explore all twelves steps.</p>
<h1 class="separator">The Road&nbsp;Home</h1>
<p>Ordinarily, this step is when our hero finds him- or herself on the (sometimes very literal) road home to the ordinary world. If our character stands to lose their reward, this is the moment where they must confront that possibility.</p>
<p>Hypothetically, let's say as Finn and Jake are traveling home, some sort of elf-witch floats out of the woods and onto the trail, revealing herself to have been the puppet-master between all our heroes' previous trials.</p>
<p>She tells Finn that the pages of&nbsp;<em>The Enchiridion</em> are poisonous to the touch, and that he only has minutes to retrieve the antidote from the amulet around her neck. Furthermore, unless the antidote is also poured upon the pages of The Enchiridion itself, its pages will melt away and no hero will ever again have the chance to possess its powers.</p>
<p>Higher stakes than before? Check. Reward at risk of being lost? Absolutely. A little dark for a children's TV show? Yeah, you could say that.</p>
<p>But at any rate, we now have everything necessary for the eleventh step.</p>
<h1>The Resurrection</h1>
<p>As suggested above, this is the moment when the hero faces his or her final battle, with higher stakes than before and at risk of everything they've fought for being lost.</p>
<p>In our hypothetical minute eleven of this episode, let's say Finn battles this witch and ultimately defeats using&nbsp;similar guile to that which he used to overcome the “last last trial.” For example, he might point over her shoulder and say, “Look out, the manly minitaur is coming.” He's not, but he says it anyway.</p>
<p>When she looks, perhaps he snatches the amulet from her neck, glugs some of it for himself, and pours the remainder over the pages of The Enchiridion.</p>
<p>That feels a little cheap, though, doesn't it? It is a bit too&nbsp;easy, but this is a cartoon, after all, and we probably don't have airtime left for a protracted battle at this point. Finn could pay some price for these shenanigans, though: perhaps after having the antidote poured on them, the ink on the pages&nbsp;runs and some information in The Enchiridion is lost forever.</p>
<h1>Return Home</h1>
<p>This final step is the moment in which our heroes return home, triumphant (probably) and changed (hopefully, though for the better or for the worse is up to you). This is a good moment to include reflections on the latter especially, as it is a natural segue into theme, lessons learned, and where our characters might go from there.</p>
<p>We actually do see a brief return home in this <em>Adventure Time</em>&nbsp;episode (kind of), as Princess Bubblegum appears via a magic bubble to join the celebration that Finn and Jake are having after their triumph over their many trials. It's not a full and complete return to the Candy Kingdom, but given the amount of time the show has to work with, it more than suffices.</p>
<h1>Summary</h1>
<p>If&nbsp;<em>Adventure Time</em> can incorporate nearly all twelve steps of The Hero's Journey in twelve minutes of airtime, we can almost certainly do so over the course of our own narratives.</p>
<p>After having read up on both the seven-point plot structure and The Hero's Journey, which one do you think might work best for your story? Maybe try plotting it out using both, and see which one might work best for you.</p>
<p>Or, if you're still not sure either structure is quite right, play with the formulas a bit and see if you can make&nbsp;<em>them</em> work for&nbsp;<em>you</em> (rather than the other way around).</p>
<p>Once you've made your (very broad) outline, feel free to hop into the next step as listed in this&nbsp;<em>Outline With Me</em> series&#8212;namely, that of <a href="http://ryanrcampbell.com/2016/12/30/character-at-the-core-the-importance-of-depth/">character development</a>.</p>
<hr>
<p>Thanks for reading. If you have thoughts on The Hero's Journey or plot structure in general, you can always reach out to me on <a href="http://www.twitter.com/iamrrcampbell" target="_blank" rel="noopener noreferrer">Twitter</a>, or find me via my <a href="http://ryanrcampbell.com/contact/">contact page</a>.</p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default TheHerosJourneyandAdventureTimePartTwo
