import React from 'react'

const MurderTheLiterarilyLiteral = () =>
  <div>
    <p>Kill your darlings, <a href="http://www.slate.com/blogs/browbeat/2013/10/18/_kill_your_darlings_writing_advice_what_writer_really_said_to_murder_your.html" target="_blank" rel="noopener noreferrer">they</a> say. Every writer has at least heard the phrase, and the interpretations of what it really means vary from deleting a <a href="http://www.writersdigest.com/editor-blogs/writers-perspective/writing-technique/kill-your-darlings-and-other-terrifying-advice" target="_blank" rel="noopener noreferrer">favorite phrase</a> to <a href="http://writeroutine.blogspot.com/2012/02/how-to-kill-your-darlings.html" target="_blank" rel="noopener noreferrer">an entire beat or event</a>. Those darlings aren't what we'll focus on in this post, however. Today, we're talking murder&#8212;actual, literary murder.</p>
<p>In literature as in life, people die. George R.R. Martin is (in)famous for killing off his characters, as <a href="https://www.wired.com/images_blogs/underwire/2013/11/Screen-shot-2013-11-20-at-9.52.03-AM.png" target="_blank" rel="noopener noreferrer">nearly any chapter</a> in the <i>A Song of Ice and Fire</i> series can attest. It should go without saying that the impact of a well executed, literal character assassination can go a long way in creating emotional resonance and contributing to theme or character development, but how can a writer maximize that impact when they decide the time has come for one of their characters to meet their maker?</p>
<p>Though there are a number of approaches to creating a memorable end-scene for a character, I'd like to focus on the three main (poisonous?) ingredients that a writer can use to help achieve this goal: <b>character appeal</b>, <b>timeliness of death</b>, and <b>manner of death</b>.</p>
<h2>Character Appeal (or Lack Thereof)</h2>
<p>So let's say you decide it's time for Henchman #4 to stop carrying out orders and start pushing daisies. That's fine, but who really gives half a hoot about him? He didn't even have a name!</p>
<p>Well, he didn't have a name to you, maybe, but he had a name to <i>someone</i>. And that's the trick, really; we need to make our readers that <i>someone, </i>and we need the character in question to be a person that our reader can get behind (or root against!). Consider the following scenario.</p>
<p>As it turns out, Henchman #4's real name is Dale. Dale has a wife and five kids, and only signed up to work for the evil Doctor Zygbo part-time because he needed a second job to help get his fifth child through school. Dale works days at the local Fun Mart for mere pennies over minimum wage, and at night, he toils for Zygbo, pushing buttons and flipping switches to further the doctor's evil designs.</p>
<p>“But wait,” you might say, “even if he has all those other things going on, couldn't he have picked up another shift at Fun Mart or gotten a job working as a janitor or something? Working for the evil doctor makes Dale a real jerk.”</p>
<p>I hate to break it to you, but the answer is no, he couldn't have done those things. Fun Mart keeps its employees working under 32 hours a week to avoid having to provide health insurance, and the only other place in town that was hiring was the puppy mill. Did I mention Dale has a soft spot for puppies? Well, he does. He loves puppies almost as much as he loves his wife and five children. He would never work at the puppy mill and you should never adopt from one.</p>
<p>Now that we've established Dale is a generally upstanding guy who, as a matter of circumstance and personal conviction, just happened to get sucked into Doctor Zygbo's hiring spree, let's move on to the next major matter that could make his previously anonymous death that much more impactful.</p>
<h2>Timeliness of Death</h2>
<p>What I mean by timeliness of a character's death has less to do with the day of the week and everything to do with where the character is at in their development arc. Where are they in their journey to accomplish their primary goal? What will the impact be of their success or failure as it relates to that goal?<b><br />
</b></p>
<p>Again, let's bring this back to good old Dale&#8212;sweet, puppy-loving, father-of-five Dale. We'll also add to the narrative that Dale got his job at Doctor Zygbo's Death Emporium to earn extra scratch for his youngest daughter's college education (she wants to be a veterinarian, you know).</p>
<p>What happens if we learn that he actually accomplished that goal months ago, and is now showing up for work out of simple habit at the time of his death? If you're a knee-jerk <a href="http://www.wpr.org/shows/why-we-blame-victims" target="_blank" rel="noopener noreferrer">victim-blamer</a> (emphasis on “jerk”), you might say something like, “well, he should have quit when he had the chance” or “he got what he deserved for selling out to Zygbo in the first place.” Others might say it's all the more tragic that he died <i>after</i> accomplishing his goal, as his death came about needlessly.</p>
<p>But what if, at the time of his death, he was still a year away from finally having saved up enough to send little Melanie (that's her name now) off to college debt-free? What if, as he looked forward to counting down the months and weeks and days to accomplish this goal, his inner thoughts revealed a man increasingly more troubled with what he had to do for Doctor Zygbo on a nightly basis? Dale would be able to forgive himself someday, right? His family would forgive him if they ever found out where the money came from, wouldn't they?</p>
<p>Lordy, even I'm starting to feel bad for Dale under that scenario.</p>
<p>Now let's compare the <i>impact</i> those two possible scenarios would have on readers. In the first setup, his family would be crushed, of course, but as it relates to Dale's primary goal, his daughter would be able to afford school, at least.</p>
<p>In the second scenario, however, not only does Dale's family have to confront his loss, but Dale himself would have died before achieving the one thing he was willing to sacrifice his integrity for. On top of that, little Melanie would have to take out massive loans for her education, something her generally risk-averse personality would ultimately discourage her from doing. Without her veterinary degree, there'd be a far greater number of sick puppies lolling around, a further affront to her father's puppy-loving memory. An extraordinary tragedy, folks. It'd be an extraordinary tragedy.</p>
<h3 style="text-align: center;">“Yeah, but emphasizing the impact of the second scenario feels like it's affirming tragedy porn.”</h3>
<p>For the unfamiliar, tragedy porn is that which relies on <em>tragedy for the sake of tragedy</em> to prove a broader point to a particular audience.</p>
<p>So, yeah… suggesting the second scenario above is absolutely superior could definitely be viewed as an affirmation of tragedy porn. That said, though I certainly fleshed out the consequences for that scenario more than the first, that's not to say it's the “one right answer” in cases like these.</p>
<p>As with all things writing, there's plenty of room for nuance. The important takeaway here shouldn't be that maximizing tragedy is One Hundred Percent the Way to Go<span style="background-color: white; color: #252525; font-family: sans-serif; font-size: 17.5px;">™</span>, but rather that we ought to be deliberate about the choices we make in our storytelling. It would be <em>perfectly valid</em> to have Dale perish after having saved up enough for his daughter's education (scenario one); the choice an author ultimately makes, however, all depends on they want to say in this moment and what they want readers to leave the page with.</p>
<p>Simply put, neither scenario is inherently superior to the other; judiciousness is where our focus ought to be.</p>
<p>That said, let's proceed under the assumption Dale's death comes before he's saved enough for his daughter's schooling, and let's say you're still one of those holdouts who says, “I don't appreciate the nuance of individuals having to make ideological sacrifices in order to overcome oppressive circumstances. Dale is still a jerk because he worked for Doctor Zygbo.”</p>
<p>Well, strap in. This is where it gets real.</p>
<h2>Manner of Death</h2>
<p>When I say “manner of death,” I don't mean what appears on the coroner's report. What I mean is what the to-be-killed-off character was doing at the time of death. Did they do anything to bring about their own demise, directly or indirectly? Did they willingly accept their end as a sacrifice for others? Was their death a matter of mere happenstance, or could they have done something to prevent it? Again, let's work with two scenarios, using the Dale-that-dies-before-achieving-his-goal as our foundation.</p>
<p>In our first scenario, Dale dies as a result of collateral damage when Good Guy<span style="background-color: white; color: #252525; font-family: sans-serif; font-size: 17.5px;">™ </span>finally arrives to dispose of Doctor Zygbo once and for all. Let's say Dale gets shot in the bum with a laser weapon of some kind while attempting to take cover behind Doctor Zygbo's Fun-sucking Funnel, for example. Bummer for Dale, right? Bummer for his family and kids and all those sick puppies of the future, right? Right. If only he'd had the courage or luck to escape unscathed. Oh, well. But what if…</p>
<p>…after years of toiling for Doctor Zygbo, Dale decides he can no longer sacrifice his ideals for his original objective? What if he decides that <i>he'll</i> take out the final loans necessary to put little Melanie through school? What if he figures by the time he has to pay off those loans that the housing market will have recovered enough to sell the home he raised his children in, using that cash to help the last of his children achieve the dream of debt-free college?</p>
<p>Yeah, Dale decides. He'll do it. It's better than the alternatives, anyway. And not only that… Dale decides he can't keep letting Doctor Zygbo get away with it. He can't. keep. getting. away with it.</p>
<p>Dale, after plotting for weeks, finally sees his window of opportunity open. He approaches Doctor Zygbo from behind, drawing his standard-issue henchman wrench from his standard-issue henchman work pants. One bludgeon is all it will take, one swing to the back of Zygbo's balding, rat-like scalp&#8212;</p>
<p>It's then that a previously unseen bodyguard shoots Dale in the bum with some sort of laser rifle.</p>
<p>“But he was so close,” you might say. “He could have rid the world of Zygbo <i>and</i> helped his family! Oh, he had everything planned out! He was going to take out that loan and sell his house and little Melanie was going to become a veterinarian and all those sick <a href="http://f.tqn.com/y/puppies/1/W/8/8/-/-/ResizePupDevelop.jpg" target="_blank" rel="noopener noreferrer">puppies</a> would have survived instead of being cast into the river!”</p>
<p>I know, right? See how you suddenly care about the man we once knew as Henchman #4?</p>
<p>That sudden investment in Dale didn't come from nowhere. It came from the <b>appeal of his character</b>, the <b>timeliness of his death</b>, and the <b>manner of his death.</b> By manipulating those three variables alone, we went from the “whatever” death of some schmo with a wrench to the tragic ending of Dale, a man whose dedication was matched only by his integrity.</p>
<h2>But What About That <em>Lack</em> of Appeal?</h2>
<p>Ah, yes. I suggested this in a couple of points above, but let's address it head on here. Throughout this post, we explored death through the lens of a sympathetic character, one for whom we'd want to root.</p>
<p>These same principles, however, can (and should!) be applied to antagonizing characters as well. The timeliness and manner of death for our villains is just as important as it is for our protagonists and their allies (or the allies of the antagonist, too).</p>
<p>In fact, the <em>lack </em>of appeal for the death or destruction of antagonizing forces can create a great deal of catharsis for our characters and our readers alike. Who doesn't love the release of knowing a big baddie has been beaten for good?</p>
<h2>Not Every Schmo Needs a Curtain Call</h2>
<p>After reading this post, you might be concerned you need this deep, rich backstory for every last one of your villain's hechmen or every last random villager who gets roasted by your manuscript's terrifying dragon creature.</p>
<p>Despite the impression the last two thousand words might have created, you <em>do not </em>need every character death to hit us in the same way the death of a protagonist, antagonist, or one of their allies would. In fact, the death of an unnamed character <strong>shouldn't </strong>carry the same weight as the departure of a prominent figure in our narratives.</p>
<p>Why use Henchman #4 a.k.a. Dale the Family Man and Puppy Lover as our example, then?</p>
<p>To demonstrate that it's <em>possible</em> for even the most side-seeming of side characters to be three dimensional in their own ways&#8212;just in case you need that arrow in your quiver. Who knows? You might one day be surprised to find a character you thought would be a one-and-done has the potential to add a new dimension to a given scene or the manuscript as a whole.</p>
<h2>Tell Me More</h2>
<p>For now, let's say R.I.P. to our pal Dale, that sweet, sweet man.</p>
<p>Having bid him adieu, I'm curious to know… how do you handle the deaths of the characters in your manuscripts? Do you make considerations similar to those described above? If not, what considerations <em>do</em> you make when it comes time for a character's bell to toll? Tell me and others in the comments!</p>
<hr />
<h3 style="text-align: center;">Did you enjoy this free resource?<br />
Buy me a coffee to say thanks!</h3>
<p><a href="https://ko-fi.com/N4N811LCO" target="_blank" rel="noopener noreferrer"><img decoding="async" class=" aligncenter" style="border: 0px; height: 36px;" src="https://i0.wp.com/az743702.vo.msecnd.net/cdn/kofi1.png?fit=1080%2C36&#038;ssl=1" alt="Buy Me a Coffee at ko-fi.com" height="36" border="0" data-recalc-dims="1" /></a></p>
<h3 style="text-align: center;"></h3>
<p>You can also <a href="http://eepurl.com/dhBxcv">subscribe to my newsletter</a>, follow me on <a href="http://www.twitter.com/iamrrcampbell">Twitter</a>, <a href="http://www.facebook.com/iamrrcampbell">Facebook</a>, and <a href="http://www.instagram.com/iamrrcampbell">Instagram</a>, or check out <a href="http://www.rrcampbellwrites.com/courses">my writing courses</a> and <a href="http://www.rrcampbellwrites.com/editing-services">editing services</a> to learn more.</p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default MurderTheLiterarilyLiteral
