import React from 'react'

const MurderTheLiterarilyLiteral = () =>
  <div>
    <p>Kill your darlings, <a href="http://www.slate.com/blogs/browbeat/2013/10/18/_kill_your_darlings_writing_advice_what_writer_really_said_to_murder_your.html" target="_blank" rel="noopener noreferrer">they</a> say. Every writer has at least heard the phrase, and the interpretations of what it really means vary from deleting a&nbsp;<a href="http://www.writersdigest.com/editor-blogs/writers-perspective/writing-technique/kill-your-darlings-and-other-terrifying-advice" target="_blank" rel="noopener noreferrer">favorite phrase</a>&nbsp;to <a href="http://writeroutine.blogspot.com/2012/02/how-to-kill-your-darlings.html" target="_blank" rel="noopener noreferrer">an entire beat or event</a>.&nbsp;Those darlings aren't what bring me here today, however. Today we talk about murder–actual, literary murder.</p>
<p>In literature as in life, people die. I can't put it much more plainly than that. George R. R. Martin is (in)famous for killing off his characters, as <a href="https://www.wired.com/images_blogs/underwire/2013/11/Screen-shot-2013-11-20-at-9.52.03-AM.png" target="_blank" rel="noopener noreferrer">nearly any chapter</a>&nbsp;in the <i>A Song of Ice and Fire</i>&nbsp;series can attest. It should go without saying that the impact of a <a href="https://ryanrcampbell.com/wp-content/uploads/2016/10/8f4b1-nedstark01.jpg" target="_blank" rel="noopener noreferrer">well executed</a>, literal <a href="http://www.reshareit.com/wp-content/uploads/stannis.jpg" target="_blank" rel="noopener noreferrer">character-assassination</a> can go a long way in creating memorable moments for readers. But how can a writer maximize that impact when he or she decides the time has come for one of their characters to meet their maker?</p>
<p>Though there are a number of approaches to creating a memorable end-scene for a character, I'd like to focus on the three main (poisonous?) ingredients that a writer can use to help achieve this goal: <b>character appeal</b>, <b>timeliness of death</b>, and <b>manner of death</b>.</p>
<h1><b>CHARACTER APPEAL</b></h1>
<p>So let's say you decide it's time for Henchman #4 to stop carrying out orders and start pushing daisies. That's fine, but who really gives half a hoot about him? He didn't even have a name!</p>
<p>Well, he didn't have a name to you, maybe, but if he were a real person he would have a name to <i>someone</i>. And that's the trick, really. You need to make your readers be part of that <i>someone, </i>and you need to make your character be a person that your reader can get behind (or root against!). Consider the following scenario.</p>
<p>As it turns out, Henchman #4's real name is Dale. Dale has a wife and five kids, and only signed up to work for the evil Doctor Zygbo part-time because he needed a second job to help get his fifth child through school. Dale has been working days at the local Fun Mart for pennies over minimum wage while he works nights for Zygbo, pushing buttons and flipping switches to further the doctor's evil designs.</p>
<p>“But wait,” you might say, “even if he has all those other things going on, couldn't he have picked up another shift at Fun Mart or gotten a job working as a janitor or something? Working for the evil doctor makes Dale a real jerk.”</p>
<p>I hate to break it to you, but the answer is no, he couldn't have done those things. Fun Mart keeps its employees at under 32 hours a week to avoid having to provide health insurance, and the only other place in town that was hiring was the puppy mill. Did I mention Dale has a soft spot for puppies? Well, he does. He loves puppies almost as much as he loves his wife and five children. He would never work at the puppy mill and you should never adopt from one.</p>
<p>Now that we've established Dale is a generally upstanding guy who, as a matter of circumstance and personal conviction, just happened to get sucked into Doctor Zygbo's hiring spree, let's move on to the next major thing that could make his previously anonymous death that much more impactful.</p>
<h1><b>TIMELINESS OF DEATH</b></h1>
<p>What I mean by timeliness of the character's death has less to do with the day of the week and everything to do with where the character is at in his or her arc of development. Where are they in their journey to accomplish their primary goal? What will the impact be of their success or failure as it relates to that goal?<b><br />
</b></p>
<p>Again, let's bring this back to good old Dale–sweet, <a href="http://www.dogchannel.com/images/dog-grooming/puppybath.jpg" target="_blank" rel="noopener noreferrer">puppy</a>-loving, father-of-five Dale. Let's stick with the narrative that Dale got his job at Doctor Zygbo's Death Emporium to earn extra scratch to send his youngest daughter off to college (she wants to be a <a href="http://homestead.pampfarms.com/wp-content/uploads/2015/04/bored-puppy-at-vet.jpg" target="_blank" rel="noopener noreferrer">veterinarian</a>, you know).</p>
<p>What happens if we learn that he actually accomplished that goal months ago, and is now showing up for work out of simple habit at the time of his death? If you're a knee-jerk <a href="http://www.wpr.org/shows/why-we-blame-victims" target="_blank" rel="noopener noreferrer">victim-blamer</a> (emphasis on “jerk”), you might say something like, “well, he should have quit when he had the chance” or “he got what he deserved for selling out to Zygbo in the first place.” Others might say it's all the more tragic that he died <i>after</i>&nbsp;accomplishing his goal, as his death came about needlessly.</p>
<p>But what if, at the time of his death, he was still a year away from finally having saved up enough to send little <a href="http://www.donwrightphoto.com/wp-content/uploads/2012/07/DWD_7647.jpg" target="_blank" rel="noopener noreferrer">Melanie</a> (that's her name now) off to college debt-free? What if, as he looked forward to counting down the months and weeks and days to accomplish this goal, his inner thoughts revealed a man increasingly more troubled with what he had to do for Doctor Zygbo on a nightly basis? Dale would be able to forgive himself someday, right? His family would forgive him if they ever found out where the money came from, wouldn't they?</p>
<p>Damn, even I'm starting to feel bad for Dale under that scenario, and I have a heart of stone (not really).</p>
<p>Now let's compare the <i>impact</i>&nbsp;those two possible scenarios would have. In the first setup, his family would be crushed, of course, but as it relates to Dale's primary goal, his daughter would be able to afford school, at least.</p>
<p>But in the second scenario, not only does Dale's family have to confront his loss, Dale himself would have died before achieving the one thing he was willing to sacrifice his integrity for. On top of that, little Melanie would have to take out massive loans for her education, something her generally risk-averse personality would ultimately discourage her from doing. Without her veterinary degree, there'd be a far greater number of sick <a href="http://mediaassets.tmj4.com/photo/2016/02/11/puppies%20story_1455228962535_31753647_ver1.0_640_480.jpg" target="_blank" rel="noopener noreferrer">puppies</a> lolling around, a further affront to her father's <a href="http://cdn2-www.dogtime.com/assets/uploads/gallery/french-bulldog-puppies/french-bulldog-puppy-14.jpg" target="_blank" rel="noopener noreferrer">puppy</a>-loving memory. A tragedy, folks. It'd be a real tragedy.</p>
<p>But let's say you're still one of those holdouts who says, “I don't appreciate the nuance of individuals having to make ideological sacrifices in order to overcome oppressive circumstances. Dale is still a jerk because he worked for Doctor Zygbo.”</p>
<p>Well strap in, <a href="https://i.ytimg.com/vi/JIg9nfzmW1o/maxresdefault.jpg" target="_blank" rel="noopener noreferrer">dopey</a>, because this is where it gets real.</p>
<h1><b>MANNER OF DEATH</b></h1>
<p>When I say “manner of death,” I don't mean what appears on the coroner's report. What I mean is what the to-be-killed-off character was doing at the time of death. Did he or she do anything to bring about their own demise, directly or indirectly? Did they willingly accept their end as a sacrifice for others? Was their death a matter of mere happenstance, or could they have done something to prevent it? Again, let's work with two scenarios, using the Dale-that-dies-before-achieving-his-goal as our foundation.</p>
<p>In our first scenario, Dale dies as a result of collateral damage when <a href="http://vignette2.wikia.nocookie.net/simpsons/images/c/ce/Duff_man.png/revision/latest?cb=20130808075436" target="_blank" rel="noopener noreferrer">Good Guy</a><span style="background-color: white; color: #252525; font-family: sans-serif; font-size: 17.5px;">™&nbsp;</span>finally arrives to dispose of Doctor Zygbo once and for all. Let's say he gets shot in the bum with a laser weapon of some kind while attempting to take cover behind Doctor Zygbo's Fun-sucking Funnel, for example. Bummer for Dale, right? Bummer for his family and kids and all those sick puppies of the future, right? Right. If only he'd had the courage or luck to escape unscathed. Oh, well. But what if…</p>
<p>…after years of toiling for Doctor Zygbo, Dale decides he can no longer sacrifice his ideals for his original objective? What if he decides that <i>he'll</i>&nbsp;take out the final loans necessary to put little Melanie through school? What if he figures by the time he has to pay off those loans that the housing market will have recovered enough to sell the home he raised his children in, using that cash to help the last of his children achieve the dream of debt-free college?</p>
<p>Yeah, Dale decides. He'll do it. It's better than the alternatives, anyway. And not only that… Dale decides he can't keep letting Doctor Zygbo get away with it. He can't. keep. getting. away with it.</p>
<p>Dale, after plotting for weeks, finally sees his window of opportunity open. He approaches Doctor Zygbo from behind, drawing his standard-issue henchman wrench from his standard-issue henchman work pants. One bludgeon is all it will take, one swing to the back of Zygbo's balding, rat-like scalp–</p>
<p>It's then that a previously unseen bodyguard shoots Dale in the bum with some sort of laser rifle.</p>
<p>“But he was so close,” you might say. “He could have rid the world of Zygbo <i>and</i>&nbsp;helped his family!&nbsp;Oh, he had everything planned out! He was going to take out that loan and sell his house and little Melanie was going to become a veterinarian and all those sick <a href="http://f.tqn.com/y/puppies/1/W/8/8/-/-/ResizePupDevelop.jpg" target="_blank" rel="noopener noreferrer">puppies</a> would have survived instead of being cast into the river!”</p>
<p>I know, right? See how you suddenly care about Henchman #4?</p>
<p>That sudden investment in Dale didn't come from nowhere. It came from the <b>appeal of his character</b>, the <b>timeliness of his death</b>, and the <b>manner of his death.</b>&nbsp;By manipulating those three variables alone, we went from the “whatever” death of some schmo with a wrench to the tragic ending of Dale, a man whose dedication was matched only by his integrity.</p>
<p>R.I.P. in pieces, Dale. Tell Harambe we say hello.</p>
<p>As always, you can holler at me on <a href="https://twitter.com/iamrrcampbell" target="_blank" rel="noopener noreferrer">Twitter</a>, or shoot me an email at rrcampbellwrites@gmail.com.</p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default MurderTheLiterarilyLiteral
