import React from 'react'

const ResearchWheretoLooktoMakeYourWritingMoreAuthentic = () =>
  <div>
    <p>You may have heard of “the three Rs” way back in elementary school–reading, (w)riting, and (a)rithmetic. If you're anything like me, you completely disregarded the ‘rithmetic, which was a great decision because it created space for a third (and actual) “R.” And that “R,” my friends, is research.</p>
<p>“Research,” you say? “That stuff's for nerds!”</p>
<p>Well, you're right, but here you are reading this post. What do you think that makes you?</p>
<p>Oh, stop. Wipe those tears from your eyes. Nerd chic is a thing now! Besides, you're going to have to embrace reading, writing, <i>and</i> research if you want to create convincing, well-rounded characters that thrive (or fail) in a reasonably realistic environment.</p>
<p>The need to ensure you're doing your homework should be apparent. Is one of your characters–a medical doctor–put on trial for a crime they are alleged to have committed against a patient? How will you write about the courtroom proceedings if you don't know the first thing about, well, courtroom proceedings? How will you write a convincing defense for your character if you don't know the first thing about medical ethics?</p>
<p>Granted, you likely don't have time to study for the bar and also complete medical school before sitting down to write your story. The good news is, you don't have to! In this golden age of access to information, there are plenty of ways to sufficiently research whatever topics might be necessary for the piece you plan on writing next. Let's take a look at some of them below, starting with the most obvious.</p>
<h1><b>READ SOME F@#+ING BOOKS</b></h1>
<p>“Whoa, hey. Easy there,” you say. “There's no need to get testy. And isn't ‘reading' one of the other three ‘Rs' already?”</p>
<p>You're right. “Reading” is already on the list, but as a writer it isn't about just whether you <i>are</i> reading, it's about the kind of reading you're doing.</p>
<p>Fiction is a fantastic thing, and reading, say, exclusively YA Fantasy may help you with your world building, but it's not as likely to come in handy when the time arrives to write about that doctor (<a href="http://www.rrcampbellwrites.com/2016/10/murder-literarily-literal.html" target="_blank" rel="noopener noreferrer">Doctor Zygbo?</a>) you're putting on trial.</p>
<p>The suggestion, then, is this: know the genre in which you plan to write. It may be fiction, but reading some well-respected medical or legal thrillers before writing <i>The Trial of Zygbo: Dale's Revenge</i> will help give you an idea of what degree of knowledge is expected in those genres. You'll also, inevitably, pick up some of the inner workings of those fields. If you're not sure what's hot in the genre you're hoping to write in, check out the <a href="https://www.amazon.com/Best-Sellers-Kindle-Store-Literature-Fiction/zgbs/digital-text/157028011/ref=zg_bs_unv_kstore_3_6361438011_2" target="_blank" rel="noopener noreferrer">Amazon Bestsellers</a> list for a sampling.</p>
<p>But how do you round out the knowledge you acquire as you learn your genre? How do you make sure you don't end up parroting the same story lines and information you find in the fiction you're reading for research purposes? That's where non-fiction comes in.</p>
<p>It's important to have a balance of both in your reading regimen. Fiction alone is great, but not all fiction can provide things like historical context, or explore current topics in the field in the same way as non-fiction. Think of it this way: you want to be a writer, but you're not reading <i>only</i> fiction to help you improve your craft. You're here after all, right?</p>
<p>So let's say you're ready to find some non-fiction, but aren't sure where to start. We'll take a look at that in our next section.</p>
<h1><b>USE THE INTERNET–WISELY</b></h1>
<p>“Wow,” you say. “Thanks for the tip, Captain Obvious.”</p>
<p>I get where you're coming from, but bear with me here. There might be some resources out there that are less obvious than you think.</p>
<p>The first thing that probably comes to mind when you think of internet research is Google. It's the only major search engine to get its own verb, after all. Have you ever heard someone say they're going to “yahoo” something? You have? Did you report them to the appropriate authorities immediately? You did? Good. Maniacs like that can't be allowed to walk the streets.</p>
<p>Google may be a great place to start, but there are plenty of other ways to source non-fiction to assist with your research needs. Places like <a href="http://mashable.com/2012/06/06/reddit-for-beginners/#FqKD7jWpukqR" target="_blank" rel="noopener noreferrer">Reddit</a>, <a href="http://metanews.com/" target="_blank" rel="noopener noreferrer">news aggregators</a>, and even <a href="https://scholar.google.com/" target="_blank" rel="noopener noreferrer">Google Scholar</a> can help you read material from experts in the field (some might even put you in touch with them!).</p>
<p>For your story about Doctor Zygbo, have you tried to find a community or message board for professionals of the same background? When writing my most recent novel, for example, I realized I needed the input of individuals with a much stronger background in IT and network security than I have. Knowing this, I sought out and found a community of people who were more than willing to help answer the questions I had at the time.</p>
<p>As further proof that this works, a search for “<a href="https://www.google.com/webhp?sourceid=chrome-instant&amp;ion=1&amp;espv=2&amp;ie=UTF-8#q=%22author%20with%20a%20question%22" target="_blank" rel="noopener noreferrer">author with a question</a>” on the ol' Google machine reveals that it's not uncommon for authors to use message boards to learn about anything from <a href="http://diabeticcatcare.com/wp-content/uploads/2011/03/treatment_page.jpg" target="_blank" rel="noopener noreferrer">feline diabetes</a> to <a href="http://www.adventurecats.org/wp-content/uploads/2015/11/BaileyBoatCat3.jpeg" target="_blank" rel="noopener noreferrer">sailing</a>. If you look hard enough through the results on that page, you might even find the question I posted on network security to help me better define (read: completely delete and rework) a major plot point.</p>
<p>Another great way to take advantage of the internet is to make use of streaming services like Netflix or HBO Now that feature documentaries. Additionally, you can seek out podcasts that discuss and explore topics related to the fields you need to research. One of the advantages to both of these media is that they are <i>passive</i>–you can listen or watch while working on another project (or finally getting caught up on laundry).</p>
<p>“Oh, okay,” you now say. “Those are slightly more useful than I anticipated. There's just one problem: any time I use the internet for research, I end up spending more time looking at cat gifs than I do actual research.”</p>
<p>I get it. I get it. Who can resist a quality cat gif?</p>
<p>Fortunately, it turns out there are a number of apps you can use to keep you on task while you do your research. Even just this <a href="http://99u.com/articles/6969/10-online-tools-for-better-attention-focus" target="_blank" rel="noopener noreferrer">one blog post</a> from Jocelyn Glei at 99u.com offers ten different apps or browser add-ons that you can use to help you better organize your time online. Find one that you think will work for you and give it a try! The cat gifs can wait.</p>
<h1><b>INTERVIEWS</b></h1>
<p>Another fantastic way to make your story come alive through your research is to rely on people–actual people–to help you better inform your characters.</p>
<p>Have you considered reaching out to your local school or college to try and talk to educators or students about the topics you'd like to learn more about? Is there an organization of students or professionals that meets regularly in your area?</p>
<p>Local businesses, journalists, city employees, pizza delivery drivers–it makes no difference. Everyone loves to talk about themselves, and any one of these folks could help you improve your narrative's authenticity if you took the time to speak with them. This is true even of your cousin Tina. I know you despise her, but as a (definitely smug) doctor-lawyer (or is it lawyer-doctor?), meeting up with her for even just an hour could give you a ton of background to help you support <i>The Trial of Zygbo: Dale's Revenge</i>.</p>
<h1><b>WRITE WHAT YOU KNOW</b></h1>
<p>One final bit of advice for those of you who are still research-shy is to start by writing what you know. Believe it or not, you're already an expert on something (even if it's how to avoid doing laundry). Your own background and skills uniquely equip you to write a story that no one else can. If all of this research seems daunting to you, that's no problem. Start with what you know to just make sure you're writing (every day!). All the research in the world won't do you any good if you're not practicing your craft.</p>
<h1><b>SUMMARY</b></h1>
<p>Ultimately, the needs of your story and characters–as well as your own personal preference–will dictate the kind of media that best help you do the necessary research to write authentic characters that you can then immerse in (almost-)true-to-life scenarios. You may not find what works best for you right away, but keep trying! You'll never find out which research type serves you best unless you keep digging.</p>
<p>Thanks for reading! As always, you can contact me on <a href="https://twitter.com/iamrrcampbell" target="_blank" rel="noopener noreferrer">Twitter</a>, or shoot me an email at rrcampbellwrites@gmail.com.</p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default ResearchWheretoLooktoMakeYourWritingMoreAuthentic
