import React from 'react'

const ADeathUnlikeAnyOther = () =>
  <div>
    <h3 style="text-align: center;"><strong>Somewhere in an empty office sits an empty chair.</strong></h3>
<p>This chair was filled once, was party to a purpose only one person could realize. Like many of us, this person was a writer, but to so many, she was much, much more. An inspiration. A community leader. A mother. A wife.</p>
<p>This writer was one of my clients, a thoughtful, optimistic individual who saw promise in the world and the people around her. She dreamed of perfecting her first fiction manuscript—insofar as perfection can ever truly be attained—and, from there, signing with an agent, earning a publishing deal, and sharing her story far and wide.</p>
<p>In July of 2019, we connected by Skype to review my comments on the most recent draft of her manuscript. We dove deep into opportunities for strengthening her character development, as well as how we might increase the resonance of some scenes by relocating them to more vibrant, unique, and tension-inducing locales.</p>
<p>Both of us left the conversation eager to see what she would make of her novel; she said she would follow up with me later that year about partnering together again once she had the chance to implement this new, shared vision for her manuscript.</p>
<p>Summer came and went, and in November, my mind drifted back to this writer and her manuscript, so I emailed her to check in and to pass along some new possibilities.</p>
<p>When I didn't hear back from her after a couple of weeks, I chalked it up to holiday business, but as time wore on without any engagement from her by email or on social media, I began to worry.</p>
<p>I don't know what came over me, but on the second of January, I checked in again, this time by visiting her on Twitter where we first connected. Nothing. No posts since shortly after the time of our conversation by Skype. I fretted, for a moment, the possibility my comments chased her away from writing altogether, that what I took for an earnest engagement with my feedback was, in fact, a coping mechanism to survive what had been, for her, a difficult conversation that challenged her more than it inspired.</p>
<p>Then I Googled her name. It autocompleted with the word “obituary.”</p>
<p>She died ten days after our conversation on Skype.</p>
<p>This writer and I never met in real life. We had no relationship outside that of editor and client, of mentor and mentee, but reading about how she—an otherwise healthy young woman in her thirties—inexplicably passed in her sleep shook me in ways I could not have expected.</p>
<p>I could linger, now, on the obvious tragedy, on the anguish her passing must have caused her family, her friends, and community, but instead, I want to focus on one word: promise.</p>
<p>Who she was lives on. Her promise is part of those whose lives she touched. It's part of the promise their lives hold now; her purpose is now, to some extent, theirs. And though her manuscript never had the chance to land an agent, to fetch her the publishing deal it would have very much deserved, that story lives on, too.</p>
<p>“Mozart, Beethoven and Chopin never died. They simply became music.”</p>
<p>This quote may come from the fictional Doctor Ford in HBO's Westworld, but it speaks, in my view, to an inspiring, reassuring truth: who we are is defined by so many things, but ultimately, we will become that which we create for ourselves, for those we love, and for those who happen upon our legacy, no matter the shape it takes.</p>
<p>So, in 2020, I'm dedicating myself to that word: promise. I will live with promise in mind, making my every step a purposeful one, embracing every new beginning and respecting—but never fearing—the inevitability of every end.</p>
<p>This client and I may never again connect, and the world may never read her manuscript as she intended, but I will think of it from time to time. I will think of it, of her and those she left behind, of how her words and her presence, however fleeting, will forever be part of the promise I bring myself and others.</p>
<p>She wrote with purpose, with all of the promise her life held and more, and I hope you'll join me in honoring that spirit in 2020 and beyond.</p>
<p>Write on. Write well. Be good to each other.</p>
<p><img loading="lazy" decoding="async" data-attachment-id="7175" data-permalink="https://ryanrcampbell.com/2019/12/02/this-friday-a-new-short-story/rr-black-signature-transparent/" data-orig-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/11/rr-black-signature-transparent.png?fit=405%2C228&amp;ssl=1" data-orig-size="405,228" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="rr black signature transparent" data-image-description="" data-image-caption="" data-medium-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/11/rr-black-signature-transparent.png?fit=300%2C169&amp;ssl=1" data-large-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/11/rr-black-signature-transparent.png?fit=405%2C228&amp;ssl=1" class="  wp-image-7175 aligncenter" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/11/rr-black-signature-transparent.png?resize=250%2C141&#038;ssl=1" alt="rr black signature transparent" width="250" height="141" srcset="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/11/rr-black-signature-transparent.png?w=405&amp;ssl=1 405w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/11/rr-black-signature-transparent.png?resize=300%2C169&amp;ssl=1 300w" sizes="(max-width: 250px) 100vw, 250px" data-recalc-dims="1" /></p>
<h3 style="text-align: center;"><em>r.r. campbell</em></h3>
<hr />
<p style="text-align: left;">This post first appeared in my January email newsletter. <a href="http://eepurl.com/dhBxcv" target="_blank" rel="noopener noreferrer">Subscribe here</a> to become among the first to receive similar news and updates on this and other endeavors.</p>
<p style="text-align: left;">You can also follow me on <a href="http://www.twitter.com/iamrrcampbell">Twitter</a>, <a href="http://www.facebook.com/iamrrcampbell">Facebook</a>, and <a href="http://www.instagram.com/iamrrcampbell">Instagram</a>, or check out <a href="http://www.rrcampbellwrites.com/courses">my writing courses</a> and <a href="http://www.rrcampbellwrites.com/editing-services">editing services</a>.</p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default ADeathUnlikeAnyOther
