import React from 'react'

const ThankYoufromAFIAandRRCampbell = () =>
  <div>
    <p>It may be the case that only one person <em>writes</em> most novels, but it takes a community to launch and support them; <em><a href="http://accountingforitall.com/book/" target="_blank" rel="noopener">Accounting for It All</a> </em>was no exception. That's why I'd like to take a moment today to thank as many of those people without whose involvement, insight, and input this book would have never been the same.</p>
<p>I'd like to start with the folks of <a href="http://www.ninestarpress.com" target="_blank" rel="noopener">NineStar Press</a>, especially Rae and BJ, for working through tight timelines to keep to our originally scheduled release date. Thanks to them and cover designer <a href="http://natashasnow.com/" target="_blank" rel="noopener">Natasha Snow</a>, with whom they work to create their fantastic covers, <em>Accounting for It All</em>‘s included.</p>
<p>This book also would have never reached its final form were it not for fellow authors <a href="https://maryannehinkle.com/" target="_blank" rel="noopener">M.A. Hinkle</a> and <a href="https://stefaniesimpson.wordpress.com/books/" target="_blank" rel="noopener">Stefanie Simpson</a>, who read and provided feedback on an early version of Robin's story. I'd like to thank Jim as well for being part of the conversation that got me thinking about writing this book in the first place; without him, Robin surely would have never existed. Thanks to <a href="https://twitter.com/AutumnFaraday" target="_blank" rel="noopener">Autumn Faraday</a>, too, whose suggested “she has the looks, but now it looks like the cooks the books” tagline was eerily perfect for this book.</p>
<p>My wife, Lacey, was and continues to be of extraordinary support, so thanks to her for her role in helping me approach my writing with a clearer head and warmer heart every day.</p>
<p>I also had a fantastic time talking <em>Accounting for It All</em> with Brianna and Rey of the <a href="https://anchor.fm/wip-podcast/episodes/24---Relaxing-All-Cool-Outside---the-Podcast-e1kkdb/a-a3v0al" target="_blank" rel="noopener">Work in Progress Podcast</a>, Baz and Vance of <a href="http://www.wrotepodcast.com/r-r-campbell/" target="_blank" rel="noopener">the WROTE Podcast</a>, and the guests who've joined me on the Writescast Network for conversations that inevitably drifted in <em>AFIA</em>‘s direction. There are far too many of them to name, but a special tip of the cap is owed to my <a href="http://www.writescast.net/podcasts/novelapproaches" target="_blank" rel="noopener">Novel Approaches</a> co-host Sione Aeschliman, who's interviewed me a number of times about the work that went into this novel.</p>
<p>It's also meant a great deal to me to have the engagement of readers, both those already known to me and those whom I've yet to meet, especially on <a href="https://www.goodreads.com/book/show/42604499-accounting-for-it-all" target="_blank" rel="noopener">Goodreads</a> and through other social media. For anyone and everyone who's gone out of their way to write a review, <a href="http://accountingforitall.com/signmybook/" target="_blank" rel="noopener">request a bookplate sticker</a>, or simply share in mine or their own excitement over this book: thank you.</p>
<p>There are also dozens of writers from the Twitterverse with whom I've been fortunate enough to celebrate and commiserate along my pathway to publication, and I thank you, all of you, for your support. I can only hope I can be there for you in the same ways you have been for me.</p>
<p>Surely many other people could be added to this by name, but for fear of recording, in alphabetical order, the complete list of everyone I've ever met, I'll leave it there for now. 2018 has been an incredible year in my corner of the writing world, and 2019 is looking like it might, somehow, be even more magical.</p>
<p>So thanks to you, dear reader, for being here with me at this stage in my journey. I hope you're looking forward to walking the rest of the way with me as much as I am with you.</p>
<p>Read on, read well, and happy Thanksgiving.</p>
<p>-r. r.</p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default ThankYoufromAFIAandRRCampbell
