import React from 'react'

const BroDoYouEvenCopyedit = () =>
  <div>
    <p>Last Friday, I completed the copyedits for <em><a href="https://ryanrcampbell.com/books/" target="_blank" rel="noopener">Accounting for it All</a></em>, which is good news since the book is now out in less than a month! This round of edits was especially grueling, both because copyedits require a sharp look at the text itself, and also because of the timeline on which they had to be completed.</p>
<p>After something in the neighborhood of 30 hours of work over the course of three and a half days, I've come out on the other side exhausted, yes, but with some additional perspective on fine tuning one's manuscript and how other writers might learn from my experience to make their own copyediting process more efficient.</p>
<h2>What is this I don't even&#8212;</h2>
<p>Good point; it probably is worth exploring what I mean by copyedits before we go any further. To tease out a definition, let's rely on some comparisons. By and large, the post-contract editing journey for this manuscript has gone or will go as follows:</p>
<ol>
<li>Content (developmental) edits - <strong><em>completed</em></strong></li>
<li>Copyedits - <strong><em>completed</em></strong></li>
<li>Proofreading - <strong><em>coming soon</em></strong></li>
</ol>
<p>Content or developmental edits are the first formal feedback a writer receives from their editor, typically in the form of an edit letter, notes on the manuscript itself, or some combination thereof. In my case, I received both over the course of two rounds of content edits.</p>
<p>These first passes are meant to attack more bird's-eye-view matters including characterization, the dreaded plot hole, or confusion brought about by possibly clunky dialogue, etc. Fortunately, no major revisions were required on my part, which gave us an opportunity to dive into a process that was almost copyedit-esque.</p>
<p>Copyedits take a closer look at things like word frequency, as well as overall clarity and consistency on a more zoomed in basis, so to speak. By and large, matters related to word frequency were the largest obstacle for me to overcome.</p>
<p>For example, in my ~89,000 word manuscript, there were 598 instances of the word “all,” 463 uses of the word “like,” 154 appearances of “maybe,” and 64 invocations of the phrase “of course.” None of this is to mention the hundreds of unnecessary or repetitive uses of know, feel, look and their various related forms (known/knows/knowing, feels/felt/feeling, etc.).</p>
<p>If I had to guess, these words appear with a significantly reduced frequency in my upcoming sci-fi debut, <em><a href="http://www.empathynovel.com" target="_blank" rel="noopener">EMPATHY: Imminent Dawn</a></em>, which has yet to go through <em>content</em> edits. Frankly, I was shocked to see the numbers above at the those levels in the first place; they're the sort of thing I'm generally pretty “eagle eye” about when editing on my own&#8212;so what happened?</p>
<p>Voice. Voice happened.</p>
<p><em>Accounting for it All </em>is written with a very intimate first person point of view, whereas the <em>EMPATHY</em> series is written in third person limited. Not only that, but the character from whose perspective <em>Accounting for it All </em>is written doesn't, as a person, have the broadest vocabulary, and with the conversational tone (voice) of the pages themselves, this led to a ballooning of word frequency to the levels cited above.</p>
<h2>So how do you edit for that?</h2>
<p>Very carefully.</p>
<p>There's something to be said for holding one's ground where matters of voice are concerned&#8212;particularly in a voice-driven narrative like <em>Accounting for it All</em>&#8212;but, as is the case with all things, balance is imperative as well.</p>
<p>As I waded through the swampy trenches of reductions in usage of “think” for example, there were many times where I had to ask myself whether swapping in a synonym was even the way to go. Then, if it was, it was critical I ensure the synonym I swapped in didn't become overused as a result while also deciding whether that particular word is one the main character would employ at all.</p>
<p>In many cases, I avoided synonym-swapping altogether in favor of an approach that other writers might consider putting to use too: rephrasing the whole dang sentence or clause.</p>
<p>Consider the following:</p>
<blockquote>
<h4>[She was] more reserved anyway&#8212;at least I thought so at the time.</h4>
</blockquote>
<p>There's nothing inherently wrong with “thought” here, but when the manuscript contains 325 collective variations on the verb “to think,” there's room for improvement.</p>
<p>The easy swap would be to take out “thought” and throw in a “believed” or something along those lines, but if I'd done that, well, I'd have ended up just trading one high-frequency verb for another. So, instead, I went with:</p>
<blockquote>
<h4>[She was] more reserved anyway—at least that was my impression at the time.</h4>
</blockquote>
<p>“That was my impression” is wordier, yes, and some might (rightly) say a violation of a strict, puritanical interpretation of <a href="https://ryanrcampbell.com/2017/03/10/edit-with-me-proportion/" target="_blank" rel="noopener">word economy</a> philosophy. As mentioned above, however, balance is key, so sacrificing word economy in the interest of word diversity becomes more than appropriate; it's almost necessary.</p>
<p><strong>Side note:</strong> I'd argue a more holistic approach to word economy would incorporate considerations of word frequency and diversity, but exploring that would merit a post or two of its own.</p>
<h2>Okay, but what was your strategy for finding these in the first place?</h2>
<p>I was surprised to hear from my editor that there are a number of writers who aren't familiar with the Ctrl + F command (or, if you use a Mac like me, <b>⌘</b> + F). If you're among those who aren't familiar with this feature, prepare to have your life changed forever.</p>
<p>Using this function will allow you to search a document, web page, etc. for a specific word or phrase, which will save you boat loads of time if you're editing a manuscript of any size. So how do you use it?</p>
<p>With this page open, press and hold the control or <b>⌘ </b>key. Now press the F key. A box should have opened in the corner of your screen. Type “ta-da” into this box. Press Enter.</p>
<p>Ta-da. You've now jumped to the previous sentence in this post, but you could have jumped anywhere by typing in a word or phrase you want to seek out. This is an extraordinarily powerful tool relative to its simplicity, but there's more to it than this, even!</p>
<p>If you're like me, for example, and you want to find not only “think,” but “thought” and “thinks” and “thinking,” etc., you might think you need to do separate searches for these words within your Word document.</p>
<p>But that's where you're wrong, kiddo. Word will let you search for all variations of a single word using an enhanced version of the Ctrl + F feature. How?</p>
<h2>Screenshot Time!</h2>
<div id="attachment_5350" style="width: 735px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-5350" data-attachment-id="5350" data-permalink="https://ryanrcampbell.com/2018/10/22/bro-do-you-even-copyedit/screen-shot-2018-10-19-at-4-00-29-pm/" data-orig-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/10/Screen-Shot-2018-10-19-at-4.00.29-PM.png?fit=725%2C414&amp;ssl=1" data-orig-size="725,414" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="Screen Shot 2018-10-19 at 4.00.29 PM" data-image-description="" data-image-caption="&lt;p&gt;Step one: click Edit, go to Find, then click Replace.&lt;/p&gt;
" data-medium-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/10/Screen-Shot-2018-10-19-at-4.00.29-PM.png?fit=300%2C171&amp;ssl=1" data-large-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/10/Screen-Shot-2018-10-19-at-4.00.29-PM.png?fit=725%2C414&amp;ssl=1" class="alignnone size-full wp-image-5350" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/10/Screen-Shot-2018-10-19-at-4.00.29-PM.png?resize=725%2C414&#038;ssl=1" alt="Screen Shot 2018-10-19 at 4.00.29 PM" width="725" height="414" srcset="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/10/Screen-Shot-2018-10-19-at-4.00.29-PM.png?w=725&amp;ssl=1 725w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/10/Screen-Shot-2018-10-19-at-4.00.29-PM.png?resize=300%2C171&amp;ssl=1 300w" sizes="(max-width: 725px) 100vw, 725px" data-recalc-dims="1" /><p id="caption-attachment-5350" class="wp-caption-text"><strong>Step one:</strong> click Edit, go to Find, then click Replace.</p></div>
<div id="attachment_5351" style="width: 306px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-5351" data-attachment-id="5351" data-permalink="https://ryanrcampbell.com/2018/10/22/bro-do-you-even-copyedit/screen-shot-2018-10-19-at-4-02-40-pm/" data-orig-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/10/Screen-Shot-2018-10-19-at-4.02.40-PM.png?fit=296%2C360&amp;ssl=1" data-orig-size="296,360" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="Screen Shot 2018-10-19 at 4.02.40 PM" data-image-description="" data-image-caption="&lt;p&gt;Step two: in the sidebar that opens, type one of the variations of the word you're looking for. Click the little sprocket-looking button. Then click “All Word Forms.” Press Enter.&lt;/p&gt;
" data-medium-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/10/Screen-Shot-2018-10-19-at-4.02.40-PM.png?fit=247%2C300&amp;ssl=1" data-large-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/10/Screen-Shot-2018-10-19-at-4.02.40-PM.png?fit=296%2C360&amp;ssl=1" class="alignnone size-full wp-image-5351" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/10/Screen-Shot-2018-10-19-at-4.02.40-PM.png?resize=296%2C360&#038;ssl=1" alt="Screen Shot 2018-10-19 at 4.02.40 PM" width="296" height="360" srcset="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/10/Screen-Shot-2018-10-19-at-4.02.40-PM.png?w=296&amp;ssl=1 296w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/10/Screen-Shot-2018-10-19-at-4.02.40-PM.png?resize=247%2C300&amp;ssl=1 247w" sizes="(max-width: 296px) 100vw, 296px" data-recalc-dims="1" /><p id="caption-attachment-5351" class="wp-caption-text"><strong>Step two:</strong> in the sidebar that opens, type one of the variations of the word you're looking for. Click the little sprocket-looking button. Then click “All Word Forms.” Press Enter.</p></div>
<div id="attachment_5352" style="width: 627px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-5352" data-attachment-id="5352" data-permalink="https://ryanrcampbell.com/2018/10/22/bro-do-you-even-copyedit/screen-shot-2018-10-19-at-4-05-24-pm/" data-orig-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/10/Screen-Shot-2018-10-19-at-4.05.24-PM.png?fit=617%2C193&amp;ssl=1" data-orig-size="617,193" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="Screen Shot 2018-10-19 at 4.05.24 PM" data-image-description="" data-image-caption="&lt;p&gt;Step three: Behold! A search for “thought” has produced a result of “think.” It will also show you “thoughts,” “thinking,” “think,” etc. Great job.&lt;/p&gt;
" data-medium-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/10/Screen-Shot-2018-10-19-at-4.05.24-PM.png?fit=300%2C94&amp;ssl=1" data-large-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/10/Screen-Shot-2018-10-19-at-4.05.24-PM.png?fit=617%2C193&amp;ssl=1" class="alignnone size-full wp-image-5352" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/10/Screen-Shot-2018-10-19-at-4.05.24-PM.png?resize=617%2C193&#038;ssl=1" alt="Screen Shot 2018-10-19 at 4.05.24 PM" width="617" height="193" srcset="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/10/Screen-Shot-2018-10-19-at-4.05.24-PM.png?w=617&amp;ssl=1 617w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/10/Screen-Shot-2018-10-19-at-4.05.24-PM.png?resize=300%2C94&amp;ssl=1 300w" sizes="(max-width: 617px) 100vw, 617px" data-recalc-dims="1" /><p id="caption-attachment-5352" class="wp-caption-text"><strong>Step three:</strong> Behold! A search for “thought” has produced a result of “think.” It will also show you “thoughts,” “thinking,” “think,” etc. You're now ready to actually edit. Great job.</p></div>
<p>In the screenshot for step two, one might also notice there are options for “Sounds Like” and “Advanced Find &amp; Replace…” I didn't use either of these features, but, if the “All Word Forms” option is any indication, I bet those other features are pretty rocking, too.</p>
<h2>How do you make sure you don't over-edit?</h2>
<p>Let's say you've Ctrl + F'ed your way through your manuscript, swapping in synonyms or re-writing whole phrases for all of the items on your list of necessary copyedits. How do you know you haven't accidentally edited in words or phrases that are now too proximate on the page to other instances of that same word or phrase?</p>
<p>Brute. Force. It's what seems to have worked for me, anyway.</p>
<p>By brute force, I mean I re-read the entire manuscript start to finish, keeping an eye out for places where I might have either created new typos, inconsistencies, or word proximity issues.</p>
<p>A full re-read may sound like a lot, but it's your book! You've already put so much work into it; why get lax with it now?</p>
<h2>But wait, there's more!</h2>
<p>By which I mean there are more copyedits in my future (and surely yours, too). My experience this time around, though certainly eye opening, was by no means comprehensive. Certainly there's far more to learn, and who knows what other strategies might reveal themselves as effective when taking on this process for other manuscripts?</p>
<p>That said, have you gone through copyedits before? What was effective for you? What wasn't?</p>
<p>If you've never been through the process, what might you take with you from this blog post or the experiences of others to help you feel more prepared?</p>
<p>Tell me in the comments below or on Twitter at <a href="http://www.twitter.com/iamrrcampbell" target="_blank" rel="noopener">@iamrrcampbell</a>. I'd love to hear from you!</p>
<p>And stay tuned for the release of <em>Accounting for it All </em>on November 19, 2018! For more about that book, you can always visit <a href="http://www.accountingforitall.com" target="_blank" rel="noopener">accountingforitall.com</a>.</p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default BroDoYouEvenCopyedit
