import React from 'react'

const NowAvailableeBookPreordersforAccountingforItAll = () =>
  <div>
    <p><img loading="lazy" decoding="async" data-attachment-id="5357" data-permalink="https://ryanrcampbell.com/2018/10/26/now-available-ebook-preorders-for-accounting-for-it-all/accountingforitall-f/" data-orig-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/10/AccountingForItAll-f.jpg?fit=1800%2C2700&amp;ssl=1" data-orig-size="1800,2700" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;1&quot;}" data-image-title="AccountingForItAll-f" data-image-description="" data-image-caption="" data-medium-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/10/AccountingForItAll-f.jpg?fit=200%2C300&amp;ssl=1" data-large-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/10/AccountingForItAll-f.jpg?fit=683%2C1024&amp;ssl=1" class="  wp-image-5357 alignleft" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/10/AccountingForItAll-f.jpg?resize=250%2C375&#038;ssl=1" alt="AccountingForItAll-f" width="250" height="375" srcset="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/10/AccountingForItAll-f.jpg?w=1800&amp;ssl=1 1800w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/10/AccountingForItAll-f.jpg?resize=200%2C300&amp;ssl=1 200w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/10/AccountingForItAll-f.jpg?resize=683%2C1024&amp;ssl=1 683w" sizes="(max-width: 250px) 100vw, 250px" data-recalc-dims="1" />That's right; you can now preorder the eBook version of my debut novel, <em>Accounting for It All</em>, directly from NineStar Press.</p>
<p>Not only that, but if you order now, you'll receive the book on November 16th, 2018&#8212;<em>three days earlier than its actual release date!</em></p>
<p>What are you waiting for? Head to <a href="https://ninestarpress.com/product/accounting-for-it-all/" target="_blank" rel="noopener">the NineStar Press preorder page now</a> to order yourself a digital copy of the book!</p>
<p><strong>Details on the print version are forthcoming. </strong>Keep your eyes on my site for further details as the book's release date nears.</p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default NowAvailableeBookPreordersforAccountingforItAll
