import React from 'react'

const SneakPeekChapterOneofAccountingforitAll = () =>
  <div>
    <p><img loading="lazy" decoding="async" data-attachment-id="5343" data-permalink="https://ryanrcampbell.com/2018/10/18/sneak-peek-chapter-one-of-accounting-for-it-all/afia-featured-for-first-chapter-release/" data-orig-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/10/AFIA-Featured-for-First-Chapter-Release.png?fit=1920%2C1439&amp;ssl=1" data-orig-size="1920,1439" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="AFIA Featured for First Chapter Release" data-image-description="" data-image-caption="" data-medium-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/10/AFIA-Featured-for-First-Chapter-Release.png?fit=300%2C225&amp;ssl=1" data-large-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/10/AFIA-Featured-for-First-Chapter-Release.png?fit=1024%2C767&amp;ssl=1" class=" size-full wp-image-5343 aligncenter" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/10/AFIA-Featured-for-First-Chapter-Release.png?resize=1080%2C809&#038;ssl=1" alt="AFIA Featured for First Chapter Release" width="1080" height="809" srcset="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/10/AFIA-Featured-for-First-Chapter-Release.png?w=1920&amp;ssl=1 1920w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/10/AFIA-Featured-for-First-Chapter-Release.png?resize=300%2C225&amp;ssl=1 300w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/10/AFIA-Featured-for-First-Chapter-Release.png?resize=1024%2C767&amp;ssl=1 1024w" sizes="(max-width: 1080px) 100vw, 1080px" data-recalc-dims="1" /></p>
<p>You're reading that right: the first chapter of <em><a href="https://accountingforitall.com/book/" target="_blank" rel="noopener">Accounting for it All</a></em> is now available on accountingforitall.com!</p>
<p>What are you waiting for? <a href="http://accountingforitall.com/2018/10/18/its-here-your-first-look-at-accounting-for-it-all" target="_blank" rel="noopener">Read the first chapter of <em>Accounting for it All</em> here!</a></p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default SneakPeekChapterOneofAccountingforitAll
