import React from 'react'

const ComingSoonEMPATHYTheGame = () =>
  <div>
    <p>At <a href="https://www.facebook.com/events/2114615952182145/" target="_blank" rel="noopener">this Friday's book launch party for <em>Imminent</em> <em>Dawn</em></a>, I'll be debuting the beta version of a choose-your-own-path-style game tentatively titled <em>EMPATHY: Madrugada.</em></p>
<p>If all goes well based on feedback received during the launch event, I'll be releasing the game shortly thereafter!</p>
<p>In anticipation of the beta's release, here are some screenshots from the game in its current state.</p>
<div id="attachment_503" style="width: 653px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-503" class="alignnone size-full wp-image-503" src="https://empathynovel.files.wordpress.com/2019/02/screen-shot-2019-02-17-at-9.18.07-am.png?resize=643%2C595" alt="Screen Shot 2019-02-17 at 9.18.07 AM" width="643" height="595" data-recalc-dims="1" /><p id="caption-attachment-503" class="wp-caption-text">You'll be able to play as Chandra in the game's first edition, with more characters to come!</p></div>
<div id="attachment_504" style="width: 652px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-504" class="alignnone size-full wp-image-504" src="https://empathynovel.files.wordpress.com/2019/02/screen-shot-2019-02-17-at-9.20.49-am.png?resize=642%2C1080" alt="Screen Shot 2019-02-17 at 9.20.49 AM" width="642" height="1080" data-recalc-dims="1" /><p id="caption-attachment-504" class="wp-caption-text">Use the cerenet and EMPATHY to interact with real characters from <em>Imminent Dawn</em>!</p></div>
<div id="attachment_505" style="width: 655px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-505" class="alignnone size-full wp-image-505" src="https://empathynovel.files.wordpress.com/2019/02/screen-shot-2019-02-17-at-9.22.08-am.png?resize=645%2C1028" alt="Screen Shot 2019-02-17 at 9.22.08 AM" width="645" height="1028" data-recalc-dims="1" /><p id="caption-attachment-505" class="wp-caption-text">Confront foes and forge alliances with the other characters you encounter!</p></div>
<div id="attachment_506" style="width: 654px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-506" class="alignnone size-full wp-image-506" src="https://empathynovel.files.wordpress.com/2019/02/screen-shot-2019-02-17-at-9.23.33-am.png?resize=644%2C819" alt="Screen Shot 2019-02-17 at 9.23.33 AM" width="644" height="819" data-recalc-dims="1" /><p id="caption-attachment-506" class="wp-caption-text">Visit real places from the novel as you attempt to escape the research compound!</p></div>
<p>There you have them&#8212;teaser images from <em>EMPATHY: Madrugada. </em>Ready to play? It'll be released to the public in a few weeks, but those who attend <a href="https://www.facebook.com/events/2114615952182145/" target="_blank" rel="noopener">the book launch party</a> will have the first opportunity to navigate the research compound as Chandra, <em>Imminent Dawn</em>‘s protagonist!</p>
<p>Want to read the book before you play? You can find it at all of the links below.</p>
<p style="text-align: center;"><a href="https://www.amazon.com/Imminent-Dawn-EMPATHY-Book-1-ebook/dp/B07N1Q8C6G/ref=tmm_kin_swatch_0?_encoding=UTF8&amp;qid=1548982375&amp;sr=8-1" target="_blank" rel="noopener">Amazon</a> | <a href="https://www.barnesandnoble.com/w/imminent-dawn-rr-campbell/1130343569?ean=2940161198599" target="_blank" rel="noopener">Barnes &amp; Noble</a> | <a href="https://ninestarpress.com/product/imminent-dawn/" target="_blank" rel="noopener">NineStar Press</a> | <a href="https://www.kobo.com/us/en/ebook/imminent-dawn" target="_blank" rel="noopener">Kobo</a> | <a href="https://www.smashwords.com/books/view/919525" target="_blank" rel="noopener">Smashwords</a> | <a href="https://www.goodreads.com/book/show/43196570-imminent-dawn">Goodreads</a></p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default ComingSoonEMPATHYTheGame
