import React from 'react'

const EMPATHYMadrugadatobeReleasedthisFriday = () =>
  <div>
    <p>It's (almost) here! This Friday will mark the public release of <em>EMPATHY: Madrugada</em>, a choose-your-own-destiny game set in the EMPATHY-verse. I had the chance to debut the game at the book launch party for <em>Imminent Dawn </em>last Friday, and those who played had a great&#8212;though challenging&#8212;time helping Chandra escape the Human/Etech research compound.</p>
<div id="attachment_530" style="width: 4397px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-530" class="alignnone size-full wp-image-530" src="https://empathynovel.files.wordpress.com/2019/02/img_6843-411.jpg?resize=1080%2C733" alt="IMG_6843-411" width="1080" height="733" data-recalc-dims="1" /><p id="caption-attachment-530" class="wp-caption-text">Launch party attendees had the chance to test EMPATHY: MADRUGADA, a choose-your-own-destiny game set in the EMPATHY universe.</p></div>
<p>So get excited! Here's some more of what you can expect from the game as you play.</p>
<div id="attachment_503" style="width: 653px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-503" class=" size-full wp-image-503 aligncenter" src="https://empathynovel.files.wordpress.com/2019/02/screen-shot-2019-02-17-at-9.18.07-am.png?resize=643%2C595" alt="Screen Shot 2019-02-17 at 9.18.07 AM" width="643" height="595" data-recalc-dims="1" /><p id="caption-attachment-503" class="wp-caption-text">Escape the compound as Chandra, the art-school dropout!</p></div>
<div id="attachment_506" style="width: 654px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-506" class=" size-full wp-image-506 aligncenter" src="https://empathynovel.files.wordpress.com/2019/02/screen-shot-2019-02-17-at-9.23.33-am.png?resize=644%2C819" alt="Screen Shot 2019-02-17 at 9.23.33 AM" width="644" height="819" data-recalc-dims="1" /><p id="caption-attachment-506" class="wp-caption-text">Visit actual locations from the book!</p></div>
<div id="attachment_505" style="width: 655px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-505" class="alignnone size-full wp-image-505" src="https://empathynovel.files.wordpress.com/2019/02/screen-shot-2019-02-17-at-9.22.08-am.png?resize=645%2C1028" alt="Screen Shot 2019-02-17 at 9.22.08 AM" width="645" height="1028" data-recalc-dims="1" /><p id="caption-attachment-505" class="wp-caption-text">Confront foes and forge alliances with the other characters you encounter!</p></div>
<div id="attachment_504" style="width: 652px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-504" class=" size-full wp-image-504 aligncenter" src="https://empathynovel.files.wordpress.com/2019/02/screen-shot-2019-02-17-at-9.20.49-am.png?resize=642%2C1080" alt="Screen Shot 2019-02-17 at 9.20.49 AM" width="642" height="1080" data-recalc-dims="1" /><p id="caption-attachment-504" class="wp-caption-text">Use the cerenet to connect with others on the compound!</p></div>
<p>Worried about spoilers? Don't be! Though the game ties into moments from the book, it's independent from the actual plot.</p>
<p>Need to get caught up on the book before you play? Just want to get a copy of it in general? The links below will have all you need.</p>
<p style="text-align: center;"><a href="https://www.amazon.com/Imminent-Dawn-EMPATHY-Book-1-ebook/dp/B07N1Q8C6G/ref=tmm_kin_swatch_0?_encoding=UTF8&amp;qid=1548982375&amp;sr=8-1" target="_blank" rel="noopener noreferrer">Amazon</a> | <a href="https://www.barnesandnoble.com/w/imminent-dawn-rr-campbell/1130343569?ean=2940161198599" target="_blank" rel="noopener noreferrer">Barnes &amp; Noble</a> | <a href="https://ninestarpress.com/product/imminent-dawn/" target="_blank" rel="noopener noreferrer">NineStar Press</a> | <a href="https://www.kobo.com/us/en/ebook/imminent-dawn" target="_blank" rel="noopener noreferrer">Kobo</a> | <a href="https://www.smashwords.com/books/view/919525" target="_blank" rel="noopener noreferrer">Smashwords</a> | <a href="https://www.goodreads.com/book/show/43196570-imminent-dawn">Goodreads</a></p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default EMPATHYMadrugadatobeReleasedthisFriday
