import React from 'react'

const ThankYouAnImminentDawnLaunchPartyRecap = () =>
  <div>
    <p>I want to thank everyone who came out to show their support at Friday's book launch party for <em>Imminent Dawn</em>! We had a really wonderful turnout, and I had a blast catching up with old friends and making some new ones as well.</p>
<p>Here are some photos from the event!</p>
<div id="attachment_528" style="width: 3692px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-528" class="alignnone size-full wp-image-528" src="https://empathynovel.files.wordpress.com/2019/02/img_6851-415.jpg?resize=1080%2C864" alt="IMG_6851-415" width="1080" height="864" data-recalc-dims="1" /><p id="caption-attachment-528" class="wp-caption-text">Signing books for some folks who heard about the event in the <em>Isthmus</em>, the city paper!</p></div>
<div id="attachment_529" style="width: 3711px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-529" class="alignnone size-full wp-image-529" src="https://empathynovel.files.wordpress.com/2019/02/img_6817-edit-edit-401.jpg?resize=1080%2C864" alt="IMG_6817-Edit-Edit-401" width="1080" height="864" data-recalc-dims="1" /><p id="caption-attachment-529" class="wp-caption-text">Books and other swag stacked up and ready to go!</p></div>
<div id="attachment_530" style="width: 4397px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-530" class="alignnone size-full wp-image-530" src="https://empathynovel.files.wordpress.com/2019/02/img_6843-411.jpg?resize=1080%2C733" alt="IMG_6843-411" width="1080" height="733" data-recalc-dims="1" /><p id="caption-attachment-530" class="wp-caption-text">Launch party attendees had the chance to test EMPATHY: MADRUGADA, a choose-your-own-destiny game set in the EMPATHY universe. Watch for it to be released publicly in the coming weeks!</p></div>
<div id="attachment_533" style="width: 1328px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-533" class="alignnone size-full wp-image-533" src="https://empathynovel.files.wordpress.com/2019/02/img_6859-420.jpg?resize=1080%2C1350" alt="IMG_6859-420" width="1080" height="1350" data-recalc-dims="1" /><p id="caption-attachment-533" class="wp-caption-text">I love engaging with readers and readers-to-be, and this event was no exception.</p></div>
<div id="attachment_534" style="width: 3368px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-534" class="alignnone size-full wp-image-534" src="https://empathynovel.files.wordpress.com/2019/02/img_6829-405.jpg?resize=1080%2C864" alt="IMG_6829-405" width="1080" height="864" data-recalc-dims="1" /><p id="caption-attachment-534" class="wp-caption-text">Thanks to my wife, Lacey, for holding down the book-sale table!</p></div>
<p>And there you have it! Or, well, <em>had </em>it.</p>
<p>If you couldn't make the launch party, no worries! I've got <a href="https://www.facebook.com/pg/iamrrcampbell/events/?ref=page_internal" target="_blank" rel="noopener noreferrer">a number of other events on the horizon</a>, and you can always catch up with me then.</p>
<p>Can't wait until one of those events to get your hands on a copy of <em>Imminent Dawn</em>? I can't blame you! You can order your copy now at any of the links below.</p>
<p style="text-align: center;"><a href="https://www.amazon.com/Imminent-Dawn-EMPATHY-Book-1-ebook/dp/B07N1Q8C6G/ref=tmm_kin_swatch_0?_encoding=UTF8&amp;qid=1548982375&amp;sr=8-1" target="_blank" rel="noopener noreferrer">Amazon</a> | <a href="https://www.barnesandnoble.com/w/imminent-dawn-rr-campbell/1130343569?ean=2940161198599" target="_blank" rel="noopener noreferrer">Barnes &amp; Noble</a> | <a href="https://ninestarpress.com/product/imminent-dawn/" target="_blank" rel="noopener noreferrer">NineStar Press</a> | <a href="https://www.kobo.com/us/en/ebook/imminent-dawn" target="_blank" rel="noopener noreferrer">Kobo</a> | <a href="https://www.smashwords.com/books/view/919525" target="_blank" rel="noopener noreferrer">Smashwords</a> | <a href="https://www.goodreads.com/book/show/43196570-imminent-dawn">Goodreads</a></p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default ThankYouAnImminentDawnLaunchPartyRecap
