import React from 'react'

const WhatexactlyisgoingonwithallthingsEMPATHY = () =>
  <div>
    <p>That's a great question. It's been a while since I've done a thorough update on the series, so let's take the books one by one and see where we're at.</p>
<h2><em>Imminent Dawn </em>(EMPATHY #1)</h2>
<p>Oh, you haven't heard? <em>Imminent Dawn </em>is now available worldwide in ebook and print with most major retailers. That's right, the story of four people, one study, and the internet-access brain implant to bind or destroy them all is in readers' hands everywhere, and <a href="https://www.goodreads.com/book/show/43196570-imminent-dawn" target="_blank" rel="noopener">wonderful reviews keep rolling in</a>!</p>
<p>If you haven't got a copy yet, you can find it on all of your favorite bookish sites below. And don't forget to leave a review once you've had a chance to read it; those make a <em>huge </em>difference in a book's visibility and will make sure it gets in front of more readers' eyes!</p>
<p style="text-align: center;"><a href="https://www.amazon.com/Imminent-Dawn-EMPATHY-Book-1-ebook/dp/B07N1Q8C6G/ref=tmm_kin_swatch_0?_encoding=UTF8&amp;qid=1548982375&amp;sr=8-1" target="_blank" rel="noopener">Amazon</a> | <a href="https://www.barnesandnoble.com/w/imminent-dawn-rr-campbell/1130343569?ean=2940161198599" target="_blank" rel="noopener">Barnes &amp; Noble</a> | <a href="https://ninestarpress.com/product/imminent-dawn/" target="_blank" rel="noopener">NineStar Press</a> | <a href="https://www.kobo.com/us/en/ebook/imminent-dawn" target="_blank" rel="noopener">Kobo</a> | <a href="https://www.smashwords.com/books/view/919525" target="_blank" rel="noopener">Smashwords</a> | <a href="https://www.goodreads.com/book/show/43196570-imminent-dawn">Goodreads</a></p>
<p>If you're in the Madison, Wisconsin area, you might be interested to know I'm hosting a book launch party on Friday, February 22nd at the Goodman Community Center on Madison's east side. I'll do a few readings from the book, hold an author Q&amp;A, and will also debut <em>EMPATHY: Madrugada</em>, a choose-your-own-destiny style game that will be available online shortly after the event!</p>
<p style="text-align: center;"><a href="https://www.facebook.com/events/2114615952182145/" target="_blank" rel="noopener">Be sure to RSVP to the book launch event here.</a></p>
<h2><em>Mourning Dove </em>(EMPATHY #2)</h2>
<p><a href="http://empathyseries.com/2019/02/04/its-official-imminent-dawn-has-a-sequel/" target="_blank" rel="noopener">Per last week's announcement</a>, the second installment of the epic EMPATHY sci-fi saga will be released with NineStar Press on <em>April 8, 2019</em>. Keep your eyes on this blog, <a href="http://eepurl.com/dhBxcv" target="_blank" rel="noopener">my newsletter</a>, and <a href="http://www.twitter.com/iamrrcampbell" target="_blank" rel="noopener">Twitter</a>, <a href="http://www.facebook.com/iamrrcampbell" target="_blank" rel="noopener">Facebook</a>, and <a href="http://www.instagram.com/iamrrcampbell" target="_blank" rel="noopener">Instagram</a> feeds for more information about the book as we get closer to its release.</p>
<p>Interested in reviewing an advance copy of <em>Mourning Dove </em>or in being part of release week promotion? <a href="https://goo.gl/forms/k4qLe8qeh2laFw8D2" target="_blank" rel="noopener">Let me know by completing this form.</a></p>
<h2><em>Event Horizon</em> (EMPATHY #3)</h2>
<p>I'm actively writing the first draft of <em>Event Horizon </em>right now, and would say I'm about two-thirds of the way through it. At this time, my goal is to deliver a manuscript to NineStar Press in May, with the aim of having this one published possibly as early as September of this year!</p>
<h2><em>Consolunarity</em> (EMPATHY #4) and <em>Nightshade</em> (EMPATHY #5)</h2>
<p>Though I know what happens in both of these books, I suspect it will be some time before I'm able to have manuscripts available to submit to NineStar. After completing <em>Event Horizon</em>, I'd like to spend some time dabbling with another series and getting another book outside of the EMPATHY-verse published.</p>
<p>I also think giving the series an opportunity to simmer after book three will put me in the best position to execute my plan for books four and five, and it'll additionally let me really focus on making sure as many readers as possible are able to connect with the series prior to the release of books four and five.</p>
<h2>“What can I do to help?”</h2>
<p>The simplest thing anyone can do is pick up a copy of any of these books and recommend them to friends! If you'd like to take your support to the next level, I <em>strongly </em>encourage you to leave reviews on <a href="https://www.goodreads.com/book/show/43196570-imminent-dawn" target="_blank" rel="noopener">Goodreads</a>, <a href="https://www.amazon.com/Imminent-Dawn-EMPATHY-R-R-Campbell/dp/1949909980/ref=zg_bsnr_17861280011_3?_encoding=UTF8&amp;psc=1&amp;refRID=XDPW6HZGEDNQSZ2GBVCF" target="_blank" rel="noopener">Amazon</a>, <a href="https://www.barnesandnoble.com/w/imminent-dawn-rr-campbell/1130343569?ean=2940161198599" target="_blank" rel="noopener">Barnes &amp; Noble</a>, and on your social media accounts.</p>
<p>And if you'll be at any of the events or cons I'll be at to talk EMPATHY or other writing-related matters, swing by and say “hi.” I'd love to meet you and get you some EMPATHY swag whenever I have it available.</p>
<p>Thanks for visiting the blog!</p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default WhatexactlyisgoingonwithallthingsEMPATHY
