import React from 'react'

const ThisWeekAuthorrrcampbellattheUWWritersInstitute = () =>
  <div>
    <p><img loading="lazy" decoding="async" class=" size-full wp-image-703 aligncenter" src="https://empathynovel.files.wordpress.com/2019/03/writers-institute-logo-30th-annual.png?resize=1050%2C248" alt="writers-institute-logo-30th-annual" width="1050" height="248" data-recalc-dims="1" /></p>
<p>This Thursday through Sunday, author r. r. campbell will be attending the University of Wisconsin Writers' Institute, which <em>The Writer </em>magazine recently selected as <a href="https://uwwritersinstitute.wisc.edu/writers-institute-the-top-writing-conference-in-wisconsin/" target="_blank" rel="noopener noreferrer">the best conference for writers in the state of Wisconsin.</a></p>
<p>Not only will r. r. be in attendance talking shop and selling books, he'll also be leading <a href="https://uwwritersinstitute.wisc.edu/speakers/r-r-campbell/" target="_blank" rel="noopener noreferrer">four sessions on the craft and business of writing</a>, and he'll be speaking on Friday afternoon's success panel.</p>
<p>Want to learn more about the Institute? Be sure to check it out on <a href="https://uwwritersinstitute.wisc.edu/" target="_blank" rel="noopener noreferrer">the official Institute page</a>, and read up on r. r.'s sessions prior to the conference's launch.</p>
<p>Can't make it? Still want to get your copies of r. r. campbell's books? You can find them at the links below.</p>
<h3 style="text-align: center;"><em><strong>Imminent Dawn</strong></em></h3>
<p style="text-align: center;"><a href="https://www.amazon.com/Imminent-Dawn-EMPATHY-Book-1-ebook/dp/B07N1Q8C6G/ref=tmm_kin_swatch_0?_encoding=UTF8&amp;qid=1548982375&amp;sr=8-1" target="_blank" rel="noopener noreferrer">Amazon</a> | <a href="https://www.barnesandnoble.com/w/imminent-dawn-rr-campbell/1130343569?ean=2940161198599" target="_blank" rel="noopener noreferrer">Barnes &amp; Noble</a> | <a href="https://ninestarpress.com/product/imminent-dawn/" target="_blank" rel="noopener noreferrer">NineStar Press</a> | <a href="https://www.kobo.com/us/en/ebook/imminent-dawn" target="_blank" rel="noopener noreferrer">Kobo</a> | <a href="https://www.smashwords.com/books/view/919525" target="_blank" rel="noopener noreferrer">Smashwords</a> | <a href="https://www.goodreads.com/book/show/43196570-imminent-dawn">Goodreads</a> | <a href="https://ryanrcampbell.com/product/signedimminentdawn/" target="_blank" rel="noopener noreferrer">Author Website</a></p>
<h3 style="text-align: center;"><em><strong>Mourning Dove<br />
</strong></em>(preorders)</h3>
<p style="text-align: center;"><a href="http://ninestarpress.com/product/mourning-dove" target="_blank" rel="noopener noreferrer">NineStar Press (ebook)</a> | <a href="https://www.goodreads.com/book/show/43728390-mourning-dove" target="_blank" rel="noopener noreferrer">Goodreads</a> | <a href="https://ryanrcampbell.com/?post_type=product&amp;p=5816&amp;preview=true" target="_blank" rel="noopener noreferrer">Author Website (print)</a></p>
<h3 style="text-align: center;"><em>Accounting for It All</em></h3>
<p style="text-align: center;"><a href="https://www.amazon.com/Accounting-All-R-R-Campbell-ebook/dp/B07KDQBZ55/ref=tmm_kin_swatch_0?_encoding=UTF8&amp;qid=1543358936&amp;sr=8-1" target="_blank" rel="noopener noreferrer">Amazon</a> | <a href="https://ninestarpress.com/product/accounting-for-it-all/" target="_blank" rel="noopener noreferrer">NineStar Press</a> | <a href="https://www.barnesandnoble.com/w/books/1129827229;jsessionid=62066B592FE7E62FA5EBFA0BBD49688F.prodny_store01-atgap15?ean=9781949909388&amp;st=AFF&amp;2sid=Goodreads,%20Inc_2227948_NA&amp;sourceId=AFFGoodreads,%20Inc" target="_blank" rel="noopener noreferrer">Barnes &amp; Noble</a> | <a href="https://www.goodreads.com/book/show/42604499-accounting-for-it-all" target="_blank" rel="noopener noreferrer">Goodreads</a></p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default ThisWeekAuthorrrcampbellattheUWWritersInstitute
