import React from 'react'

const NowAvailableEditingandWritescastAcademyGiftCards = () =>
  <div>
    <p><img loading="lazy" decoding="async" data-attachment-id="6989" data-permalink="https://ryanrcampbell.com/gift-card/" data-orig-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/10/GIFT-CARD.png?fit=1080%2C1080&amp;ssl=1" data-orig-size="1080,1080" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="GIFT CARD" data-image-description="" data-image-caption="" data-medium-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/10/GIFT-CARD.png?fit=300%2C300&amp;ssl=1" data-large-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/10/GIFT-CARD.png?fit=1024%2C1024&amp;ssl=1" class="  wp-image-6989 aligncenter" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/10/GIFT-CARD.png?resize=400%2C400&#038;ssl=1" alt="GIFT CARD" width="400" height="400" srcset="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/10/GIFT-CARD.png?w=1080&amp;ssl=1 1080w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/10/GIFT-CARD.png?resize=150%2C150&amp;ssl=1 150w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/10/GIFT-CARD.png?resize=300%2C300&amp;ssl=1 300w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/10/GIFT-CARD.png?resize=768%2C768&amp;ssl=1 768w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/10/GIFT-CARD.png?resize=1024%2C1024&amp;ssl=1 1024w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/10/GIFT-CARD.png?resize=180%2C180&amp;ssl=1 180w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/10/GIFT-CARD.png?resize=624%2C624&amp;ssl=1 624w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/10/GIFT-CARD.png?resize=100%2C100&amp;ssl=1 100w" sizes="(max-width: 400px) 100vw, 400px" data-recalc-dims="1" /></p>
<p>Based on feedback from the community and in keeping with my goal of making my writing coach services as accessible as possible, I'm proud to now offer gift cards through my online shop!</p>
<h2>What are these gift cards? What are they for?</h2>
<p>These gift cards allow writers' family members and friends to make it even more affordable for the writers in their lives to take advantage of <a href="http://www.rrcampbellwrites.com/editing-services">my editing services</a> or my courses through <a href="http://www.rrcampbellwrites.com/courses">Writescast Academy</a>!</p>
<h2>Who can buy these gift cards?</h2>
<p>Gift cards can be purchased by anyone at any time.</p>
<h2>Where can I buy them?</h2>
<p>These gift cards are available <em>exclusively </em>through <a href="https://ryanrcampbell.com/product/editing-services-or-writescast-academy-gift-card/">my online shop</a> here at rrcampbellwrites.com.</p>
<h2>Is there a minimum amount that needs to be put on a gift card?</h2>
<p>With card values ranging from $5 to $500, flexibility is at your fingertips!</p>
<h2>How are they redeemed?</h2>
<p>After completing a gift card purchase through my online shop, the gift card will be sent as an attachment by email to the address provided at check-out.</p>
<p>When printing the gift card, be sure to write the confirmation number of the transaction (found in the email that includes the gift card) and the value of the gift card.</p>
<h2>When will these gift cards become available for purchase?</h2>
<p>These gift cards are available now! <a href="https://ryanrcampbell.com/product/editing-services-or-writescast-academy-gift-card/">Head to my online shop today</a> to get the writer in your life a gift that will keep on giving—that of a quality writerly education through my editing and coaching services.</p>
<h2>What if I have other questions?</h2>
<p>You can always <a href="http://www.rrcampbellwrites.com/contact">contact me by email</a> with questions about this or any of my other offerings.</p>
<p><img loading="lazy" decoding="async" data-attachment-id="7003" data-permalink="https://ryanrcampbell.com/2019/11/01/now-available-editing-and-writescast-academy-gift-cards/gift-card-sample/" data-orig-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/10/Gift-Card-Sample.png?fit=794%2C1123&amp;ssl=1" data-orig-size="794,1123" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="Gift Card Sample" data-image-description="" data-image-caption="" data-medium-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/10/Gift-Card-Sample.png?fit=212%2C300&amp;ssl=1" data-large-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/10/Gift-Card-Sample.png?fit=724%2C1024&amp;ssl=1" class="aligncenter size-full wp-image-7003" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/10/Gift-Card-Sample.png?resize=794%2C1123&#038;ssl=1" alt="Gift Card Sample.png" width="794" height="1123" srcset="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/10/Gift-Card-Sample.png?w=794&amp;ssl=1 794w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/10/Gift-Card-Sample.png?resize=212%2C300&amp;ssl=1 212w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/10/Gift-Card-Sample.png?resize=768%2C1086&amp;ssl=1 768w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/10/Gift-Card-Sample.png?resize=724%2C1024&amp;ssl=1 724w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/10/Gift-Card-Sample.png?resize=624%2C883&amp;ssl=1 624w" sizes="(max-width: 794px) 100vw, 794px" data-recalc-dims="1" /></p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default NowAvailableEditingandWritescastAcademyGiftCards
