import React from 'react'

const LetsTalkQuerying = () =>
  <div>
    <p>Querying. The word alone is enough to have some writers retreating into their shells, but to those outside the writing community, it's a topic with which few have any familiarity.</p>
<p>So let's talk querying today&#8212;not the hows, per se, but the what, the why, and how it's going in my own querying journey for the manuscript I'm currently shopping.</p>
<p>For those unfamiliar with the term, querying is the act of sending query letters (essentially cover letters for your book) to literary agents with the goal of attracting their attention, having them request pages&#8212;or, ideally, the full manuscript&#8212;and, from there, signing with them to have them represent you, your manuscript, and your interests to a publisher.</p>
<p>The process then begins all over again, but this time, it's your agent&#8212;an industry insider&#8212;introducing your work to the publishing world's gatekeepers, who, at the largest publishing houses, do not take submissions directly from authors.</p>
<p>If this seems daunting, it is; ask any writer who's undertaken the task. There's a specific format one must generally use in their queries, and distilling one's book into a single page that follows this format is all the more challenging.</p>
<p>But it <em>is </em>possible, and it's an absolutely critical step for any writer who dreams of having their work traditionally published with one of the major publishing houses.</p>
<p>Those of you who know me or my work might be wondering at this juncture why I'm actively querying a manuscript. Don't I already have a publisher? Aren't my books slated for publication from now to the end of time?</p>
<p>First, yes. I do have a publisher, or did for <em><a href="https://www.amazon.com/dp/B07KDQBZ55/" target="_blank" rel="noopener noreferrer">Accounting for It All</a> </em>and the first two books in my <a href="https://www.amazon.com/gp/product/B07R7DLZ1L" target="_blank" rel="noopener noreferrer">EMPATHY sci-fi saga</a>. NineStar Press, however, is a smaller, independent press that <em>does </em>accept queries directly from authors.</p>
<p>Working with presses like NineStar is a wonderful way to get one's feet wet in the publishing world. By querying small presses and&#8212;if your work is up to the content and quality standards of what they're looking to publish&#8212;having your work published with them, a writer can learn an immense amount about publishing, marketing, and navigating rejection.</p>
<p>Oh, and your books can wind up published, too, which isn't a bad deal, either.</p>
<p>That said, for the next few manuscripts I'm working on or have written, I'm ready, again, to hit query road and reach new audiences with my work. Working with an agent and then, hopefully, a large publisher also means broader distribution, a marketing budget funded by the publisher, and, in most cases an advance&#8212;all of which are hard to come by or non-existent in the world of working with independent presses.</p>
<p>Since mid-March, I've been actively querying a manuscript tentatively entitled <em>When the Stars Conspire</em>. Here's a selection of the query letter I've been sending out to agents in the time since.</p>
<blockquote>
<h5>Zachary Carmichael is going to die, and all he’s left with are questions. When cranberry farmer Kelsey Lilageist discovers the wreckage of his plane on her farm, he has no answer for who he is or how he came to be in his aircraft, and the mystery only deepens when Kelsey drives Zach to the address on his license; there’s no home on the property—it’s as thickly forested as the rest of Vilas County.</h5>
<h5>At Kelsey’s invite, Zach takes up temporary residence on her farm, but he’s haunted by incomplete visions of a past life, one of extraordinary technology—and danger—far beyond the seemingly simple routine Kelsey’s built for herself in rural Wisconsin. Kelsey’s life isn’t, however, as straightforward as it appears: horrifying visions of her own preceded Zach’s arrival, and as the two of them grow closer, those visions grow darker and more ominous. Between Zach and Kelsey, they begin to suspect she was once murdered for a secret Zach was willing to travel light years to ascertain—and that those who killed her are now after Zach, too.</h5>
<h5>As otherworldly foes with murderous intentions encroach upon Kelsey’s farm, Zach and Kelsey find themselves caught, too, between their search for the forbidden knowledge Kelsey died to learn and their growing attraction to each other. To overcome, the two of them must decide: embrace the imperfect beauty of the present, or surge on in the face of mortal peril to secure a future for all sentient life in the universe.</h5>
</blockquote>
<p>These are the sections known as “the hook” and “the book.” I've left off the so-called “cook” section&#8212;in which you mention your platform and publishing credentials to date&#8212;as well as the comparison titles section, in which one mentions the manuscript's word count and other successful books to which your title can be compared.</p>
<p>So with that context in mind, how has my querying experience gone so far? Let's take a look at the numbers.</p>
<p><div id="attachment_7714" style="width: 1802px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-7714" data-attachment-id="7714" data-permalink="https://ryanrcampbell.com/2020/04/23/lets-talk-querying/april-2020-query-table-blurred/" data-orig-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/04/April-2020-Query-Table-Blurred.png?fit=1792%2C828&amp;ssl=1" data-orig-size="1792,828" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="April 2020 Query Table Blurred" data-image-description="" data-image-caption="&lt;p&gt;My query log to date. Red are rejections, yellow indicates pending submissions, and green is used to indicate various stages of interest from an agent. Individual rows are blurred to protect individuals' privacy.&lt;/p&gt;
" data-medium-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/04/April-2020-Query-Table-Blurred.png?fit=300%2C139&amp;ssl=1" data-large-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/04/April-2020-Query-Table-Blurred.png?fit=1024%2C473&amp;ssl=1" class="alignnone size-full wp-image-7714" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/04/April-2020-Query-Table-Blurred.png?resize=1080%2C499&#038;ssl=1" alt="April 2020 Query Table Blurred" width="1080" height="499" srcset="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/04/April-2020-Query-Table-Blurred.png?w=1792&amp;ssl=1 1792w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/04/April-2020-Query-Table-Blurred.png?resize=300%2C139&amp;ssl=1 300w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/04/April-2020-Query-Table-Blurred.png?resize=1024%2C473&amp;ssl=1 1024w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/04/April-2020-Query-Table-Blurred.png?resize=768%2C355&amp;ssl=1 768w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/04/April-2020-Query-Table-Blurred.png?resize=1536%2C710&amp;ssl=1 1536w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/04/April-2020-Query-Table-Blurred.png?resize=624%2C288&amp;ssl=1 624w" sizes="(max-width: 1080px) 100vw, 1080px" data-recalc-dims="1" /><p id="caption-attachment-7714" class="wp-caption-text">My query log to date. Red are rejections, yellow indicates pending submissions, and green is used to indicate various stages of interest from an agent. Individual rows are blurred to protect individuals' privacy.</p></div></p>
<ul>
<li>21 queries sent</li>
<li>10 rejections (7 form, 3 personal)</li>
<li>9 awaiting reply</li>
<li>1 partial request</li>
<li>1 full request</li>
</ul>
<p>Having twenty-one queries sent since mid-March is nothing to shrug off; what this number doesn't convey is the amount of time necessary to research agents to whom this book might appeal. That's right; you don't simply copy every agent you've ever heard of into a single email and hope for the best. Each query should be personalized and appeal to their particular taste, which they often convey in what's known as a manuscript wish list (often abbreviated as MSWL).</p>
<p>Ten rejections isn't what one wants, but it's by no means awful. Keep in mind<strong> agents do not get paid until the author gets paid. </strong>This means an agent has to be willing to work with you <strong>for free </strong>until they find a publisher for your work, at which point they generally get a 15% cut of your advance and royalties. In other words, they have to <em>love </em>your work from the moment they first read of it to consider reading your actual manuscript. They have their own client list already, after all, and it's with their clients that their focus really has to be.</p>
<p>And nine awaiting reply, huh? Some might think it's rude to have not heard back from someone in a month, but in the world of publishing, a month is the equivalent of an hour elsewhere. It can be three to six months before you hear back from an agent, assuming one hears back at all. This, again, is a result of their need to focus on their clients first, as well as, you know, themselves and their families outside of the world of work.</p>
<p>Then we get into the requests! This is where one wants to be. A partial request means an agent has written you back and asked for a portion of your manuscript. In my case, an agent has requested the first three chapters of my manuscript after having read my query letter. Interestingly enough, this is an agent I didn't initially query, but rather one who works at the same agency as an agent to whom I did reach out. That's another noteworthy dynamic at play here: if your manuscript isn't right for one agent but they work with another agent to whom they think your work might appeal, they'll pass along your work to their colleague. Teamwork!</p>
<p>And of course, then, we have the full requests. These come about when an agent has been really drawn in my your query letter or any sample pages they've seen of yours so far. At this stage, they're asking for the full manuscript, which, if it holds their attention, remains up their alley insofar as publishing-world connections are concerned, and they think you're a good fit after what's essentially a phone interview known as “the call,” they then offer you representation!</p>
<p>So, yes, there are quite a few dominoes that have to align even after a full request has been made, but I'm thrilled to have a full request after only a month of querying work. This is doubly the case considering the individual who has requested a full from me is someone I would absolutely love to work with should I be so fortunate.</p>
<p>And that's querying in a nutshell, as well as where I'm at in my journey for the moment. I've put querying on pause until early May, at which point I'll resume the work. There are strategic reasons for this I can get into in a future post, but for now, we'll leave it there.</p>
<p>Questions? Comments? Learn something new today? Let me know in the comments!</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default LetsTalkQuerying
