import React from 'react'

const PresentingJustMewithRRCampbell = () =>
  <div>
    <p><img loading="lazy" decoding="async" data-attachment-id="7545" data-permalink="https://ryanrcampbell.com/just-me-4/" data-orig-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/02/Just-Me-4.png?fit=3000%2C3000&amp;ssl=1" data-orig-size="3000,3000" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="Just Me (4)" data-image-description="" data-image-caption="" data-medium-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/02/Just-Me-4.png?fit=300%2C300&amp;ssl=1" data-large-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/02/Just-Me-4.png?fit=1024%2C1024&amp;ssl=1" class="  wp-image-7545 aligncenter" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/02/Just-Me-4.png?resize=400%2C400&#038;ssl=1" alt="Just Me (4)" width="400" height="400" srcset="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/02/Just-Me-4.png?w=3000&amp;ssl=1 3000w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/02/Just-Me-4.png?resize=300%2C300&amp;ssl=1 300w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/02/Just-Me-4.png?resize=1024%2C1024&amp;ssl=1 1024w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/02/Just-Me-4.png?resize=150%2C150&amp;ssl=1 150w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/02/Just-Me-4.png?resize=768%2C768&amp;ssl=1 768w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/02/Just-Me-4.png?resize=1536%2C1536&amp;ssl=1 1536w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/02/Just-Me-4.png?resize=2048%2C2048&amp;ssl=1 2048w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/02/Just-Me-4.png?resize=180%2C180&amp;ssl=1 180w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/02/Just-Me-4.png?resize=624%2C624&amp;ssl=1 624w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/02/Just-Me-4.png?resize=100%2C100&amp;ssl=1 100w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2020/02/Just-Me-4.png?w=2160&amp;ssl=1 2160w" sizes="(max-width: 400px) 100vw, 400px" data-recalc-dims="1" /></p>
<p>It took nearly four years and over one hundred episodes of podcasting before I realized I was never <em>once </em>myself in any of them. This left me with one haunting question.</p>
<p><em>Why?</em></p>
<p>Fear, I suspect. Fear of what it might mean to open up, to let go, to let in the light and the dark and the in between. Fear of sharing who I am, what I value, and how I feel about how I arrived at all of this and more.</p>
<p>And the more I thought on this, <strong>the more I came to suspect I'm not alone.</strong></p>
<p>That's why, on March 30th, I'm launching “Just Me with R.R. Campbell,” a new podcast and video series.</p>
<p>Over the course of twenty-minute episodes, we'll explore topics like grief, joy, friendship, and fear, and we'll do it all with one goal in mind: living unscripted, living unedited, and living unafraid.</p>
<p>Along the way, we'll learn more about ourselves, too: who we've been, who we are, and who we might become.</p>
<p>So I hope you'll <strong>join me on March 30th, when the first three episodes of “Just Me” debut</strong> on <a href="https://podcasts.apple.com/us/podcast/id1503674576" target="_blank" rel="noopener noreferrer">Apple Podcasts</a>, <a href="https://www.podchaser.com/podcasts/just-me-with-rr-campbell-1045962" target="_blank" rel="noopener noreferrer">Podchaser</a>, <a href="https://tunein.com/podcasts/Arts--Culture-Podcasts/Just-Me-with-RR-Campbell-p1307446/" target="_blank" rel="noopener noreferrer">TuneIn</a>, <a href="https://open.spotify.com/show/5PFUecepf4qrbOkBRg7a3r" target="_blank" rel="noopener noreferrer">Spotify</a>, and <a href="https://www.youtube.com/channel/UCR7HG_mnTLwGCLnDLbEOpUg?sub_confirmation=1" target="_blank" rel="noopener noreferrer">YouTube</a>. Two more episodes will follow later that week, and then, starting on Thursday, April 9th, we'll move to weekly explorations of all the topics mentioned above and beyond.</p>
<p>See you soon, everyone. Until March 30th, live unscripted, live unedited, and live unafraid.</p>
<p><span class="embed-youtube" style="text-align:center; display: block;"><iframe loading="lazy" class="youtube-player" width="1080" height="608" src="https://www.youtube.com/embed/njYarj72bPI?version=3&#038;rel=1&#038;showsearch=0&#038;showinfo=1&#038;iv_load_policy=1&#038;fs=1&#038;hl=en-US&#038;autohide=2&#038;wmode=transparent" allowfullscreen="true" style="border:0;" sandbox="allow-scripts allow-same-origin allow-popups allow-presentation allow-popups-to-escape-sandbox"></iframe></span></p>
<h3 style="text-align: center;"><a href="https://link.chtbl.com/justmewithrr" target="_blank" rel="noopener noreferrer">Subscribe to “Just Me with R.R. Campbell” on your favorite podcasting platform.</a></h3>
<h3 style="text-align: center;"><a href="https://www.youtube.com/channel/UCR7HG_mnTLwGCLnDLbEOpUg?sub_confirmation=1" target="_blank" rel="noopener noreferrer">Prefer video? Subscribe on YouTube!</a></h3>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default PresentingJustMewithRRCampbell
