import React from 'react'

const CoursesandSeminarsListNowAvailable = () =>
  <div>
    <p>In light of a great deal of positive feedback on my craft of writing sessions at the University of Wisconsin Writers' Institute and WisCon, I'm thrilled to announce a new course and seminar list here on rrcampbellwrites.com!</p>
<p><a href="https://ryanrcampbell.com/courses/">This page</a> now includes a partial listing of courses and seminars I can conduct at your organization's upcoming conference or event.</p>
<p>More exciting still is that my flagship course, <em>Write Your Novel Now - Plotting Your Way to Success</em>, is now open for enrollment through AllWriters' Workshop and the University of Wisconsin Department of Continuing Studies in Writing.</p>
<p><img loading="lazy" decoding="async" data-attachment-id="6396" data-permalink="https://ryanrcampbell.com/courses/write-your-novel-now/" data-orig-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/07/write-your-novel-now.png?fit=1180%2C435&amp;ssl=1" data-orig-size="1180,435" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="write your novel now" data-image-description="" data-image-caption="" data-medium-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/07/write-your-novel-now.png?fit=300%2C111&amp;ssl=1" data-large-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/07/write-your-novel-now.png?fit=1024%2C377&amp;ssl=1" class=" size-full wp-image-6396 aligncenter" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/07/write-your-novel-now.png?resize=1080%2C398&#038;ssl=1" alt="write your novel now" width="1080" height="398" srcset="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/07/write-your-novel-now.png?w=1180&amp;ssl=1 1180w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/07/write-your-novel-now.png?resize=300%2C111&amp;ssl=1 300w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/07/write-your-novel-now.png?resize=768%2C283&amp;ssl=1 768w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/07/write-your-novel-now.png?resize=1024%2C377&amp;ssl=1 1024w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/07/write-your-novel-now.png?resize=624%2C230&amp;ssl=1 624w" sizes="(max-width: 1080px) 100vw, 1080px" data-recalc-dims="1" /></p>
<h3>Write Your Novel Now - Plotting Your Way to Success</h3>
<p>“How’s that novel coming?” A tough question, but never fear! After attending this course, writers will have strengthened their concepts, explored various plot structure models, and outlined their novels scene-by-scene. Not only will attendees then be empowered to take to the page, they’ll never fret answering that dreaded question again!</p>
<h3 style="text-align: center;">Enrollment is <em>now open</em> for a one-day seminar and for a more in-depth multi-week course for the fall of 2019. Sign up now! Space is limited.</h3>
<h3 style="text-align: center;"><a href="https://continuingstudies.wisc.edu/classes/plot-your-way-to-success/" target="_blank" rel="noopener noreferrer">Enroll for this fall's multi-week course with the UW Continuing Studies Department here!</a></h3>
<h3 style="text-align: center;"><a href="http://www.allwritersworkshop.com/events/celebrity-saturdays/" target="_blank" rel="noopener noreferrer">Sign up for my one-day course through AllWriters' Workshop at this address.</a></h3>
<h6 style="text-align: center;"><em>Please note the AllWriters' Workshop program is listed at the bottom of the page and under a different name. To fit within the five-hour window available, the course material for this program will be condensed relative to that of the UW's course in the fall.</em></h6>
<p>In the future, I also plan to offer most of <a href="https://ryanrcampbell.com/courses/">the classes seen on this page</a> online as well. Sound like something you'd be interested in? <a href="http://eepurl.com/dhBxcv">Be sure to sign up for my newsletter</a> to be among the first to know when enrollment opens.</p>
<p>Have questions? Interested in having me present one of these courses or seminars for writers in your area in the near future? <a href="http://www.rrcampbellwrites.com/contact">Let me know through my contact page.</a></p>
<p>In the meantime, I'm curious&#8212;which classes are <em>you</em> most excited about? Tell me in the comments!</p>
<p>Thanks as always for visiting. Write on and write well.</p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default CoursesandSeminarsListNowAvailable
