import React from 'react'

const ItsHereMourningDoveCharacterArt = () =>
  <div>
    <p>Over Memorial Day weekend, I had the privilege of speaking at WisCon 43. While there, I also worked as a vendor, peddling my books and chatting with other conference-goers.</p>
<p>One such conference-goer was artist <a href="https://www.a-damicoart.com/" target="_blank" rel="noopener noreferrer">A D'Amico</a>, who snagged a copy of <em>Imminent Dawn </em>(yay!) and also took a moment to pass along a sample of her portfolio. I really loved her work and, after a brief back and forth, she agreed to do a commission for the EMPATHY series!</p>
<p>I've been waiting for the “perfect” moment to share all of this with you, but… what does “perfect” even mean? I can't sit on these forever! I've got to share this wonderful art with the world.</p>
<p>With that in mind, away we go!</p>
<p><div id="attachment_1115" style="width: 1090px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-1115" class="alignnone size-full wp-image-1115" src="https://empathynovel.files.wordpress.com/2019/07/emd-group-close-up.png?resize=1080%2C1080" alt="EMD Group Close Up" width="1080" height="1080" data-recalc-dims="1" /><p id="caption-attachment-1115" class="wp-caption-text">Ty (left), Chandra, (middle), and Kyra (right)!</p></div></p>
<p><div id="attachment_1116" style="width: 1090px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-1116" class=" size-full wp-image-1116 aligncenter" src="https://empathynovel.files.wordpress.com/2019/07/emd-chandra.png?resize=1080%2C1080" alt="EMD Chandra.png" width="1080" height="1080" data-recalc-dims="1" /><p id="caption-attachment-1116" class="wp-caption-text">Chandra, our art-school dropout who's just trying to get by in the present.</p></div></p>
<p><div id="attachment_1117" style="width: 1090px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-1117" class="alignnone size-full wp-image-1117" src="https://empathynovel.files.wordpress.com/2019/07/emd-kyra.png?resize=1080%2C1080" alt="EMD Kyra" width="1080" height="1080" data-recalc-dims="1" /><p id="caption-attachment-1117" class="wp-caption-text">Kyra, determined as always to reclaim the past.</p></div></p>
<p><div id="attachment_1118" style="width: 1090px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-1118" class="alignnone size-full wp-image-1118" src="https://empathynovel.files.wordpress.com/2019/07/emd-ty.png?resize=1080%2C1080" alt="EMD Ty" width="1080" height="1080" data-recalc-dims="1" /><p id="caption-attachment-1118" class="wp-caption-text">Ty, a goof to be sure, but one who's determined to seize the future.</p></div></p>
<p><div id="attachment_1121" style="width: 1090px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-1121" class="alignnone size-full wp-image-1121" src="https://empathynovel.files.wordpress.com/2019/07/emd-sphinx-1.png?resize=1080%2C1080" alt="EMD Sphinx" width="1080" height="1080" data-recalc-dims="1" /><p id="caption-attachment-1121" class="wp-caption-text">Oh, and Sphinx, whose name really should have been spelled M-I-S-C-H-I-E-F.</p></div></p>
<p><img loading="lazy" decoding="async" class="alignnone size-full wp-image-1120" src="https://empathynovel.files.wordpress.com/2019/07/emd-group-with-book.png?resize=1080%2C1080" alt="EMD - Group with Book" width="1080" height="1080" data-recalc-dims="1" /></p>
<p>And there you have it! I think they look great, don't you? I'm looking forward to rolling these out more in the coming weeks and months.</p>
<p>If you haven't yet got your hands on <em>Mourning Dove </em>or book one in the series, <em>Imminent Dawn</em>, you can find them at the links below!</p>
<h2 style="text-align: center;"><em>Imminent Dawn</em></h2>
<p style="text-align: center;"><a href="https://www.amazon.com/dp/B07N1Q8C6G/" target="_blank" rel="noopener noreferrer">Amazon</a> | <a href="https://www.barnesandnoble.com/w/imminent-dawn-rr-campbell/1130343569?ean=2940161198599" target="_blank" rel="noopener noreferrer">Barnes &amp; Noble</a> | <a href="https://ninestarpress.com/product/imminent-dawn/" target="_blank" rel="noopener noreferrer">NineStar Press</a> | <a href="https://www.kobo.com/us/en/ebook/imminent-dawn" target="_blank" rel="noopener noreferrer">Kobo</a> | <a href="https://www.smashwords.com/books/view/919525" target="_blank" rel="noopener noreferrer">Smashwords</a>| <a href="https://www.goodreads.com/book/show/43196570-imminent-dawn">Goodreads</a> | <a href="https://ryanrcampbell.com/product/signedimminentdawn/" target="_blank" rel="noopener noreferrer">Author Website</a></p>
<h2 style="text-align: center;"><em>Mourning Dove</em></h2>
<p style="text-align: center;"><a href="https://www.amazon.com/dp/B07QZGSDX6/">Amazon</a> | <a href="https://www.barnesandnoble.com/w/books/1131295072" target="_blank" rel="noopener noreferrer">Barnes &amp; Noble</a> | <a href="http://ninestarpress.com/product/mourning-dove" target="_blank" rel="noopener noreferrer">NineStar Press</a> | <a href="https://www.kobo.com/us/en/ebook/mourning-dove-7" target="_blank" rel="noopener noreferrer">Kobo</a> | <a href="https://www.smashwords.com/books/view/935036" target="_blank" rel="noopener noreferrer">Smashwords</a> | <a href="https://www.goodreads.com/book/show/43728390-mourning-dove" target="_blank" rel="noopener noreferrer">Goodreads</a>| <a href="https://ryanrcampbell.com/?post_type=product&amp;p=5816&amp;preview=true" target="_blank" rel="noopener noreferrer">Author Website</a></p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default ItsHereMourningDoveCharacterArt
