import React from 'react'

const TheWorstWritingAdviceIEverReceived = () =>
  <div>
    <p>This is a topic that rears its head from time to time in the writing community, and it was recently reignited on Twitter after a creative writing teacher told one of his students the below.</p>
<blockquote class="twitter-tweet" data-width="550" data-dnt="true">
<p lang="en" dir="ltr">My creative writing teacher just said I should wait 10 years to publish a book or I’ll regret it. He called my book a burner novel, he’s never seen it. When I tried to protest he said I was stubborn and impatient.</p>
<p>Please tell me he’s wrong, I’m crying.<a href="https://twitter.com/hashtag/WritingCommnunity?src=hash&amp;ref_src=twsrc%5Etfw">#WritingCommnunity</a></p>
<p>&mdash; Avy Aubin (@26LetterWorlds) <a href="https://twitter.com/26LetterWorlds/status/1152001467647004672?ref_src=twsrc%5Etfw">July 18, 2019</a></p></blockquote>
<p><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></p>
<p>Yikes.</p>
<p>Not only is this bad advice, it's downright harmful and discouraging to the community at large. Though it is true that many writers' first manuscripts don't often live up to the high hopes they have for them, there are plenty of exceptions to this generalization. I personally know at least one author who came to the world of fiction as a total stranger and, within a year, had her debut novel published with NineStar Press.</p>
<p>There are also hundreds of authors who opt-in to independently publishing their own work&#8212;first manuscripts included&#8212;and, aided by savvy marketing and advertising plans, go on to achieve great success. In some cases, they even surpass the sales numbers of authors who are with traditional publishers!</p>
<p>Knowing that, there's no doubt the advice Avy was given by her creative writing teacher is beyond bad. Lamentably, however, it's not the only bad advice out there. At some point in our writing careers, we're going to encounter some jaw-droppingly foul suggestions, and my experience is no exception.</p>
<p>So strap in; it's time for me to regale you with the worst writing advice I ever received (or at least the WTF-level advice that had me spinning in my chair while I fumed).</p>
<p>Those of you who have read <a href="http://www.rrcampbellwrites.com/books">my work</a> know I enjoy stitching in small details to enrich the settings and cultures in which my novels take place (something that's true for any author worth their salt, in my opinion). This is especially the case when I have scenes that take place in regions where English isn't the primary language.</p>
<p>This means I'll often include simple phrases in the dialogue (normally cognates most English speakers would recognize) in the native language of those on the page (French, Spanish, Portuguese, what have you). At times, I'll stretch my use of foreign languages a little more when I feel the broader context of the scene makes it apparent what's being said.</p>
<p>Fun, right?</p>
<p>Not if you're the person who gave me the worst writing advice I ever received.</p>
<p>The individual in question was working as a proofreader for one of my manuscripts at the time, and their angst regarding the inclusion of foreign languages was clear from the start. Even the simplest of phrases (think <em>bonjour </em>or <em>buenos días </em>or <em>obrigado </em>in a situation where it's clear someone is being thanked) were flagged with comments like “readers will not want to have to stop to look this up” and “this is taking me so far out of the scene.”</p>
<p>You can imagine my consternation, not only because these were the teensiest of teeny linguistic flairs but because, given they were working as a proofreader, comments like those were outside their purview (a developmental editor might comment on matters like these, but a proofreader? Go home, you're drunk!).</p>
<p>Then we got to the scenes where a character might use three or five foreign language words in a row. These were highlighted and commented on with abandon, each note more derisive than the last&#8212;until we reached the grandaddy of them all. I'm paraphrasing here, but:</p>
<blockquote><p>I know you had a native speaker double check all of this, but when I put many of these phrases into Google Translate, they just don't make any sense. If you're going to insist on including them, I think they should be changed so that they match Google Translate.</p></blockquote>
<p>Yes, you read that right; their comment <em>actively encouraged me to do something incorrectly </em>by using Google Translate instead of trusting input from a native speaker of the language in question. Not only that, but they made this recommendation for completely personal reasons, another big no-no in the editing world (or at least on the editing planet I come from, anyway).</p>
<p>I understand the intention behind their feedback, I do, but the audacity to think one's insight as a proofreader should trump that of a trained linguist and polyglot (me) and a native speaker of the language in question (a beta reader who was kind enough to double check my work), well, that had me leaving some rather scathing replies in the document's margins. Imagine being a native speaker of French and going, “Wow, how neat this author took the time to include French in this book,” only for that reader to get a few lines down and go, “Uh, all of this is wrong. The author clearly didn't do any research.”</p>
<p>Bummer with a capital B, right?</p>
<p>Needless to say, I disregarded the proofreader's input and forged onward, buoyed by support from my regular beta readers and my developmental editor (yes, even editors need editors, and anyone who says otherwise should not be trusted, but that's a post for another time). I worry sometimes, however, about writers who might not yet have the depth of experience or the support from others in the community to know when it's okay (and wholly justified!) to call out and push back against poor writing advice.</p>
<p>That's one of the reasons I try to make <a href="http://www.rrcampbellwrites.com/editing-services" target="_blank" rel="noopener noreferrer">my editing services</a> as collaborative as possible, using “we” statements and ensuring the suggestions I offer are in line with the vision my clients have for their manuscripts. One also has to consider context in when giving a particular bit of advice; plenty of situations are better served by including adverbs than by shunning them, for example, and there are also so many occasions where a simple “tell” (rather than a “show”) would be the stronger, more economical choice.</p>
<p>As is the case with writing itself, there's a great deal of nuance to quality writing advice, which is why I encourage writers to narrow their eyes at any broad, sweeping generalizations and absolutist platitudes (like <em>Google Translate is the Holy Grail and shall not be contradicted</em>). Chances are, any writing “wisdom” that's full of words like <em>always</em> and <em>never</em> and <em>only </em>is more likely to harm or restrict than it is to do good, so stay skeptical out there.</p>
<p>Alright, that's my story, but now it's your turn. What's the worst writing advice <em>you </em>ever received? Tell me in the comments!</p>
<hr />
<p>Like what you've read here? You can <a href="http://eepurl.com/dhBxcv" target="_blank" rel="noopener noreferrer">subscribe to my newsletter</a> to get more articles like these throughout the year. And don't forget to follow me on <a href="http://www.twitter.com/iamrrcampbell" target="_blank" rel="noopener noreferrer">Twitter</a>, <a href="http://www.instagram.com/iamrrcampbell" target="_blank" rel="noopener noreferrer">Instagram</a>, and <a href="http://www.facebook.com/iamrrcampbell" target="_blank" rel="noopener noreferrer">Facebook</a>, too. You can also meet me at any one of <a href="http://www.rrcampbellwrites.com/events">my upcoming events</a>, or <a href="http://www.rrcampbellwrites.com/contact">reach out about having me speak at one of your own</a>.</p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default TheWorstWritingAdviceIEverReceived
