import React from 'react'

const ThisFallUWCoursewithRRCampbell = () =>
  <div>
    <p>I'm honored to formally announce I'll be teaching a class this fall through the University of Wisconsin-Madison's Division of Continuing Studies in Writing Department.</p>
<p>I've been an attendee of the department's conferences and seminars since graduating from the university in 2012, and to now be in a position to empower other writers in the same way my own instructors have empowered me over the years is truly a thrill.</p>
<p>So what will we be covering in this course, and how can you enroll? Great questions! Read on to find out.</p>
<p><img loading="lazy" decoding="async" data-attachment-id="6396" data-permalink="https://ryanrcampbell.com/courses/write-your-novel-now/" data-orig-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/07/write-your-novel-now.png?fit=1180%2C435&amp;ssl=1" data-orig-size="1180,435" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="write your novel now" data-image-description="" data-image-caption="" data-medium-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/07/write-your-novel-now.png?fit=300%2C111&amp;ssl=1" data-large-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/07/write-your-novel-now.png?fit=1024%2C377&amp;ssl=1" class=" size-full wp-image-6396 aligncenter" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/07/write-your-novel-now.png?resize=1080%2C398&#038;ssl=1" alt="write your novel now" width="1080" height="398" srcset="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/07/write-your-novel-now.png?w=1180&amp;ssl=1 1180w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/07/write-your-novel-now.png?resize=300%2C111&amp;ssl=1 300w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/07/write-your-novel-now.png?resize=768%2C283&amp;ssl=1 768w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/07/write-your-novel-now.png?resize=1024%2C377&amp;ssl=1 1024w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/07/write-your-novel-now.png?resize=624%2C230&amp;ssl=1 624w" sizes="(max-width: 1080px) 100vw, 1080px" data-recalc-dims="1" /></p>
<h3>Write Your Novel Now - Plotting Your Way to Success</h3>
<p>“How’s that novel coming?” A tough question, but never fear! After attending this course, writers will have strengthened their concepts, explored various plot structure models, and outlined their novels scene-by-scene. Not only will attendees then be empowered to take to the page, they’ll never fret answering that dreaded question again!</p>
<h3 style="text-align: center;"><a href="https://continuingstudies.wisc.edu/classes/plot-your-way-to-success/" target="_blank" rel="noopener noreferrer">Enroll for this fall's multi-week course with the UW Continuing Studies Department here! Space is limited, so sign up now.</a></h3>
<p>In the future, I also plan to offer most of <a href="https://ryanrcampbell.com/courses/">the classes seen on this page</a> online as well. Sound like something you'd be interested in? <a href="http://eepurl.com/dhBxcv">Be sure to sign up for my newsletter</a> to be among the first to know when enrollment opens.</p>
<p>Thanks to the staff of the UW's Department of Continuing Studies in Writing for this opportunity, and thanks to those of you who created the demand for this course. I look forward to working with you in the fall and beyond.</p>
<p>Have questions about this course or just want to get in touch? You can reach out through <a href="http://www.rrcampbellwrites.com/contact">my contact page.</a></p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default ThisFallUWCoursewithRRCampbell
