import React from 'react'

const WhatILearnedAboutWritingbyNotWritinginMontana = () =>
  <div>
    <p>On the longest day of the year, my wife and I set off on a westward trek across five states and countless cities. From La Crosse to Rochester to Sioux Falls to Gilette to Missoula (and so many places in between), we took in the wildlife, played <em>90s Trivial Pursuit</em>, and listened to the <em>Hamilton </em>soundtrack ad nauseam.</p>
<p>Writing, however, was the one thing I <em>didn't</em> do during our week of road tripping.</p>
<div id="attachment_6368" style="width: 4042px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-6368" data-attachment-id="6368" data-permalink="https://ryanrcampbell.com/2019/07/01/what-i-learned-about-writing-by-not-writing-in-montana/img_1075/" data-orig-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/06/IMG_1075.jpg?fit=4032%2C3024&amp;ssl=1" data-orig-size="4032,3024" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;1.8&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;iPhone XR&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;1561386840&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;4.25&quot;,&quot;iso&quot;:&quot;25&quot;,&quot;shutter_speed&quot;:&quot;0.00022401433691756&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;1&quot;}" data-image-title="IMG_1075" data-image-description="" data-image-caption="&lt;p&gt;Some of Montana's approximately six quadrillion mountains.&lt;/p&gt;
" data-medium-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/06/IMG_1075.jpg?fit=300%2C225&amp;ssl=1" data-large-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/06/IMG_1075.jpg?fit=1024%2C768&amp;ssl=1" class="alignnone size-full wp-image-6368" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/06/IMG_1075.jpg?resize=1080%2C810&#038;ssl=1" alt="IMG_1075" width="1080" height="810" srcset="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/06/IMG_1075.jpg?w=4032&amp;ssl=1 4032w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/06/IMG_1075.jpg?resize=300%2C225&amp;ssl=1 300w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/06/IMG_1075.jpg?resize=768%2C576&amp;ssl=1 768w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/06/IMG_1075.jpg?resize=1024%2C768&amp;ssl=1 1024w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/06/IMG_1075.jpg?resize=624%2C468&amp;ssl=1 624w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/06/IMG_1075.jpg?w=2160&amp;ssl=1 2160w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/06/IMG_1075.jpg?w=3240&amp;ssl=1 3240w" sizes="(max-width: 1080px) 100vw, 1080px" data-recalc-dims="1" /><p id="caption-attachment-6368" class="wp-caption-text">Some of Montana's approximately six quadrillion mountains.</p></div>
<p>That's right. There were no fresh words for any of my manuscripts. No outlines. No new blog posts or (writing-related) Instagram pics. Yes, all really was quiet while I was on our equivalent of the western front.</p>
<p>This may sound glorious to some, but those who know me are likely ready to dial a doctor, concerned about what this lack of productivity might mean for my general wellbeing.</p>
<p>Well, I'm here to say <em>at ease, folks</em>.</p>
<div id="attachment_6369" style="width: 259px" class="wp-caption alignright"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-6369" data-attachment-id="6369" data-permalink="https://ryanrcampbell.com/2019/07/01/what-i-learned-about-writing-by-not-writing-in-montana/img_1127/" data-orig-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/06/IMG_1127.jpg?fit=3024%2C4032&amp;ssl=1" data-orig-size="3024,4032" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;1.8&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;iPhone XR&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;1561492801&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;4.25&quot;,&quot;iso&quot;:&quot;25&quot;,&quot;shutter_speed&quot;:&quot;0.0015060240963855&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;1&quot;}" data-image-title="IMG_1127" data-image-description="" data-image-caption="&lt;p&gt;The view from atop the land on which we stayed.&lt;/p&gt;
" data-medium-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/06/IMG_1127.jpg?fit=225%2C300&amp;ssl=1" data-large-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/06/IMG_1127.jpg?fit=768%2C1024&amp;ssl=1" class="alignnone  wp-image-6369" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/06/IMG_1127.jpg?resize=249%2C331&#038;ssl=1" alt="IMG_1127" width="249" height="331" srcset="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/06/IMG_1127.jpg?w=3024&amp;ssl=1 3024w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/06/IMG_1127.jpg?resize=225%2C300&amp;ssl=1 225w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/06/IMG_1127.jpg?resize=768%2C1024&amp;ssl=1 768w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/06/IMG_1127.jpg?resize=624%2C832&amp;ssl=1 624w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/06/IMG_1127.jpg?w=2160&amp;ssl=1 2160w" sizes="(max-width: 249px) 100vw, 249px" data-recalc-dims="1" /><p id="caption-attachment-6369" class="wp-caption-text">The view from atop the land on which we stayed.</p></div>
<p>In fact, a week away might have been the best thing I could have done for my writing. By putting some space between me and the daily writerly grind, I'm seeing it anew. For the first time in months, I'm not just feeling <em>good</em> about getting back to the keys; I'm genuinely excited for it.</p>
<p>That said, I really should have seen this coming. The weeks leading up to our trip weren't the first during which I felt as though I was on the verge of a creative meltdown, only to see it countered by taking some time away.</p>
<p>And I know I'm not alone in experiencing these on-the-brink-of-creative-disaster scenarios, either. Far too often I talk to writers and other creatives who'll say their work is giving them trouble or that they're feeling stuck. These can be (and in a great number of cases are) story-related issues, but many times I suspect it's an ongoing or impending burnout that's causing such frustration.</p>
<div id="attachment_6371" style="width: 4042px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-6371" data-attachment-id="6371" data-permalink="https://ryanrcampbell.com/2019/07/01/what-i-learned-about-writing-by-not-writing-in-montana/img_1099/" data-orig-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/06/IMG_1099.jpg?fit=4032%2C3024&amp;ssl=1" data-orig-size="4032,3024" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;1.8&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;iPhone XR&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;1561389167&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;4.25&quot;,&quot;iso&quot;:&quot;25&quot;,&quot;shutter_speed&quot;:&quot;0.00073099415204678&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;1&quot;}" data-image-title="IMG_1099" data-image-description="" data-image-caption="&lt;p&gt;Yes, the water was *that* blue.&lt;/p&gt;
" data-medium-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/06/IMG_1099.jpg?fit=300%2C225&amp;ssl=1" data-large-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/06/IMG_1099.jpg?fit=1024%2C768&amp;ssl=1" class="alignnone size-full wp-image-6371" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/06/IMG_1099.jpg?resize=1080%2C810&#038;ssl=1" alt="IMG_1099" width="1080" height="810" srcset="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/06/IMG_1099.jpg?w=4032&amp;ssl=1 4032w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/06/IMG_1099.jpg?resize=300%2C225&amp;ssl=1 300w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/06/IMG_1099.jpg?resize=768%2C576&amp;ssl=1 768w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/06/IMG_1099.jpg?resize=1024%2C768&amp;ssl=1 1024w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/06/IMG_1099.jpg?resize=624%2C468&amp;ssl=1 624w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/06/IMG_1099.jpg?w=2160&amp;ssl=1 2160w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/06/IMG_1099.jpg?w=3240&amp;ssl=1 3240w" sizes="(max-width: 1080px) 100vw, 1080px" data-recalc-dims="1" /><p id="caption-attachment-6371" class="wp-caption-text">Yes, the water was *that* blue.</p></div>
<p>For as counterintuitive as it might seem, if you're feeling as though you're in this position, <em>take a break</em>. Stop trying to untie that plot knot for a day, a week, or a month, and fill your time with anything else instead (<em>90s Trivial Pursuit</em>, anyone?). Or, even better, fill your time with absolutely nothing (by which I mean take a hike or go for a swim or recline outdoors and listen to the birds, letting your thoughts go where they may).</p>
<div id="attachment_6370" style="width: 343px" class="wp-caption alignleft"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-6370" data-attachment-id="6370" data-permalink="https://ryanrcampbell.com/2019/07/01/what-i-learned-about-writing-by-not-writing-in-montana/img_1051/" data-orig-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/06/IMG_1051.jpg?fit=4032%2C3024&amp;ssl=1" data-orig-size="4032,3024" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;1.8&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;iPhone XR&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;1561383492&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;4.25&quot;,&quot;iso&quot;:&quot;25&quot;,&quot;shutter_speed&quot;:&quot;0.0012562814070352&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;1&quot;}" data-image-title="IMG_1051" data-image-description="" data-image-caption="&lt;p&gt;A scene from Glacier National Park.&lt;/p&gt;
" data-medium-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/06/IMG_1051.jpg?fit=300%2C225&amp;ssl=1" data-large-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/06/IMG_1051.jpg?fit=1024%2C768&amp;ssl=1" class="alignnone  wp-image-6370" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/06/IMG_1051.jpg?resize=333%2C250&#038;ssl=1" alt="IMG_1051" width="333" height="250" srcset="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/06/IMG_1051.jpg?w=4032&amp;ssl=1 4032w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/06/IMG_1051.jpg?resize=300%2C225&amp;ssl=1 300w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/06/IMG_1051.jpg?resize=768%2C576&amp;ssl=1 768w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/06/IMG_1051.jpg?resize=1024%2C768&amp;ssl=1 1024w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/06/IMG_1051.jpg?resize=624%2C468&amp;ssl=1 624w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/06/IMG_1051.jpg?w=2160&amp;ssl=1 2160w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/06/IMG_1051.jpg?w=3240&amp;ssl=1 3240w" sizes="(max-width: 333px) 100vw, 333px" data-recalc-dims="1" /><p id="caption-attachment-6370" class="wp-caption-text">A scene from Glacier National Park.</p></div>
<p>If you're anything like me, you'll find that putting some time and distance between you and your projects is all that's required to recognize possibilities you once thought impossible or to feel rejuvenated enough to breathe new life into your work. It took me a week of driving, hiking, and keeping my ears preened and eyes peeled for bears to finally overcome the malaise that had me in its grips, but perhaps all you'll need is a day, an afternoon, or an hour of lounging to get your groove back.</p>
<p>So go on. I dare you to do it. I dare you to not write.</p>
<p>Your writing will thank you for it.</p>
<hr />
<p>Like what you've read here? You can <a href="http://eepurl.com/dhBxcv" target="_blank" rel="noopener noreferrer">subscribe to my newsletter</a> to get more articles like these throughout the year. And don't forget to follow me on <a href="http://www.twitter.com/iamrrcampbell" target="_blank" rel="noopener noreferrer">Twitter</a>, <a href="http://www.instagram.com/iamrrcampbell" target="_blank" rel="noopener noreferrer">Instagram</a>, and <a href="http://www.facebook.com/iamrrcampbell" target="_blank" rel="noopener noreferrer">Facebook</a>, too. You can also meet me at any one of <a href="http://www.rrcampbellwrites.com/events">my upcoming events</a>, or <a href="http://www.rrcampbellwrites.com/contact">reach out about having me speak at one of your own</a>.</p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default WhatILearnedAboutWritingbyNotWritinginMontana
