import React from 'react'

const BiblioBreakdownAThousandSplendidSunsPart1 = () =>
  <div>
    <p>Welcome to the inaugural Biblio Breakdown, a series in which we'll explore books not from the perspective of a reviewer or casual reader, but rather as writers. Every book has something to teach us about our own writing, and this series is designed to get us to examine just that.</p>
<p>To kick off things off, we'll be doing a deep dive into Khaled Hosseini's <em>A Thousand Splendid Suns</em>, a harrowing work of historical fiction that takes place in the latter half of the 20th century in principally Afghanistan, but Pakistan as well.</p>
<p>Before we get into breaking this one down, I want to say that I wholeheartedly recommend this book to anyone who feels that may have even only a casual interest in it after reading this post. I know this isn't meant to be a review or a recommendation, but if you haven't made time to read this one since its debut in 2008, you absolutely must.</p>
<h2>Inciting Incident</h2>
<p>As writers, we know the first five pages of any manuscript are crucial. In them, we need to give readers a look-in at our protagonist, what they want, what might stop them, and what our protagonist plans to do about it, more or less.</p>
<p>Then, of course, the goal is to accomplish all of the above in as compelling of a way as possible, often by introducing a spectacular change moment where a suggestion of the stakes, too, comes into play. To accomplish this, it's not uncommon (at least in my case, anyway) to want to give those first five pages some spectacular action or a body count or the breaking of a severe bit of news to propel our protagonist to action.</p>
<p><em>A Thousand Splendid Suns</em> shows us that the first five pages don't have to be chockfull of explosions and space invasions to draw readers in. No, Hosseini's approach to the inciting incident is much more foreboding than any of that.</p>
<p>The below excerpt is from the end of the second and beginning of the third paragraphs of the book. In this scene, Mariam&#8212;our protagonist&#8212;is a young child who is climbing a chair to retrieve her deceased mother's Chinese tea set from its perch. Nana, the other character featured, is Mariam's grandmother, with whom she lives.</p>
<blockquote><p>… Nana cherished each blue-and-white porcelain piece, the graceful curve of the pot's spout, the hand-painted finches and chrysanthemums, the dragon on the sugar bowl, meant to ward off evil.</p>
<p>It was this last piece that slipped from Mariam's fingers, that fell to the wooden floorboards of the <em>kolba</em> and shattered.</p></blockquote>
<p>Did you catch it? I don't mean the porcelain sugar bowl, but rather the inciting incident. It's in there, but easy to miss.</p>
<p>See where it mentions the dragon on the sugar bowl is meant to ward off evil? Yup. <em>That's</em> the piece Mariam shatters.</p>
<p>Let me be clear: <em>A Thousand Splendid Suns </em>is not a work of magic realism; there was no actual ward or protective seal on the sugar bowl. And yet, for a book that pits myth against modernity and past against present, the shattering of this sugar bowl means everything: it sets the stage for the direction of Mariam's arc, one which will lead her through incredible evil (but incredible, dark, and bittersweet triumph as well).</p>
<p>The point is this: the use of subtlety in one's inciting incident can&#8212;just like the explosive alternatives&#8212;also propel an entire novel forward. In <em>A Thousand Splendid Suns</em>, Hosseini crafts his inciting incident such that readers can't help but feel drawn in by the sense of foreboding that comes with the simple act of a sugar bowl having broken. I know he had me intrigued from page one, anyway.</p>
<p><strong>Exercise: </strong>Write a scene or inciting incident that propels a story forward through the use of subtlety or metaphor. How does this compare to other inciting incidents you've written? How might you reframe your approach to writing scenes like this going forward?</p>
<h2>Character as Relationships</h2>
<p>If there's ever a book that proves character is more than a list of traits, this is it. If that reads as odd coming from me&#8212;<a href="https://ryanrcampbell.com/2016/12/30/character-at-the-core-the-importance-of-depth/" target="_blank" rel="noopener">the guy whose post on character literally treats it as a list of traits</a>&#8212;let's explore how we get from a list of traits and to the relationships between characters themselves, all through the lens of <em>A Thousand Splendid Suns</em>.</p>
<p>By page two of the book, we learn that one of our point of view characters, Mariam, is a <em>harami</em>, or a child had out of wedlock. Let's imagine we're completing the character trait list found at the above link; surely this would figure among the things on the list that define her.</p>
<p>BUT, of course, no one is a <em>harami</em> in a vacuum. Just like we strive to define ourselves as individuals in the real world, we're inevitably a summation of our relationships and interactions to and with others as well. Our manuscripts should, unsurprisingly, be no different.</p>
<p>In <em>A Thousand Splendid Suns</em>, Hosseini establishes a dynamic whereby Mariam is inevitably estranged from her father and his “real” family, banished to live instead with her mother in a <em>kolba</em> on the outskirts of her father's estate. Mariam wants nothing more than to have a relationship with her wealthy father, whom she idolizes, but their relationship <em>as defined by the culture in which they exist</em> inhibits them from being seen together publicly.</p>
<p>And that notion of culture? That's where another dimension of character as relationships comes into play. We (and our characters) also find ourselves defined not just by our relationships to those around us, but by the culture(s) of which we are a part.</p>
<p>This is a further demonstration that nothing exists in a vacuum: how can we know who our characters truly are if we don't have an understanding of the culture they inhabit? How are they seen by others, and how do they react similarly or differently when in the presence of any given set of individuals? Are they more prideful and outgoing when comfortable with those and the dynamics that surround them? Are they meek and cowering before individuals and in environments where society expects them to be deferential? Perhaps they cast tradition to the wind and insist on violating cultural norms. What are the consequences they (or others) face, if any, as a result?</p>
<p>Mariam's status as a <em>harami</em> defines her significantly for at least the first fifth of the book, and continues to haunt her throughout the entire text. In this way, Hosseini has created a cultural antagonist for his protagonist, which is something that cannot be overlooked as a possibility when crafting our own manuscripts.</p>
<h2>Conclusion, Part One</h2>
<p>To try to keep these posts as bite-sized as possible, we'll leave off here for now. <em>A Thousand Splendid Suns </em>has so much more to offer, though, <a href="https://ryanrcampbell.com/2018/01/24/biblio-breakdown-a-thousand-splendid-suns-part-2/" target="_blank" rel="noopener">so read on to part two</a>, wherein we'll examine relationships as metaphor before advancing to part three, in which we'll tackle setting as character and dramatic irony.</p>
<hr />
<p>If you like what you've read here, you can sign up for monthly updates on Biblio Breakdowns, the writescast, and other writerly news in the r. r. campbell writes newsletter. <a href="http://www.rrcampbellwrites.com/newsletter" target="_blank" rel="noopener">Follow this link to subscribe!</a></p>
<h2></h2>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default BiblioBreakdownAThousandSplendidSunsPart1
