import React from 'react'

const BiblioBreakdownAThousandSplendidSunsPart2 = () =>
  <div>
    <p>Welcome to part two of this Biblio Breakdown for <em>A Thousand Splendid Suns. </em>Looking for part one? <a href="https://ryanrcampbell.com/2018/01/22/biblio-breakdown-a-thousand-splendid-suns-part-1" target="_blank" rel="noopener">You can find that here.</a> Want more background on Biblio Breakdowns before reading on? <a href="http://www.rrcampbellwrites.com/bibliobreakdown" target="_blank" rel="noopener">You can learn more at this link.</a></p>
<p>Alright&#8212;now let's get right back to it.</p>
<h2>Relationships as Metaphor</h2>
<p>In part one, we explored the notion that characters are comprised of more than a list of traits: that they're defined also by the cultures they inhabit and the relationships they have to other characters. Once we as writers have established that foundation for our own characters, we can build upon that in such a way that these relationships grow upward beyond the terrestrial world of the page, and into a sort of atmosphere that surrounds the world of the book itself. For the purposes of this post and those going forward, we'll call this atmosphere the metasphere.</p>
<p>Before you get to wondering what I'm smoking, consider this: like our characters, nothing exists in a vacuum, including the books we read and write. That is to say, we must consider all things against a greater context, which, for our readers, includes things like the society in which they're living as they read, the history of the cultures in which we write, and the presentation of our book's subject matter.</p>
<p>Woe be it of me to suggest that writers must actively be considering all of the above as a necessity when writing, <em>but</em> if these matters are considered when writing, one can craft a manuscript with an even further enriched theme, using the power of nuance and subtlety by pulling from the metasphere to shape readers' understandings of character, plot, and theme.</p>
<p>Where <em>A Thousand Splendid Suns</em> does this masterfully is through the use of interpersonal relationships as metaphor for the greater sociopolitical constructs of mid-20th century Afghanistan.</p>
<p>Sound boring? Trust me, it's not&#8212;especially because Hosseini doesn't stand upon a soapbox and harp about the struggle for Afghan national identity in a manner that one might expect if this were a work of non-fiction. Instead, he reaches into the metasphere and makes use of character relationships to shape the astute reader's appreciation for the complexities of Afghanistan's (or any nation facing a similar crisis of identity) relationship to itself.</p>
<p>Let's examine this concretely. I found the exploration of this theme to be most prevalent in the book's first fifty pages or so (though it runs throughout), so we'll limit our discussion to this section as to avoid spoilers. As mentioned in part one, <em>A Thousand Splendid Suns</em> features two perspective characters, one of whom is Mariam, a child had out of wedlock by the wealthy, forward-looking Jalil, and Nana, Mariam's lore-bound, myth-hustling mother.</p>
<p>The dynamic Khaled Hosseini creates between these three characters and the culture in which they live is already rife with tension. Mariam is pulled in opposing directions constantly, but deep down knows what she really wants (or thinks she does, anyway): to be with her father, living in the cozy, sealed off world he has created for himself and his family.</p>
<p>As these dynamics are explored, readers begin to understand&#8212;not explicitly from the words on the pages themselves, mind you, but rather through the lens of the metasphere&#8212;that Jalil represents an unattainable dream: not just for Mariam personally, but for Afghanistan as a whole. As time progresses and the cozy, sweater-like feel of Jalil's world (and Mariam's relationship to it) begins to fray, readers are introduced to the notion that the dream itself may be a lie, unattainable not because it is generally impossible, but because it is in a constant struggle against the harsh realities of the cultural stasis that Nana represents.</p>
<p>Nana, unlike Jalil, is an absolute lore-monger, deferring to tradition to define herself, Mariam, and any kind of future the two of them might have as a family or as individuals. Nana holds back Mariam through purposeful manipulation and distortion, all in an attempt to keep Mariam from abandoning her and the world she represents in favor of the promise Jalil represents&#8212;even if there is a chance that this future is unattainable.</p>
<p>Mariam then&#8212;like mid-20th century Afghanistan itself&#8212;faces a choice: does she cling to her past, or risk pushing forward toward what she believes to be a brighter future, even if that would mean possible instability or a different kind of disillusionment in itself?</p>
<p>Where Mariam is concerned, the choice she makes goes on to define her for the rest of her life, and I can't exactly dive into too many details without revealing a major plot point, so we'll leave it at that for now.</p>
<p><strong>Exercise: </strong>Take a look at a bit of fiction you've written or are working on. When you read it, do you, with ease, see any connections between the words on the page and the metasphere? Do they help you shape your theme, better define your characters, or enrich the relationship between the reader and the story itself? If so, is this something you think you did intentionally? Does this enhance or detract from the story you're trying to tell?</p>
<p>If you don't see a relationship between your work and the metasphere, what do you think you could do to introduce this, if you feel it to be necessary? Can your characters' relationships, the world in which they live, or the hardships they endure be shaped through nuance and subtlety to create a greater connection between the story itself and the context in which a reader enjoys it?</p>
<h2>Conclusion, Part Two</h2>
<p>There was a lot to be said about relationships as metaphor, context, and the metasphere in <em>A Thousand Splendid Suns</em>, so we'll wind this post down and <a href="https://ryanrcampbell.com/2018/01/26/biblio-breakdown-a-thousand-splendid-suns-part-3/" target="_blank" rel="noopener">pick up with part three</a>, in which we'll discuss setting as character and dramatic irony.</p>
<hr />
<p>If you like what you've read here, you can sign up for monthly updates on Biblio Breakdowns, <a href="http://www.rrcampbellwrites.com/podcasts" target="_blank" rel="noopener">the writescast</a>, and other writerly news in the r. r. campbell writes newsletter. <a href="http://www.rrcampbellwrites.com/newsletter" target="_blank" rel="noopener">Follow this link to subscribe!</a></p>
<h2></h2>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default BiblioBreakdownAThousandSplendidSunsPart2
