import React from 'react'

const BiblioBreakdownAThousandSplendidSunsPart3 = () =>
  <div>
    <p>Alright, it's time for part three of this Biblio Breakdown for <em>A Thousand Splendid Suns. </em>Looking for parts one and two? You can find them <a href="https://ryanrcampbell.com/2018/01/22/biblio-breakdown-a-thousand-splendid-suns-part-1" target="_blank" rel="noopener">here</a> and <a href="https://ryanrcampbell.com/2018/01/24/biblio-breakdown-a-thousand-splendid-suns-part-2" target="_blank" rel="noopener">here</a>, respectively. Want more background on Biblio Breakdowns before reading on? <a href="http://www.rrcampbellwrites.com/bibliobreakdown" target="_blank" rel="noopener">You can learn more at this link.</a></p>
<p>Now let's discuss setting as character before we advance into an exploration of dramatic irony!</p>
<h2>Setting as Character</h2>
<p><a href="https://ryanrcampbell.com/2017/01/06/setting-more-than-just-place/" target="_blank" rel="noopener">In other posts</a>, we've covered the importance of setting as character more generally, but one dimension to setting that is often overlooked (including by yours truly) is <em>time</em>. In <em>A Thousand Splendid Suns</em>, however, Hosseini puts on a masterclass in the use of <em>time as character</em> (and a generally antagonizing character, at that).</p>
<p>We as people are shaped by the times in which we live, and our characters should be no different. As the perspective characters in <em>A Thousand Splendid Suns </em>grow and struggle throughout their lives, the city of Kabul&#8212;and Afghanistan more broadly&#8212;does as well. In the earliest parts of the book, we are party to an Afghanistan with progressive urban leanings, but as Afghanistan and our main characters endure the overthrow of its leadership in a communist coup followed by Soviet occupation followed by an attempt to establish a democracy followed by a civil war followed by the seizure of control by the Taliban and then their eventual overthrow in the 2000s (and I may have missed a step or two in there), our characters' daily lives are impacted immensely by the ongoing turmoil, loss of life, and the sociopolitical tendencies of those in power.</p>
<p>The one constant throughout, however, is that regardless of who runs the show in Kabul, Afghanistan (or at least the bits of it we see in the book) remained an oppressive place for women. The rules may have changed at the fringes, and stability as well, but women are almost universally regarded as second-class citizens, a primary focus of the book.</p>
<p>The lesson we take away is this: for those of us writing fiction of any kind&#8212;but especially historical fiction&#8212;the times in which our characters flourish (or fail) should not be disregarded. They, too, can make the world feel more lived in and fill the role of an additional antagonist or ally in the proper context.</p>
<p><strong>Exercise: </strong>Think about not where, but <em>when</em> your work in progress takes place. What is your main character's relationship to the times in which he or she lives? Do they feel very much a part of the zeitgeist or rather detached from it? Even if they do feel detached, why? How can their attachment or detachment from their world's goings-on help define their journey and your theme as the author? Once you've answered these questions for your main character, consider them for your supporting cast as well&#8212;they, too, surely have opinions and reactions of their own to share!</p>
<h2>Dramatic Irony</h2>
<p>Dramatic irony is another topic we've broached in <a href="https://ryanrcampbell.com/2017/06/09/who-knows-what-and-when-mystery-suspense-and-dramatic-irony/" target="_blank" rel="noopener">previous posts</a>, but <em>A Thousand Splendid Suns</em> provides such a salient example of it that I have to mention it as part of this series.</p>
<p>Above I mentioned that this novel takes place across many decades and seismic shifts in the power structures that govern the daily lives of Afghanistan's citizens, including through the mid-to-late 2000s.</p>
<p>There's a scene during the times of the Taliban's rule that begins as seemingly innocuous (or as innocuous as possible all things considered), but as our perspective characters learn more about the events unfolding in New York City on an entirely different continent, readers are able to start assembling the pieces on their own: that the 9/11 attacks have happened, and the American invasion and occupation of Afghanistan will certainly come next.</p>
<p>Readers in this scenario have access to information that our characters do not: namely, that the attacks on the World Trade Center and Pentagon will have tremendous consequences for their daily lives. This is a perfect example of dramatic irony.</p>
<p>In fact, if one is even only tangentially familiar with Afghanistan's history, there are moments of dramatic irony laced throughout the story. Specifically, I'm referring to the Soviet occupation and the takeover of the Taliban, along with, of course, the subsequent invasion by U.S. forces.</p>
<p>All of this is, again, a testament to the value of setting as character, and, most specifically, time as character. Had this story taken place at another time in Afghanistan's history (or had it chosen to ignore or de-emphasize the setting's historical context), the dramatic irony would either have not existed or played a significantly diminished role.</p>
<p>In <em>A Thousand Splendid Suns</em>, however, it plays a major part in one's journey as a reader: even when our perspective characters achieve minor victories, history tells us that earth-shattering change is right around the corner, and with it, almost exclusively a worsening of our characters' situations.</p>
<p><strong>Exercise: </strong>Are there moments in your own work where dramatic irony comes into play? If not, could playing with point of view to introduce bits of it help increase the tension on the page? Of course, any time we discuss possible point of view shifts we want to be very deliberate and consistent about our choices, but, when done well, they can be used to employ dramatic irony in some, well, dramatic ways.</p>
<h2>Concluding Notes</h2>
<p>Though some nearly 3,000 words have already been dedicated to an exploration of <em>A Thousand Splendid Suns</em> using this Biblio Breakdown approach, I can't help but feel as though I'm still giving this title short shrift. It truly is among the handful of books whose impression will stick with me so long as I live. The portraits that Hosseini paints of person, place, and the relationships between it all are something I encourage every writer to read and learn from, regardless of the genre or category for which one writes.</p>
<hr />
<p>Thanks for reading. Want more Biblio Breakdowns, writing advice, and updates on upcoming releases from author r. r. campbell? You can <a href="http://www.rrcampbellwrites.com/newsletter" target="_blank" rel="noopener">subscribe to the r. r. campbell writes newsletter</a> and get all of this and more by email once per month!</p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default BiblioBreakdownAThousandSplendidSunsPart3
