import React from 'react'

const BiblioBreakdownTurtlesAlltheWayDown = () =>
  <div>
    <p>It's time for another <a href="http://www.rrcampbellwrites.com/bibliobreakdown" target="_blank" rel="noopener">Biblio Breakdown</a>! In this installment of the series, we'll examine John Green's <em>Turtles All the Way Down</em>.</p>
<p>If you recognize the name John Green, you should. Aside from <em>Turtles </em>(and a number of other titles), he's the author of <em>The Fault in Our Stars</em>, a book so impactful that even just typing its title gets me misty-eyed. <em>Stars </em>deserves its own Biblio Breakdown at some point, but for now we'll focus on <em>Turtles All the Way Down</em>, Green's 2017 release.</p>
<h2>Narrative Conflict Types</h2>
<p>There are four narrative conflict types we as writers can choose from for our protagonist to endure throughout the course of our manuscripts. These are:</p>
<ul>
<li>character against character</li>
<li>character against nature</li>
<li>character against society</li>
<li>character against self</li>
</ul>
<p>Ideally, we choose one of these as our protagonist's primary conflict type and sprinkle in the others in our subplots or scenes throughout. The most commonly put to use among these (in my reading experience, anyway) is character against character&#8212;wherein our protagonist must overcome the obstacles put in their way by another character.</p>
<p>If you're looking for a visual to drive this home, think of your main character as a ram. Now think of your antagonist as another ram. Now they butt heads.</p>
<p>Repeat ad nauseam for 60,000+ words, and now you have a novel. It's just that easy. *rolls eyes at self*</p>
<p>Character against character is great, and I was certain after the first couple of chapters that <em>Turtles All the Way Down</em> would feature this as its primary narrative conflict type.</p>
<p>After the first five chapters or so, however, it became apparent that the book's true conflict, in my view, was actually character against self, which I believe can be one of the most rewarding paths to pursue as a writer, and among the most harrowing to follow as a reader.</p>
<p>Green's choice of character versus self is even more noteworthy because of its depth: Aza's intrusive thoughts and obsessive-compulsive disorder define how she navigates her everyday life, so much so that Aza often employs metaphors to describe her relationship to them.</p>
<p>That's right; her relationship <em>to</em> them. The character versus self conflict is so deep within our protagonist that it actually turns inward on itself as Aza frames it not as a struggle against <em>herself</em>, but rather as if it were a struggle against another third-party entirely.</p>
<p>Granted, one could go on then to frame this as a character-against-nature narrative conflict, and I wouldn't begrudge anyone who chose to do so. I, however, feel as though the conflict reads as a character-versus-self narrative&#8212;at least that seems to be how Aza <em>experiences</em> the conflict despite how she might frame it externally.</p>
<p>Further to these points, I feel the “easy” (as if anything in writing is ever easy) thing for Green to have done with this narrative conflict in mind would have been to put to use the <a href="http://tvtropes.org/pmwiki/pmwiki.php/Main/ThrowingOffTheDisability" target="_blank" rel="noopener">throwing off the disability</a> or miracle-cure tropes. Aside from those approaches treading in <a href="http://avajae.blogspot.com/2015/05/why-miracle-cure-trope-hurts.html" target="_blank" rel="noopener">harmful</a> <a href="https://theestablishment.co/the-miraculous-cure-trope-is-not-the-disability-representation-we-need-1608ee948349" target="_blank" rel="noopener">waters</a>, I'm glad Green didn't go this direction for two reasons:</p>
<ol>
<li>Realism</li>
<li>Theme</li>
</ol>
<p>Where the first of these is concerned, the book throughout is set in a world that is, insofar as we can tell, just like our own. In fact, Aza's psychiatrist treats her OCD with medication and what, in my observation, would be something like cognitive behavioral therapy. Simply put: there's no “magic drug” presented as a <a href="http://tvtropes.org/pmwiki/pmwiki.php/Main/MacGuffin" target="_blank" rel="noopener">MacGuffin</a> to help move the plot along, which is great because Aza being “cured” is fundamentally not what the story is about.</p>
<p>One might argue, “Wait, the primary narrative conflict is character against self, and you're trying to tell me the protagonist triumphing in that conflict isn't the story's focus? Seems shaky to me.”</p>
<p>And I could understand that argument: yes, there's a reason we call it the <em>primary</em> narrative conflict. It's meant to be the central challenge our main character must confront by the time the book reaches its conclusion. And that's still the case in <em>Turtles</em>&#8212;Aza <em>does</em> confront this conflict throughout the novel, but where it may differ from expectations is that we don't get the “neat and tidy” resolution of said conflict that one might expect were the above-mentioned tropes employed.</p>
<p>Realism is key here in that very rarely in real life do things reach an absolutely perfect equilibrium. All things come with a cost of some kind, be it physical, emotional, monetary&#8212;you name it. It's a rare day in Oz that we can click our heels together three times and wake up back in Kansas, only to discover all of our trials were nothing more than a dream and <a href="https://en.wikipedia.org/wiki/Political_interpretations_of_The_Wonderful_Wizard_of_Oz" target="_blank" rel="noopener">an allegory about the gold standard.</a></p>
<p>My point is this: without getting too spoilery, Green's resolution of Aza's primary conflict is well played in that it, like life, achieves its resolution not in a “miraculous curing,” but rather through a long road of trials that lead her (and those around her) to develop a better framework through which to view these parts of her. That is to say, there is <em>no</em> absolute triumph of good over evil or vice versa, which is where my second point, theme, comes into play.</p>
<p>Put metaphorically: the book's lesson (at least for me, anyway) is that there will always be rainy days, but developing strategies to manage rainy days might help us better understand how to survive them since there's no stopping the weather itself.</p>
<p>Yes, I recognize I've used a character-against-nature metaphor to describe this character-versus-self conflict, but that doesn't make the take home any less true or diminish the symbiotic relationship between realism and theme in the book itself.</p>
<p>After reading the above, one might also be concerned that I've spoiled the ending somehow. Trust me, I haven't. Recognizing virtue isn't the same as having read or heard the parable, and this is undoubtedly true of <em>Turtles All the Way Down</em>. I do recommend you read it for yourself.</p>
<p><strong>Exercise: </strong>Which of the above-listed narrative conflict types do you put to work in your WIP? Don't be surprised if you find you make use of more than one&#8212;or all of them&#8212;at various points throughout your manuscript. If you have written more than one of them into your story, which is most prevalent? What lessons does it communicate to readers? Have you considered alternatives to the resolution of these conflicts in order to subvert or play with readers' expectations? Brainstorm how you might do this, and then write separate versions of a few of your scenes wherein one of these alternative resolutions is reached. How does this change your story or impact your theme?</p>
<h2>Word, or, in this case, <em>Character</em> Economy</h2>
<p>Let's take a hard left turn, screeching our tires as we peel out in a different direction entirely.</p>
<p>I've written on word economy <a href="https://ryanrcampbell.com/?s=word+economy" target="_blank" rel="noopener">in a handful of posts</a>, but in this post I'd like to focus on an extension of word economy: character economy, or the idea that a manuscript should only feature as many characters as are necessary to tell the story, and that said characters should only receive exactly as much focus and detail as is required to tell the story.</p>
<p><em>Turtles All the Way Down</em> features a brilliant use of character economy upon the introduction of one character in particular, more specifically, a lawyer.</p>
<p>When first introduced in chapter eleven, the lawyer, Simon, calls Aza with advice regarding something she has just received from his client's family. Aza has never heard of or spoken with this lawyer previously, and so naturally one might expect him to be given his due: what does his voice sound like? How does Aza feel about him? Does she develop an idea of what he might look like by imagining him in his office on the other end of the call?</p>
<p>We never get any of this information, though, and that's (more than) okay! Because, quite frankly, <em>who cares</em>? Simon exists only to nudge the plot along in a handful of places, and, if memory serves, he's never physically present in any given scene. Some readers might swoop in and try to argue that this is hack&#8212;that the lawyer is being used as a patch to cover up some kind of hole in plot development&#8212;but I think this couldn't be further from the truth. Why?</p>
<p>Well, the nature of this plot line begs for the inclusion of a lawyer, but what it doesn't need is a new character to sweep in and become a mainstay throughout the rest of the manuscript; Aza and the others can manage that just fine, thank-you-very-much.</p>
<p>Instead of thrusting a new character rife with description and complicated backstory of his own upon readers, Green instead gives readers a simple, two-page scene that is <em>almost exclusively dialogue</em>. As a result, the scene achieves everything required of it in as economical of a manner as possible.</p>
<p><strong>Exercise: </strong>Take an inventory of the characters in your WIP. Is every last one of them absolutely necessary? Is every character given exactly as much&#8212;and only as much&#8212;description as is warranted by the role they play? When asking yourself these questions, however, it's worth considering the genre in which you're writing, as fantasy and sci-fi tend toward more description than other genres.</p>
<h2>Concluding Remarks</h2>
<p>Whether interested in exploring the above topics or simply looking for a breezy read with great depth, <em>Turtles All the Way Down</em> is worth a read. Or, if after looking into it further you're not sure it'd be right for you, perhaps look into <em>The Fault in Our Stars</em>, which is another fantastic title from John Green.</p>
<hr />
<p>Thanks for reading. For updates on future Biblio Breakdowns as they're released, you can subscribe to the monthly <a href="http://www.rrcampbellwrites.com/newsletter" target="_blank" rel="noopener">r. r. campbell writes newsletter</a>. By subscribing, you'll not only ensure you catch every <a href="http://www.rrcampbellwrites.com/bibliobreakdown" target="_blank" rel="noopener">Biblio Breakdown</a>, but you'll also receive monthly <a href="http://www.rrcampbellwrites.com/podcasts" target="_blank" rel="noopener">writescast</a> recaps, writing tips, discounts on editing services, and updates on the publication process for <em><a href="http://www.rrcampbellwrites.com/books" target="_blank" rel="noopener">Accounting For It All</a></em>. Check it out!</p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default BiblioBreakdownTurtlesAlltheWayDown
