import React from 'react'

const APeculiarAffliction = () =>
  <div>
    <p class="p1"><i>I drive better after I’ve had a few</i>.</p>
<p class="p1"><i>It’s, like, five miles</i>.</p>
<p class="p1"><i>I don’t want to put anyone out of their way</i>.</p>
<p>These are phrases one hears all too often in Wisconsin's taverns, bars, and pubs, expressions of perilous confidence in taking to the roadways after a long (or short!) night of drinking.</p>
<p>Drunk driving is a scourge in many places, surely, but against a backdrop of <a href="https://www.mic.com/articles/90253/one-u-s-state-has-way-more-bars-than-grocery-stores" target="_blank" rel="noopener noreferrer">2.7 times more bars than grocery stores</a>, <a href="https://arborypsilaw.com/wisconsin-has-some-of-the-softest-dui-laws-in-the-nation-could-this-soon-change/" target="_blank" rel="noopener noreferrer">lax impaired driving laws</a>, and <a href="https://www.revenue.wi.gov/Pages/FAQS/ise-atundrg.aspx#undrg2a" target="_blank" rel="noopener noreferrer">a state statute that permits children to drink in public with their parents' permission</a>, Wisconsin fosters an environment in which impaired driving is widely accepted as a cultural peculiarity.</p>
<p>Everyone has an uncle or friend or cousin who's been pulled over after a night out, and we've all heard legends of drivers who've been ticketed and jailed more than a dozen times for the offense&#8212;yet still retain their license.</p>
<p>There's always talk of tightening the state's operating while impaired (OWI) policies, but very rarely are meaningful reforms enacted into law.</p>
<p>This begs the questions <em>why </em>and <em>what can we do to free ourselves of this peculiar affliction?</em></p>
<p>To liberate ourselves&#8212;and to make our roadways safer&#8212;many, including myself, are resigned to person-to-person advocacy, to intercepting friends and family before they turn the keys in their vehicle's ignition. This produces mixed results, though the intervention and success rates have, at least anecdotally, improved in recent years.</p>
<p>The <em>why </em>is more complex. Miserably cold winters, the state's infamous Tavern League, and deeply entrenched cultural defaults all play a role in the furtherance and maintenance our state's embrace of this affliction.</p>
<p>It's said defaults&#8212;this self-stereotyping&#8212;with which I reckon in my forthcoming flash fiction piece, “State Line.” In it, I explore interstate bias, particularly as it pertains to how poorly drivers from the state of Illinois handle Wisconsin roadways while we gladly cruise about three sheets to the wind&#8212;at least if the stereotypes are to believed.</p>
<p>“State Line” debuts on <a href="https://www.wattpad.com/user/iamrrcampbell" target="_blank" rel="noopener noreferrer">Wattpad</a> this Friday, and I do hope you'll give it a read. Until then, however, write on. Write well. Be your best you.</p>
<p><img loading="lazy" decoding="async" data-attachment-id="7175" data-permalink="https://ryanrcampbell.com/2019/12/02/this-friday-a-new-short-story/rr-black-signature-transparent/" data-orig-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/11/rr-black-signature-transparent.png?fit=405%2C228&amp;ssl=1" data-orig-size="405,228" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="rr black signature transparent" data-image-description="" data-image-caption="" data-medium-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/11/rr-black-signature-transparent.png?fit=300%2C169&amp;ssl=1" data-large-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/11/rr-black-signature-transparent.png?fit=405%2C228&amp;ssl=1" class="  wp-image-7175 aligncenter" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/11/rr-black-signature-transparent.png?resize=300%2C169&#038;ssl=1" alt="rr black signature transparent" width="300" height="169" srcset="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/11/rr-black-signature-transparent.png?w=405&amp;ssl=1 405w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/11/rr-black-signature-transparent.png?resize=300%2C169&amp;ssl=1 300w" sizes="(max-width: 300px) 100vw, 300px" data-recalc-dims="1" /></p>
<h3 style="text-align: center;"><em>r.r. campbell</em></h3>
<p>&nbsp;</p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default APeculiarAffliction
