import React from 'react'

const RRCampbellintheLifelongLearner = () =>
  <div>
    <p>I was recently mentioned in <em>The Lifelong Learner</em>, news from the University of Wisconsin-Madison Continuing Studies!</p>
<p><a href="https://news.continuingstudies.wisc.edu/writing-success-stories-9-authors-who-got-published-with-the-help-of-writing-classes-conferences-retreats-and-critiques-at-uw-madison/?utm_campaign=coschedule&amp;utm_source=twitter&amp;utm_medium=UWContinStudies&amp;utm_content=Writing%20success%20stories:%209%20authors%20who%20got%20published%20with%20the%20help%20of%20writing%20classes,%20conferences,%20retreats,%20and%20critiques%20at%20UW%E2%80%93Madison" target="_blank" rel="noopener noreferrer">This article</a> by Lisa Bauer details how nine authors, yours truly included, received support from the University of Wisconsin-Madison's Continuing Studies Division on the way to becoming published.</p>
<p>The authors alongside whom I'm mentioned are award-winners, bestsellers, and, most importantly, friends and familiar faces I've come to know over the years at events like the <a href="https://uwwritersinstitute.wisc.edu/" target="_blank" rel="noopener noreferrer">Writers' Institute</a> and beyond.</p>
<p>So check out this article when you have a moment, and consider paying a visit to the 31st annual Writer's Institute when it takes place in March of 2020. I'd love to see you there.</p>
<p><img loading="lazy" decoding="async" data-attachment-id="7175" data-permalink="https://ryanrcampbell.com/2019/12/02/this-friday-a-new-short-story/rr-black-signature-transparent/" data-orig-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/11/rr-black-signature-transparent.png?fit=405%2C228&amp;ssl=1" data-orig-size="405,228" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="rr black signature transparent" data-image-description="" data-image-caption="" data-medium-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/11/rr-black-signature-transparent.png?fit=300%2C169&amp;ssl=1" data-large-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/11/rr-black-signature-transparent.png?fit=405%2C228&amp;ssl=1" class="  wp-image-7175 aligncenter" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/11/rr-black-signature-transparent.png?resize=300%2C169&#038;ssl=1" alt="rr black signature transparent" width="300" height="169" srcset="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/11/rr-black-signature-transparent.png?w=405&amp;ssl=1 405w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/11/rr-black-signature-transparent.png?resize=300%2C169&amp;ssl=1 300w" sizes="(max-width: 300px) 100vw, 300px" data-recalc-dims="1" /></p>
<h3 style="text-align: center;"><em>r.r. campbell</em></h3>
<hr />
<p>You can also <a href="http://eepurl.com/dhBxcv">subscribe to my newsletter</a>, follow me on <a href="http://www.twitter.com/iamrrcampbell">Twitter</a>, <a href="http://www.facebook.com/iamrrcampbell">Facebook</a>, and <a href="http://www.instagram.com/iamrrcampbell">Instagram</a>, or check out <a href="http://www.rrcampbellwrites.com/courses">my writing courses</a> and <a href="http://www.rrcampbellwrites.com/editing-services">editing services</a> to stay in touch.</p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default RRCampbellintheLifelongLearner
