import React from 'react'

const TheWorstDriversintheUnion = () =>
  <div>
    <p>They never signal. They pass on the right. They weave in and out of traffic with no regard for their safety or that of others.</p>
<p>I'm talking, of course, about drivers from the state of Nevada.</p>
<p>Or Georgia.</p>
<p>Or Missouri.</p>
<p>It really depends on who you ask.</p>
<p>One study, in fact, did ask this question, and the results raised some eyebrows&#8212;or they did mine, at least.</p>
<p><div style="width: 610px" class="wp-caption aligncenter"><a href="https://smartasset.com/checking-account/states-worst-drivers-2019" target="_blank" rel="noopener noreferrer"><img loading="lazy" decoding="async" class=" aligncenter" src="https://i0.wp.com/dr5dymrsxhdzh.cloudfront.net/blog/images/aa7ab7e09/2019/06/worst-drivers_2019_map.png?resize=600%2C522&#038;ssl=1" width="600" height="522" data-recalc-dims="1" /></a><p class="wp-caption-text"><a href="https://smartasset.com/checking-account/states-worst-drivers-2019" target="_blank" rel="noopener noreferrer">Image from SmartAsset.com</a></p></div></p>
<p>Mississippi, then. It's settled, at least if we trust the methodology SmartAsset employed when conducting <a href="https://smartasset.com/checking-account/states-worst-drivers-2019">this analysis.</a></p>
<p>Personally, I have no qualms with drivers from the Magnolia State, likely because here in Wisconsin I never find myself tailgated, cut off, or otherwise confounded by the actions of vehicles with Mississippi plates.</p>
<p>That honor belongs to drivers from the great state of Illinois.</p>
<p>You can imagine my frustration, then, when I learned that, at least according to SmartAsset, Illinois drivers finished just outside the top ten <em>best </em>in the United States, with folks from my home state coming in right in the middle of the pack.</p>
<p>I mean, how could we Wisconsinites be any worse than the Illinois-plated trucks roaring down our interstates at twenty-five over the speed limit? How could anything we're doing compare to left turns from right-turn-only lanes, the speeding down one-ways in the opposite direction of, well, the one way?</p>
<p><span style="color: var(--color-text);">If we permit ourselves some distance from SmartAsset's metrics, the answer, naturally, is it's all relative.</span></p>
<p>Of <em>course </em>drivers from Wisconsin are more likely to be wary of those from Illinois who are wary of folks from Indiana who are wary of motorists from Ohio. When drivers from adjacent states are on their neighbors' roadways, they're less likely to be familiar with the area, and probably just want to get home&#8212;and home, for them, is much farther than a couple of blocks or a few country miles.</p>
<p>But even if we set aside matters of proximity and unfamiliarity, I suspect some of this wariness is also based on other regional stereotypes, in a tendency to distrust <em>the other</em>, and further manifestations of tribalism that play out across and within cultures and subcultures everywhere.</p>
<p>I don't expect any of this to be revelatory.</p>
<p>Still, it's worth noting that simply because one appreciates these concepts intellectually, that doesn't necessarily mean one's blood pressure doesn't increase that much more upon noting it was some Illinois-plated peon who barreled down the shoulder to bypass those holding up our end of the social contract by waiting our turns in gridlocked traffic because <em>we live in a society</em>.</p>
<p>But wouldn't it be nice if we <em>could </em>keep ourselves from having and acting on those prejudices?</p>
<p>This Friday, I'll be exploring just that in my new flash fiction piece, “State Line,” the story of a widower confronting a recent loss and interstate misconceptions. As I've written in <a href="https://ryanrcampbell.com/2019/12/02/this-friday-a-new-short-story">other</a> <a href="https://ryanrcampbell.com/2019/12/03/on-writing-ones-anxieties">posts</a> this week, I'm proud of this new short&#8212;not only because it's the first I've written in years&#8212;but because it comes from a place of honesty.</p>
<p>Yes, I <em>do </em>grip the steering wheel that much harder when a vehicle from Illinois is flying past at speeds unsafe even in ideal conditions. I <em>do </em>fist pump when state troopers have an Illinois-plated vehicle pulled over. I <em>do </em>wonder why I permit myself to feel this way, even when I understand these attitudes are maintained, at this point, almost entirely by my unabating desire to keep them alive.</p>
<p>I don't have an answer to this particular question, nor will “State Line” provide one definitively. Writing it, however, did force me to reckon with perceptions I hold about Illinois, yes, and also with perceptions folks from Chicagoland undoubtedly have about their neighbors to the north.</p>
<p>We'll see how all of this plays out when “State Line” debuts on <a href="https://www.wattpad.com/user/iamrrcampbell" target="_blank" rel="noopener noreferrer">Wattpad</a> this Friday, but until then, write on. Write well. Be your best you.</p>
<p><img loading="lazy" decoding="async" data-attachment-id="7175" data-permalink="https://ryanrcampbell.com/2019/12/02/this-friday-a-new-short-story/rr-black-signature-transparent/" data-orig-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/11/rr-black-signature-transparent.png?fit=405%2C228&amp;ssl=1" data-orig-size="405,228" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="rr black signature transparent" data-image-description="" data-image-caption="" data-medium-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/11/rr-black-signature-transparent.png?fit=300%2C169&amp;ssl=1" data-large-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/11/rr-black-signature-transparent.png?fit=405%2C228&amp;ssl=1" class="  wp-image-7175 aligncenter" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/11/rr-black-signature-transparent.png?resize=300%2C169&#038;ssl=1" alt="rr black signature transparent" width="300" height="169" srcset="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/11/rr-black-signature-transparent.png?w=405&amp;ssl=1 405w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/11/rr-black-signature-transparent.png?resize=300%2C169&amp;ssl=1 300w" sizes="(max-width: 300px) 100vw, 300px" data-recalc-dims="1" /></p>
<h3 style="text-align: center;"><em>r.r. campbell</em></h3>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default TheWorstDriversintheUnion
