import React from 'react'

const PointofViewPartTwo = () =>
  <div>
    <p style="text-align:center;"><em>This post is part of the </em>Write With Me<em> series. For more like this, check out the <a href="https://ryanrcampbell.com/writing-your-novel/">writing your novel</a> page.</em></p>
<p>Now that we've established the notion of point of view in <a href="https://ryanrcampbell.com/2017/02/24/edit-with-me-point-of-view-part-one/">this post</a>, let's hop right in to what to watch for with it when writing. We'll treat each POV in a separate section.</p>
<h1>First Person</h1>
<p>I'm of the opinion that the first person is the most straightforward POV to write because you can put yourself directly in the POV character's perspective to watch out for common mistakes. Let's take a look at a few mistakes to avoid when writing in the first person.</p>
<h2>The “I” Has It</h2>
<p>Let's say you have a main character named Xander. The below could be a scene from your manuscript.</p>
<blockquote class="tr_bq">
<h4>Fridays are always the worst. Leaning back in my chair, staring up at the in-laid tiles on the ceiling, I pass the hours hurling pencils toward it in an attempt to see how many I can get stuck by punch-out time. Eighteen's the record in case you're curious. Eighteen pencils in eight hours. You'd think a man with twelve years of practice could do better than that. To be honest, Xander really should have. Today I manage nine. Nine! Pathetic. I stand on my chair and pluck each pencil from the ceiling, one-by-one.</h4>
</blockquote>
<p>Well, the issue here probably sticks out like light-up sneakers in a dark garage. The reference to “Xander” in the third person is a break from first-person POV, and reads as though the comment is coming from the narrator itself. Replacing Xander with “I” tidies this up nicely.</p>
<p>Of course, the character could refer to him- or herself in the third person as if talking to themselves or making self-aware commentary. The line in question could be revised to something like:</p>
<blockquote class="tr_bq">
<h4>A real dolt, me. The magnificent Xander: piss-poor at even the mundane.</h4>
</blockquote>
<p>This isn't a point of view shift since we can read it in the character's voice and know it's self-referential.</p>
<p>Realistically, POV shifts of the variety displayed in the paragraph above tend to be of little concern for most folks writing in the first person. It is definitely worth watching out for if you previously wrote a piece in the third person and are now shifting to first, however. That's where mistakes can be made.</p>
<h2>Inner Monologue and The Observable Universe</h2>
<p>When writing in the first person, it's important to ensure that your character's thoughts remain grounded in information he actually has available to him at the time of the scene. Not only that, but the experience of the world should be based on this character's direct observations. To explore this, let's return to Xander and his scene in the office.</p>
<blockquote class="tr_bq">
<h4>Somewhere down the hall, Johnny Copymachine is waxing poetic about how he could've been a famous film producer. Malcolm is listening politely while Cora bows out before Johnny can ask her if she'd like to star in another one of his so-called indie films. Last time he asked, she agreed to a bit role for the sake of saving face around the office, and when she showed up on set (if you could really call it that), Johnny Copymachine had the bollocks to tell her it was a nudey bit. A real mess, the whole thing.</h4>
</blockquote>
<p>All of the information in the above paragraph could be true, but how do we know Xander knows all this? Last we knew, Xander was standing on his chair in his office. One could assume Xander knows this because it is a matter of routine, or that he can hear these events taking place (but how could he “hear” Cora bowing out of the office? Remember, in first-person POV (barring any magical powers), your main character should only have access to the past and the observable world (from where they are or were in it at the time the events occurred). Let's revise the above to ground it a bit more in the first person.</p>
<blockquote class="tr_bq">
<h4>Somewhere down the hall, Johnny Copymachine's voice is waxing poetic about how he could've been a famous film producer. Sounds as though Malcolm is politely engaged, but if Cora's around&#8212;and she's always around the copier&#8212;she's surely bowing out before Johnny can ask her to be in another one of his so-called indie films. Rumor has it that the last time she agreed to a bit part in one of his videos, he had the bollocks to tell her it was a nudey bit. Brent in HR said the whole thing was a damn mess to sort out, given that it happened off-hours and off-property, but it was a damn mess all the same.</h4>
</blockquote>
<p>Bam. Same information (in fact, we get more this time), and it remains grounded in Xander's POV throughout the excerpt. The crucial bit here is that we know <i>how</i> he knows what he knows&#8212;direct observation (hearing), hearsay (rumors), and supposition (based on what he knows of people from past interaction). This helps readers develop a better feel for the credibility of the information they're being given as well, which can be an asset in many circumstances.</p>
<h1>Second Person</h1>
<p>Writing in the second person? I wish… I wish I could be of some assistance. My experience with the second person is so limited (read: read non-existent), that it'd be a disservice for me to attempt to assist with it. I can imagine, however, that similar rules apply here as would apply in the first person: keep things grounded in what the “you” can actually see, hear, taste, smell, and touch, while also ensuring they don't consider information that hasn't been previously provided to them.</p>
<p>That being said, let's hop into the third person, specifically third-person limited.</p>
<h1>Third-Person Limited</h1>
<p>We can use our analysis of the first-person POV when looking at the third person as well&#8212;we just have to do it from a slightly different angle.</p>
<h2>Mind Your “He” and Remember Your “She”</h2>
<p>Making sure you keep consistent with your personal pronouns should be as easy here as it was for first person. In this case, if your narrative voice refers to your main character as “I” or part of a “we,” then you've got a POV inconsistency on your hands.</p>
<p>Because I kind of like this Xander guy, let's rework our original paragraph with him so that it's in the third person. We'll use that as a starting point for some example editing.</p>
<blockquote class="tr_bq"><p>Fridays are always the worst. Leaning back in his chair, staring up at the in-laid tiles on the ceiling, Xander passes the hours hurling pencils toward it in an attempt to see how many he can get stuck by punch-out time. Eighteen's the record. Eighteen pencils in eight hours. A man with twelve years of practice should do better than that. If he's honest with himself, Xander really should have. Today he manages nine. Nine! Pathetic. He stands on his chair and plucks each pencil from the ceiling, one-by-one.</p></blockquote>
<p>Ugh. It reads strangely, doesn't it? Let's explore why.</p>
<p>The first thing that comes to mind for me is that it's in the present tense. This is probably because the present tense in the third person reads unnaturally to me, for some reason. If this were shifted to the past, it might have a better feel to it, but let's save ourselves that step and see how else we can improve this.</p>
<p>There are no references to “I” or “we,” so we POV inconsistency isn't causing the trouble. What I think really drives me mad about this paragraph is this strange contrast of voice. Lines like “Eighteen's the record” that were once firmly grounded in Xander's direct commentary now read as though the narrator is providing that information.</p>
<p>Perhaps Xander is no longer our narrator. Think of <i>The Great Gatsby</i>. Gatsby, though the main character, isn't the narrator in that book&#8212;Nick Carraway is. Maybe this story about Xander needs to morph into something like that. It's an option, anyway, but it would require the introduction of a very present narrator, which could throw off the narrative itself.</p>
<p>Let's check out a reworked paragraph below, which attempts to strike a balance between narrative voice and Xander's voice.</p>
<blockquote class="tr_bq"><p>Fridays are always the worst. Leaning back in his chair, staring up at the in-laid tiles on the ceiling, Xander passes the hours hurling pencils toward it in an attempt to see how many he can get stuck by punch-out time. Eighteen's his record. Eighteen pencils in eight hours. A man with twelve years of practice should do better than that, he thinks to himself.</p>
<p>Today he manages nine. Nine! He shakes his head. Pathetic. Standing on his chair, he curses himself as he plucks each pencil from the ceiling, one-by-one.</p></blockquote>
<p>Look at that! This is a step in the right direction. changing “Eighteen's <i>the</i> record” to “Eighteen's <i>his</i> record” creates a more clear delineation between the narrator (who now, in my opinion, reads as less of an actual character), and Xander himself.</p>
<p>Splitting this into two paragraphs seems to help this excerpt breathe a bit more, too. I've also tossed in some commentary on actions Xander is taking (shaking his head, cursing himself under his breath), to reinforce that comments like “Nine!” and “Pathetic” are coming from Xander, not the narrator.</p>
<p>One last trick I slipped in was the inclusion of “he thinks to himself” at the end of the first paragraph. This works as a clarification here, but I know some editors are already upset with me for doing it like this. Why, you ask?</p>
<p>Because it's filtering.</p>
<p>Filtering is the temptation to toss in observational verbs like think, wonder, watch, smell, etc. as a way of clarifying that the perspective character is thinking, wondering, watching, or smelling whatever the objects of said verbs are.</p>
<p>I'll admit to doing this once in a while for the sake of rhythm, for example, but instances of filtering should be minimized whenever possible.</p>
<p>Let's use our other example from our first-person POV with Xander to explore what filtering is, and how it can be edited out. The below paragraph is a third-person rehash, littered with examples of filtering.</p>
<blockquote class="tr_bq"><p>Somewhere down the hall, Xander hears Johnny Copymachine waxing poetic about how he could've been a famous film producer. Xander thinks it sounds as though Malcolm is politely engaged, but if Cora's around&#8212;and she's always around the copier&#8212;she's surely bowing out before Johnny can ask her to be in another one of his so-called indie films. The rumors around the office&#8212;at least the ones Xander's heard&#8212;suggest the last time she agreed to a bit part in one of his videos, she showed up to the set and Johnny had the bollocks to tell her it was a nudey bit. Brent in HR told Xander the whole thing was a damn mess, given that it happened off-hours and off-property, but it was a damn mess all the same.</p></blockquote>
<p>So this reads okay, in my opinion. It's firmly grounded in the third person and there are no clear perspective changes.</p>
<p>But should we settle for okay? Of course not. Let's edit this to remove examples of filtering.</p>
<blockquote class="tr_bq"><p>Xander gets down from his chair to the sounds of Johnny Copymachine jabbering down the hall, waxing poetic about how he could've been a famous film producer. Malcolm's voice pipes up, politely engaged. Xander snickers. Malcolm may be polite, but if Cora's around&#8212;and she's always around the copier&#8212;she's surely bowing out before Johnny can ask her to be in another one of his so-called indie films. The rumors around the office have suggested the last time she agreed to a bit part in one of his videos, she showed up to the set and Johnny had the bollocks to tell her it was a nudey bit. Brent in HR said the whole thing was a damn mess, given that it happened off-hours and off-property, but it was a damn mess all the same.</p></blockquote>
<p>Alright, we're at better than okay here in my opinion. This version grounds everything in Xander, and also refocuses the attention on him before diving into any inner monologue. I think these changes offer a more crisp read by eliminating the clunkiness of the Xander hears/sees/thinks, etc.</p>
<p>So the moral of the story with third-person limited? Avoid filtering and keep your POV character as your reference point.</p>
<h1>Third-Person Omniscient</h1>
<p>I'll be frank. This category is similar to the second person for me. I don't use it often (ever?) and read it about as frequently. Since omniscience grants a great deal of freedom, however, I think the primary focus for anyone writing a story told in this POV should be to avoid shifting focus characters too frequently, as this can be jarring for a reader. To avoid this when shifting point of view, start a new paragraph or include a page break, for example.</p>
<h1>Lessons Learned</h1>
<p>Writing these (epically long) posts the last two weeks as well as engaging in some POV-related conversations on Twitter has been a helpful exercise for me, anyway. It's been a real demonstration of the importance and value of voice, and how that voice can be better focused in on (or zoomed away from) depending on the POV chose.</p>
<p>Most transcendentally, it has me realizing that I may need to rewrite my WIP in the first person after hitting the 25,000-word mark in third-person limited. The story moves along alright, but what it really needs is a fresh voice&#8212;something I think the above has shown is most reflected in the first person perspective.</p>
<p><strong><em>Update: </em></strong><em>As of April 19th, 2017, I've rewritten all of </em><a href="https://ryanrcampbell.com/current-projects/">XXX Accounting</a> <em>in the first person, and my goodness: what a difference a fresh perspective can make. If you're struggling to connect with your main character, I definitely suggest giving them a go in a different point of view to see if that helps change things.</em></p>
<hr />
<p>Thanks as always for reading. Have questions on POV? Reach out on <a href="http://www.twitter.com/iamrrcampbell">Twitter</a> or through <a href="https://ryanrcampbell.com/contact/">the contact page</a>. I'd love to hear from you.</p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default PointofViewPartTwo
