import React from 'react'

const Proportion = () =>
  <div>
    <p style="text-align:center;"><em>This post is part of the </em>Write With Me<em> series. For more like this, check out the <a href="https://ryanrcampbell.com/writing-your-novel/">writing your novel</a> page.</em></p>
<h1><span style="font-size:x-large;">P</span><span style="font-size:x-small;">R</span>O<span style="font-size:large;">P</span><span style="font-size:x-large;">O</span><span style="font-size:large;">R</span>T<span style="font-size:x-small;">I</span>O<span style="font-size:large;">N</span></h1>
<p>Well, that was annoying. Before you abandon thread, though, let's ask ourselves <i>why </i>that was so off-putting.</p>
<p>The answer comes easily: writing “proportion” like that just wasn't necessary&#8212;except that it was for reasons that will become apparent later on.</p>
<p>Proportion in writing refers to the number of words expended on any given facet of a story relative to all others&#8212;dialogue, description of characters or setting, advancement of the plot… the list goes on.</p>
<p>There are two key concepts to keep in mind at proportion's core: word economy and purpose. In order to know how to edit for proportion, let's explore each concept one at a time, starting with word economy.</p>
<h1>Word Economy</h1>
<div id="attachment_373" style="width: 553px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-373" data-attachment-id="373" data-permalink="https://ryanrcampbell.com/2017/03/10/edit-with-me-proportion/pexels-photo-159888/" data-orig-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/03/pexels-photo-159888.jpeg?fit=867%2C650&amp;ssl=1" data-orig-size="867,650" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="pexels-photo-159888" data-image-description="" data-image-caption="" data-medium-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/03/pexels-photo-159888.jpeg?fit=300%2C225&amp;ssl=1" data-large-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/03/pexels-photo-159888.jpeg?fit=867%2C650&amp;ssl=1" class="alignnone  wp-image-373" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/03/pexels-photo-159888.jpeg?resize=543%2C407&#038;ssl=1" alt="pexels-photo-159888" width="543" height="407" data-recalc-dims="1" /><p id="caption-attachment-373" class="wp-caption-text">Buy strong verbs. Sell adverbs. Almost always sell adverbs.</p></div>
<p>I've mentioned word economy in a handful of posts in the last couple of months, but we've never really explored it in any detail. The best metaphor I have for how to describe word economy is, of course, financial.</p>
<p>Every book has or will have a set number of words in it. Think of each word as a dollar or euro or dollarydoo, whatever works best for you. If your genre normally runs at about 80,000 words, for example, you've got 80,000 words to “spend” over the course of your book.</p>
<p>How will you spend them? Different books call for different budgets. Fantasy as a genre, for example, will often see more spent on description and world-building than a thriller, which will focus more on tight scenes of action.</p>
<p>Before I dive too far into this metaphor, I'll acknowledge that genre word-count rules are not always so rigid. Like any rule in something as subjective as writing, there are always going to be exceptions. When actively writing or editing though, especially as an unpublished author, it's practical to ensure we're more or less within the target word-count range for our genre before querying. Not every novel can be <i>Infinite Jest</i>, nor can it be published at 25,000 words.</p>
<p>Disregarding exceptions to word-count guidelines, let's press on with considerations of our word budget.</p>
<p>Unlike an actual personal budget, I don't think (nor do I recommend) any individual writer should attempt to assign an actual quantity of words to a given category of expenditures. In fact, an efficient writer advances plot, develops character, and builds description with a purposeful choice behind (almost) every word.</p>
<p>What I recommend instead of creating an actual budget is to consider which investments might be worth it, and which may not.</p>
<p>Let's say we're writing a scene in a bar. Our goal is for readers to have a good feel for the place, and to play up the role the bartender plays in fomenting tension between our protagonist and antagonist as they try to hash things out over a couple of beers.</p>
<p>After finishing this scene, we find ourselves really proud. We've accomplished the goals we set out to achieve with it, and man alive we cannot believe we actually pulled it off for once. We should probably give ourselves a little credit once in a while, but that's another matter entirely.</p>
<p>The first inclination we have may be to leave the scene as it is. Don't fix what isn't broken, right? Well, with writing it isn't about just whether things work, but <i>why</i> and <i>how</i> they work, too. “Serviceable” is rarely the sort of praise one is looking for from readers (I hope so, anyway), so let's dive in to purpose and see how we can evaluate the scene's word economy for better proportionality.</p>
<h1>Purpose<span style="font-size:large;"><br />
</span></h1>
<div id="attachment_374" style="width: 560px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-374" data-attachment-id="374" data-permalink="https://ryanrcampbell.com/2017/03/10/edit-with-me-proportion/pexels-photo-196744/" data-orig-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/03/pexels-photo-196744.jpeg?fit=940%2C623&amp;ssl=1" data-orig-size="940,623" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="pexels-photo-196744" data-image-description="" data-image-caption="" data-medium-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/03/pexels-photo-196744.jpeg?fit=300%2C199&amp;ssl=1" data-large-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/03/pexels-photo-196744.jpeg?fit=940%2C623&amp;ssl=1" class="  wp-image-374 aligncenter" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/03/pexels-photo-196744.jpeg?resize=550%2C365&#038;ssl=1" alt="pexels-photo-196744" width="550" height="365" data-recalc-dims="1" /><p id="caption-attachment-374" class="wp-caption-text">Simply put, our scenes have to do more than pass butter. Or is that cheese?</p></div>
<p style="text-align:left;">Let's start with the bartender. As the writers of the scene, we love this guy. He has that really cool mustache and he wears the vest from a three-piece suit over a pit-stained white tee. What a crusty guy. Fun, but crusty. Oh, and he starts the scene by telling that story about the dude he had to throw out of the bar last week for telling another patron he looked like “the bovine equivalent of Marilyn Manson.” He swept in and stopped that spat before it could get any worse. What a boss! Clyde–that's the bartender's name. Boy, we sure do love us some Clyde.</p>
<p>Looking over the scene, we might say, “Nice! Clyde gets a whole page to himself, and then Stock Protagonist and Stock Antagonist appear and he really rustles their jimmies.”</p>
<p>Before we just leave Clyde to his one page of stardom (or worry too much about the details of jimmie-rustling), let's ask ourselves some of the <i>why</i> and <i>how</i> suggested at the end of the Word Economy section.</p>
<p>Why was Clyde included? Why was he described in such great detail? Is he a recurring character? How does he figure into the story's overall plot? How does he figure into any subplots?</p>
<p>We could (and should) ask ourselves similar questions about the bar itself, too. How much detail was provided? Why? Will the characters be back here? Is it important that the reader know exactly what each character is drinking and how much it cost? Whose idea was it to come to this place, anyway?</p>
<p>The answers to these questions can give a guide to where, how, and what needs to be cut or tightened up from the scene. What each question attempts to get at is this: what is the purpose for the inclusion of these details and will they be necessary to know later?</p>
<p>If the answers to these questions are: “I just really like [setting, character, or subplot],” and “Not really, kind of, maybe,” those probably are not reason enough to keep those details in the next draft. As mentioned in the word economy section, every word, paragraph, scene, chapter&#8212;it all has to give you the best bang for your buck. When we have words or scenes or characters or setting descriptions that serve themselves more than they serve the overall arcs of our stories, they're not giving us the best return possible.</p>
<p>That is to say, they're not serving a greater purpose.</p>
<h1>Summary</h1>
<p>Essentially, to write with proportion in mind, we're asking ourselves whether each scene or word is the best way to serve our stories. I repeat: serve <i>our stories</i>, not ourselves as the authors of them.</p>
<p>When going through our manuscripts, we should watch out for places where we may have done the equivalent of writing proportion as <span style="font-size:x-large;">P</span><span style="font-size:x-small;">R</span>O<span style="font-size:large;">P</span><span style="font-size:x-large;">O</span><span style="font-size:large;">R</span>T<span style="font-size:x-small;">I</span>O<span style="font-size:large;">N</span><span style="font-size:medium;"> (see? I told you it would come full circle). Writing it like that (or writing about a one-time-appearing bartender in agonizing detail) might have seemed like a really cool idea at the time, but unless it serves a greater, transcendent purpose, it's time to reconsider the scene's construction.</span></p>
<p>If I say so myself, writing “proportion” all googly-moogly certainly served this blog post well as an illustrative example, but can the same be said for our manuscripts' equivalents?</p>
<p>As writers, we can't always trust ourselves to know the answer to that question. We have to trust our beta readers, our critique groups, our editors. They'll have more objective eyes than we ever could.</p>
<hr />
<p>Thanks as always for reading. Have questions or comments on proportion? Or are you looking for another set of eyes on your manuscript? Aside from writing these posts and putting together <a href="http://ryanrcampbell.com/podcasts/" target="_blank" rel="noopener noreferrer">these podcasts</a>, I'm also an <a href="http://ryanrcampbell.com/editing-services/" target="_blank" rel="noopener noreferrer">editor available for hire</a>. If you just want to join in on the conversation, you can find me on <a href="http://www.twitter.com/iamrrcampbell">Twitter</a>, too. I'd love to see you there.</p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default Proportion
