import React from 'react'

const AnnouncingTheWritescastNetwork = () =>
  <div>
    <p><img loading="lazy" decoding="async" data-attachment-id="5117" data-permalink="https://ryanrcampbell.com/2018/05/04/announcing-the-writescast-network/writescast-network-featured-image/" data-orig-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/05/Writescast-Network-Featured-Image.png?fit=1180%2C435&amp;ssl=1" data-orig-size="1180,435" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="Writescast Network - Featured Image" data-image-description="" data-image-caption="" data-medium-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/05/Writescast-Network-Featured-Image.png?fit=300%2C111&amp;ssl=1" data-large-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/05/Writescast-Network-Featured-Image.png?fit=1024%2C377&amp;ssl=1" class="alignnone size-full wp-image-5117" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/05/Writescast-Network-Featured-Image.png?resize=1080%2C398&#038;ssl=1" alt="Writescast Network - Featured Image" width="1080" height="398" srcset="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/05/Writescast-Network-Featured-Image.png?w=1180&amp;ssl=1 1180w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/05/Writescast-Network-Featured-Image.png?resize=300%2C111&amp;ssl=1 300w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/05/Writescast-Network-Featured-Image.png?resize=1024%2C377&amp;ssl=1 1024w" sizes="(max-width: 1080px) 100vw, 1080px" data-recalc-dims="1" /></p>
<p><span style="font-weight: 400;">I'm excited to announce that as of May 4th, 2018, <a href="http://www.rrcampbellwrites.com/podcasts" target="_blank" rel="noopener">the r. r. campbell writescast</a> is now part of <a href="http://www.writescast.net" target="_blank" rel="noopener">The Writescast Network</a>, a writing-podcast cooperative that will gather all of your favorite podcasts for writers, by writers in one place. </span></p>
<p><span style="font-weight: 400;">So what does this mean for listeners? If you’re already a subscriber to the r. r. campbell writescast through iTunes or your favorite podcast-listening app, you’ll continue to receive every episode of the show without interruption. The additional benefit of this transition is that you’ll also get every episode of the new podcasts under The Writescast Network umbrella, including <a href="https://writescast.net/podcasts/bibliobreakdown/" target="_blank" rel="noopener">Biblio Breakdown</a>, <a href="http://writescast.net/podcasts/novelapproaches/" target="_blank" rel="noopener">Novel Approaches</a>, and other shows that will be added to our lineup in late 2018 and early 2019.</span></p>
<p><span style="font-weight: 400;">In other words, this innovation is all about delivering more writerly content to you all in one place: both on our RSS feed and <a href="http://www.writescast.net" target="_blank" rel="noopener">our new website, writescast.net!</a> </span></p>
<p><span style="font-weight: 400;">Have questions about this change? Or are you the host of a writing-related podcast that would like to be added to the family? You can email us at writescast [at] gmail.com</span><span style="font-weight: 400;"> or holler at us on Twitter at <a href="http://www.twitter.com/writescast" target="_blank" rel="noopener">@writescast.</a></span></p>
<p><span style="font-weight: 400;">Thank you for your continued support as we undergo this exciting innovation. Write on and write well.</span></p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default AnnouncingTheWritescastNetwork
