import React from 'react'

const SoYourePlanningaBookLaunchParty = () =>
  <div>
    <p style="text-align: center;"><em><strong>Note:</strong></em><em> a more in-depth version of this material is available as a podcast.<br />
<a href="http://writescast.net/2018/12/21/writescast048" target="_blank" rel="noopener">To listen instead, click here.</a></em></p>
<p>On the heels of hosting my own book launch party for <em><a href="https://ryanrcampbell.com/books/accountingforitall/" target="_blank" rel="noopener">Accounting for It All</a></em>, I thought I'd pass along some bullet point advice you might take into consideration when planning a launch party of your own.</p>
<p>With that in mind, let's explore <strong>why</strong> <strong>you should have a party</strong>, how to choose <strong>where to</strong> <strong>host it</strong>, and <strong>what to do</strong> <em>at</em> and <strong>what to bring<em> </em></strong><em>to </em>the event to make it memorable for you and your guests.</p>
<h2>Why have a book launch party?</h2>
<div id="attachment_5516" style="width: 430px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-5516" data-attachment-id="5516" data-permalink="https://ryanrcampbell.com/2018/12/21/so-youre-planning-a-book-launch-party/img_1021-13/" data-orig-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/12/IMG_1021-13.jpg?fit=4240%2C3392&amp;ssl=1" data-orig-size="4240,3392" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;5&quot;,&quot;credit&quot;:&quot;Leo Duijvestijn&quot;,&quot;camera&quot;:&quot;Canon EOS 5D Mark II&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;1543676920&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;24&quot;,&quot;iso&quot;:&quot;800&quot;,&quot;shutter_speed&quot;:&quot;0.008&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="IMG_1021-13" data-image-description="" data-image-caption="&lt;p&gt;Signing books at the ACCOUNTING FOR IT ALL launch party&lt;/p&gt;
" data-medium-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/12/IMG_1021-13.jpg?fit=300%2C240&amp;ssl=1" data-large-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/12/IMG_1021-13.jpg?fit=1024%2C819&amp;ssl=1" class="alignnone  wp-image-5516" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/12/IMG_1021-13.jpg?resize=420%2C336&#038;ssl=1" alt="IMG_1021-13" width="420" height="336" srcset="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/12/IMG_1021-13.jpg?w=4240&amp;ssl=1 4240w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/12/IMG_1021-13.jpg?resize=300%2C240&amp;ssl=1 300w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/12/IMG_1021-13.jpg?resize=768%2C614&amp;ssl=1 768w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/12/IMG_1021-13.jpg?resize=1024%2C819&amp;ssl=1 1024w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/12/IMG_1021-13.jpg?w=2160&amp;ssl=1 2160w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/12/IMG_1021-13.jpg?w=3240&amp;ssl=1 3240w" sizes="(max-width: 420px) 100vw, 420px" data-recalc-dims="1" /><p id="caption-attachment-5516" class="wp-caption-text">Signing books at the ACCOUNTING FOR IT ALL launch party.</p></div>
<ul>
<li><strong>You wrote a book <em>and </em>got it published</strong>; celebrate that success with friends, family, and other readers!</li>
<li><strong>Generate additional buzz for your book's release.</strong> Book launches are great opportunities to increase one's reach in person and online once guests post about the awesome time they had at your event.</li>
<li><strong>Sell and sign books for your most avid fans in person.</strong> Creating these connections will go a long way into reinforcing your brand and drumming up more word of mouth recommendations for you and your book.</li>
</ul>
<h2>Where should you host your launch?</h2>
<ul>
<li><strong>As counter-intuitive as it may seem, <em>avoid </em>having your launch party at a bookstore.</strong> Why? They'll want or will take a cut of your sales for the event. The folks who come to your launch party are likely people who will buy your book no matter what, so why not maximize your return on those sales? You can always host a signing or a separate reading at your local bookseller on a later date.</li>
<li><strong>Pick somewhere comfortable and memorable for your guests (and you!).</strong> Creating a fun environment in a casual setting will make them more likely to come to future events (and it'll also make you more likely to host them in the future).</li>
<li><strong>Consider choosing a venue that complements your book's setting and themes. </strong>Does your book take place on a farm? See if you can find somewhere in your local community that offers a rustic, rural setting. Or, if it takes place in a school or your main character is a teacher, consider reaching out to schools, community colleges, or universities near you about hosting your event. Get creative and reinforce your book through the tiny details!</li>
</ul>
<h2>What might you do at your party and why?</h2>
<div id="attachment_5515" style="width: 408px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-5515" data-attachment-id="5515" data-permalink="https://ryanrcampbell.com/2018/12/21/so-youre-planning-a-book-launch-party/img_1036-19/" data-orig-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/12/IMG_1036-19-189858651-1545089853923.jpg?fit=2989%2C2391&amp;ssl=1" data-orig-size="2989,2391" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="IMG_1036-19" data-image-description="" data-image-caption="&lt;p&gt;Attendees to the Accounting for It All launch party listen to a reading.&lt;/p&gt;
" data-medium-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/12/IMG_1036-19-189858651-1545089853923.jpg?fit=300%2C240&amp;ssl=1" data-large-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/12/IMG_1036-19-189858651-1545089853923.jpg?fit=1024%2C819&amp;ssl=1" class="alignnone  wp-image-5515" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/12/IMG_1036-19-189858651-1545089853923.jpg?resize=398%2C318&#038;ssl=1" alt="IMG_1036-19" width="398" height="318" srcset="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/12/IMG_1036-19-189858651-1545089853923.jpg?w=2989&amp;ssl=1 2989w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/12/IMG_1036-19-189858651-1545089853923.jpg?resize=300%2C240&amp;ssl=1 300w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/12/IMG_1036-19-189858651-1545089853923.jpg?resize=768%2C614&amp;ssl=1 768w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/12/IMG_1036-19-189858651-1545089853923.jpg?resize=1024%2C819&amp;ssl=1 1024w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/12/IMG_1036-19-189858651-1545089853923.jpg?w=2160&amp;ssl=1 2160w" sizes="(max-width: 398px) 100vw, 398px" data-recalc-dims="1" /><p id="caption-attachment-5515" class="wp-caption-text">Attendees to the <em>ACCOUNTING FOR IT ALL</em> launch party listen to a reading.</p></div>
<ul>
<li><strong>Readings</strong>. Picking one or two selections from your novel and reading them aloud will get launch party attendees engaged directly with your book. Try to choose short but riveting selections that don't give away major plot points. Keep your party guests wanting more!</li>
<li><strong>Author Q&amp;A</strong>. Give your guests an opportunity to pick your brain about how you wrote this book, why, and what research might have gone into writing it. For folks who haven't written a book before, they might be curious about your process as well. You might also consider doing one reading, then opening the floor to questions, then doing your second reading once questions have died down.</li>
<li><strong>Do a teaser from your work in progress or other upcoming release. </strong>Whether an additional reading or a book trailer, letting attendees know they can expect more from you in the future will keep them excited about your books and about you as an author.</li>
<li><strong>Raffle. </strong>Who doesn't love free things? Raffle off some swag or a copy of your book to those who sign up for your author newsletter at the event, for example. This will let you expand your reach while also giving guests something to stick around for (aside from you and your wonderful book) when you select the raffle's winner at the end of the event.</li>
<li><strong>Sell books! </strong>Make sure you have enough on hand to meet demand. It's also worth appointing a close friend or family member to handle selling books during the event so that you're free to greet attendees, thank them for coming, and generally relax before doing your readings, etc.</li>
</ul>
<h2>What should you bring to your launch party?</h2>
<ul>
<li><strong>Business cards. </strong>If you don't have any printed already, it's worth getting some made up. Make it easy for readers or readers-to-be to get in touch with you by email or find you on social media!</li>
<li><strong>Bookmarks. </strong>The great things about bookmarks are they 1) help us keep track of where we are in books and 2) if branded well, can be used to keep our book at the forefront of readers' minds long after they've finished reading our particular book. By having bookmarks like those available at the launch for people to grab (or, for bonus points, you can just put them in every copy you have available), readers might be more likely to remember to recommend your book to their family and friends as it'll be fresh in their mind.</li>
</ul>
<p style="text-align: center;"><em><strong>Pro tip:</strong> </em>find the Little Free Libraries in your town and leave a few bookmarks in each of them. People like free stuff, and if the bookmarks you issue help them find your book, all the better!</p>
<ul>
<li><strong>Other swag. </strong>You might consider getting stickers made up or printing out some quarter-page leaflets with tips for how your guests can best support you and other authors. An example of the quarter-page leaflet I included in the books themselves at my event can be found below.</li>
</ul>
<div id="attachment_5518" style="width: 414px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-5518" data-attachment-id="5518" data-permalink="https://ryanrcampbell.com/2018/12/21/so-youre-planning-a-book-launch-party/image1/" data-orig-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/12/image1-2026741462-1545090246484.jpeg?fit=2697%2C3140&amp;ssl=1" data-orig-size="2697,3140" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="image1" data-image-description="" data-image-caption="&lt;p&gt;Quarter-page inserts can keep the buzz coming long after your launch party has ended.&lt;/p&gt;
" data-medium-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/12/image1-2026741462-1545090246484.jpeg?fit=258%2C300&amp;ssl=1" data-large-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/12/image1-2026741462-1545090246484.jpeg?fit=880%2C1024&amp;ssl=1" class="alignnone  wp-image-5518" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/12/image1-2026741462-1545090246484.jpeg?resize=404%2C470&#038;ssl=1" alt="image1" width="404" height="470" srcset="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/12/image1-2026741462-1545090246484.jpeg?w=2697&amp;ssl=1 2697w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/12/image1-2026741462-1545090246484.jpeg?resize=258%2C300&amp;ssl=1 258w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/12/image1-2026741462-1545090246484.jpeg?resize=768%2C894&amp;ssl=1 768w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/12/image1-2026741462-1545090246484.jpeg?resize=880%2C1024&amp;ssl=1 880w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/12/image1-2026741462-1545090246484.jpeg?w=2160&amp;ssl=1 2160w" sizes="(max-width: 404px) 100vw, 404px" data-recalc-dims="1" /><p id="caption-attachment-5518" class="wp-caption-text">Quarter-page inserts can keep the buzz coming long after your launch party has ended.</p></div>
<ul>
<li><strong>Poster-sized cover. </strong>This is a big one&#8212;and not just the poster, I mean. Getting a poster-sized printout of your cover made and then propping it up on an easel will make for a natural anchor point around which your guests can congregate to take photos, and it's also an opportune place to do signings and generally attract attention for your event. This is the one thing I absolutely recommend doing that might not be among the more standard considerations of business cards and bookmarks.</li>
<li><strong>Change for selling books. </strong>If you'll be taking cash for books, make sure you have change! Twenties are the most common denomination of bill in circulation, so make sure you can give people cash back for their purchases by visiting the bank before your event and getting some ones, fives, and tens on hand.</li>
<li><strong>Card reader for credit or debit transactions. </strong>Taking credit and debit has never been easier, especially if you have a smartphone. I use Square to process credit transactions, and their app is free to download, and the most basic of their card scanners is free to have mailed to you as well. They do take a small percentage of each transaction, however, so you might consider pricing credit sales accordingly. You also don't <em>need</em> to get the scanner to use the app; you can manually punch in card numbers, too, which is a nice option to have available. And the good news? You can have the funds you bring in through these charges dumped directly in your bank account the following business day. Not a bad deal at all.</li>
</ul>
<h2>Okay, this feels like a lot to do. I'm scared. Please help.</h2>
<p>Planning an event of any kind can be daunting, but remember you can space all of this out over the course of months. It's also worth keeping in mind that, again, <em>you wrote a book</em>. That'll honestly be enough to excite your party's guests; don't feel like you have to go all “I must get an inflatable bouncy castle for this event to really show off my party-hosting chops” or anything.</p>
<p>Just relax. You've already done the hard part. Now it's time to celebrate!</p>
<hr />
<p>Thanks for reading. For more content like this, <a href="https://rrcampbellwrites.us16.list-manage.com/subscribe?u=d5b261c0c9ed58a1907dfdc4e&amp;id=26327b8a65" target="_blank" rel="noopener">subscribe to my newsletter</a> or <a href="https://writescast.net/2018/12/21/writescast048" target="_blank" rel="noopener">check out the podcast I did on this very topic</a>. It goes even more in-depth than the above, though the same material is covered overall.</p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default SoYourePlanningaBookLaunchParty
