import React from 'react'

const WestworldS02E08NonlinearStorytelling = () =>
  <div>
    <p style="text-align: center;">Note: spoilers for Westworld through season two, episode eight follow.</p>
<p>From a storytelling standpoint, one of the most transcendent decisions <em>Westworld</em>‘s writers made was to make use of non-linear storytelling. In fact, it's this very decision that makes some of the biggest reveals in season one as impactful as they are.</p>
<p>With viewers under the assumption that the events they are watching unfold are, by and large, occurring in a linear order, it boggles the mind when it's revealed that William and the Man in Black are one in the same, for example.</p>
<p>There's obviously great utility in a non-linear presentation of events, but as a storytelling device it doesn't come without its risks&#8212;especially when the use of the device is wholly concealed from viewers or readers and used as fuel for earth-shattering twists.</p>
<p>So what's the risk one runs and why is it important to understand its implications? To answer those questions, let's begin by exploring what <em>Westworld</em>‘s use of non-linear storytelling buys the show before exploring its costs.</p>
<h3>Mystery on Stage, Dramatic Irony in the Wings</h3>
<p>Throughout season one, viewers watch each episode unfold under the presumption that what they're viewing is all happening more or less at the same time.</p>
<p>Why is that, you ask?</p>
<p>I'll posit that it's mostly because the linear presentation of events is the most widely implemented choice for the telling of tales in general, and the <em>why</em> behind that follows from our experiences as people: in our day to day lives, we live with time as our fourth dimension, only ever able to experience the present while reflecting on the past and looking toward the future. One can divide up their experiences into clear demarcations in space and time, which flow smoothly from past to present to future (though we're never technically in the future, I suppose) in discrete, observable units. So why shouldn't our storytelling be the same?</p>
<p>It's a result of this, then, that viewers of <em>Westworld</em> are left with their jaws on the floor when they learn that everything they've watched unfold between William and Logan actually took place decades earlier than the show's “present,” however difficult that may be to define.</p>
<p>This buys the writers a great deal <a href="https://ryanrcampbell.com/2017/06/09/who-knows-what-and-when-mystery-suspense-and-dramatic-irony/" target="_blank" rel="noopener">in terms of mystery</a>, wherein characters have access to information that viewers lack. Once the jig is up where timelines are concerned, that sense of mystery then converts its mass <a href="https://ryanrcampbell.com/2017/06/09/who-knows-what-and-when-mystery-suspense-and-dramatic-irony/" target="_blank" rel="noopener">into dramatic irony</a>, and as a result viewers realize they now know things the characters do not. In looking back, one's opinions and interpretations of William's actions in the past are changed dramatically since we know his experiences ultimately make him into the Man in Black.</p>
<p>Similarly, we view Dolores and her relationship with William (and to the Man in Black) through a new lens as well: how horrifying it would be (and becomes) for her to know that the two men are one in the same.</p>
<p>All of this enriches one's relationships to the characters most impacted by the reveal that non-linear storytelling has been put to use throughout the first season.</p>
<p>Of course, the show's deliberate failure to be forthright about the use of non-linear storytelling incurs costs as well, some of which I believe might be greater than the return on investment. Let's take a look at those costs now, and how they come into play in the show's most recent episode and beyond.</p>
<h3>Pay No Attention to the Man Behind the Curtain</h3>
<p>One of the greatest costs of <em>Westworld</em>‘s particular implementation of non-linear storytelling is that we as viewers now expect it as a portal to revelation, which has led to what I feel to be some of the more foundational criticisms of the second season: namely that we can no longer trust <em>when</em> we are as we watch certain storylines unfold.</p>
<p>This skepticism or lack of trust between viewers and the show itself has therefore gone from an asset to a liability for a subset of the show's fans. Though the manner in which the show's writers used non-linear reveals in season one ultimately led to great investment from viewers, it did another thing from which there is no turning back: it jostled us from the narrative dream by making us aware of the writers themselves.</p>
<p>Now conscious of the writers' presence and the tools they're comfortable using, we're like Dorothy and her crew in <em>The Wizard of Oz</em>. We know there's a man behind the curtain, so to speak, which now has us concentrated on him at times instead of focused on the great show he might be putting on before us.</p>
<h3>Analysis of the Utility of Non-linear Storytelling</h3>
<p>So what's can be said of non-linear storytelling, then? Are we to shun it in our own work? Is it a fundamentally flawed, hacky tool that should be laid to rest forevermore?</p>
<p>No, not at all. There are actually a few other stories that come to mind that effectively use non-linear storytelling to great acclaim. Books like David Mitchell's <em>Cloud Atlas</em> have us travel forward and then backward in time as the book advances, taking great leaps and bounds in time and space with each shift of the timeline. Though jarring at first, this presentation of events doesn't have the same impact on reader-writer trust as <em>Westworld</em>‘s choices have for viewer-writer trust.</p>
<p>Then of course there's the <em>A Song of Ice and Fire </em>series, in which the events of books four and five, <em>A Feast for Crows </em>and <em>A Dance with Dragons</em>, occur concurrently. Though one could argue the volume of those two books necessitated this particular split, the split unto itself doesn't betray reader-writer trust in the same way that <em>Westworld </em>does.</p>
<p>I myself briefly dip into non-linear storytelling in the first book in <a href="https://empathynovel.com/books/" target="_blank" rel="noopener">the <em>EMPATHY</em> series</a>. Near the book's climax, there are moments during which one character's perspective is followed to the natural conclusion of a scene, only for the following chapter to begin minutes earlier from the perspective of another character who's in a slightly different location than the last. Early readers of <em><a href="https://empathynovel.com/books/" target="_blank" rel="noopener">EMPATHY: Imminent Dawn</a> </em>found this presentation particularly effective as opposed to becoming a betrayal of their trust.</p>
<p>So what's the difference between these three examples and <em>Westworld</em>?</p>
<p>In <em>Cloud Atlas</em>, <em>A Song of Ice and Fire</em>, and <em>EMPATHY: Imminent Dawn</em>, <strong>the authors are forthcoming about their use of non-linear storytelling.</strong> That is to say, it's not used as part of some great reveal that shakes and splits the very ground on which readers or viewers stand. In so doing, those books allow readers to have a greater appreciation for the mystery and dramatic irony on the page&#8212;at least compared to the sense of mystery that exists in <em>Westworld</em>.</p>
<p>Truthfully, the above-cited sense of mystery is hardly a mystery at all; how can we as viewers appreciate receiving the key that unlocks mystery's door if we don't know there's a key in the first place&#8212;or, perhaps more aptly, if we don't know there's a <em>door</em> in the first place?</p>
<h3>So what about season two, episode eight?</h3>
<p>“Kiksuya” provides a heartbreaking portal into one host's journey, and does so by spending much of the episode bringing viewers up to speed on his personal trials and tribulations over the course of the entire history of the park.</p>
<p>Within the episode itself, the presentation of this host's story is mostly linear, but it stands out against the greater timeline since much of what we as viewers watch unfold in the episode has occurred not only in the past, but the distant past where the park's history is concerned.</p>
<p>Put another way, it would be like reading the second book in a series, getting seventy percent of the way through it, and then spending the next ten percent of the book getting to know not only a new perspective character, but doing so on a timeline that actually reaches all the way back to the first chapter of the first book in the series.</p>
<p>Disorienting, right?</p>
<p>My goal in presenting this metaphor isn't to suggest that the approach the show's writers took for “Kiksuya” is misguided. In fact, it's almost out of necessity that the story is presented this way; if viewers knew what the Ghost Nation knew going back to season one, episode one, it would have vastly undercut the impact of the timeline-related reveals on which the first season hinges in many ways.</p>
<p>The aim of providing said metaphor is to demonstrate that what might work in one medium&#8212;assuming one agrees that <em>Westworld</em>‘s take on non-linear storytelling works at all&#8212;doesn't always work in another.</p>
<p>In film or television, there are a number of unique considerations one must take into account that don't receive the same weight as when writing a manuscript for a work of fiction, with the same being true the other way around.</p>
<p>What are these considerations? They're explored to an extent in <a href="https://ryanrcampbell.com/podcast/writescast026/" target="_blank" rel="noopener">this episode of the r. r. campbell writescast</a> featuring screenwriter Aria Gmitter, but in this case let's consider that in a novelized version of <em>Westworld</em>, nothing would stop the author from selectively lacing the various scenes featured in “Kiksuya” throughout the more linear, greater timeline of events.</p>
<p>Doing so would require the deliberate withholding of certain details from readers as to not overly tip them off to impending revelations, but it could perhaps be more easily done than it could have been in the show itself given the different set of parameters with which these two media have to work.</p>
<h3>The Takeaway</h3>
<p>The conclusion here is this: though “Kiksuya” might have been a carefully crafted snapshot into one character's history, doing the same at a similar juncture in one's novel is not therefore by extension a necessarily advisable approach.</p>
<p>Could it work? I would never say no, but there are a great number of things to consider when making any decisions about the lens through which a story is told, whether it's choosing a point of view or, in this case, the order in which the plot is presented.</p>
<p><em>Westworld </em>has made its bed in electing a non-linear approach, and now, for better or worse, it's a bed in which it must lie.</p>
<p>The moral of the story? Before you get to choosing the bed-set that will become your manuscript, take a minute to make sure you're satisfied with your story's mattress first.</p>
<hr />
<p>Like what you read here? What more content like this delivered to your inbox regularly? <a href="http://www.rrcampbellwrites.com/newsletter" target="_blank" rel="noopener">You can subscribe to my newsletter here</a> for posts like these and other writerly updates. Thanks for reading!</p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default WestworldS02E08NonlinearStorytelling
