import React from 'react'

const EMPATHYonTourThankYouBooksandBeer = () =>
  <div>
    <p>I had a blast at last night's Books and Beer event in Columbus, Wisconsin. Thanks to everyone who attended, to author Valerie Biel for organizing the event, and to Cercis Brewing Company for hosting.</p>
<p>This was the final stop of the EMPATHY spring tour, but I'm already adding <a href="https://empathyseries.com/events/">new events for this summer</a>! Be sure to keep an eye on that page and on <a href="https://www.facebook.com/iamrrcampbell/events">my Facebook events page</a> for additional events in the coming months.</p>
<p>That said, here are some photos from Books and Beer!</p>
<div id="attachment_1085" style="width: 4042px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-1085" class="alignnone size-full wp-image-1085" src="https://empathynovel.files.wordpress.com/2019/06/img_3321-1.jpeg?resize=1080%2C810" alt="IMG_3321-1" width="1080" height="810" data-recalc-dims="1" /><p id="caption-attachment-1085" class="wp-caption-text">The event might have been called Books and Beer, but that didn't stop me from having a Moscow Mule instead.</p></div>
<div id="attachment_1086" style="width: 3034px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-1086" class="alignnone size-full wp-image-1086" src="https://empathynovel.files.wordpress.com/2019/06/img_3315.jpeg?resize=1080%2C1440" alt="IMG_3315" width="1080" height="1440" data-recalc-dims="1" /><p id="caption-attachment-1086" class="wp-caption-text">Valerie Biel (right) was a great host; she kept the conversation flowing and moderated the event expertly.</p></div>
<p>&nbsp;</p>
<div id="attachment_1087" style="width: 4042px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-1087" class="alignnone size-full wp-image-1087" src="https://empathynovel.files.wordpress.com/2019/06/img_3329.jpeg?w=4032&#038;resize=1080%2C810" alt="IMG_3329.jpeg" width="1080" height="810" data-recalc-dims="1" /><p id="caption-attachment-1087" class="wp-caption-text">Janet (right) was visiting from California! She'd already read <em>Imminent Dawn</em>; I was more than happy to sign it and a copy of <em>Mourning Dove </em>for her.</p></div>
<div id="attachment_1088" style="width: 1745px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-1088" class="alignnone size-full wp-image-1088" src="https://empathynovel.files.wordpress.com/2019/06/img_3325-e1561114325676.jpeg?resize=1080%2C1710" alt="IMG_3325" width="1080" height="1710" data-recalc-dims="1" /><p id="caption-attachment-1088" class="wp-caption-text">Behold! The signed copy of <em>Mourning Dove</em>.</p></div>
<p>Thanks again to everyone who made this a memorable evening.</p>
<p>Want to get in on the book that brought all of these people together? Good news&#8212;this June, <em><strong><a href="https://ryanrcampbell.com/shop/" target="_blank" rel="noopener noreferrer">signed print copies are 15% off with keyword SUMMER19</a>!</strong> </em>And you can get <em><strong><a href="https://ninestarpress.com/product/imminent-dawn/" target="_blank" rel="noopener noreferrer">40% off ebooks with keyword PRIDE</a></strong> </em>if you order directly from my publisher.</p>
<h2 style="text-align: center;"><em>Imminent Dawn</em></h2>
<p style="text-align: center;"><a href="https://www.amazon.com/dp/B07N1Q8C6G/" target="_blank" rel="noopener noreferrer">Amazon</a> | <a href="https://www.barnesandnoble.com/w/imminent-dawn-rr-campbell/1130343569?ean=2940161198599" target="_blank" rel="noopener noreferrer">Barnes &amp; Noble</a> | <a href="https://ninestarpress.com/product/imminent-dawn/" target="_blank" rel="noopener noreferrer">NineStar Press</a> | <a href="https://www.kobo.com/us/en/ebook/imminent-dawn" target="_blank" rel="noopener noreferrer">Kobo</a> | <a href="https://www.smashwords.com/books/view/919525" target="_blank" rel="noopener noreferrer">Smashwords</a>| <a href="https://www.goodreads.com/book/show/43196570-imminent-dawn">Goodreads</a> | <a href="https://ryanrcampbell.com/product/signedimminentdawn/" target="_blank" rel="noopener noreferrer">Author Website</a></p>
<h2 style="text-align: center;"><em>Mourning Dove</em></h2>
<p style="text-align: center;"><a href="https://www.amazon.com/dp/B07QZGSDX6/">Amazon</a> | <a href="https://www.barnesandnoble.com/w/books/1131295072" target="_blank" rel="noopener noreferrer">Barnes &amp; Noble</a> | <a href="http://ninestarpress.com/product/mourning-dove" target="_blank" rel="noopener noreferrer">NineStar Press</a> | <a href="https://www.kobo.com/us/en/ebook/mourning-dove-7" target="_blank" rel="noopener noreferrer">Kobo</a> | <a href="https://www.smashwords.com/books/view/935036" target="_blank" rel="noopener noreferrer">Smashwords</a> | <a href="https://www.goodreads.com/book/show/43728390-mourning-dove" target="_blank" rel="noopener noreferrer">Goodreads</a>| <a href="https://ryanrcampbell.com/?post_type=product&amp;p=5816&amp;preview=true" target="_blank" rel="noopener noreferrer">Author Website</a></p>
<div id="jp-post-flair" class="sharedaddy sd-like-enabled sd-sharing-enabled">
<div class="sharedaddy sd-sharing-enabled" style="text-align: center;"></div>
</div>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default EMPATHYonTourThankYouBooksandBeer
