import React from 'react'

const EMPATHYonTourThankYouLaCrosse = () =>
  <div>
    <p>The EMPATHY spring and summer tour kept on chugging this last weekend with an event at Pearl Street Books in La Crosse! It was wonderful to return to beautiful northwestern Wisconsin so soon after <a href="http://empathyseries.com/2019/05/13/empathy-on-tour-thank-you-eau-claire/" target="_blank" rel="noopener noreferrer">my recent event in Eau Claire</a>. Thank you, Pearl Street Books, for hosting, and thanks to everyone who made it to the reading or swung by afterward.</p>
<p><a href="http://www.empathyseries.com/events">The EMPATHY tour</a> will continue this upcoming weekend at <a href="https://www.facebook.com/events/558467391305359/" target="_blank" rel="noopener noreferrer">the Reader's Loft in Green Bay</a> before it concludes on Thursday, June 20th at <a href="https://www.facebook.com/events/413453452791377/" target="_blank" rel="noopener noreferrer">Books and Beer in Columbus, Wisconsin</a>.</p>
<p>Until then, here are some of my favorite photos from last weekend’s event!</p>
<div id="attachment_media-209" style="width: 9064px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-media-209" class="alignnone size-full wp-image-958" src="https://empathynovel.files.wordpress.com/2019/06/image2-1-1.jpeg?resize=1080%2C466" alt="image2 (1).jpeg" width="1080" height="466" data-recalc-dims="1" /><p id="caption-attachment-media-209" class="wp-caption-text">I thought I'd take a panoramic shot of the store before attendees arrived. Pearl Street Books is an old shoe store converted into a bookstore!</p></div>
<div id="attachment_956" style="width: 3034px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-956" class="alignnone size-full wp-image-956" src="https://empathynovel.files.wordpress.com/2019/06/img_3172.png?resize=1080%2C1440" alt="IMG_3172" width="1080" height="1440" data-recalc-dims="1" /><p id="caption-attachment-956" class="wp-caption-text">An attendee listens in during the morning's first reading.</p></div>
<div id="attachment_955" style="width: 3034px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-955" class="alignnone size-full wp-image-955" src="https://empathynovel.files.wordpress.com/2019/06/img_3163.png?resize=1080%2C1440" alt="IMG_3163" width="1080" height="1440" data-recalc-dims="1" /><p id="caption-attachment-955" class="wp-caption-text">People *always* ask who did the covers for the series (Natasha Snow)!</p></div>
<div id="attachment_959" style="width: 3034px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-959" class="alignnone size-full wp-image-959" src="https://empathynovel.files.wordpress.com/2019/06/image1-1.jpeg?resize=1080%2C1440" alt="image1 (1)" width="1080" height="1440" data-recalc-dims="1" /><p id="caption-attachment-959" class="wp-caption-text">In case you're ever in the area and have trouble finding the place, here it is!</p></div>
<h2 style="text-align: center;"><em>Imminent Dawn</em></h2>
<p style="text-align: center;"><a href="https://www.amazon.com/dp/B07N1Q8C6G/" target="_blank" rel="noopener noreferrer">Amazon</a> | <a href="https://www.barnesandnoble.com/w/imminent-dawn-rr-campbell/1130343569?ean=2940161198599" target="_blank" rel="noopener noreferrer">Barnes &amp; Noble</a> | <a href="https://ninestarpress.com/product/imminent-dawn/" target="_blank" rel="noopener noreferrer">NineStar Press</a> | <a href="https://www.kobo.com/us/en/ebook/imminent-dawn" target="_blank" rel="noopener noreferrer">Kobo</a> | <a href="https://www.smashwords.com/books/view/919525" target="_blank" rel="noopener noreferrer">Smashwords</a>| <a href="https://www.goodreads.com/book/show/43196570-imminent-dawn">Goodreads</a> | <a href="https://ryanrcampbell.com/product/signedimminentdawn/" target="_blank" rel="noopener noreferrer">Author Website</a></p>
<h2 style="text-align: center;"><em>Mourning Dove</em></h2>
<p style="text-align: center;"><a href="https://www.amazon.com/dp/B07QZGSDX6/">Amazon</a> | <a href="https://www.barnesandnoble.com/w/books/1131295072" target="_blank" rel="noopener noreferrer">Barnes &amp; Noble</a> | <a href="http://ninestarpress.com/product/mourning-dove" target="_blank" rel="noopener noreferrer">NineStar Press</a> | <a href="https://www.kobo.com/us/en/ebook/mourning-dove-7" target="_blank" rel="noopener noreferrer">Kobo</a> | <a href="https://www.smashwords.com/books/view/935036" target="_blank" rel="noopener noreferrer">Smashwords</a> | <a href="https://www.goodreads.com/book/show/43728390-mourning-dove" target="_blank" rel="noopener noreferrer">Goodreads</a>| <a href="https://ryanrcampbell.com/?post_type=product&amp;p=5816&amp;preview=true" target="_blank" rel="noopener noreferrer">Author Website</a></p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default EMPATHYonTourThankYouLaCrosse
