import React from 'react'

const EMPATHYOnTourThankYouGreenBay = () =>
  <div>
    <p>Last weekend's stop for the EMPATHY spring tour was another fantastic one. I had a wonderful time visiting the Reader's Loft bookstore in Green Bay and am thankful for their support. Thanks, too, to everyone who came out to say hello.</p>
<p><a href="http://www.empathyseries.com/events">The EMPATHY spring tour</a> will conclude on Thursday, June 20th at <a href="https://www.facebook.com/events/413453452791377/" target="_blank" rel="noopener noreferrer">Books and Beer in Columbus, Wisconsin</a>; don't miss this last chance to catch me this spring!</p>
<p>Until then, here are some of my favorite photos from last weekend’s event!</p>
<div id="attachment_978" style="width: 3034px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-978" class="alignnone size-full wp-image-978" src="https://empathynovel.files.wordpress.com/2019/06/readers-loft-facade.jpeg?resize=1080%2C1440" alt="Reader's Loft Facade" width="1080" height="1440" data-recalc-dims="1" /><p id="caption-attachment-978" class="wp-caption-text">It was a beautiful day for a bookstore event!</p></div>
<div id="attachment_979" style="width: 3034px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-979" class="alignnone size-full wp-image-979" src="https://empathynovel.files.wordpress.com/2019/06/gb-sandwich-board-sign.jpeg?resize=1080%2C1440" alt="GB sandwich board sign" width="1080" height="1440" data-recalc-dims="1" /><p id="caption-attachment-979" class="wp-caption-text">Oh, hey! Look who's listed on the board!</p></div>
<div id="attachment_980" style="width: 3034px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-980" class="alignnone size-full wp-image-980" src="https://empathynovel.files.wordpress.com/2019/06/lacey-and-greta.jpeg?resize=1080%2C1440" alt="Lacey and Greta" width="1080" height="1440" data-recalc-dims="1" /><p id="caption-attachment-980" class="wp-caption-text">There were two cats who lived in the store! Here's Lacey petting Greta.</p></div>
<div id="attachment_981" style="width: 3034px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-981" class="alignnone size-full wp-image-981" src="https://empathynovel.files.wordpress.com/2019/06/sophie.jpeg?resize=1080%2C1440" alt="Sophie" width="1080" height="1440" data-recalc-dims="1" /><p id="caption-attachment-981" class="wp-caption-text">And this is Sophie! She was a little more shy.</p></div>
<div id="attachment_982" style="width: 3034px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-982" class="alignnone size-full wp-image-982" src="https://empathynovel.files.wordpress.com/2019/06/img_3216.jpg?resize=1080%2C1440" alt="IMG_3216" width="1080" height="1440" data-recalc-dims="1" /><p id="caption-attachment-982" class="wp-caption-text">The afternoon's setup!</p></div>
<div id="attachment_983" style="width: 4042px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-983" class="alignnone size-full wp-image-983" src="https://empathynovel.files.wordpress.com/2019/06/signed-author-copies.jpeg?resize=1080%2C810" alt="Signed Author Copies" width="1080" height="810" data-recalc-dims="1" /><p id="caption-attachment-983" class="wp-caption-text">Shiny-looking signed author copies were available right near the entrance to the store!</p></div>
<p>Still need to get your hands on a copy of any of the books in the EMPATHY series? Remember, paperbacks are currently 15% off (with free shipping!) on <a href="http://www.rrcampbellwrites.com/shop">my author site</a>, and you can get 40% off ebooks at <a href="https://ninestarpress.com/authors/r-r-campbell/">ninestarpress.com with keyword PRIDE</a>.</p>
<h2 style="text-align: center;"><em>Imminent Dawn</em></h2>
<p style="text-align: center;"><a href="https://www.amazon.com/dp/B07N1Q8C6G/" target="_blank" rel="noopener noreferrer">Amazon</a> | <a href="https://www.barnesandnoble.com/w/imminent-dawn-rr-campbell/1130343569?ean=2940161198599" target="_blank" rel="noopener noreferrer">Barnes &amp; Noble</a> | <a href="https://ninestarpress.com/product/imminent-dawn/" target="_blank" rel="noopener noreferrer">NineStar Press</a> | <a href="https://www.kobo.com/us/en/ebook/imminent-dawn" target="_blank" rel="noopener noreferrer">Kobo</a> | <a href="https://www.smashwords.com/books/view/919525" target="_blank" rel="noopener noreferrer">Smashwords</a>| <a href="https://www.goodreads.com/book/show/43196570-imminent-dawn">Goodreads</a> | <a href="https://ryanrcampbell.com/product/signedimminentdawn/" target="_blank" rel="noopener noreferrer">Author Website</a></p>
<h2 style="text-align: center;"><em>Mourning Dove</em></h2>
<p style="text-align: center;"><a href="https://www.amazon.com/dp/B07QZGSDX6/">Amazon</a> | <a href="https://www.barnesandnoble.com/w/books/1131295072" target="_blank" rel="noopener noreferrer">Barnes &amp; Noble</a> | <a href="http://ninestarpress.com/product/mourning-dove" target="_blank" rel="noopener noreferrer">NineStar Press</a> | <a href="https://www.kobo.com/us/en/ebook/mourning-dove-7" target="_blank" rel="noopener noreferrer">Kobo</a> | <a href="https://www.smashwords.com/books/view/935036" target="_blank" rel="noopener noreferrer">Smashwords</a> | <a href="https://www.goodreads.com/book/show/43728390-mourning-dove" target="_blank" rel="noopener noreferrer">Goodreads</a>| <a href="https://ryanrcampbell.com/?post_type=product&amp;p=5816&amp;preview=true" target="_blank" rel="noopener noreferrer">Author Website</a></p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default EMPATHYOnTourThankYouGreenBay
