import React from 'react'

const SpeakingAppearanceCelebritySaturdaywithAllWritersWorkshop = () =>
  <div>
    <p style="text-align: center;"><img loading="lazy" decoding="async" data-attachment-id="5565" data-permalink="https://ryanrcampbell.com/2019/01/08/speaking-appearance-celebrity-saturday-with-allwriters-workshop/speaking-announcement-allwriters/" data-orig-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/01/Speaking-Announcement-Allwriters.png?fit=1024%2C512&amp;ssl=1" data-orig-size="1024,512" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="Speaking Announcement - Allwriters'" data-image-description="" data-image-caption="" data-medium-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/01/Speaking-Announcement-Allwriters.png?fit=300%2C150&amp;ssl=1" data-large-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/01/Speaking-Announcement-Allwriters.png?fit=1024%2C512&amp;ssl=1" class=" size-full wp-image-5565 aligncenter" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/01/Speaking-Announcement-Allwriters.png?resize=1024%2C512&#038;ssl=1" alt="Speaking Announcement - Allwriters'" width="1024" height="512" srcset="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/01/Speaking-Announcement-Allwriters.png?w=1024&amp;ssl=1 1024w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/01/Speaking-Announcement-Allwriters.png?resize=300%2C150&amp;ssl=1 300w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/01/Speaking-Announcement-Allwriters.png?resize=768%2C384&amp;ssl=1 768w" sizes="(max-width: 1024px) 100vw, 1024px" data-recalc-dims="1" /></p>
<p>I'm pleased to announce I've been invited to lead a session on mapping one's way to story as part of the AllWriters' Workshop 2019 Celebrity Saturday series!</p>
<p>On July 27, 2019, I'll be teaching a five-hour seminar entitled <em><strong>Treasure ho! Mapping Your Way to Story</strong></em><em> </em>at the AllWriters' Workshop in Waukesha, Wisconsin.</p>
<p>So what is AllWriters' Workshop, and what, exactly, will I be covering?</p>
<p><a href="http://www.allwritersworkshop.com/about-us/about-allwriters/" target="_blank" rel="noopener">Per their website</a>, their philosophy centers around the notion that “AllWriters’ provides community for writers. We give encouragement. We give education. And we give you great company.”</p>
<p>Where this particular seminar is concerned, I'll be focusing on how to develop a concept before turning that concept step-by-step into a scene-by-scene outline. With our outlines in hand, we'll then be in the best position we've ever been to take on writing the tale that just won't let us out of its grips.</p>
<p><strong>Please note this event requires registration in advance, and seats are limited. </strong>So don't delay&#8212;learn more about AllWriters' Workshop and this seminar by visiting this page, which also includes information about the other five Celebrity Saturday events AllWriters will host throughout the year.</p>
<p>Have questions? Reach out to me through <a href="https://ryanrcampbell.com/contact/">my contact page</a> or <a href="http://www.allwritersworkshop.com/contact-us/" target="_blank" rel="noopener">send an email to Kathie Giorgio</a>, the director and founder of AllWriters.</p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default SpeakingAppearanceCelebritySaturdaywithAllWritersWorkshop
