import React from 'react'

const SettingMoreThanJustPlace = () =>
  <div>
    <p style="text-align:center;"><em>This post is part of the </em>Outline With Me <em>series. </em><em>For more like this, check out the <a href="https://ryanrcampbell.com/outlining-your-novel/">outlining your novel</a> page.</em></p>
<p style="text-align:left;">One need look no further than Tolkien's <i>The Lord of the Rings</i> series or George R. R. Martin's <i>A Song of Ice and Fire</i> to understand how a thoroughly developed world can enrich a narrative. In both of these examples and countless others, however, setting isn't just a place. It can be a character itself! Think of Hogwarts from the <i>Harry Potter</i> series, the silo from Hugh Howey's <i>Wool</i>, and the titular Room from Emma Donoghue's 2010 bestseller.</p>
<div style="text-align:center;">
<p style="text-align:left;">Each of these environments separates themselves from simple set dressing in that they are unique, contrary to expectations, and described in vivid but tactful detail. In this post, we'll explore how to craft an engrossing setting in which your characters can thrive.</p>
<h1 style="text-align:left;">Unique</h1>
<p style="text-align:left;">Creating a unique setting for your characters is easier said than done. Degrees of uniqueness can vary, however, ranging from the setting in its entirety to elements thereof. For the former, consider <i>Wool</i> by Hugh Howey, the premise of which is that survivors of the apocalypse are living out their lives within a silo that burrows deep into the ground. The silo is partitioned into over one hundred floors, each of which is different from the others based on the function performed by those that work or live on that floor. This entire environment is unique–not the sort of thing most of us have (or will?) encounter within our lifetimes.</p>
<p style="text-align:left;">On the other hand, consider <i>Room</i> by Emma Donoghue. Room is what you might think it is: a room. At first glance, there's really nothing special about a space with a bathroom, small kitchen, and a bed. In fact, it sounds an awful lot like a studio apartment. What makes Room unique isn't the setting itself, but the <i>nature </i>of the setting. Once readers learn that Room is actually a shed in which the five year-old protagonist, Jack, and his mother have been held against their will for the entirety of the Jack's life, we get a much different take on the space itself. With Room being the only world the perspective character has ever known, the relationship he has with his environment is equally as rich as the relationship he has with his mother.</p>
<p style="text-align:left;">It's easy to get discouraged when pitting your own settings up against those in <i>Room</i> and <i>Wool</i>. Those authors are bestsellers, after all, and setting plays a major role in the plot for both books. If you're stuck on how to add unique or stand-out flair to your settings, try to think of the little things you appreciate (or don't) from places you see in your day-to-day life and incorporate them into your writing. Do you have a faucet that always leaks? Your character can, too. Hate how you have to turn the key all the way to the left and then wiggle it before your front door will unlock? Your character hates that, too. Or maybe they find it appealing for some reason. I don't know. In any case, I should really call my landlord.</p>
<p style="text-align:left;">Tying these ideas into the prospective novel about our Mormon bartender, Joseph, I've decided to have the story take place in a township surrounded by a bustling metropolis on all sides. The reason it remains a township separate from the surrounding city has to do with its resistance to historic annexation on the part of the nearby city. Not only that, but the town has some historically bizarre laws, which are enforced by a constable rather than a traditional police force. Joseph's bar will be located within the township's limits, which will open up the door to all sorts of out-of-the-box legal wrangling and shenanigans.</p>
<p style="text-align:left;">I'll get into more details regarding Joseph's setting as we advance through the post. Let's leave it there for now.</p>
<h1 style="text-align:left;">Contrary to Expectations</h1>
<p style="text-align:left;">Tied closely to uniqueness, countering popular expectations is another way to make your settings stand out. This is something that's already been incorporated in the model novel for these <em><a href="https://ryanrcampbell.com/outlining-your-novel/">Outline With Me</a></em> posts: the fact that this novel will feature a bar run by a Mormon who himself does not drink.</p>
<p style="text-align:left;">One not need create total contradictions to meddle with expectations, however. Think about Hogwarts from the <i>Harry Potter</i> series. J.K. Rowling could have simply set her magical school in, well, a school, but instead she had the school be a castle. Not only that, but elements of the castle (moving staircases, the room of requirement, paintings whose subjects can visit subjects in other pieces of art) run contrary to the expectations of muggles like us. As mentioned above, creating elements in a setting that violate what is commonly accepted also adds to the setting's uniqueness, which demonstrates how intertwined these two concepts are.</p>
<p style="text-align:left;">Looking at setting for our Mormon bartender, I thought it would be best to avoid the “stock” or “default” location for a story that features a number of Mormon characters. The first place most people probably think of as it relates to Mormonism is Utah, which is why I've decided to set this novel in Minneapolis (well, a <i>fictional</i> township contained within Minneapolis city limits, but you get the picture).</p>
<p style="text-align:left;">Toying with readers' expectations by challenging their “stock” and “default” notions for setting should increase your story's memorability, which, if they enjoy reading it, can never be a bad thing.</p>
<h1 style="text-align:left;">Vivid and Tactful Detail</h1>
<p style="text-align:left;">A third way to ensure your settings are more than just stage dressing is to incorporate details that are bold and well dispersed throughout your manuscript.</p>
<p style="text-align:left;">In <i>Room</i>, we are given the literal dimensions of the space, which should trip the careful writer's “tell” alarm. Rather than simply provide us the dimensions of Room, however, Emma Donoghue presents them to us via her protagonist as he makes a game out of quantifying his environment with a makeshift measuring system. In this way, we aren't <i>told</i> of Room's dimensions, but rather we experience it through the manner in which Jack explores the space. In this way, this information is presented both memorably and tactfully.</p>
<p style="text-align:left;">Think again of Hogwarts and its various paintings. A casual mention of them would have certainly been unique and run contrary to expectations, but the details Rowling provides regarding them is what breathes life into their presence in that world. The subjects of the paintings have names, backstories, and personalities all their own. Not only that, but the details aren't dumped on us the moment Harry encounters one for the first time. We learn about them as Harry learns about them, which makes for a tactful presentation.</p>
<p style="text-align:left;">I'll pull a final example of vivid and tactful detail from George R. R. Martin's <i>A Song of Ice and Fire</i> series. Consider the Wall. Its scope is tremendous, yes, but I often find the tiniest details regarding it to be some of the most unforgettable. The way it is described as “weeping” when the ice upon it is melting, the sound of weapons <i>clang</i>ing against one another in the yard, the smell of Three-Finger Hobb's meals wafting about the mess hall–all of it helps create a location that, actual magic aside, feels truly magical. It's immersing in the very least. Similarly to how Harry explores Hogwarts, Jon Snow learns about and explores the Wall (as do Tyrion and Melisandre, both of whom also give us glimpses at Castle Black from their perspectives). Again, we see the value of point of view in enhancing the appeal (or lack thereof) for a given location.</p>
<p style="text-align:left;">For Joseph and his bar, I've decided to run really contrary to expectations, while also giving myself a lot of opportunities for vivid and tactful detail. His bar won't be just any bar, no–it will be the most popular Packers bar in all of Minneapolis.</p>
<p style="text-align:left;">What's this all about, you say? For the uninitiated, the Green Bay Packers (American) football team has a rival in the team based out of Minneapolis, the Minnesota Vikings. By owning a bar that is against the common beliefs of both Joseph's religion and popular sentiment in the area, I'll establish a memorable quirk while also creating more opportunities for tension.</p>
<p style="text-align:left;">On top of this, I'll be able to “write what I know” as a lifelong Packers fan when creating a lore for the bar. The history should write itself in naturally (where appropriate!).</p>
<p style="text-align:left;">When creating a setting for your own work, try to make use of all five senses in order to create vivid details. You get bonus points for incorporating smells, as this sense is not only the least employed in fiction, but it is also the most closely tied sense to memory.</p>
<p style="text-align:left;">Once you have your details, make sure you knit them into your manuscript tidily as well. Avoid massive detail dumps at the start of a scene, for example, by having your point of view character experience the space themselves. Think of it this way: when you walk into a room, do you drop everything you are doing and analyze the environment down to the very last detail? No, of course not. You may remark on the lighting or the smell or the damp feel of the place, but you don't necessarily notice the fine woodwork supporting the room's sconces until you're right up against it. Depending on who you are (and which character is telling the story), such details might not go noticed at all!</p>
<p style="text-align:left;">The important thing as the author is to know these details yourself, whether they make it to the final draft or not. The more immersed you are as the author, the easier it will be to immerse your readers as well.</p>
<h1 style="text-align:left;">Keeping Track of Your World</h1>
<p style="text-align:left;">On a final note, though creating a world is a challenge in itself, keeping track of all its details can be even more trying. To help yourself keep things sorted, try drawing maps, diagrams, or drawings of your different settings. You don't need to be a visual artist to put pencil to paper and draw out something that makes sense to you. You're the only person that has to be able to tell what you're looking at, after all. These are <i>your</i> reference materials!</p>
<p style="text-align:left;">If drawing or mapping doesn't do it for you, try creating a list similar to the one used in our <a href="https://ryanrcampbell.com/2016/12/30/character-at-the-core-the-importance-of-depth/" target="_blank" rel="noopener noreferrer">post on creating characters</a>. What attributes do you think are worth including in a template like that? Think of the five senses and let them lead the way. With the basic elements of plot, character, and setting now fleshed out, we're ready to move on to creating an outline for the story in its entirety, which we'll cover in next week's installment of the <em><a href="https://ryanrcampbell.com/outlining-your-novel/">Outline With Me</a></em> series.</p>
<p style="text-align:left;">&#8212;</p>
<p style="text-align:left;">Have thoughts on world-building or setting? What do you do to develop vivid worlds and keep track of them? <a href="https://twitter.com/iamrrcampbell" target="_blank" rel="noopener noreferrer">Tweet at me</a> or get in touch through <a href="https://ryanrcampbell.com/contact/">the contact page</a> to join the conversation!</p>
</div>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default SettingMoreThanJustPlace
