import React from 'react'

const TheWritingquotFormulaquot = () =>
  <div>
    <p>Anyone who has watched <i>Spongebob Squarepants</i> knows that Plankton's overall goal is to get a hold of the Krabby Patty formula by any means necessary, including the creation of a robot version of Mr. Krabs. <a href="https://youtu.be/KQi3r88-rT4?t=23s" target="_blank" rel="noopener noreferrer">Who could forget this classic scene?</a></p>
<p>Though a formula (and love!) may be sufficient to approximate the taste of a Bikini-Bottom-renowned delicacy, the same is not true for writing. There is no one “formula” to guarantee the successful completion of a novel, the landing of an agent, or the securing of a publishing deal.</p>
<p>This may seem contradictory in light of my <em><a href="https://ryanrcampbell.com/outlining-your-novel/">Outline With Me</a></em> series, which is why I think it's important to contextualize both that advice and the advice I aim to provide in general.</p>
<p>I feel positive that the strategy I outline in that series can be effective one for “planners,” those who like to have (almost?) everything outlined before they dive in to writing a new novel. Obviously, this strategy would mean little to pantsers&#8212;those who write by the seat of their pants.</p>
<p>Beyond this contrast, you may find yourself thinking, “For as much as I'd love to start outlining by hammering out a <a href="https://ryanrcampbell.com/2016/12/09/the-logline-your-novel-in-50-words-or-fewer/" target="_blank" rel="noopener noreferrer">logline</a>, it's a <a href="https://ryanrcampbell.com/2016/12/30/character-at-the-core-the-importance-of-depth/" target="_blank" rel="noopener noreferrer">character</a> that actually came to me first.” If that's the case, that's great! Start with character and use them to guide you into your logline, <a href="https://ryanrcampbell.com/2016/12/16/from-logline-to-narrative-arc-connecting-the-dots-part-one/" target="_blank" rel="noopener noreferrer">narrative arc</a>, <a href="https://ryanrcampbell.com/2017/01/06/setting-more-than-just-place/" target="_blank" rel="noopener noreferrer">world-building</a>, and <a href="https://ryanrcampbell.com/2017/01/13/the-outline-not-one-but-many/" target="_blank" rel="noopener noreferrer">outlining</a>. The same can be said if you develop the world first, or are simply inspired by a line or <a href="https://ryanrcampbell.com/2016/11/18/goal-conflict-resolution-cliffhanger-the-elements-of-a-scene/" target="_blank" rel="noopener noreferrer">particular scene</a>.</p>
<p>Given the ambiguity this might create, the lack of a “go-to” way to do things might be discouraging at first glance. But I promise it's just the opposite! What this essentially means is that you have to (and should!) do what works for <i>you</i> above all else. If going through the steps of the <em>Outline With Me</em> series doesn't work for you, switch it up and see what does. If certain bits of advice in the <em><a href="https://ryanrcampbell.com/writing-your-novel/">Write With Me</a></em> series don't quite land for you, stick with what helps keep you moving forward.</p>
<p>Since writing my first novel, my strategy and style has changed immensely over time, ultimately leading to the steps portrayed over the course of the last handful of weeks and the tips you can find throughout this site. Who knows? Maybe by the time I'm done with my current WIP, that strategy and style will have evolved once again.</p>
<p>As writers, what counts in the end is that we're putting in the work, and putting it in <a href="https://ryanrcampbell.com/2017/03/30/on-writing-every-day/" target="_blank" rel="noopener noreferrer">every day</a>. Finding what works best for us will take that much longer if we're only writing once a week or month. The sooner we find what works, the sooner we can focus on what really counts: the writing itself.</p>
<p>A writer's journey will be as diverse as those of their characters, so be open, be ready, and be willing to put in the work.</p>
<p>Write on and write well.</p>
<p>&#8212;</p>
<p>Want to join in the #writingtips conversation on Twitter? Follow me <a href="http://www.twitter.com/iamrrcampbell" target="_blank" rel="noopener noreferrer">here</a>. Or, if email is more of your thing, you can get in touch through the <a href="https://ryanrcampbell.com/contact/" target="_blank" rel="noopener noreferrer">contact page</a>.</p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default TheWritingquotFormulaquot
