import React from 'react'
import { Quote } from '../../../../../components'
import { Link } from 'react-router-dom'

const BookReviewTheGoodEnoughJob = () => {
  const moreThanQuote = `By subsequently accepting ourselves as more than, we empower ourselves to be defined not merely by what we do for a living or by our relationships to others, but by who we are to ourselves, both now and in the future.`
  return (
    <>
      <h2 id='footnote-marker'>The Right Book. The Right Time. <em>Right On.</em></h2>
      <p>That's how I felt mere pages into <em>The Good Enough Job</em> by Simone Stolzoff. This came as a great relief; given its title, I came to the book with a bit of trepidation. Would it prove to be a thinly-conceived anti-work<a href='#anti-work'>*</a> screed? Would reading it undercut the momentum I'd been building to push myself out of my professional comfort zone?</p>
      <p>I'm happy to report I was incorrect on both counts.</p>
      <p>In the end, <em>The Good Enough Job</em> serves as an affirmation of what many skeptics of workism surely feel at times, even if it's difficult—or a professional hazard—to articulate.</p>
      <h2>Workism: the <em>-ism</em> that Should Be an <em>Isn't</em></h2>
      <p>In <em>The Good Enough Job</em>, Stolzoff presents workism as a philosophy that elevates work as the altar at which many (read: most) Americans worship, with the majority of the afflicted doing so unknowingly or, for those who do it with an alleged sense of agency, at their own peril.</p>
      <p><em>What do you do for a living?</em></p> 
      <p>This is the question the book's introduction posits to be the first many Americans will ask another shortly after meeting. If that rings true, well, case in point: the primacy of this icebreaker as a supposed gateway into understanding a person as defined by the trade they ply is, on its own, an indicator of the value our culture places on work.</p>
      <p>The book's own author concedes that they've “spent much of [their] career searching for a vocational soulmate, for a job that doesn't just pay the bills but is a unique reflection of who [they are].”</p>
      <p>Again, if this resonates, you're not alone. </p>
      <p>In fact, that single quote speaks to the heart of two of the themes in <em>The Good Enough Job</em> that hit home for me particularly hard as a reader, namely vocational awe and enmeshment.</p>
      <h2>The Awesome (Awful?) Power of Vocational Awe</h2>
      <p>Let me be clear: Simone Stolzoff did not coin the term <em>vocational awe</em>, nor does he take credit for having done so. On the contrary, Stolzoff cedes the stage through <em>The Good Enough Job</em> to the nine individuals he interviewed for the book, including Fobazi Ettarh, who introduced the world to the term vocational awe in the context of librarianship.</p>
      <p>There are a number of facets to be explored with respect to vocational awe—Ettarh wrote an entire academic paper on the topic, after all—but for our purposes, we'll explore it as the notion that there are some professions inherently worth holding in high esteem, not because they are the highest-earning careers, but rather because they are jobs that individuals sacrifice a great deal for personally while often earning very little for the privilege.</p>
      <Quote 
        text='[Vocational awe is] the notion that there are some professions inherently worth holding in high esteem... because they are jobs that individuals sacrifice a great deal for personally while often earning very little for the privilege.'
      />
      <p>The trade-off for those who assume these positions is, as the prevailing narrative would have it, that those in these fields are <em>following their passion</em> or <em>doing what they love</em> or <em>realizing their dreams</em>.</p>
      <p>Those of you who have followed my <Link to='/2021/05/15/im-done-writing-for-now-i-promise-you-this-is-okay/'>blog</Link> or <Link to='/podcast/youre-not-your-author-you-featuring-m-a-hinkle-writescast-097/'>podcasts</Link> over the years may see where I'm going with this. Worse yet, you may be already feeling acutely the same pang that plagued me as I turned from one page to the next in this particular section of <em>The Good Enough Job</em>.</p>
      <p>If you're not there yet, let me be direct. Authorship and work in publishing—especially the closer you are to content creation—far too often take advantage of those who participate in the ecosystem by abusing the air of vocational awe that surrounds it.</p>
      <p>To expound on this, there was a time, years ago, when <a href='https://www.reddit.com/r/selfpublish/comments/tzh1o7/in_your_opinion_when_can_a_person_call_herself_an/' noopener noreferrer target='_blank'>some</a> <a href='https://www.google.com/search?q=when+can+you+call+yourself+an+author' noopener noreferrer target='_blank'>debate</a> emerged online about when one could say they had made the transition from “aspiring author” to “author.” Those in the gatekeeping camp argued that to be an author is to have earned it via publication, whereas those in the inclusive camp suggested that to have written is to have become a writer.</p>
      <p>The merits of either argument aside, that the debate existed at all speaks to a consequence of vocational awe. If to be worthy of the social esteem associated with authorship requires some amount of sacrifice, should those who have made such sacrifices not demand some scrutiny with respect to that which, as they might have it, separates the <em>doers</em> from those who <em>would do?</em></p>
      <p>The debate itself is not particularly productive. It serves, ultimately, as a distraction from the true injury suffered by creators and creators-adjacent in the publishing ecosystem, which, excepting the exceedingly successful or otherwise wise to the game, preys on those whose passion drives it, no matter what they call themselves.</p>
      <p id='footnote-marker-2'>Some will object to this characterization of the business of publishing as predatory. I would challenge that reaction, however, by countering that any knee-jerk objection is likely a culturally conditioned extension of the very vocational awe to which I in this post—and Ettarh in her work in library sciences—draw attention. One not need look particularly long to uncover examples of the abuses—or opportunities for abuse—that exist in publishing: the <a href='https://ucsdguardian.org/2021/11/21/unbalanced-power-dynamics-in-the-music-industry/' noopener noreferrer target='_blank'>unbalanced publisher-publishee power dynamic</a><a href='#music-industry'>**</a>, the <a href='https://writerbeware.blog/category/vanity-publishing/' noopener noreferrer target='_blank'>proliferation of profiteering pay-for-play vanity publishers</a> (or vanity publishers disguised in the clothing of independent presses), the <a href='https://writerbeware.blog/2024/03/15/the-impersonation-list/' noopener noreferrer target='_blank'>litany of scams that prey on the hope of the aspiring</a>, <a href='https://www.reddit.com/r/books/comments/12g3m5g/how_much_do_authors_actually_make/' noopener noreferrer target='_blank'>pay that amounts to pennies on the hour</a>. The list goes on.</p>
      <Quote 
        text={<>And how is this ecosystem perpetuated? Via statements that anyone who participates in the industry as a creator should be <strong>so grateful</strong> they get to work in a field that lets them follow their passion.</>}
      />
      <p>And how is this ecosystem perpetuated? Via statements that anyone who participates in the industry as a creator should be <em>so grateful they get to work in a field that lets them follow their passion</em>.</p>
      <p>This, I suspect, is the origin of the mantra that reminds creators to write not for the fame or fortune, but rather <a href='https://www.thecrackpotwriter.com/how-do-authors-get-paid/#:~:text=I%20can%20hear,what%20we%20do.' noopener noreferrer target='_blank'>for the love of the written word</a>. I believe this to be a right-minded recommendation, even if many may more shallowly interpret it as commentary on the likelihood of success as opposed to a philosophy that even those who succeed ought to abide.</p>
      <p><em>The Good Enough Job</em> explores these sentiments in a manner that lets readers understand vocational awe in the context of specific industries. The book also recognizes vocational awe as a notion whose very existence becomes an indictment of a culture whose regard for work makes willing sacrifices of those who embrace it, or at least those who embrace it as an extension of the workist philosophy.</p>
      <p>Stolzoff does not stop at merely familiarizing readers with vocational awe, either. Instead, through Ettarh's story and his own commentary, Stolzoff provides a structure for understanding the impact of vocational awe and, critically, how one can find ways to overcome its corrupting effects. In this way, <em>The Good Enough Job</em> is not only a descriptive guide, but a prescriptive one as well, not only with respect to vocational awe, but to enmeshment as well.</p>
      <h2>The Loss of <em>Me</em> in Enmeshment</h2>
      <p>Listeners to <Link to='/podcast/youre-not-your-author-you-featuring-m-a-hinkle-writescast-097/'>the Writescast Network</Link> or visitors to this site (<Link to='/about'>see the extended version of the about page</Link>) will have some familiarity with enmeshment already, even if not by that name.</p>
      <p>Simply put, enmeshment describes the phenomenon of the loss of one's self to the idea of one's self as their career. For example, those affected by enmeshment may fail to draw a distinction between who they are as a person and their identity as, say, a paramedic, author, or software engineer.</p>
      <p><Link to='/about'>I've written about</Link>—or at least hinted at—my experiences with enmeshment as an author, but my acquaintance with enmeshment extends beyond the realm of publishing. As part of my about-face from all things writerly, <a href='/2021/05/15/im-done-writing-for-now-i-promise-you-this-is-okay/#:~:text=I%20Am%20Become%20Hackerman' noopener noreferrer>I ran headfirst into web development</a>, not as a matter of passion, but desperation.</p>
      <p>Having only understood my adult self as one defined by his trade, I found myself falling into the same traps that had ensnared me in my time as an author-first individual. At what point in my web development journey would I no longer be an aspiring engineer? And until I could drop <em>aspiring</em> from that sense of self, what did that mean in the in-between? If I was neither an author nor an engineer then, well, what was I?</p>
      <p>That these questions were asked at all is indicative of the toll enmeshment—and a residual nastiness imposed by a longstanding adherence to vocational awe—can take on an individual's sense of self-worth in a culture so willing to entangle one's career and one's identity.</p>
      <p>However, when Stolzoff writes “we are not born with a fixed identity; it's something we build over time,” I find myself refreshed. It's true, after all: how similar is your sense of identity now to the sense of identity you held at seven, nineteen, or thirty years of age? It's not as if one only comes into an identify of their own upon finding a career; imagine believing a seven-year-old lacks an identity because they haven't yet become a triple-threat astronaut-cowboy-archaeologist. Laughable, right? </p>
      <Quote 
        text="Imagine believing a seven-year-old lacks an identity because they haven't yet become a triple-threat astronaut-cowboy-archaeologist. Laughable, right?"
      />
      <p>If we're willing to accept the notion of identity as malleable, we liberate ourselves relative to a paradigm that encourages one's sense of self to be defined by their occupation and the value one provides to stakeholders.</p>
      <p>I'll point out that enmeshment need not be limited to one's vocation, either. I suspect the inspiration for <a href='https://youtube.com/shorts/PD_J4AGRt1k?si=hzPp_TurZEF-djtH' noopener noreferrer target='_blank'>this Tim Robinson sketch</a> (if you have Netflix and can watch the full version, do) comes from the frequently-reported loss of personal identity associated with parenthood. When one's identity is consumed by the idea of being a parent, what happens when one becomes an empty-nester? Those individuals remain parents, of course, but, well, it's certainly not in the same way as when their children were still at home. And what became of those parents' senses of self while the kids <em>were</em> under their roof?</p>
      <p>Here, again, we see the trappings of enmeshment. Whether via cultural conditioning, biology, or a sense of duty, the outcomes are the same.</p>
      <h2><em>More Than</em> Through Less</h2>
      <p>It would be easy to, given the above, feel as though there is little reason for hope. If we're up against the prevailing narratives of the culture in which we persist—as well as, in the context of parenthood, thousands of years of evolutionary biology—what's to be done when we find ourselves stricken by vocational awe or unsure where we end and our careers begin?</p>
      <p>When <a href='https://www.megangreenwell.com/' noopener noreferrer target='_blank'>Megan Greenwell</a>, the individual profiled for <em>The Good Enough Job</em>'s chapter on enmeshment, says that she wonders “what percentage of [her] drive to work all the time is that [she] truly [loves] it, and how much is that [she doesn't] know what else to do with [herself],” the situation can feel even more dire.</p>
      <p>But it's not all doom and gloom. Cultivating an awareness of these phenomena is an important first step in the journey to reclaiming one's autonomy and sense of self. By subsequently accepting ourselves as <em>more than</em>, we empower ourselves to be defined not merely by what we do for a living or by our relationships to others, but by who we are to ourselves, both now and in the future.</p>
      <Quote 
        text={<>By subsequently accepting ourselves as <strong>more than</strong>, we empower ourselves to be defined not merely by what we do for a living or by our relationships to others, but by who we are to ourselves...</>}
      />
      <p>After all, despite Greenwell's lack of certainty regarding her relationship to work, Stolzoff writes that she still “sleeps, eats, and breathes journalism” but has “taken her foot off the gas [by leaving the industry in a formal capacity] for long enough to find worth in other ways too.”</p>
      <p>And how has she done this? By spending time with family and, as Stolzoff recounts it, “by being a better friend than in any other period of her adult life.”</p>
      <p>So, yes, we can <em>be</em> more without needing to <em>do</em> more. In fact, it's entirely possible that one might have to do <em>less</em> to become <em>more than</em>.</p>
      <p>To do this requires courage, yes, but it's a courage that lies at the heart of all the <em>whos</em> who make our <em>us</em>. That courage can be channeled. It can be directed. It can be the key to unleashing that <em>more than</em> inherent within us all.</p>
      <p>And it can start with the you who is reading this. It can start right now.</p>
      <h2>The Verdict</h2>
      <p>Ultimately, <em>The Good Enough Job</em> does more than a good enough job describing these and many other facets of the struggle to reclaim life from work, and I recommend it to anyone who has ever endeavored to understand themselves as more than any one act, job, or choice.</p>
      <p>I suspect there are at least a few of you out there.</p>
      <div className='footnotes'>
        <p>--</p>
        <p id='anti-work'><em>*For the record, I hold acolytes of the anti-work movement in a fair amount of esteem. That said, as with many other movements on the cutting edge of redefining or reframing deeply entrenched social or cultural narratives, there are a number of boisterous hangers-on who undermine the message and whose volume, I suspect, is increased by those who would see the movement stymied. It's far easier to uphold a prevailing narrative—even one worth questioning—when those who benefit from its hegemony make caricatures of select targets in the counterculture.</em> <br/><a className='bookmark-link' href='#footnote-marker'>back to bookmarked section^</a></p>
        <p id='music-industry'><em>**Yes, this example is taken from the realm of music publication, but, as an "of the arts" industry that is historically difficult to break into without the aid of a record label, the point remains. As it turns out—excepting the obvious abuses at the hands of vanity publishers and outright scammers—it's hard to find individual authors speaking out about their naivete having been taken advantage of by a publisher. This</em> could <em>be because it simply doesn't happen. I can think of at least one other reason why there might be an absence of stories about this, though, too. That said, I'm working on a follow-up post that will explore this in more detail and offer plenty of counterpoints to this assertion as well, so stay tuned.</em> <br/><a className='bookmark-link' href='#footnote-marker-2'>back to bookmarked section^</a></p>
      </div>
    </>
  )
}

export default BookReviewTheGoodEnoughJob
