import React from 'react'

const RRCampbellonWriteThroughtheRoof = () =>
  <div>
    <p style="text-align: center;"><img loading="lazy" decoding="async" data-attachment-id="7080" data-permalink="https://ryanrcampbell.com/2019/10/28/r-r-campbell-on-write-through-the-roof/write-through-the-roof/" data-orig-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/10/Write-Through-the-Roof.jpg?fit=1024%2C512&amp;ssl=1" data-orig-size="1024,512" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="Write Through the Roof" data-image-description="" data-image-caption="" data-medium-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/10/Write-Through-the-Roof.jpg?fit=300%2C150&amp;ssl=1" data-large-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/10/Write-Through-the-Roof.jpg?fit=1024%2C512&amp;ssl=1" class="alignnone wp-image-7080 size-full" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/10/Write-Through-the-Roof.jpg?resize=1024%2C512&#038;ssl=1" alt="" width="1024" height="512" srcset="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/10/Write-Through-the-Roof.jpg?w=1024&amp;ssl=1 1024w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/10/Write-Through-the-Roof.jpg?resize=300%2C150&amp;ssl=1 300w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/10/Write-Through-the-Roof.jpg?resize=768%2C384&amp;ssl=1 768w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2019/10/Write-Through-the-Roof.jpg?resize=624%2C312&amp;ssl=1 624w" sizes="(max-width: 1024px) 100vw, 1024px" data-recalc-dims="1" /></p>
<p style="text-align: center;"><em>“There's no Twitter, no email. The coffee is here. The time has come.”</em></p>
<p>I'm thrilled to share my appearance on Madeleine D'Este's Write Through the Roof podcast.</p>
<p>Write Through the Roof is a podcast that asks writers to share the one thing that took their writing to the next level. With the release of my interview, there are now seventy episodes of the show, which is also distributed in France on Art District Radio as part of its English-language programming.</p>
<p>Though the premise for the show is to encourage writers to share the one thing that most improved their writing, Madeleine and I discussed so much more than that over the course of our half hour conversation, including the interplay between the art and science of language, as well as how an emphasis on generating empathy in our work can lead to longstanding reader-character connections.</p>
<p>To listen in, you can <a href="http://madeleinedeste.com/2019/10/27/70-write-through-the-roof-r-r-campbell/" target="_blank" rel="noopener noreferrer">check out this link</a> or subscribe to Write Through the Roof on any of the platforms below.</p>
<p style="text-align: center;"><a href="https://podcasts.apple.com/au/podcast/write-through-roof-for-writers-who-want-to-improve/id1298910159" target="_blank" rel="noopener noreferrer">Apple Podcasts</a><br />
<a href="https://www.stitcher.com/podcast/write-through-the-roof?refid=stpr" target="_blank" rel="noopener noreferrer">Stitcher</a><br />
<a href="https://www.iheart.com/podcast/263-writethroughtheroof-29825999/" target="_blank" rel="noopener noreferrer">iHeart Radio</a></p>
<p>Thanks so much to Madeleine for having me on her podcast. If you'd like to listen to my interview of her for my own podcast network, you can find that episode <a href="https://writescast.net/2019/07/05/writescast061/" target="_blank" rel="noopener noreferrer">here.</a></p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default RRCampbellonWriteThroughtheRoof
