import React from 'react'

const ItsOkaytoTakeaBreakIPromise = () =>
  <div>
    <p>Between soccer injuries, car wrecks, getting married, and signing my first two publishing contracts, 2018 has been a heck of a year. Throughout it all, I've viewed my daily writing time as one of the only constants in which I could find solace, one of the only things around which I could center myself to get through the day to day.</p>
<p>Or at least that's how I felt about it until the last two weeks forced me to take a break from it all.</p>
<p>I knew this break was coming. I'd been dreading it all year, if I'm honest, and not because of <em>why</em> I'd have to take the break, but that it would be happening at all. What if I failed to meet my deadlines in the lead-up to the time off? What if after two weeks away from my manuscripts, my prose lost its luster? What if the break put me so far behind on blogging and podcasting and preparing for <a href="https://ryanrcampbell.com/books/" target="_blank" rel="noopener">my upcoming releases</a> that the anxiety surrounding getting back into the swing of things left me unable to lift a finger in the direction of any of it?</p>
<p>Or, perhaps worst of all, what if I lost the motivation or passion to write altogether?</p>
<p>That's how deeply rooted my unease became. It wasn't pleasant, no. Not pleasant at all.</p>
<p>But now on the far side of that break&#8212;one that included getting married and a trip across the country to go roast in the desert for a week&#8212;I'm here to report that it's all going to be okay. Better than that, even: I'm now feeling refreshed and invigorated in ways I haven't experienced in months, if not a year.</p>
<div id="attachment_5284" style="width: 10274px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-5284" data-attachment-id="5284" data-permalink="https://ryanrcampbell.com/2018/09/02/its-okay-to-take-a-break-i-promise/img_4417/" data-orig-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/09/IMG_4417.jpg?fit=10264%2C3044&amp;ssl=1" data-orig-size="10264,3044" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;2.2&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;iPhone 6&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;1535537853&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;4.15&quot;,&quot;iso&quot;:&quot;32&quot;,&quot;shutter_speed&quot;:&quot;0.00045495905368517&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;1&quot;}" data-image-title="IMG_4417" data-image-description="" data-image-caption="&lt;p&gt;From our hike near Sedona, Arizona. Sometimes all one needs is a little 108°F (42°C) to set one's mind at ease.&lt;/p&gt;
" data-medium-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/09/IMG_4417.jpg?fit=300%2C89&amp;ssl=1" data-large-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/09/IMG_4417.jpg?fit=1024%2C304&amp;ssl=1" class="alignnone size-full wp-image-5284" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/09/IMG_4417.jpg?resize=1080%2C320&#038;ssl=1" alt="IMG_4417" width="1080" height="320" srcset="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/09/IMG_4417.jpg?w=10264&amp;ssl=1 10264w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/09/IMG_4417.jpg?resize=300%2C89&amp;ssl=1 300w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/09/IMG_4417.jpg?resize=1024%2C304&amp;ssl=1 1024w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/09/IMG_4417.jpg?w=2160&amp;ssl=1 2160w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/09/IMG_4417.jpg?w=3240&amp;ssl=1 3240w" sizes="(max-width: 1080px) 100vw, 1080px" data-recalc-dims="1" /><p id="caption-attachment-5284" class="wp-caption-text">From our hike near Sedona, Arizona, where I learned a little 108°F (42°C) heat can apparently help set my mind at ease.</p></div>
<p>So what is it that led to this reinvigoration? Did I have some religious experience while wandering the desert? Did getting married open some magical portal to a whole new understanding of what it means to be?</p>
<p>No.</p>
<p>Don't get me wrong: both our wedding and the desert were life-changers, but those events and places in and of themselves aren't what's got me feeling more ready than ever to wrap up my revisions of <em>When the Stars Conspire </em>this week. What seems to be making all the difference for me <em>is that I took a break at all</em>.</p>
<p>This isn't the first time this has happened, but it <em>is</em> the first time it's happened since writing went from an anxiety reliever to an anxiety causer for me, which is something with which I was struggling in the background on and off this summer.</p>
<p>Now, though, on the far side of that Big Bad Break I was fearing all year, I'm here to confirm what many might find to be unexpected advice from someone who has generally advocated for developing and sticking with one's writing habit: not only is it okay to take a break, sometimes it's the best thing you can do for your creative endeavors.</p>
<p>This might be something you already know and are actively in the habit of putting to use for yourself. If so, that's great! If, on the other hand, your creative endeavors have you feeling stressed, anxious, or like an all-around curmudgeon, trust me on this one: a break might be the best thing for you.</p>
<p>How long of a break should you take, you ask? What should you do in the time you'd normally spend writing or painting or sculpting?</p>
<p>You don't have to get down on one knee and propose to anyone or spend a week a couple thousand miles away. On the contrary, the amount of time you spend away from your creative work is entirely up to you, as is what you do to fill that time in a way that allows you to relieve the tension in your shoulders.</p>
<p>If you're looking for ideas, <a href="https://anchor.fm/wip-podcast/episodes/24---Relaxing-All-Cool-Outside---the-Podcast-e1kkdb" target="_blank" rel="noopener">consider this episode of the WIP Podcast</a> in which I chatted with fellow creatives Brianna Kienitz and Rey Noble about what we do to, as it's framed in the episode description, <em>chill</em>. Or, if you're the kind of person who's already struck a solid work-chill balance, <a href="http://www.twitter.com/iamrrcampbell" target="_blank" rel="noopener">share your suggestions with me and other writers on Twitter</a>.</p>
<div id="attachment_5285" style="width: 3274px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-5285" data-attachment-id="5285" data-permalink="https://ryanrcampbell.com/2018/09/02/its-okay-to-take-a-break-i-promise/img_4427/" data-orig-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/09/IMG_4427.jpg?fit=3264%2C2448&amp;ssl=1" data-orig-size="3264,2448" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;2.2&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;iPhone 6&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;1535545446&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;4.15&quot;,&quot;iso&quot;:&quot;32&quot;,&quot;shutter_speed&quot;:&quot;0.00080906148867314&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;1&quot;}" data-image-title="IMG_4427" data-image-description="" data-image-caption="&lt;p&gt;There might have been no literal chill in the Sonora Desert, but that didn't mean I couldn't find my inner chill.&lt;/p&gt;
" data-medium-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/09/IMG_4427.jpg?fit=300%2C225&amp;ssl=1" data-large-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/09/IMG_4427.jpg?fit=1024%2C768&amp;ssl=1" class="alignnone size-full wp-image-5285" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/09/IMG_4427.jpg?resize=1080%2C810&#038;ssl=1" alt="IMG_4427" width="1080" height="810" srcset="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/09/IMG_4427.jpg?w=3264&amp;ssl=1 3264w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/09/IMG_4427.jpg?resize=300%2C225&amp;ssl=1 300w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/09/IMG_4427.jpg?resize=1024%2C768&amp;ssl=1 1024w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2018/09/IMG_4427.jpg?w=2160&amp;ssl=1 2160w" sizes="(max-width: 1080px) 100vw, 1080px" data-recalc-dims="1" /><p id="caption-attachment-5285" class="wp-caption-text">There might have been no literal chill in the Sonora Desert, but that didn't mean I couldn't find my <em>inner</em> chill.</p></div>
<p>The lesson is this: despite my fretting over taking time away and my insatiable desire to remain productive for validation if only from myself, <em>I managed to take a two week break and live to tell about it.</em></p>
<p>And tomorrow? Well, tomorrow's a big day. Tomorrow I'm back to the grind, and I couldn't be more excited about it. The rest of the night, though? The rest of the night is for me, my wife, and our cats. I've gotten pretty used to this whole “take a break thing.”</p>
<p>But not too used to it.</p>
<hr />
<p>Want content like this and other updates from author r. r. campbell delivered to your inbox? <a href="https://rrcampbellwrites.us16.list-manage.com/subscribe?u=d5b261c0c9ed58a1907dfdc4e&amp;id=26327b8a65" target="_blank" rel="noopener">You can sign up for the r. r. campbell writes newsletter here!</a> Thanks for visiting.</p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default ItsOkaytoTakeaBreakIPromise
