import React from 'react'

const TheIntersectionofArtandPoliticsPrevailingandCountervailingNarratives = () =>
  <div>
    <p style="text-align: center;"><em>Note: this content first appeared in episode 088 of the R.R. Campbell Writescast (below).</em></p>
<p style="text-align: center;"><iframe loading="lazy" class="castos-iframe-player" src="https://5e010b52a747f5-56133313.castos.com/player/228074" width="100%" height="150" frameborder="0" scrolling="no"></iframe></p>
<p><span style="font-weight: 400;">I’d like to talk, for a moment, about the intersection of art and politics. Why? Because you asked me to. Well, someone did, anyway, and they did so by visiting <a href="http://www.writescast.net/hello" target="_blank" rel="noopener noreferrer">writescast.net/hello</a> and submitting their question for me to tussle with.</span></p>
<p><span style="font-weight: 400;">So let’s check out the full scope of their comment:</span></p>
<blockquote>
<h4><span style="font-weight: 400;">Poets have long been moved by social unrest, as have some nonfiction Writers. Do you think all writers, including fiction have a responsibility through writing and discussion groups to respond to social justice and unrest?</span></h4>
</blockquote>
<p><span style="font-weight: 400;">First of all, thank you to this anonymous question contributor. </span><span style="font-weight: 400;">It's an excellent question.</span></p>
<p><span style="font-weight: 400;">As to whether we have a responsibility</span>—<span style="font-weight: 400;">on that, I’m not entirely sure responsibility figures into it. Why? Because art</span>—<span style="font-weight: 400;">particularly wordcraft</span>—i<span style="font-weight: 400;">s often inherently political.</span></p>
<h3>Social Responsibility in Fiction: Two Case Studies</h3>
<p>To explore this, we'll use two unique lenses, namely those of my debut novel, <em><a href="https://www.amazon.com/dp/1949909387/" target="_blank" rel="noopener noreferrer">Accounting for It All</a></em>, and the first two books in my science fiction saga, the <a href="https://ryanrcampbell.com/2020/07/23/imminent-dawn-named-as-finalist-in-2020-international-book-awards/" target="_blank" rel="noopener noreferrer">International Book Awards finalist</a> <em><a href="https://www.amazon.com/dp/1949909980" target="_blank" rel="noopener noreferrer">Imminent Dawn</a> </em>and its sequel, <em><a href="https://www.amazon.com/dp/1950412644/" target="_blank" rel="noopener noreferrer">Mourning Dove</a></em>.</p>
<p>Let's start with <em>Accounting for It All</em>. For those who are unfamiliar, it's the s<span style="font-weight: 400;">tory of an adult-film star turned accountant who finds herself mired in an IRS audit of a money laundering scheme she had no idea she was part of.</span></p>
<p><span style="font-weight: 400;">If you're thinking a novel like this would be rife with opportunities to explore matters of social justice, the treatment of society’s most vulnerable, educational discrepancies and how they affect interactions with the government and other groups—among other topics—you're right!</span></p>
<p><span style="font-weight: 400;">That’s why, for <em>Accounting for It All</em>, I deliberately chose to embrace the intersection of art and politics or social justice. </span></p>
<p><span style="font-weight: 400;">That said, rather than rely on society’s <strong>prevailing narratives</strong> about those who work in pornography and sex work, I chose to research <strong>countervailing narratives</strong> that I could use to buoy the themes I wanted to explore and the point I wanted to make about the nature of self-actualization.</span></p>
<p><span style="font-weight: 400;">Okay, so a lot of big stuff there. Why don’t we break that down further so we can better understand how we might approach this in our own work?</span></p>
<p><span style="font-weight: 400;">First, let's examine prevailing and countervailing narratives. Let’s define and discuss.</span></p>
<h3>Prevailing Narratives</h3>
<p><span style="font-weight: 400;">Let's begin with prevailing narratives. These are the stories that a culture tends to tell itself about itself. These often come in the form of value statements or morals that are, intentionally or not, seen as prescriptive. <strong>To deviate from these prevailing narratives is, in the eyes of the supposed majority, to betray the values of society itself and to risk becoming an outcast.</strong></span></p>
<p><span style="font-weight: 400;">Where </span><i><span style="font-weight: 400;">Accounting for It All </span></i><span style="font-weight: 400;">is concerned, the prevailing narratives against which our main character, Robin, finds herself pitted are those with which many of us are familiar: that those who partake in the consumption or production of pornography—or otherwise participate in sex work—are deviants, destitute, otherwise unfit to be embraced by society writ large.</span></p>
<p><span style="font-weight: 400;">In other words, our society has instituted and maintained a series of statements about itself and its values that cast aspersions on those who participate in this line of work. The prevailing narrative is one that says, “Hey, we don’t like this and we don’t like </span><i><span style="font-weight: 400;">you</span></i><span style="font-weight: 400;">.”</span></p>
<h3>Countervailing Narratives</h3>
<p><span style="font-weight: 400;"><strong>Countervailing narratives</strong>, on the other hand, <strong>are those that challenge society’s prevailing narratives.</strong> These are the narratives that come to the fore at times of social unrest, during protests, or oftentimes form the basis for petitions or challenges to long-standing legal or cultural precedent. </span></p>
<p><span style="font-weight: 400;">In </span><i><span style="font-weight: 400;">Accounting for It All</span></i><span style="font-weight: 400;">, the primary countervailing narrative can be distilled into a single thematic statement: namely, that there are countless paths one might take to self-actualization, but so long as one can find happiness and become the best version of themselves that they can, that’s enough—society’s expectations be damned.</span></p>
<p><span style="font-weight: 400;">In this way, then, I made an </span><i><span style="font-weight: 400;">active choice </span></i><span style="font-weight: 400;">when writing </span><i><span style="font-weight: 400;">Accounting for It All</span></i><span style="font-weight: 400;">: I would choose to research, ruminate on, and then write about countervailing narratives surrounding pornography and sex work, and then explore the interplay between society’s prevailing and countervailing narratives through the experiences of my main character, Robin, a young woman from middle America who, feeling desperately out of place among the circumstances in which she was raised, pursues a career in front of and later behind the camera.</span></p>
<p><span style="font-weight: 400;">Now, was this exploration an easy one to do? No. As one might expect, it’s challenging to find people who are willing to talk about or argue in favor of society’s countervailing narratives when it comes to topics as sensitive as these.</span></p>
<p><span style="font-weight: 400;">And, after having written this book, seeing it published, and having some distance between myself and the time at which I wrote it, do I still agree with every presentation I made, with every argument I took up, with every facet of the story I chose to include in order to present these countervailing narratives? I don’t know.</span></p>
<p><span style="font-weight: 400;">But here’s the thing: <strong>my thoughts on it now don’t really matter</strong>. The readers’ thoughts, however, </span><i><span style="font-weight: 400;">do</span></i><span style="font-weight: 400;">. </span></p>
<h3>Readers and Their Reality</h3>
<p><span style="font-weight: 400;">In presenting </span><i><span style="font-weight: 400;">Accounting for It All </span></i><span style="font-weight: 400;">as I have, I’m offering readers the opportunity to engage with prevailing and countervailing narratives in a private space and in a fictional world. </span></p>
<p><span style="font-weight: 400;"><strong>The conclusions they choose to reach are for them and them alone</strong>; I factor little into how they ultimately interact with that which I wrote. The best I could—and did, hopefully—do, was to write a story that lets the world know these countervailing narratives exist and that there are people out there who are—happily, I might add—actively living them every day. What readers choose to do with these presentations in the end is completely up to them. </span></p>
<h3>Not All Manuscripts Are the Same</h3>
<p><span style="font-weight: 400;">That brings me, actually, to the first two books in my EMPATHY sci-fi saga, <em>Imminent Dawn</em> and <em>Mourning Dove</em>.</span></p>
<p><span style="font-weight: 400;">For these books, my process was vastly different than the one I employed for </span><i><span style="font-weight: 400;">Accounting for It All</span></i><span style="font-weight: 400;">. In these, I had no overt political statement to make or social exploration to perform.</span></p>
<p><span style="font-weight: 400;">Instead, I wanted to focus on this speculative world in which humankind was going through the first round of human trials for an internet-access brain implant. </span></p>
<p><span style="font-weight: 400;">My goals with the EMPATHY series were to put entertainment—things like incredible twists and spellbinding suspense—first and foremost. </span><span style="font-weight: 400;">And this stance is an absolutely valid one to take!</span></p>
<p><span style="font-weight: 400;">But here’s the thing: as I started writing and as readers started reacting, it was apparent that, yes, even in the EMPATHY series, the dilemmas our characters face create situations where readers inevitably must tussle with moral conundrums that, at times, enter into a political space.</span></p>
<p><span style="font-weight: 400;">Consider even just one of <em>Imminent Dawn</em>’s perspective characters, the ruthless tech magnate, Wyatt Halman. In his very first chapter, he’s rebuffing attempts from the North American Union government to gain access to the EMPATHY internet-access brain implant he’s developing.</span></p>
<p><span style="font-weight: 400;">This scene alone is teeming with political underpinnings and statements about the prevailing and countervailing narratives our society tells itself about the nature of power, what it means for something to be in “the greater good,” and whether one person’s ambition should override the will of the people via a government that, at least in theory, has been elected by popular vote.</span></p>
<p><span style="font-weight: 400;"><strong>Whether I want this subtext to be in those scenes or not, it’s there</strong>. That the North American Union government exists at all is, in some ways, a political statement of sorts. In other words, the very existence of an alternative government structure forces readers to contend with the possibilities and the problems that might create, and the work, then, wades into the intersection of realms of politics and social justice.</span></p>
<p><span style="font-weight: 400;">And these explorations need not always be political for us to find ourselves at the crux of colliding prevailing and countervailing narratives.</span></p>
<h3>Prevailing and Countervailing Narratives as Moral Dilemmas</h3>
<p><span style="font-weight: 400;">Consider later in </span><i><span style="font-weight: 400;">Imminent Dawn</span></i><span style="font-weight: 400;">, when our ruthless tech magnate Wyatt must tussle with the question of whether to shut down his research study. It’s not exactly going according to plan, and that lives very well might be at risk presents an extraordinary conundrum for him: does he shut down the study and forfeit any possibility of ushering in a new age of enlightenment, or does he press on in the name of progress and risk losing lives along the way?</span></p>
<p><span style="font-weight: 400;">I think our society’s prevailing narrative would suggest the study ought to be shut down, but if a new age of peace and understanding might await on the far side of the trials if they proceed, might it not be worth the loss of a few lives to see that through?</span></p>
<p><span style="font-weight: 400;">I don’t know. Wyatt, however, has to make a decision, and when he does, readers no doubt are left with strong feelings about him one way or the other, and the ensuing unrest and years-long battles in the name of social justice inevitably consume much of </span><i><span style="font-weight: 400;">Imminent Dawn </span></i><span style="font-weight: 400;">and </span><i><span style="font-weight: 400;">Mourning Dove </span></i><span style="font-weight: 400;">as those novels proceed.</span></p>
<h3>So What Does This Mean for Us?</h3>
<p><span style="font-weight: 400;">The point is this: whether we have a responsibility to explore topics related to prevailing and countervailing narratives, moral proclamations, social justice, or unrest in our work is, in some ways, beside the point. </span></p>
<p><span style="font-weight: 400;">No matter what we choose to write about, our work will, to some extent, inevitably find itself confronting tough questions. </span></p>
<p><span style="font-weight: 400;">Because that’s fiction. That’s art. And as artists, that’s what we do.</span></p>
<hr />
<p style="text-align: center;"><em>A version of this content first appeared in episode 088 of the R.R. Campbell Writescast. <a href="https://link.chtbl.com/writescast" target="_blank" rel="noopener noreferrer">Click here to subscribe to these episodes and never again miss conversations like these.</a></em></p>
<p style="text-align: center;"><em>If you prefer to receive this content in blog or newsletter format, you can <a href="http://eepurl.com/dhBxcv" target="_blank" rel="noopener noreferrer">subscribe to my biweekly newsletter here.</a></em></p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default TheIntersectionofArtandPoliticsPrevailingandCountervailingNarratives
