import React from 'react'

const WritescastRaconteursWhatstheUnitofMeasurementforCompleteEvisceration = () =>
  <div>
    <p style="text-align: center;"><em>This is part thirteen of the misadventures of the <a href="http://www.rrcampbellwrites.com/podcasts">Writescast</a> Raconteurs. For more on what this is and why it’s happening, feel free to check out the <a href="https://ryanrcampbell.com/writescast-raconteurs/">Writescast Raconteurs home page</a>.</em></p>
<h1>Scoreboard</h1>
<div id="attachment_4733" style="width: 977px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-4733" data-attachment-id="4733" data-permalink="https://ryanrcampbell.com/2017/11/27/writescast-raconteurs-whats-the-unit-of-measurement-for-complete-evisceration/week-12-score/" data-orig-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/11/week-12-score.png?fit=967%2C481&amp;ssl=1" data-orig-size="967,481" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="week 12 score" data-image-description="" data-image-caption="&lt;p&gt;Waiver Warriors? More like Waiver Check-the-score-iors. Or something.&lt;/p&gt;
" data-medium-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/11/week-12-score.png?fit=300%2C149&amp;ssl=1" data-large-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/11/week-12-score.png?fit=967%2C481&amp;ssl=1" class="alignnone size-full wp-image-4733" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/11/week-12-score.png?resize=967%2C481&#038;ssl=1" alt="week 12 score" width="967" height="481" srcset="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/11/week-12-score.png?w=967&amp;ssl=1 967w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/11/week-12-score.png?resize=300%2C149&amp;ssl=1 300w" sizes="(max-width: 967px) 100vw, 967px" data-recalc-dims="1" /><p id="caption-attachment-4733" class="wp-caption-text">Waiver Warriors? More like Waiver Check-the-score-iors. Or something.</p></div>
<p>Well, I finally came out on the right side of a drubbing. Not only that, but with all of our players' games having wrapped up on Sunday, I can post this week's results before our records are updated. I'm actually at 5-7 now, which actually gives me an outside shot at the playoffs if I manage to win next week and a few other things go my way.</p>
<p>Next week may prove difficult, though, since production from Jamaal Williams may decrease if Ty Montgomery returns, and Amari Cooper took a devastating hit in his game and may likely miss next week due to a concussion. Rex Burkhead also did great work this week, but I doubt that'll keep up two weeks in a row.</p>
<p>Who knows? Maybe I'll get lucky, though, and we'll sneak into the playoffs where anything can happen.</p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default WritescastRaconteursWhatstheUnitofMeasurementforCompleteEvisceration
