import React from 'react'

const WritescastRaconteursEveryDogHasItsDay = () =>
  <div>
    <p style="text-align: center;"><em>This is part twelve of the misadventures of the <a href="http://www.rrcampbellwrites.com/podcasts">Writescast</a> Raconteurs. For more on what this is and why it’s happening, feel free to check out the <a href="https://ryanrcampbell.com/writescast-raconteurs/">Writescast Raconteurs home page</a>.</em></p>
<h1>Scoreboard</h1>
<div id="attachment_4725" style="width: 980px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-4725" data-attachment-id="4725" data-permalink="https://ryanrcampbell.com/2017/11/22/writescast-raconteurs-every-dog-has-its-day/scoreboard-12/" data-orig-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/11/scoreboard-12.png?fit=970%2C485&amp;ssl=1" data-orig-size="970,485" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="scoreboard 12" data-image-description="" data-image-caption="" data-medium-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/11/scoreboard-12.png?fit=300%2C150&amp;ssl=1" data-large-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/11/scoreboard-12.png?fit=970%2C485&amp;ssl=1" class="alignnone size-full wp-image-4725" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/11/scoreboard-12.png?resize=970%2C485&#038;ssl=1" alt="scoreboard 12.png" width="970" height="485" srcset="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/11/scoreboard-12.png?w=970&amp;ssl=1 970w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/11/scoreboard-12.png?resize=300%2C150&amp;ssl=1 300w" sizes="(max-width: 970px) 100vw, 970px" data-recalc-dims="1" /><p id="caption-attachment-4725" class="wp-caption-text">Whatever works.</p></div>
<p>The team managed a respectable score this week, which makes this win all the sweeter since I actually didn't simply scrape by after my opponent's squad somehow did more poorly than my own team.</p>
<p>I can also feel good about not having traded with this week's opponent after he offered up Alex Smith and Matt Forte for Russell Wilson and Ted Ginn, Jr. a few weeks back. That alone could have meant defeat in this match-up.</p>
<p>Basically, it's still not impossible for me to sneak into the playoffs if I win out and some other teams stumble, but I'm not counting on it. The new goal? WIN THE CONSOLATION LADDER. WE CAN DO IT. ANYTHING IS POSSIBLE.</p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default WritescastRaconteursEveryDogHasItsDay
