import React from 'react'

const MagicBeansWhatTheyAreandWheretoPlantThem = () =>
  <div>
    <p style="text-align: center;"><em>This post is part of the </em>Write With Me<em> series. For more like this, check out the <a href="https://ryanrcampbell.com/writing-your-novel/">writing your novel</a> page.</em></p>
<p>Magic beans aren't just for planting. Most of them don't even grow into beanstalks. In fact, nearly all of them aren't even beans, or magic for that matter.</p>
<p>So what am I going on about?</p>
<p>I'm talking about superstition and mythos–and how you can use them to make your story and characters that much more memorable.</p>
<p>Over the weekend, I had the opportunity to attend a session by Christine DeSmet, author of the <a href="https://www.amazon.com/First-Degree-Fudge-Shop-Mystery/dp/0451416473/ref=sr_1_3?ie=UTF8&amp;qid=1478558069&amp;sr=8-3&amp;keywords=christine+desmet" target="_blank" rel="noopener noreferrer"><em>Fudge Shop Mystery</em> series</a>. Among the many topics covered, one that I found particularly elucidating was the notion of a magic bean, which is something about a character that inspires some sort of awe or wonder in the reader.</p>
<p>Magic beans can take many forms, from physical objects to pieces of music to recurring numbers or colors or phrases. What makes magic beans so useful is that they can really deepen the emotional underpinnings of your story, and also give depth to your characters even you may not have previously realized they had.</p>
<p>Though Christine's session included a number of literary examples, I'd like to focus on one of my own from film for the purposes of this post.</p>
<p>So, today, friends… we're talking <i>Inception</i>.</p>
<p>Whatever your opinion of this movie might be, it's hard to deny how memorable it is. When recalling it, what are the first things that come to mind?</p>
<p>Dreams? Check.<br />
Leo? Check.<br />
That little spinny top thing? Big check.</p>
<p>That little spinny top thing&#8212;or, as it's called in the film, a totem&#8212;is a prime example of the so-called magic bean.</p>
<p>Even the thought of the totem ought to trigger a memory of that final moment&#8212;the top spinning spinning spinning, and Cobb (DiCaprio) eyeing it before accepting that whether it toppled or not, he could go on living happily in whatever reality he ultimately found himself. Ugh. I get chills just thinking about it. But what makes this moment&#8212;centered on a simple, revolving piece of metal&#8212;so powerful? Let's explore.</p>
<h1>The Totem (Magic Bean) Does Three Things</h1>
<h2>Explains Plot</h2>
<p>One of the first things the inclusion of the totem does is to enrich and add to the plot. When Cobb is first seen using it, we as viewers are just as mystified the concept as Ariadne (Ellen Page). Fortunately, we have Arthur (Joseph Gordon-Levitt) to break down the concept for us viewers and Ariadne all at once, as seen in <a href="https://www.youtube.com/watch?v=PKvnRSKUgC4&amp;w=320&amp;h=266" target="_blank" rel="noopener noreferrer">this clip</a>.</p>
<p>Through the use of the totem in this scene, we as viewers receive critical information about what this magic bean can do in order to help characters discern between dreams and reality. As magic beans, the totems in <i>Inception</i> have clear import and clear rules governing them, regardless of what shape they might take.</p>
<p>While creating your magic bean, however, keep in mind that it doesn't need to necessarily play by the same rules as totems do in <i>Inception</i>. For example, one of my characters in my WIP has a song as her magic bean. The first time she “hears” it,  it's simply repeating over and over in her head, and she isn't quite sure why or even what song it is. She does feel an inexplicably deep connection to it, however, and as the song revs up for another repetition&#8212;bam! Readers are struck with the first plot point.</p>
<p>The magic bean I'm implementing for this character does not relate to the rules governing the world, but it <i>does</i> create a sense of mystery. Why did she hear <i>that</i> song? What song was it, anyway? Will she ever get answers to either of these questions?</p>
<p>The answer is yes, but those come later&#8212;when the magic bean is used for purposes beyond thickening the sense of mystery surrounding a key plot point.</p>
<h2>Builds Relationships</h2>
<p>Magic beans are also fantastic ways to augment the relationships between characters. In the above scene in <i>Inception</i>, for example, having the concept of the totem explained to her allows Ariadne to become a more complete member of the team. Having one's own totem is a bit of a rite of initiation for our dreaming (dreamy?) heist squad as well.</p>
<p>A crucial way that the Cobb's totem builds relationships in <i>Inception</i> is by deepening the connection between him and his deceased wife, Mal (Marion Cotillard). <a href="https://youtu.be/3B_YubBVOAY?t=33s">Here's the relevant portion</a> of the clip in question.</p>
<p>When we see Mal locking away the top that becomes Cobb's totem, the mystique of this particular magic bean becomes even deeper. As a tool, it is now not only useful in helping him determine whether he is still dreaming, it is also tied not only to the haunting memory of what became of his wife, but also his central goal of being reunited with his children.</p>
<p>Building on this example, let's turn back to the example from my own WIP&#8212;the song my protagonist hears just before the first plot point.</p>
<p>In a later scene, she hears the song once again&#8212;though this time, out loud. Following its sound, the song leads her to her first ally, who happened to use this song in the soundtrack for a video game he created. Furthermore, when she finally recognizes the tune for what it is, my protagonist also realizes the reason it sounded so familiar was because her wife used to play the game all of the time and hum the tune nonchalantly to herself when not playing it.</p>
<p>The relationship my protagonist has with this song (and the one her wife has with it, as well), help my protagonist to trust this possible newfound ally more quickly. It also deepens the relationship between her and her wife for readers, as they get deeper insight into the relationship between the two of them.</p>
<p>All of this may be fine and good, but there's one last way in which magic beans can be used to maximize their impact with a final knockout blow.</p>
<h2>Deepens Emotion</h2>
<p>Any magic bean worth its weight will carry with it a gravitas so immense that readers or viewers can't help but feel connected to it emotionally. Where <i>Inception</i> is concerned, I'm of course talking about <a href="https://youtu.be/khYx7P2t59I?t=3m20s">the final shot of the film.</a></p>
<p>That's right&#8212;that final scene I referenced earlier, the one in which Cobb produces the totem in an attempt to figure out if the reality in which he finds himself is too good to be true. This moment is so powerful emotionally because this magic bean has become connected to 1) the ultimate success or failure of the protagonist's main goal, and 2) the impact of his success or failure via the emotional relationship Cobb has to the device.</p>
<p>Think of how different the end of this movie would be without the inclusion of that final shot. Now think about how different the movie would be if it didn't include totems at all. It wouldn't have been particularly difficult for the writers and producers to develop some other sort of test for whether one is dreaming or awake, and Mal and Cobb's relationship was already rather rich without the introduction of the totem that Cobb inherited from her after she died.</p>
<p>Including the totem as a magic bean, however, opened up all of the possibilities described throughout this post, however, and I'm sure many more I don't have the opportunity to cover here.</p>
<p>In my WIP, the song that serves as my protagonist's magic bean has an eerily similar connection to the book's final scene as the totem does for Cobb at the end of <i>Inception</i> (I didn't even realize this until writing this post, I swear). As my protagonist hears this song again, it triggers a previously inaccessible memory of her and her wife, and also suggests that she as the protagonist may not have actually lost as much of herself as previously advertised in the chapters leading to the conclusion. I'd go into more specifics, but, you know, I don't want to give too many spoilers (especially for my beta readers!).</p>
<h1>Summary</h1>
<p>Whether it's a totem, a song, a stuffed animal, or even another character, employing the use of so-called magic beans can go a long way into creating a more robust plot with deeper relationships between characters and greater emotional depth.</p>
<p>If you're struggling to come up with a magic bean for a character of yours, try this exercise: think of a place that is important to your character. In this location, they have a secret stash where they keep all of the things that are most important to them. What is the location? What is the storage device for all these objects? What are the objects specifically? What makes them worthy of being in the secret stash?</p>
<p>Just try to brainstorm using the above exercise. Don't stop writing until, say, two minutes are up. If you know your character well enough, you'd be surprised the things this exercise reveals to you. Don't believe me? Give it a try and find out for yourself.</p>
<p>If your character already has a magic bean of their own, what is it? How do they employ it over the course of the manuscript? Hit me up on <a href="https://twitter.com/iamrrcampbell" target="_blank" rel="noopener noreferrer">Twitter </a>or email me through my <a href="https://ryanrcampbell.com/contact/">contact page</a> to join the conversation.</p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default MagicBeansWhatTheyAreandWheretoPlantThem
