import React from 'react'

const YouveFinishedYourFirstManuscriptNowwhat = () =>
  <div>
    <p style="text-align: center;"><em>This post is part of the </em>Write With Me<em> series. For more like this, check out the <a href="https://ryanrcampbell.com/writing-your-novel/">writing your novel</a> page.</em></p>
<p>First of all, congratulations! There are so many people who take on the challenge of writing a novel, only to constantly start over or abandon the project entirely. If you've made it start to finish, you're already on the right track to (maybe) holding your book-baby in your arms.</p>
<p>But how do you get to the proud moment where you can flip through the pages of all your hard work? It's a long and winding road, one that is a little different for all writers. There are two people we can pull in for advice on the matter, however.</p>
<p>One of them is me. I'll tell you what <i>not</i> to do, based on my own experience.</p>
<p>The bearer of sage advice, is, well Vanilla Ice.</p>
<p>In his 1990 definitely-not-a-ripoff-of-Queen hit<i> </i>“Ice Ice Baby,” Vanilla Ice utters words which will be remembered until the end of days–<i>stop, collaborate, and listen</i>.</p>
<p>Little did he know then that those three words would provide perhaps some of the greatest advice any beginning writer should take into consideration after completing their first novel. Let's see how they apply below.</p>
<h1>Stop</h1>
<p>The number one mistake any beginning writer can make at this stage is, in my opinion, to not take a step away from their manuscript for a time.</p>
<p>The difficult truth is, your book-baby is a lot like everyone else's book-baby after a first draft. With the right care, it <i>could</i> become a star athlete or a true-to-self artist or a wonderful teacher, but how you raise (read: edit) your book-child has an immense effect on its ability to reach its full potential. If it were a real child, you couldn't just kick it out into the world and hope someone else would raise it for you, appreciating the potential it holds within its genes. You have to put in the work to help shape that potential.</p>
<p>What many take from this, of course, is that one must smother their book-baby with love and attention. If only they do enough editing, if only they make sure they differentiated their thans and thens and they'res, theirs, and theres, their book-baby will be on the path to glory, right?</p>
<p>Wrong&#8212;thus spoke Vanilla Ice.</p>
<p>It may be hard to do, but you need to STOP for a specific amount of time. Maybe it's a week or a month or half a year, but you need time away so you can come back to it with a renewed perspective. Your book-child will benefit from this space, and so will you. You're not abandoning it, you're just letting it reveal its best self to you.</p>
<p>When the completion of my first manuscript was in sight, I did everything in my power to ensure I had a “finished” copy in my hands before an upcoming writers' conference in my area. I was positive that the manuscript's premise alone would guarantee me a book deal, and after three extremely validating pitches to literary agents during the conference, I had every reason to believe my initial hunch was correct.</p>
<p>One of the agents with which I met requested a full manuscript immediately. Another one asked for the first fifty pages. The third, not really a literary agent but more of a TV/film type, told me to contact her personal assistant “when” (not <i>if</i>, but <i>when</i>) I got my book deal. She wanted to acquire the visual media rights!</p>
<p>As one might imagine, I was pie-in-the-sky elated. My book-baby was unique! My book-baby was special! My book-baby was going to be the one that defied all odds.</p>
<p>I read the entire manuscript over one more time (yes, only one more time), before sending off the requested pages. A month passed. Then another. One agent never got back to me, even after attempts to follow up. The other did after a few months, confirming my worst fears–they still loved the premise, but the writing just didn't bring it home for them.</p>
<p>I was devastated.</p>
<p>As I reread my manuscript trying to figure out where I went wrong when birthing my book-baby, I realized that all of that agent's criticisms were spot on. My characters didn't take center stage. The action took too long to develop. My prose was clunky and overwritten.</p>
<p>Those weren't this agent's words (this agent was much nicer to me than I was to myself), but the lesson was clear: my book-baby just wasn't ready to be a star quarterback. My book-baby wasn't even ready to tie its shoes. I don't even know if I gave it shoes, to be honest. I was a bad bookdad.</p>
<p>So what should I have done? Number one, I shouldn't have rushed the “final” product. I should have listened to Mr. Ice. I should have STOPped and given myself a chance to come back to the manuscript at a time when I wasn't so attached to it emotionally.</p>
<p>But stopping alone wouldn't have been enough to save this book-baby, oh no. And it may not enough to save yours. That's why it's also important to follow through to step number two.</p>
<p style="text-align: center;"><em>Bonus post: Trying to figure out what to do with yourself once you've set your book-baby aside for a time? <a href="http://ryanrcampbell.com/2017/04/30/youre-between-novels-now-what/" target="_blank" rel="noopener noreferrer">This post</a> can help!</em></p>
<h1>Collaborate</h1>
<p>All parents love their book-babies. Well, maybe not all. Sometimes we write something that we know is garbage, but in my experience those are rarely the projects we finish. Chances are that if you stuck out a manuscript long enough to finish it with “END,” you're taking some pride in it, at least.</p>
<p>And pride, well… pride will leave you blind. That's why collaboration is key to helping you coach your book-baby through its first steps.</p>
<p>“But writing is a solitary art,” you might say. You wouldn't be wrong to say that, but the world of editing and publishing is anything but solitary.</p>
<p>There are a handful of ways to collaborate with others in order to make your book-baby the best that it can be. Beta readers are a fantastic place to start. For those of you unfamiliar with the term, beta readers are those who get the distinct privilege (read: horror) of seeing your completed copy.</p>
<p>Beta readers should be chosen wisely. Your mom might love you, but unless she's also a literary agent, she's probably not the best person to provide advice on what you can do to improve your work. The same goes for significant others and close friends. Instead, you should seek the feedback of people who are a 1) avid readers, and 2) not going to sugar-coat their criticism for fear of damaging a personal relationship.</p>
<p>Where do you find readers like that, you ask? A <a href="http://aprildavila.com/beta-readers/" target="_blank" rel="noopener noreferrer">fantastic blog post</a> from <a href="https://twitter.com/aprildavila" target="_blank" rel="noopener noreferrer">April Dávila </a> can help guide you through the selection process, as well as how to process the feedback you receive.</p>
<p>Another great resource for collaboration is to enlist the help of other writers. If you're not in a writers' group already, I highly recommend you try to find one in your area. When attended regularly, the sort of critique you can receive (and provide!) in a writers' submission group can go a long way into helping you become a more informed reader, writer, and editor. You might be surprised what other creative-types have to say about your work. Some of the best suggestions I have received have come from the group I've been attending for four years now.</p>
<p>If you're unsure how to find or start a group in your area, check out <a href="http://thewritelife.com/join-writing-group/" target="_blank" rel="noopener noreferrer">this post</a> from <a href="https://twitter.com/bigstatebiglife" target="_blank" rel="noopener noreferrer">Lorena Knapp</a>, which has eight great suggestions for ways to meet <span style="text-decoration: line-through;">singles</span> writers in your area.</p>
<p>After reading the above, one might say, “Hold up, r.r., <i>you</i> were in a writers' group but still managed to blow it. How is that possible?”</p>
<p>Well, dear reader, there are many reasons why a manuscript doesn't gain traction, and one of them is because sometimes those manuscripts are written by me. Seriously though, the version of me that had just finished his novel had already been in the writers' group for almost two years. I had run my entire novel through the group, all the while receiving consistent feedback like “ease up on the purple prose” and “these character actions don't seem organically motivated” and “you spent an entire paragraph describing a handshake.” I heard all of these things and made some (very minor) attempts to correct them.</p>
<p>At the end of the day though, I told myself that I knew better than everyone else. I had a clear vision! I knew what was best for the story! I was going to bridge the gap between literary and genre fiction like no one had before!</p>
<p>It turned out none of those things were true. I was just a real [redacted].</p>
<p>If I had taken more of that criticism to heart and actually invested the time to understand where those writers and friends were coming from, I could have maybe (read: definitely not) salvaged that initial draft.</p>
<p>This brings me to Vanilla Ice's final, and perhaps most important, point.</p>
<h1>Listen</h1>
<p>After the previous section, it should be apparent that two of the groups you should be listening to are your beta readers and your trusted group of writers. It's probably not a huge issue if one individual in either of these groups doesn't understand the importance of a scene, but if more than one person makes the same complaint, you're going to want to start considering that advice. You're asking them to provide feedback for a reason, right? Use it to your advantage.</p>
<p>The most important folks you can listen to, however, are your <i>characters</i>.</p>
<p>If you've taken your time to create character profiles and have developed a deep understanding of who they are as people, you <i>need</i> to trust them to guide you through your manuscript. If someone were to ask you, “Hey, what's Character A's goal in this scene?” and you don't have an answer right away, you don't know your characters well enough. If that same person were to say, “What is Character B's fatal flaw?” and you don't have an answer to that, either, you need to spend some time with your characters (in your head or on the page–outside your primary manuscript) and get to know them better.</p>
<p>If your characters aren't the center of your story, it will almost certainly fall flat. The words you are putting on the page can't be thought of as yours as much as they are those of your characters. Who were these people before the story began, and who will they be after the story ends? I'm not talking about their backstory or the wiggle room you're trying to leave yourself for a sequel, I'm talking about the one toy they loved above all others when they were kids. I'm talking about their first experience with water. What was their reaction the first time they heard and saw fireworks? Awe? Fear? Something in between?</p>
<p>The above may seem irrelevant and convoluted, but asking these questions of your characters and then listening to their responses will guide you down the path to a more smooth and coherent manuscript.</p>
<p>Don't do what I did with my first novel: throw caution to the wind and force my characters into situations that suited the outcome I desired as the writer. This can only lead you down a path of logical fallacies and inconsistent behavior. Woof.</p>
<p>So, once you type the magical (and completely false) word END on your work's final page, don't immediately start querying agents or hustling it through the indie publishing process. “Future You” will thank “Now You” if you heed Vanilla Ice first.</p>
<h1><strong>Summary: Stop. Collaborate. Listen.</strong></h1>
<p>If you manage to do these three steps after completing your manuscript, after a few months (or years) or taking time to improve, you may find yourself back with brand new invention (read: manuscript).</p>
<p>&#8212;</p>
<p>Looking for more writing tips on the daily? Follow me on <a href="https://twitter.com/iamrrcampbell" target="_blank" rel="noopener noreferrer">Twitter</a>! Have a question or just want to reach out? You can always get a hold of me through my <a href="http://ryanrcampbell.com/contact/">contact page</a>.</p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default YouveFinishedYourFirstManuscriptNowwhat
