import React from 'react'

const EMPATHYonTourThankYouEauClaire = () =>
  <div>
    <p>The EMPATHY spring and summer tour continued last weekend with an event at Dotters Books in Eau Claire! I had a wonderful time visiting this new, blossoming bookstore in the heart of the Chippewa Falls area. Thank you, Dotters, for hosting!</p>
<p>Prior to the event, my wife and I were able to visit a number of local mainstays, including Phoenix Park, Tangled Up in Hue, The Local Store, Ramone's, the Acoustic Cafe, and more. Eau Claire really is a beautiful city, and I definitely recommend anyone in the area or passing through stop to take at least an afternoon to enjoy all Eau Claire has to offer.</p>
<p><a href="http://www.empathyseries.com/events">The EMPATHY tour</a> will continue on Memorial Day weekend with my visit to <a href="http://www.wiscon.net">WisCon 43 in Madison, Wisconsin</a>, but, until then, here are some of my favorite photos from last weekend's event!</p>
<div id="attachment_891" style="width: 4042px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-891" class="alignnone size-full wp-image-891" src="https://empathynovel.files.wordpress.com/2019/05/image2-1.jpeg?resize=1080%2C810" alt="image2" width="1080" height="810" data-recalc-dims="1" /><p id="caption-attachment-891" class="wp-caption-text"><em>Imminent Dawn</em> already had a home on the shelves before I arrived!</p></div>
<div id="attachment_894" style="width: 2754px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-894" class="alignnone size-full wp-image-894" src="https://empathynovel.files.wordpress.com/2019/05/image2-ec.jpeg?resize=1080%2C1441" alt="image2 EC" width="1080" height="1441" data-recalc-dims="1" /><p id="caption-attachment-894" class="wp-caption-text">Letting a pause linger at a tense moment during one of the evening's readings.</p></div>
<div id="attachment_892" style="width: 3034px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-892" class="alignnone size-full wp-image-892" src="https://empathynovel.files.wordpress.com/2019/05/image3-1.jpeg?resize=1080%2C1440" alt="image3" width="1080" height="1440" data-recalc-dims="1" /><p id="caption-attachment-892" class="wp-caption-text">The setup at the store's entrance.</p></div>
<div id="attachment_893" style="width: 760px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-893" class="alignnone size-full wp-image-893" src="https://empathynovel.files.wordpress.com/2019/05/image6-e1557689807296.jpeg?resize=750%2C750" alt="image6.jpeg" width="750" height="750" data-recalc-dims="1" /><p id="caption-attachment-893" class="wp-caption-text">Someone thought they'd have fun with their filters on this one.</p></div>
<p style="text-align: center;">Still need to get your copies of <em>Imminent Dawn </em>and <em>Mourning Dove</em>? You can find them at the links below.</p>
<h2 style="text-align: center;"><em>Imminent Dawn</em></h2>
<p style="text-align: center;"><a href="https://www.amazon.com/dp/B07N1Q8C6G/" target="_blank" rel="noopener noreferrer">Amazon</a> | <a href="https://www.barnesandnoble.com/w/imminent-dawn-rr-campbell/1130343569?ean=2940161198599" target="_blank" rel="noopener noreferrer">Barnes &amp; Noble</a> | <a href="https://ninestarpress.com/product/imminent-dawn/" target="_blank" rel="noopener noreferrer">NineStar Press</a> | <a href="https://www.kobo.com/us/en/ebook/imminent-dawn" target="_blank" rel="noopener noreferrer">Kobo</a> | <a href="https://www.smashwords.com/books/view/919525" target="_blank" rel="noopener noreferrer">Smashwords</a>| <a href="https://www.goodreads.com/book/show/43196570-imminent-dawn">Goodreads</a> | <a href="https://ryanrcampbell.com/product/signedimminentdawn/" target="_blank" rel="noopener noreferrer">Author Website</a></p>
<h2 style="text-align: center;"><em>Mourning Dove</em></h2>
<p style="text-align: center;"><a href="https://www.amazon.com/dp/B07QZGSDX6/">Amazon</a> | <a href="https://www.barnesandnoble.com/w/books/1131295072" target="_blank" rel="noopener noreferrer">Barnes &amp; Noble</a> | <a href="http://ninestarpress.com/product/mourning-dove" target="_blank" rel="noopener noreferrer">NineStar Press</a> | <a href="https://www.kobo.com/us/en/ebook/mourning-dove-7" target="_blank" rel="noopener noreferrer">Kobo</a> | <a href="https://www.smashwords.com/books/view/935036" target="_blank" rel="noopener noreferrer">Smashwords</a> | <a href="https://www.goodreads.com/book/show/43728390-mourning-dove" target="_blank" rel="noopener noreferrer">Goodreads</a>| <a href="https://ryanrcampbell.com/?post_type=product&amp;p=5816&amp;preview=true" target="_blank" rel="noopener noreferrer">Author Website</a></p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default EMPATHYonTourThankYouEauClaire
