import React from 'react'

const HuzzahAWisCon43Recap = () =>
  <div>
    <p>I had a wonderful time at this last weekend's WisCon 43, which was held in Madison, Wisconsin at the Concourse Hotel. Not only did I attend as a vendor peddling my EMPATHY-verse wares, but I was also included on a panel about writing a series and had the chance to lead a couple of workshops on the craft of writing.</p>
<p>There were dozens of engaging sessions throughout the weekend that covered everything from capitalist anxiety, labor exploitation in space, queer storytelling versus stories that feature queer characters&#8212;you name it, there was a panel or discussion about it.</p>
<p>Here are some photos from the weekend!</p>
<div id="attachment_924" style="width: 3034px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-924" class="alignnone size-full wp-image-924" src="https://empathynovel.files.wordpress.com/2019/05/sff-series-panel.jpeg?resize=1080%2C685" alt="SFF Series Panel" width="1080" height="685" data-recalc-dims="1" /><p id="caption-attachment-924" class="wp-caption-text">From the “Plotting Past Book One: Writing a Series” Panel with Laurie J. Marks, Sarah Kozloff, David D. Levine, and your truly.</p></div>
<div id="attachment_925" style="width: 4042px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-925" class="alignnone size-full wp-image-925" src="https://empathynovel.files.wordpress.com/2019/05/lacey-at-booth.jpeg?resize=1080%2C810" alt="Lacey at Booth" width="1080" height="810" data-recalc-dims="1" /><p id="caption-attachment-925" class="wp-caption-text">Lacey held down the fort when I was in sessions or had to step away.</p></div>
<div id="attachment_926" style="width: 3031px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-926" class="alignnone size-full wp-image-926" src="https://empathynovel.files.wordpress.com/2019/05/out-in-hall-e1558800789751.jpeg?resize=1080%2C810" alt="Out in Hall" width="1080" height="810" data-recalc-dims="1" /><p id="caption-attachment-926" class="wp-caption-text">The setup on day one, when we were just outside the dealers' room.</p></div>
<div id="attachment_945" style="width: 3034px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-945" class="alignnone size-full wp-image-945" src="https://empathynovel.files.wordpress.com/2019/05/img_0863.jpg?resize=1080%2C1440" alt="IMG_0863" width="1080" height="1440" data-recalc-dims="1" /><p id="caption-attachment-945" class="wp-caption-text">And here's day two when we were moved into the dealers' room!</p></div>
<div id="attachment_947" style="width: 3034px" class="wp-caption alignnone"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-947" class="alignnone size-full wp-image-947" src="https://empathynovel.files.wordpress.com/2019/05/resolution-gesture.jpeg?resize=1080%2C1440" alt="Resolution Gesture" width="1080" height="1440" data-recalc-dims="1" /><p id="caption-attachment-947" class="wp-caption-text">Taken during Saturday evening's session on scene structure. We had a great turnout!</p></div>
<p>And there you have it–another event on the EMPATHY spring and summer tour has come and gone. There are still a number of chances to meet up in the coming months, so be sure to check those out.</p>
<p>If you're unable to attend any event&#8212;or simply can't wait for them to arrive to get your hands on a copy of a book in the EMPATHY series&#8212;you can find books one and two below!</p>
<h2 style="text-align: center;"><em>Imminent Dawn</em></h2>
<p style="text-align: center;"><a href="https://www.amazon.com/dp/B07N1Q8C6G/" target="_blank" rel="noopener noreferrer">Amazon</a> | <a href="https://www.barnesandnoble.com/w/imminent-dawn-rr-campbell/1130343569?ean=2940161198599" target="_blank" rel="noopener noreferrer">Barnes &amp; Noble</a> | <a href="https://ninestarpress.com/product/imminent-dawn/" target="_blank" rel="noopener noreferrer">NineStar Press</a> | <a href="https://www.kobo.com/us/en/ebook/imminent-dawn" target="_blank" rel="noopener noreferrer">Kobo</a> | <a href="https://www.smashwords.com/books/view/919525" target="_blank" rel="noopener noreferrer">Smashwords</a>| <a href="https://www.goodreads.com/book/show/43196570-imminent-dawn">Goodreads</a> | <a href="https://ryanrcampbell.com/product/signedimminentdawn/" target="_blank" rel="noopener noreferrer">Author Website</a></p>
<h2 style="text-align: center;"><em>Mourning Dove</em></h2>
<p style="text-align: center;"><a href="https://www.amazon.com/dp/B07QZGSDX6/">Amazon</a> | <a href="https://www.barnesandnoble.com/w/books/1131295072" target="_blank" rel="noopener noreferrer">Barnes &amp; Noble</a> | <a href="http://ninestarpress.com/product/mourning-dove" target="_blank" rel="noopener noreferrer">NineStar Press</a> | <a href="https://www.kobo.com/us/en/ebook/mourning-dove-7" target="_blank" rel="noopener noreferrer">Kobo</a> | <a href="https://www.smashwords.com/books/view/935036" target="_blank" rel="noopener noreferrer">Smashwords</a> | <a href="https://www.goodreads.com/book/show/43728390-mourning-dove" target="_blank" rel="noopener noreferrer">Goodreads</a>| <a href="https://ryanrcampbell.com/?post_type=product&amp;p=5816&amp;preview=true" target="_blank" rel="noopener noreferrer">Author Website</a></p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default HuzzahAWisCon43Recap
