import React from 'react'

const UpdatesontheEMPATHYSciFiSaga = () =>
  <div>
    <p>It's been more than six months since I last provided <a href="https://empathyseries.com/2018/12/05/empathy-series-december-updates/" target="_blank" rel="noopener noreferrer">an update on the EMPATHY sci-fi saga</a>, and with book one, <em>Imminent Dawn</em>, having debuted as <a href="https://empathyseries.com/2019/01/26/imminent-dawn-debuts-at-1-for-lgbt-science-fiction/" target="_blank" rel="noopener noreferrer">the number one new release in LGBT sci-fi</a> and book two, <em>Mourning Dove</em>, making it into readers' hands as of a little more than three weeks ago, now feels like a good time for an update.</p>
<h2><em>Imminent Dawn</em></h2>
<p>As this site's headers and its debut status on Amazon might imply, <em>Imminent Dawn </em>has been very well received. It's hard to believe it hasn't even been out for four months yet, either; it feels as though many of the folks with whom I've spoken at conferences or other book events have at least heard of it, are reading it, or have it on their list of to-reads.</p>
<p>If you've had a chance to read it and enjoyed it, have you left a review on <a href="https://www.amazon.com/dp/B07N1Q8C6G/" target="_blank" rel="noopener noreferrer">Amazon</a> or <a href="https://www.goodreads.com/book/show/43196570-imminent-dawn" target="_blank" rel="noopener noreferrer">Goodreads</a>? Those reviews go a long way into spreading the good news about the EMPATHY series, and every last one of them makes a difference. Even if you didn't buy the book on Amazon, you can leave a review there that's as little as twenty words long!</p>
<p>Or, if you haven't yet had a chance to nab your copy of the book <em>New York Times </em>bestselling author Matt Forbeck has hailed as “an incisive techno-thriller that gets more tense with every page,” you can get in on the action at any of the links below.</p>
<h3 style="text-align: center;"><strong>Find <em>Imminent Dawn</em> here:</strong></h3>
<p style="text-align: center;"><a href="https://www.amazon.com/dp/B07N1Q8C6G/" target="_blank" rel="noopener noreferrer">Amazon</a> | <a href="https://www.barnesandnoble.com/w/imminent-dawn-rr-campbell/1130343569?ean=2940161198599" target="_blank" rel="noopener noreferrer">Barnes &amp; Noble</a> | <a href="https://ninestarpress.com/product/imminent-dawn/" target="_blank" rel="noopener noreferrer">NineStar Press</a> | <a href="https://www.kobo.com/us/en/ebook/imminent-dawn" target="_blank" rel="noopener noreferrer">Kobo</a> | <a href="https://www.smashwords.com/books/view/919525" target="_blank" rel="noopener noreferrer">Smashwords</a>| <a href="https://www.goodreads.com/book/show/43196570-imminent-dawn">Goodreads</a> | <a href="https://ryanrcampbell.com/product/signedimminentdawn/" target="_blank" rel="noopener noreferrer">Author Website</a></p>
<h2><em>Mourning Dove</em></h2>
<p>Like I mention above, <em>Mourning Dove </em>has hardly been out for three weeks, but with the EMPATHY spring and summer tour in full swing, it feels like it's been around for much longer than that.</p>
<p>So far, I've visited <a href="https://ryanrcampbell.com/2019/05/06/empathy-on-tour-thank-you-beloit/" target="_blank" rel="noopener noreferrer">Beloit</a> and <a href="https://ryanrcampbell.com/2019/05/13/empathy-on-tour-thank-you-eau-claire/" target="_blank" rel="noopener noreferrer">Eau Claire</a> as part of this tour, and <a href="http://empathyseries.com/2019/05/20/this-week-r-r-campbell-at-wiscon" target="_blank" rel="noopener noreferrer">I'll be in my hometown of Madison this weekend for WisCon</a>, a sci-fi and fantasy conference at which I'll be discussing writing a series, scene structure, and conflict as part of panels or seminars I'm leading. The response to <em>Mourning Dove </em>at both the Beloit and Eau Claire events has been incredible, and I'm looking forward to sharing it with the rest of you as <a href="https://empathyseries.com/2019/03/20/hello-wisconsin/" target="_blank" rel="noopener noreferrer">the tour continues through June</a>.</p>
<p>All in all, it's still early for <em>Mourning Dove</em>, but I'm loving the responses that have come in to date, especially those from readers who have said they're already jonesing for book three in the series!</p>
<h3 style="text-align: center;"><strong>Find <em>Mourning Dove</em> here:</strong></h3>
<p style="text-align: center;"><a href="https://www.amazon.com/dp/B07QZGSDX6/">Amazon</a> | <a href="https://www.barnesandnoble.com/w/books/1131295072" target="_blank" rel="noopener noreferrer">Barnes &amp; Noble</a> | <a href="http://ninestarpress.com/product/mourning-dove" target="_blank" rel="noopener noreferrer">NineStar Press</a> | <a href="https://www.kobo.com/us/en/ebook/mourning-dove-7" target="_blank" rel="noopener noreferrer">Kobo</a> | <a href="https://www.smashwords.com/books/view/935036" target="_blank" rel="noopener noreferrer">Smashwords</a> | <a href="https://www.goodreads.com/book/show/43728390-mourning-dove" target="_blank" rel="noopener noreferrer">Goodreads</a>| <a href="https://ryanrcampbell.com/?post_type=product&amp;p=5816&amp;preview=true" target="_blank" rel="noopener noreferrer">Author Website</a></p>
<h2><em>Event Horizon </em>and <em>Rubicon</em></h2>
<p>Speaking of book three in the series, this is actually where I have the most updates. Before you read on, though, know that <strong>here there be spoilers. </strong>As in if you keep reading without having read books one and two, you run the risk of having a few things spoiled for you. Fair warning.</p>
<p>Let me start by saying <em>Event Horizon </em>has proven to be an extraordinary challenge to write. As I near the completion of a fourth draft, it's looking like this will be the longest installment in the series yet&#8212;and it only features half of our perspective characters.</p>
<p><em>Half of our perspective characters</em>, you say, <em>what madness is this</em><em>?</em></p>
<p>It is indeed madness, but it's less mad than the alternatives. Let's explore why and what I've done to counter some unforeseen challenges.</p>
<p>Firstly, due to matters beyond my control, I'm hard-capped for word count at 140,000 words per book. For perspective, <em>Imminent Dawn </em>is about 118,000 words, and <em>Mourning Dove</em>, 116,000. With the original vision for <em>Event Horizon </em>set to include twelve perspective characters, it became apparent after a first draft that I could not effectively tell this chunk of the story while keeping our total word count below 140,000 words.</p>
<p>To address this, I elected to split <em>Event Horizon </em>into two concurrent installments, now known as <em>Event Horizon </em>and <em>Rubicon</em>. The former will focus on Ty, Kyra, and Chandra primarily, while the latter will center around Ren and the Halman siblings, as well as the overworld plots to which they belong.</p>
<p>What this means, then, is that <em>Event Horizon </em>will walk us through six to eight months of the lives of Chandra, Kyra, Ty (and some other POVs) before <em>Rubicon </em>walks us through those same six to eight months for the other half of our character set.</p>
<p>So what can you expect from these installments, and when will they be released?</p>
<p><em>Event Horizon </em>is, per a draft of its back cover description, “a dark, haunting exploration of isolation, self-worth, and identity.” In this way, it is a much more character-drama-driven book, with Kyra, Chandra, and Ty forced to confront the darkest bits of themselves and their circumstances yet. This has made for a book that is much more personal for all three of these characters. And though separated from one another, they're on journeys that will greatly impact the others as they themselves, grow and (hopefully) overcome their inner demons (and the circumstances in the outside world that are forcing them to confront those demons).</p>
<p><em>Rubicon, </em>on the other hand, is where we get back to the “wonderful” world of tech-driven drama. Though much of this installment will center around the politicking Alistair has at play in attempting to garner support for EMPATHY throughout the NAU, we'll get a fair share of Heather and Peter as they work toward actually, you know, making EMPATHY work with “help” from a ghost from their past.</p>
<p><em>Event Horizon </em>is nearing the completion of its fourth draft, and I've written about 40,000 words of <em>Rubicon</em>. At this time, though, only <em>Event Horizon </em>is on the publishing calendar, where it's scheduled to debut in <strong>Spring 2020</strong>. I should have more information concrete information about the release date in about two months' time, so stay tuned.</p>
<p><em>Rubicon </em>will (hopefully) be out in late 2020, but we'll see. Once <em>Event Horizon </em>is in my editor's hands, I plan to take some time to work on a romantic suspense novel outside the EMPATHY universe, but I might also write a novel focusing on Chandra and Kyra's lives before the EMPATHY study took place.</p>
<p>That's right&#8212;you might get a HappyTimes™ romance origin tale to help tide you over until <em>Rubicon </em>comes out.</p>
<h2>The Rest</h2>
<p>Once <em>Event Horizon </em>and <em>Rubicon </em>were out, my original plan was to finish off the main series with two installments, <em>Consolunarity </em>and <em>Nightshade</em>. The former might end up having to be split like <em>Event Horizon </em>and <em>Rubicon</em>, though, so for now I'd better leave it at this: you're going to end up with six or seven total books in this saga, and we'll get back to the five-alarm, Halman-help-us techno-thriller feel for the final three books especially. So strap on those VR headsets and secure the room around you. It's going to be a wild ride.</p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default UpdatesontheEMPATHYSciFiSaga
