import React from 'react'

const BiblioBreakdownExitWest = () =>
  <div>
    <p>It's <a href="http://www.rrcampbellwrites.com/bibliobreakdown" target="_blank" rel="noopener">Biblio Breakdown</a> time! In this installment, we'll explore voice and intimacy in point of view in Mohsin Hamid's <em>Exit West</em>.</p>
<p>Before we begin our analysis, I'll quote the book blurb so we have a little bit of context as we move forward.</p>
<blockquote>
<h4>In a country teetering on the brink of civil war, two young people meet—sensual, fiercely independent Nadia and gentle, restrained Saeed. They embark on a furtive love affair, and are soon cloistered in a premature intimacy by the unrest roiling their city. When it explodes, turning familiar streets into a patchwork of checkpoints and bomb blasts, they begin to hear whispers about doors—doors that can whisk people far away, if perilously and for a price. As the violence escalates, Nadia and Saeed decide that they no longer have a choice. Leaving their homeland and their old lives behind, they find a door and step through…</h4>
</blockquote>
<p>If that sounds fascinating, it's because it is. <em>Exit West</em> is one of the best books I've read in the last few years, so please do yourself the favor of picking it up. You don't have to take my word for it, though: it was named best book of the year (or listed among them) by the <em>New York Times</em>, <em>NPR</em>, <em>TIME</em>, <em>GQ</em>, <em>O The Oprah Magazine</em>&#8212;you name it, they loved it.</p>
<p>Biblio Breakdowns aren't means as reviews or recommendations, though, so let's get technical, beginning with point of view.</p>
<h2>Point of View</h2>
<p>In other blog posts, I've explored the various types of point of view: first, second, and third (limited and omniscient). Choosing the point of view to employ in any given manuscript is a major choice; it's the lens through which readers will access the story, and each point of view lends itself to varying degrees of intimacy between the reader and the perspective characters.</p>
<p>In <em>Exit West</em>, Mohsin Hamid employs the third-person omniscient point of view, through which readers have access to all of the thoughts and feelings of any character at any given time. Personally, I steer clear of omniscience in my own writing for a few reasons. Let's take a look at what those reasons are before examining why Hamid's choice to use the third-person omniscient was, despite my qualms with the use of omniscience more broadly, an absolutely brilliant choice for this book.</p>
<h3>Mystery, Suspense, and Dramatic Irony</h3>
<p>Regular readers of my blog probably roll their eyes at the above header; it describes topics I've covered a few times in other posts, too. These are, however, crucial to consider when developing a scene or examining a character's arc.</p>
<p>When writing in the third person, I prefer to employ the third-person limited perspective, as it tends toward increased mystery and suspense. How? Simply by the virtue of only giving readers access to the feelings and inner machinations of a single character. That is to say, in any scene, we only know what our perspective character knows (suspense), and sometimes our perspective character knows things that haven't yet been shared with the reader (mystery).</p>
<p>In this way, readers don't know what the true intentions of other characters might be: whether they've actually forgotten our perspective character's birthday, for example, or if they've actually planned a surprise party and their “forgetfulness” is all part of an elaborate ruse.</p>
<p>Setups like the above create suspense for the reader, something that can be lost in total omniscience. Granted, this argument could be construed as a bit of a straw man since authors who employ omniscience could choose not to provide this secondary character's true intentions to the reader, but that's another one of my qualms with omniscience: it gives authors the ability to be inconsistent in or withholding about what they share at any given time, which, in my view at least, gives the author too much power over a story that is, ultimately, about characters and their experiences.</p>
<p>In <em>Exit West</em>, Mohsin Hamid dodges any tendency toward inconsistency or penchant for being withholding, and he does so by going full-on with his omniscience. We get to know what both of our perspective characters are thinking and feeling, <em>even if we don't get to know it immediately.</em></p>
<p>“Whoa, wait,” you might say. “Isn't the whole deal with omniscience that we get to know who's thinking what and when they're thinking it, any time they're thinking it?”</p>
<p>Well, sure. Yeah. But given the linear presentation of content in a novel, as writers we're limited to only truly be presenting the thoughts and feelings of one given character (or group of like-minded characters) at a single point in time.</p>
<p>Though this may feel like a limitation (and it often is), Hamid uses it to his advantage countless times throughout <em>Exit West</em>. The most prevalent examples of this, I feel, are when he spends short spurts inside of Saeed's head, expressing his doubts and his concerns about his relationship with Nadia. The questions he raises put us on the same page as Saeed, and they help foment a strong sense of suspense since the answers to those questions aren't known to the reader when they're asked.</p>
<p>Then, however, Hamid uses that suspense as fuel to push us into Nadia's thoughts, where we learn she's often thinking along similar lines as Saeed. In fact, sometimes Nadia's thoughts would answer Saeed's questions or quell his doubts, which converts that feeling of suspense readers had earlier into dramatic irony. Readers can now think to themselves, “Oh, Saeed, if only you knew what I know!”</p>
<p>This conversion of suspense to dramatic irony is a great way to use the third person omniscient point of view, in my opinion. It works especially well in <em>Exit West</em>, where our two primary point of view characters would stand to benefit if only they just <em>talked</em> about these things a bit more.</p>
<p>I mean, they do talk about them from time to time, but in nowhere near as forthcoming of a way as they express their inner thoughts on the same topics. This also means that when the two characters are conversing but not quite expressing themselves clearly or being 100% honest, we as readers again are presented with more dramatic irony.</p>
<p><em><strong>Exercise</strong></em>: Pick one of your favorite scenes from your work in progress, preferably something that features both your main character and their antagonist, or your main character and their love interest, for example. How would the scene change if readers were privy to the thoughts of the non-perspective character? How would the scene change if each character knew what the other knew?</p>
<p>Thinking about this “information economy” can help us better understand our characters themselves, and also create greater tension for readers who might be wondering the same things.</p>
<p><strong>Caution: </strong>though after doing this exercise you may be tempted to tease bits of information that's only known to a non-perspective character, be sure to avoid head-hopping if you're writing in a third-person limited perspective. If you're unfamiliar with head-hopping, we'll cover it in the next section, so strap in.</p>
<h3>Head-hopping</h3>
<p>Readers who are familiar with this blog (or who hired me as an editor) probably read the above section and think that this sounds an awful lot like a limited perspective (rather than omniscient) with lots of head-hopping. Isn't that a dreaded no-no?</p>
<p>Before we answer this question, let's do a refresher on head hopping for those who are unfamiliar.</p>
<p>Let's say we're reading a spy thriller that follows our favorite special agent from one high-flying action scene to the next. We're with her the whole time, only knowing what she knows and feeling what she feels. Then, somewhere around page 100, she's having a standoff with one of the baddies. Before they prepare to battle, the author leaves us with something like, “The evil henchman knew that Agent Leona was unarmed.”</p>
<p>Wait. What?</p>
<p>How does the henchman know this? How do we know that the henchman knows this?</p>
<p>Well, we know because the author decided to hop into his head for a moment and tell us. Imagine if this sentence were rewritten to something like this, for example: “The evil henchman's eyes landed on her hip, her empty holster.”</p>
<p>We now get the same information, but remain with our perspective character and her observations of the scene, rather than the author casting themselves forcefully onto the page for a moment to make sure readers get some extra suspense.</p>
<p>In <em>Exit West</em>, I feel that despite the ability to visit any character at any time, we're not dealing with head-hopping because what would otherwise be hops are established as part of the storytelling from the book's very first pages.</p>
<p>Mohsin Hamid also makes the incredible storytelling choice to, at times, leave our two main characters to travel halfway around the world for brief anecdotes about how the lives of others are changed by these doors that suddenly let people visit one part of the world or another simply by walking through them.</p>
<p>This is, admittedly, something else I would have flagged as an editor if I were reading with a critical eye (and it was something I felt “off” about until I let the writing style wash over me), but the reason I was able to look past it is because of how this and the perspective changes were employed: namely, voice.</p>
<h2>Voice</h2>
<p>Voice is one of those tricky things to define&#8212;you know it when you read it, but until you have an example of it thrown into your face, it's tough to put it into words on its own.</p>
<p>With that in mind, let's use a few examples to try to tease out what I mean when I refer to voice. Compare the presentation of the main character in Emma Donoghue's <em>Room</em> with Salinger's <em>Catcher in the Rye</em> or Fitzgerald's <em>The Great Gatsby</em>. Each has his own manner of speaking, presenting the facts, and guiding readers through the narrative. If you were to take Nick Carraway from <em>Gatsby </em>and have him narrate <em>Room</em> or, say, any of the <em>A Song of Ice and Fire</em> series, you'd wind up with a markedly different presentation of the story (Gatsby said, “When you play the game of thrones, you win or you die, old sport.”)</p>
<p>As we can see, voice can clearly affect a reader's understanding (and enjoyment!) of any given story. Writers whose characters are able to set themselves apart from the writing of others through the use of voice can help readers identify more thoroughly with the protagonist and their world, which is, of course, always a plus.</p>
<p>In <em>Exit West</em>, the voice Mohsin Hamid employs on the page has an almost epic, biblical feel to it. Admittedly, this was a bit of a turn off for me when I first started reading&#8212;that is, until I appreciated the complexity injected into it through the use of what I'll call a sort of “zoom” feature. This “zoom” allows readers to begin a sentence feeling rather distant from any given character&#8212;seeing the goings-on in the neighborhood or on the far side of the planet&#8212;before winding its way toward a character's inner thoughts and feelings more closely over the course of the sentence. Conversely, we were also presented with sentences where we could begin zoomed in on and highly intimate with a character, then slowly zoom out, then zoom into another character, completing the head-hop, but doing so in a graceful, one-thing-leads-to-another sort of way. Here's an example.</p>
<blockquote>
<h4>There was no physical violence in Nadia's home, and much giving to charity, but when after finishing university Nadia announced, to her family's utter horror, and to her own surprise for she had not planned to say it, that she was moving out on her own, an unmarried woman, the break involved hard words on all sides, from her father, from her mother, even more so from her sister, and perhaps most of all from Nadia herself, such that Nadia and her family both considered her thereafter to be without a family, something all of them, all four, for the rest of their lives, regretted, but which none of them would ever act to repair, partly out of stubbornness, partly out of bafflement at how to go about doing so, and partly because the impending descent of their city into the abyss would come before they realized that they had lost the chance.</h4>
</blockquote>
<p>There's no way that's one sentence, right? Well, read it again. I promise you it is, and this isn't even the longest of the book!</p>
<p>Where this “zoom feature” is concerned, let's examine how the focus changes over the course of the sentence, sliding gracefully from one focus point to the next.</p>
<ol>
<li>Nadia's home more generally</li>
<li>Nadia's family's reaction to her announcement</li>
<li>Nadia's own reaction to her announcement</li>
<li>The implications for her announcement</li>
<li>Interpretations of the implications of her announcement</li>
</ol>
<p>This could be broken down even further, honestly, but perhaps I'll save that for the podcast version of this Biblio Breakdown. The point is this: we do have head hops and commentary on events not yet come to pass where the linear presentation of the narrative is concerned, but all of that works here&#8212;in my opinion, at least&#8212;because the narrative voice moves from one idea to the next through the use of proximity in presentation on the page and the richness with which it allows us to further appreciate the import of what could otherwise have been just another family argument. The context that the voice provides&#8212;namely, that any argument can change the course of time or be the last that any group of people has&#8212;is truly devastating, especially once pit against the action of the narrative as it advances.</p>
<p><em><strong>Exercise</strong></em>: Imagine one of your characters. Now, imagine them as being from a different background than the one they currently have. Think along the lines of where they're from, their socioeconomic status, the people they grew up alongside of and how those individuals might have affected their manner of speaking, the metaphors they employ, and their world view more generally.</p>
<p>Now write a scene from the perspective of this character that now has a slightly different background than your original. How does their presentation of events change? What different mannerisms, words, and interpretations of events do they provide?</p>
<p><strong>Caution: </strong>when doing this exercise, try to push yourself past stereotypified interpretations of voice, especially if writing a character of a significantly different background than your own. Remember, we're writing characters, not caricatures, and it's critically important we examine and challenge our own (oftentimes innate) biases from time to time in order to do so.</p>
<h2>Conclusion</h2>
<p>That's all for this Biblio Breakdown of Mohsin Hamid's <em>Exit West</em>. Go forth and play with point of view and voice in your own work! You might be amazed at what you discover.</p>
<hr />
<p style="text-align: center;"><em>To stay up to date with Biblio Breakdowns</em><em>, <a href="http://www.rrcampbellwrites.com/podcasts" target="_blank" rel="noopener">the r. r. campbell writescast</a>, and my forthcoming releases, <a href="http://www.rrcampbellwrites.com/newsletter" target="_blank" rel="noopener">you can subscribe to my monthly newsletter at this link</a>, and never miss a thing!</em></p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default BiblioBreakdownExitWest
