import React from 'react'

const NowPublished40000toFlesh = () =>
  <div>
    <p>I'm pleased to announce my article “40,000 to Flesh: How I Journaled My Way to Character” <a href="https://ryanrcampbell.com/podcast/writescast-episode-three-dylan-davis-on-flash-fiction-writing-fear-and-publishing-tips/" target="_blank" rel="noopener">is now available at this link</a> through <em>National Journal Writing Month</em>.</p>
<p>“40,000 to Flesh” details my character-creation journey for <em>Accounting for it All</em>. <em>AFIA </em>is the story of Robin Whethers, a porn-star-turned-accountant who must evade an IRS audit while confronting the impending death of her terminally ill mother and rekindling a relationship with the love of her life, who's finally ready to make things work.</p>
<p>You can learn more about <em>Accounting for it All</em> on my <a href="https://ryanrcampbell.com/current-projects/" target="_blank" rel="noopener">current projects</a> page.</p>
<p>“40,000 to Flesh” is my third piece to make it to publication, following in the footsteps of <em><a href="https://ryanrcampbell.com/2017/08/24/now-published-what-it-is-to-smell-of-man/" target="_blank" rel="noopener">What It Is To Smell Of Man</a></em> and <em><a href="https://ryanrcampbell.com/2017/07/28/now-published-wool/" target="_blank" rel="noopener">Wool</a></em>.</p>
<p>The founder of <em>National Journal Writing Month</em>, Bakari Chavanu, will also appear on <a href="https://ryanrcampbell.com/podcasts/" target="_blank" rel="noopener">the writescast</a> on September 15th to talk about unleashing the power of the creative mind through journaling. Stay tuned to rrcampbellwrites.com for more.</p>
<p><img loading="lazy" decoding="async" data-attachment-id="3634" data-permalink="https://ryanrcampbell.com/chavanu-twitter-author-photo-promo/" data-orig-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/09/Chavanu-Twitter-Author-Photo-Promo.png?fit=1024%2C512&amp;ssl=1" data-orig-size="1024,512" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="Chavanu - Twitter, Author Photo Promo" data-image-description="" data-image-caption="" data-medium-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/09/Chavanu-Twitter-Author-Photo-Promo.png?fit=300%2C150&amp;ssl=1" data-large-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/09/Chavanu-Twitter-Author-Photo-Promo.png?fit=1024%2C512&amp;ssl=1" class="  wp-image-3634 aligncenter" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/09/Chavanu-Twitter-Author-Photo-Promo.png?resize=426%2C213&#038;ssl=1" alt="Chavanu - Twitter, Author Photo Promo" width="426" height="213" srcset="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/09/Chavanu-Twitter-Author-Photo-Promo.png?w=1024&amp;ssl=1 1024w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/09/Chavanu-Twitter-Author-Photo-Promo.png?resize=300%2C150&amp;ssl=1 300w" sizes="(max-width: 426px) 100vw, 426px" data-recalc-dims="1" /></p>
<hr />
<p>Want updates like these delivered to your inbox once a month? You can sign up for the r. r. campbell writes newsletter <a href="http://www.rrcampbellwrites.com/newsletter" target="_blank" rel="noopener">at this link</a>, or follow me on Twitter at <a href="http://www.twitter.com/iamrrcampbell" target="_blank" rel="noopener">@iamrrcampbell </a>and <a href="http://www.twitter.com/writescast" target="_blank" rel="noopener">@writescast</a>.</p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default NowPublished40000toFlesh
