import React from 'react'

const OnAuthenticityandFollowingYourBliss = () =>
  <div>
    <p>If you follow me on Twitter, you might know I recently got a promotion over at Dayjob, Inc. I mention this not to be a braggadocio, but because reflecting on the path that led me to this position made me realize a number of lessons I learned in my dayjob experience  are equally applicable in the world of writing, which we'll touch on at the end of this post.</p>
<p>With that in mind, I figured it'd be worth exploring these journeys publicly should this perspective be of use to you as you navigate your own winding path in the world of writing.</p>
<h1>It Starts with a Decision</h1>
<p>Back when I was starting college&#8212;and even before then, frankly&#8212;if you had told me I'd wind up in international regulatory affairs, my immediate reaction would have probably been, “Well, yeah. That's what happens when you study business: you get to do business things.”</p>
<p>This, however, aside from being a weird thing to say, is actually not representative of the path that would get me where I am now.</p>
<p>Past-me would be shocked to hear this, especially since it felt predestined that I'd apply, be admitted to, and graduate from my university's business school after having started myself down that road in high school and my first year of college.</p>
<p>Then, of course, while meandering my way through my freshman year, something about the path I was on started to irk me: the brush was gnarled and overgrown, its fruits were sour on the tongue, and the people I encountered along the way seemed more likely to commit highway robbery than they did to lend a hand to a neighbor whose wagon had a broken axle.</p>
<p>“One foot in front of the other,” were the words that dogged me onward. “Everyone has to deal with things they don't like along the way. Onward! This is part of a bigger process.”</p>
<p>And it <em>was</em> part of a bigger process&#8212;just not in the way I expected.</p>
<p>There reached a point in my figurative travels where I had to decide whether to keep on keeping on, or forfeit the progress I'd made to begin anew on the road less traveled. But what lied down that road? What would the road itself look like? What if it, too, bore fruit that rotted on the tongue? What if fending off highway robbery had less to do with the road one traveled, and more to do with traveling at all?</p>
<p>In short: I had a decision to make, but first I needed something to guide my choice.</p>
<h1>Stay True</h1>
<p>I knew I had a penchant for foreign language, but I always saw the advantages of mastering one as secondary to getting one of those high-powered, kick 'em in the teeth degrees. After all, what good is speaking another language if you don't bring a technical skill to the table? Right?</p>
<p>Wrong, though it took me longer than I'd like to admit to stumble into that answer.</p>
<p>Spanish seemed a natural fit since I already had a few years of experience tucked away in my travel sack, but could I really get away with studying just that? I didn't know, but I knew I had to start somewhere, so I dove in hard with Spanish.</p>
<p>Focusing intensely on it eventually led me to an introductory linguistics course, and it only took one class at that level for me to fall in love with it as a field of study. I'd never had that feeling from my business-school prep work, and as a result, I decided to declare linguistics as my primary major and pursue an honors distinction in that field. I was pumped!</p>
<p>Ah, but then the inevitable flurry of questioners and nay-sayers reached out like so many thorny vines, taking swipes at me as I walked a path where the sun was otherwise shining.</p>
<p>“You're studying what?” they'd say. “How do you plan on getting a job with that? What can you really do with a degree in linguistics?”</p>
<p>These questions came at me all of the time from well-meaning people in my life, and most of them at least managed to get the <em>linguistics</em> part right (Sorry-not-sorry to everyone who confused linguistics with <em>logistics</em>. They're two very different things.).</p>
<p>Thankfully, the department of linguistics actually provided handouts to its majors in order to answer these and other pesky questions, so that was certainly of some help. Perhaps more critically, though, I was <em>enjoying</em> my field of study and staying true to myself. I loved going to class, writing papers, and designing and carrying out experiments. Once I graduated, the jobs would surely come.</p>
<p>Well, they didn't.</p>
<p>What was wrong with me? Was fluency in Spanish, Portuguese, and German not enough for the job market? Should I have stuck with the business path all along? HAD I MADE A HUGE MISTAKE?</p>
<p>No. I just wasn't being patient enough. I also hadn't spent enough time meeting the right people, the ones who would eventually recognize someone doesn't need one of those kick 'em in the teeth degrees to merit being given a chance.</p>
<h1>Networking, Engagement, Platform</h1>
<p>I cringe at the word networking. I revile it. Truly. It's not that I don't like to meet and engage with people, it's that, to me, there's something inherently artificial about a roomful of people glad-handing one another in an attempt to work toward “synergistic personnel solutions” and “direct-engagement human-resources development.” Gross.</p>
<p>The good news (in my case, anyway) is that networking, as it turns out, isn't so narrowly defined as the image I always had in mind. Through the use of various job sites, I put together a prospective employment profile that didn't undersell my linguistic assets, but  embraced them instead.</p>
<p>Still, actively pursuing positions for which I felt I'd be a great fit bore no fruit. For longer than I like to remember, I had a hard time even securing phone interviews.</p>
<p>Then, out of the blue, I received a message from a company I'd never heard of in an industry I knew nothing about… wondering if I'd be interested in becoming an international sales coordinator, of all things.</p>
<p>I was thrilled to know someone saw something of value in my resume, but I was more than apprehensive about returning their correspondence&#8212;that is, until I saw why they had reached out to me specifically.</p>
<p>See, they <em>desperately</em> needed someone who spoke Portuguese to help them with their accounts in Brazil, and that I also spoke Spanish was a plus for them as well. So, after a Skype interview with their Brazilian sales manager and some reassuring talks with management, I agreed to take the job.</p>
<p>And then the wheels fell off my metaphorical cart.</p>
<p>I was in over my head&#8212;WAY over my head&#8212;where the actual industry side of things was concerned. Fortunately, I had a manager with whom I'd invested deeply in cultivating a positive relationship. Beyond him, too, I made sure to ask questions of subject-matter experts within the company to slowly construct a more cohesive vision for what my own role was supposed to be.</p>
<p>Fast forward a year later, and one of those experts (who had since moved on from the company) emails me out of the blue, asking if I'm looking for a new job. I wasn't, per se, but I asked her to forward on the information anyway.</p>
<p>And am I ever glad I did. Not only did the position she recommended have a significantly shorter commute and better compensation for a nearly identical role, she'd recently interviewed for the job herself, but had ultimately decided to turn it down because it was too long of a commute from where she lived. That is to say, I had an in! With her recommendation to that new company on top of the experience I'd finally accumulated in the previous year, all it took was a single thirty minute interview to secure the new job.</p>
<p>Then it was a matter of lather, rinse, repeat.</p>
<p>I made friendly with my new supervisor and the rest of the team, and also befriended colleagues in the regulatory department, firstly because I depended on them to do my job, and secondly because the work seemed genuinely interesting to me.</p>
<p>Fast forward two years later, and one of those regulatory colleagues has decided to take a job someplace else. On her way out, she recommended me for her position, going so far as to tell my supervisor she should also push me to apply for the role. I wasn't sure about taking that step at first, but after encouragement from both of them, I decided to apply.</p>
<p>And, after a winding month-plus interview process with enough twists and turns to make you swear it was fiction, here we are. I'll be starting that position in two weeks, and I couldn't be happier about it.</p>
<h1>Cool, but what does this have to do with writing?</h1>
<p>It has EVERYTHING to do with writing.</p>
<p>Let's take a look at the three major takeaways from my journey above.</p>
<ul>
<li>Decision time</li>
<li>Staying true to oneself</li>
<li>Networking and positive engagement</li>
</ul>
<p>Where the first of these is concerned, I had a similar decision-point moment in the world of writing like I did with my dayjob career.</p>
<p>During my first stint in Brazil, the volunteer program in which I had enrolled went off the rails after only a couple of weeks. That is to say, the manner in which I was supposed to be filling my days for three months was basically non-existent after the second week of my time there.</p>
<p>After a few transitional weeks full of ungodly amounts of coffee and wandering the streets to seemingly no end, I figured out what had been clawing at me every day as I sidestepped dog poop and spent far too many <em>reais</em> on fruit smoothies: I needed a purpose, and all along some part of me knew what that purpose was supposed to be.</p>
<p>So I filled my time by writing.</p>
<p>Not only that, but I actively <em>decided</em> that this wasn't something I was going to give up. Once I moved out of the one-car garage that served as my bedroom and pseudo-office in Brazil, I took that writing home with me, and resolved to not betray my momentum or the story I'd been furiously typing to the soundtrack of ceaselessly barking dogs.</p>
<p>Five years later, here I am: writing this blog post, outlining what will become my fourth manuscript, and preparing to hit the query road (again) in 2018 for two of the manuscripts I've written in recent years.</p>
<p>Realistically, though, a lot happened in the five years we just so brazenly fast forwarded through. In fact, those five skipped-over years were loaded with miniature lessons on all of the topics we're exploring in this post, so let's hone in on a couple of those experiences to flesh out both <em>staying true to oneself</em> and <em>the importance of networking and engagement.</em></p>
<p><em><a href="http://www.rrcampbellwrites.com/current-projects" target="_blank" rel="noopener">EMPATHY: Imminent Dawn</a></em> has been my baby ever since the idea for it first came to me (as a short story, nonetheless) sometime in 2012. Despite any number of projects I've worked on over the last five years, I've <em>always</em> come back to it&#8212;though that wasn't always the case. At one point, in fact, I was ready to abandon it completely.</p>
<p>I remember how I lurched forward on the couch when I first saw the ad. Some network television show featuring technology nearly identical to EMPATHY was all set to launch in the coming months. That was it. I'd been beaten to it. There was no point in writing my story; its themes and their vehicle for delivery were already in the cultural zeitgeist.</p>
<p>Then, once that show went off the air after a rather brief run, I was sure there was no way forward. If network TV couldn't make the concept work with all of the resources at its disposal, then how could I?</p>
<p>I don't remember exactly what snapped me out of that self-induced stupor, but if I had to guess, it was a sort of calling back to the story itself; I just couldn't stop thinking about it. Over time, I realized that though the technological concepts were similar, the stories were fundamentally different. Not only that, but I had no way of really knowing why the show went off the air.</p>
<p>So&#8212;just like in my educational journey that led me to the land of linguistics&#8212;I decided to follow my bliss.</p>
<p>A handful of years later, <i>EMPATHY </i>has grown from a short story into a multi-POV technothriller. And am I glad to have written (all ten-plus drafts of) it? Absolutely. I can't imagine how I'd feel if I hadn't. It's still not perfect, but I'm working on it, and won't be stopped until I'm satisfied with what it's become.</p>
<p>And <em>EMPATHY</em> is, of course, only one of the many projects I've worked on since deciding to write more seriously.</p>
<p>Of course, the act of writing itself, too, is, at least by my preference, solitary by nature. So where does networking come into play?</p>
<p>Well, it didn't until probably about six months after I returned home from Brazil for the first time. After some research, I discovered the University of Wisconsin-Madison's Division of Continuing Studies planned to host a one-day seminar on self-pub on a Saturday I happened to be free.</p>
<p>While there, I mostly kept to myself, but near the end of the session, a writer asked to make an announcement about this critique group of which he was a member. They were actively looking to round out their roster, and asked that anyone who's interested talk to him before they leave.</p>
<p>Forever INFJ, I threw my laptop and notebook into my bag and made for the door, sure I'd be unable to handle meeting a bunch of strangers in the interest of letting them tear my work apart. A minute later, though, I doubled back. In that time, a small group of people had already crowded around this guy, and I was sure I'd missed my shot. Still, though, I talked to him and got him my contact info, and he followed up with me a few days later with more information on the group.</p>
<p>Who was this mystery author, you ask? As it turns out, it was Dan Schiro.</p>
<p>If you recognize that name, you're either a fan of space opera, a listener to the writescast, or both. Dan, almost exactly five years after our conversation about the critique group, would become <a href="https://ryanrcampbell.com/podcast/writescast-episode-one-author-dan-schiro-and-action-scenes/" target="_blank" rel="noopener">the show's first guest.</a></p>
<p>Over the course of those five years, I became more comfortable at the critique group, through which I was able to learn more than I could possibly communicate in any number of blog posts. Not only that, but it and other conferences from the Continuing Studies division led me to meet eventual writescast guests like <a href="https://ryanrcampbell.com/podcast/writescast-015-keeping-the-science-in-science-fiction-and-the-fiction-too-with-scott-birrenkott/" target="_blank" rel="noopener">Scott Birrenkott</a>, <a href="https://ryanrcampbell.com/podcast/writescast-episode-nine-kristin-a-oakley-and-the-hybrid-publishing-process/" target="_blank" rel="noopener">Kristin Oakley</a>, and <a href="https://ryanrcampbell.com/podcast/writescast-012-promoting-your-work-through-traditional-media-with-valerie-biel/" target="_blank" rel="noopener">Valerie Biel</a>.</p>
<p>Speaking with them and folks like <a href="https://ryanrcampbell.com/podcast/writescast-episode-three-dylan-davis-on-flash-fiction-writing-fear-and-publishing-tips/" target="_blank" rel="noopener">Dylan Davis</a> pushed me to explore new approaches to my own work, which eventually led to the publication of my flash fiction and short story pieces like <a href="http://five2onemagazine.com/wool-r-r-campbell-flash-fiction-thesideshow/" target="_blank" rel="noopener">“Wool”</a> and <a href="http://eroticreviewmagazine.com/fiction/what-it-is-to-smell-of-man/" target="_blank" rel="noopener">“What it is to Smell of Man”</a> (NSFW).</p>
<p>Now, I'm working on some collaborative projects to try to pay forward the lessons I've learned as a result of all of this networking, staying true to myself, and, ultimately, that decision I made in a moldy, one-car Brazilian garage half a decade ago.</p>
<p>And I couldn't be more excited about whatever it is that comes next.</p>
<h1>Concluding Remarks</h1>
<p>At this point, whether I've achieved my goal of presenting this without being a braggart is immaterial. Truthfully, I hope my journey has left you with a new perspective on your own, and, with any luck, laid out some tools that might be of use to you going forward.</p>
<p>If it hasn't, maybe it's just that my background doesn't match up well enough with your own. And that's fine. If you think someone else's journey might help you better understand yours, you can of course check out <a href="https://ryanrcampbell.com/podcast/writescast023/" target="_blank" rel="noopener">writescast episode 023</a> where Barbara Britton and I talk about her writing journey, and frame it all through music.</p>
<p>Though her experiences were different from mine on the surface, I'm confident you'll find the same axioms apply: she made a decision, stayed true to herself, and engaged positively with the writing community to arrive where she's at today.</p>
<p>If Barbara can do it, if I can do it, if any number of authors out there can do it, you can, too.</p>
<p>To begin, all you need to do is make a decision.</p>
<hr />
<p>Thanks for reading. If you like posts like these, be sure to subscribe to <a href="http://www.rrcampbellwrites.com/newsletter" target="_blank" rel="noopener">the r. r. campbell writes newsletter</a>, where I publish monthly recaps of the writescast and other writing resources. By subscribing, you not only get those insights delivered directly to your inbox, but you're eligible for 10% off most of my <a href="http://www.rrcampbellwrites.com/editing-services" target="_blank" rel="noopener">editing services.</a></p>
<p>Thanks again for visiting. Write on and write well.</p>
<p>&nbsp;</p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default OnAuthenticityandFollowingYourBliss
