import React from 'react'

const WritescastRaconteursPostDraftSummary = () =>
  <div>
    <p style="text-align: center;"><em>This is part one of the misadventures of the <a href="http://www.rrcampbellwrites.com/podcasts">Writescast</a> Raconteurs. For more on what this is and why it's happening, feel free to check out the <a href="https://ryanrcampbell.com/writescast-raconteurs/">Writescast Raconteurs home page</a>.</em></p>
<p>Look, I'm no expert on fantasy football. The one year I won a league had to be back in 2005, and even then I was somehow accused of cheating. So I'm not exactly expecting greatness, but I am seeking mediocrity.</p>
<p>You know why? Because mediocrity will sneak you into the playoffs. And once you're in the playoffs, it's a whole new world (cue soundtrack from <em>Aladdin</em>).</p>
<p>To spice things up a bit, I decided to “sponsor” a team this year (my own team, yes), and I'll be doing week-by-week summaries of the “action” throughout the season. Why, you ask? Because why not? Oh, also: synergy. Branding. Marketing. Buzzwords. Or something.</p>
<p>Without further ado, I'd like to introduce the 2017 Writescast Raconteurs.</p>
<div id="attachment_3120" style="width: 314px" class="wp-caption aligncenter"><img loading="lazy" decoding="async" aria-describedby="caption-attachment-3120" data-attachment-id="3120" data-permalink="https://ryanrcampbell.com/2017/08/25/writescast-raconteurs-post-draft-summary/screen-shot-2017-08-25-at-8-06-03-am/" data-orig-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/08/Screen-Shot-2017-08-25-at-8.06.03-AM.png?fit=304%2C568&amp;ssl=1" data-orig-size="304,568" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="Roster - Writescast Raconteurs" data-image-description="" data-image-caption="&lt;p&gt;The Bells of a Bowl (a super one, if we're lucky)&lt;/p&gt;
" data-medium-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/08/Screen-Shot-2017-08-25-at-8.06.03-AM.png?fit=161%2C300&amp;ssl=1" data-large-file="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/08/Screen-Shot-2017-08-25-at-8.06.03-AM.png?fit=304%2C568&amp;ssl=1" class="alignnone size-full wp-image-3120" src="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/08/Screen-Shot-2017-08-25-at-8.06.03-AM.png?resize=304%2C568&#038;ssl=1" alt="Roster - Writescast Raconteurs" width="304" height="568" srcset="https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/08/Screen-Shot-2017-08-25-at-8.06.03-AM.png?w=304&amp;ssl=1 304w, https://i0.wp.com/ryanrcampbell.com/wp-content/uploads/2017/08/Screen-Shot-2017-08-25-at-8.06.03-AM.png?resize=161%2C300&amp;ssl=1 161w" sizes="(max-width: 304px) 100vw, 304px" data-recalc-dims="1" /><p id="caption-attachment-3120" class="wp-caption-text">The Bells of a Bowl (a super one, if we're lucky)</p></div>
<p>Historically I've failed to draft enough RBs and WRs to survive the plague of injuries that will surely befall all of these men since they've now been drafted by my daft hands (sorry to Randall Cobb, sorry-not-sorry to all the Seahawks that made it to my roster) This year, however, I drafted five WRs and six RBs, before rounding things out from there. Maybe I hyper-corrected against my old habits a bit much, but we'll see how things turn out.</p>
<p>Given that we're playing in a twelve-team, 0.5 PPR league, how do you think the Writescast Raconteurs will fare? You can leave comments below or harass the team sponsor over at <a href="http://www.twitter.com/writescast" target="_blank" rel="noopener">@writescast</a> on Twitter. Because why not?</p>
<p>Week one kicks off on Thursday, September 7th, and I'm aiming to have weekly recaps out on the Tuesday following each week of action. Stay tuned and remember: Go, Writescast Raconteurs!</p>
<span class="et_bloom_bottom_trigger"></span>
  </div>

export default WritescastRaconteursPostDraftSummary
